/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 * 严格对齐 Semi Design（semi-ui/input/textarea.tsx）：props / DOM / token 全部镜像 Semi。
 */
export const meta = {
  name: 'TextArea',
  category: 'input',
  semiEquivalent: 'TextArea',
  description:
    '多行文本录入框，支持计数（maxCount/getValueLength）、清除、校验态、IME、autosize 自适应高度、行号、resize 全值域。严格对齐 Semi。',
  capabilities: ['multiline', 'autosize', 'char-count', 'clearable', 'validation-status', 'line-number'],
  props: [
    { name: 'value', type: 'string', default: 'undefined', desc: '受控值；提供则为受控' },
    { name: 'defaultValue', type: 'string', default: "''", desc: '非受控初始值' },
    { name: 'size', type: "'small'|'default'|'large'", default: "'default'" },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'readonly', type: 'boolean', default: 'false' },
    { name: 'placeholder', type: 'string', default: 'undefined' },
    { name: 'showCount', type: 'boolean', default: 'false', desc: '显示字数统计（对齐 Semi showCounter；maxCount 存在时亦显示）' },
    { name: 'maxLength', type: 'number', default: 'undefined', desc: '原生硬性长度限制（截断输入）' },
    { name: 'maxCount', type: 'number', default: 'undefined', desc: '计数上限（计数展示与超限提示，不截断，对齐 Semi）' },
    { name: 'showClear', type: 'boolean', default: 'false', desc: '显示清除按钮（非空且非禁用/只读，对齐 Semi）' },
    { name: 'autoFocus', type: 'boolean', default: 'false', desc: '挂载后自动聚焦' },
    { name: 'validateStatus', type: "'default'|'warning'|'error'|'success'", default: "'default'", desc: '校验态（对齐 Semi validateStatus）' },
    { name: 'rows', type: 'number', default: '4', desc: '默认行数（对齐 Semi）' },
    { name: 'cols', type: 'number', default: 'undefined', desc: '默认列数（对齐 Semi cols）' },
    { name: 'autosize', type: 'boolean | { minRows?: number; maxRows?: number }', default: 'false', desc: '随内容自适应高度（对齐 Semi）' },
    { name: 'resize', type: "'none'|'both'|'horizontal'|'vertical'|'block'|'inline'", default: 'undefined', desc: '拖拽调整方向（对齐 Semi resize 全值域）；autosize 时忽略；仅显式传入生效' },
    { name: 'borderless', type: 'boolean', default: 'false', desc: '无边框模式（对齐 Semi borderless）' },
    { name: 'showLineNumber', type: 'boolean', default: 'false', desc: '展示行号（对齐 Semi showLineNumber）' },
    { name: 'lineNumberStart', type: 'number', default: '1', desc: '行号起始值（对齐 Semi lineNumberStart）' },
    { name: 'lineNumberClassName', type: 'string', default: 'undefined', desc: '行号区自定义类名（对齐 Semi）' },
    { name: 'lineNumberStyle', type: 'string', default: 'undefined', desc: '行号区自定义样式（对齐 Semi）' },
    { name: 'textareaStyle', type: 'string', default: 'undefined', desc: 'textarea 元素样式，可设高度等（对齐 Semi textareaStyle）' },
    { name: 'getValueLength', type: '(value: string) => number', default: 'undefined', desc: '自定义字符计数函数（对齐 Semi getValueLength）' },
    { name: 'disabledEnterStartNewLine', type: 'boolean', default: 'false', desc: '禁用 Enter 换行（Shift+Enter 才换行，对齐 Semi，Chat 场景用）' },
    { name: 'composition', type: 'boolean', default: 'false', desc: '输入法模式：开启后 IME 未确认期间不触发 onChange，确认后触发一次（对齐 Semi）' },
    { name: 'name', type: 'string', default: 'undefined' },
    { name: 'id', type: 'string', default: 'undefined' },
    { name: 'class', type: 'string', default: "''", desc: '根容器自定义类名（对齐 Semi className）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根容器内联样式（对齐 Semi style）' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'ariaLabelledby', type: 'string', default: 'undefined' },
    { name: 'ariaDescribedby', type: 'string', default: 'undefined' },
    { name: 'ariaErrormessage', type: 'string', default: 'undefined' },
    { name: 'ariaRequired', type: 'boolean', default: 'undefined' },
    { name: 'onChange', type: '(value: string, e: Event) => void', default: 'undefined', desc: '内容变化（对齐 Semi：第二参为原生事件）' },
    { name: 'onInput', type: '(value: string, e: Event) => void', default: 'undefined' },
    { name: 'onClear', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击清除按钮（对齐 Semi：透传鼠标事件）' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined', desc: '获得焦点' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined', desc: '失去焦点' },
    { name: 'onEnterPress', type: '(e: KeyboardEvent) => void', default: 'undefined', desc: '按下 Enter（透传原生事件，对齐 Semi；composition 中不触发）' },
    { name: 'onPressEnter', type: '(e: KeyboardEvent) => void', default: 'undefined', desc: 'onEnterPress 别名（对齐 Semi onPressEnter）' },
    { name: 'onResize', type: '(p: { height: number; width?: number }) => void', default: 'undefined', desc: 'autosize 高度变化，或 resize 拖拽（含 width，对齐 Semi）' },
    { name: 'onKeyDown', type: '(e: KeyboardEvent) => void', default: 'undefined', desc: '透传原生 keydown（对齐 Semi）' },
    { name: 'onKeyUp', type: '(e: KeyboardEvent) => void', default: 'undefined' },
    { name: 'onKeyPress', type: '(e: KeyboardEvent) => void', default: 'undefined' },
    { name: 'onCompositionStart', type: '(e: CompositionEvent) => void', default: 'undefined', desc: 'IME 开始' },
    { name: 'onCompositionEnd', type: '(e: CompositionEvent) => void', default: 'undefined', desc: 'IME 结束' },
    { name: 'onCompositionUpdate', type: '(e: CompositionEvent) => void', default: 'undefined' },
  ],
  methods: [
    { name: 'focus()', desc: '命令式聚焦（对齐 Semi）' },
    { name: 'blur()', desc: '命令式失焦（对齐 Semi）' },
  ],
  slots: [
    { name: 'count', scope: '{ count, maxCount, overLimit }', desc: '自定义计数器渲染（覆盖内建，本库超集扩展）' },
    { name: 'clearIcon', desc: '自定义清除图标' },
  ],
  a11y: {
    role: 'textbox',
    notes: [
      '原生 textarea',
      'error 时 aria-invalid',
      'IME composition 安全',
      '超限经 aria-live=polite 播报',
      '清除按钮可 Tab 到达，aria-label 来自 i18n',
    ],
  },
  i18nKeys: ['Textarea.clear', 'Textarea.countFormat', 'Textarea.countOnly', 'Textarea.overLimitAnnounce'],
  tokens: ['--cd-color-input-*', '--cd-color-textarea-*', '--cd-spacing-textarea-*', '--cd-radius-input-wrapper'],
} as const;
