/**
 * Machine-readable component metadata for AI/docs consumption.
 * Modal — 严格镜像 Semi Design。见 Modal.svelte 顶部注释。
 */
export const meta = {
  name: 'Modal',
  category: 'feedback',
  description:
    '模态对话框，严格镜像 Semi Design。DOM：.cd-modal-fixed > .cd-modal-mask + .cd-modal-wrap(role=none 滚动/遮罩点击) > .cd-modal(尺寸壳) > .cd-modal-content(role=dialog aria-modal)。API 对齐 Semi 名：visible/closeOnEsc/getPopupContainer/afterClose/motion/okType(5 种)/size(small|medium|large|full-width)/header(Snippet)/footerFill 等。关闭按钮用 IconButton + IconClose（@chenzy-design/icons），标题用 Typography.Title heading=5。受控 visible 不回写，仅 onVisibleChange/onCancel 通知。命令式工厂 Modal.confirm/info/success/warning/error（异步 onOk 自动 loading）+ Modal.destroyAll + Modal.useModal（配合 ModalContextHolder 继承 context）。可拖拽经 modalRender + DragMove（对齐 Semi）。堆叠 z-index 由模块级计数器分配（声明式与命令式共享）。',
  exports: ['Modal', 'ModalContextHolder', 'modal', 'useModal'],
  props: [
    { name: 'visible', type: 'boolean', default: 'undefined', desc: '对话框是否可见（受控；受控时不回写）' },
    { name: 'title', type: 'string', default: 'undefined', desc: '标题文案' },
    { name: 'header', type: 'Snippet | null', default: 'undefined', desc: '自定义头部，null 不展示头部' },
    { name: 'width', type: 'number | string', default: '448', desc: '宽度' },
    { name: 'height', type: 'number | string', default: 'undefined', desc: '高度' },
    {
      name: 'size',
      type: "'small' | 'medium' | 'large' | 'full-width'",
      default: 'undefined',
      desc: '预设宽度：small(448) / medium(684) / large(920) / full-width(100vw-64px)',
    },
    { name: 'centered', type: 'boolean', default: 'false', desc: '垂直居中' },
    { name: 'closable', type: 'boolean', default: 'true', desc: '右上角关闭按钮' },
    { name: 'closeIcon', type: 'Snippet', default: 'undefined', desc: '自定义关闭图标' },
    { name: 'maskClosable', type: 'boolean', default: 'true', desc: '点遮罩关闭' },
    { name: 'closeOnEsc', type: 'boolean', default: 'true', desc: 'Esc 关闭' },
    { name: 'confirmLoading', type: 'boolean', default: 'false', desc: '确认按钮 loading' },
    { name: 'okText', type: 'string', default: 'undefined', desc: '确认按钮文字' },
    { name: 'cancelText', type: 'string', default: 'undefined', desc: '取消按钮文字' },
    {
      name: 'okType',
      type: "'primary'|'secondary'|'tertiary'|'warning'|'danger'",
      default: "'primary'",
      desc: '确认按钮类型',
    },
    { name: 'okButtonProps', type: 'Record<string, unknown>', default: 'undefined', desc: '确认按钮额外 props' },
    { name: 'cancelButtonProps', type: 'Record<string, unknown>', default: 'undefined', desc: '取消按钮额外 props' },
    { name: 'hasCancel', type: 'boolean', default: 'true', desc: '是否显示取消按钮' },
    {
      name: 'footer',
      type: 'Snippet<[{ ok; cancel }]> | null',
      default: 'undefined',
      desc: 'null 隐藏默认按钮；snippet 自定义尾部（接收 { ok, cancel }）',
    },
    { name: 'footerFill', type: 'boolean', default: 'false', desc: '底部按钮撑满' },
    { name: 'mask', type: 'boolean', default: 'true', desc: '是否显示遮罩' },
    { name: 'maskStyle', type: 'string', default: 'undefined', desc: '遮罩内联样式' },
    { name: 'bodyStyle', type: 'string', default: 'undefined', desc: '内容区内联样式' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根节点内联样式（如 top）' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根节点类名' },
    { name: 'modalContentClass', type: 'string', default: 'undefined', desc: '内容区类名' },
    { name: 'fullScreen', type: 'boolean', default: 'false', desc: '全屏（覆盖 width/height）' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '动画开关' },
    {
      name: 'getPopupContainer',
      type: '() => HTMLElement | null',
      default: 'undefined',
      desc: '指定父级 DOM，缺省 document.body',
    },
    { name: 'zIndex', type: 'number', default: 'undefined', desc: '遮罩/面板的 z-index（缺省由堆叠计数分配）' },
    { name: 'keepDOM', type: 'boolean', default: 'false', desc: '关闭时保留内部组件不销毁' },
    { name: 'lazyRender', type: 'boolean', default: 'true', desc: '配合 keepDOM，为 true 时挂载时不渲染' },
    { name: 'icon', type: 'Snippet', default: 'undefined', desc: '命令式类型图标' },
    {
      name: 'modalRender',
      type: 'Snippet<[Snippet]>',
      default: 'undefined',
      desc: '自定义渲染 Modal content；接收默认 content Snippet，返回包裹结构（可拖拽经此 + DragMove）',
    },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '内容主体' },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '无 title 时的 aria-label' },
    { name: 'onOk', type: '() => void', default: 'undefined', desc: '点击确认' },
    { name: 'onCancel', type: '() => void', default: 'undefined', desc: '取消/关闭' },
    { name: 'afterClose', type: '() => void', default: 'undefined', desc: '对话框完全关闭后回调' },
    { name: 'onVisibleChange', type: '(visible: boolean) => void', default: 'undefined', desc: '显隐变化通知' },
    {
      name: 'maskFixed',
      type: 'boolean',
      default: 'true',
      desc: '遮罩是否 position:fixed；false 时 absolute，配合 getPopupContainer 局部弹层',
    },
  ],
  events: [
    { name: 'onOk', desc: '确认按钮点击（非受控自动关闭）' },
    { name: 'onCancel', desc: '取消/关闭按钮/遮罩/Esc 关闭' },
    { name: 'onVisibleChange', desc: '显隐变化通知' },
    { name: 'afterClose', desc: '完全关闭后' },
  ],
  slots: [
    { name: 'children', desc: '内容主体' },
    { name: 'header', desc: '自定义头部（null 不展示）' },
    { name: 'footer', desc: '自定义尾部（接收 { ok, cancel }）' },
    { name: 'closeIcon', desc: '自定义关闭图标' },
    { name: 'icon', desc: '命令式类型图标' },
    { name: 'modalRender', desc: '自定义渲染 content（可拖拽）' },
  ],
  methods: [
    { name: 'Modal.info / success / error / warning / confirm', type: '(config) => { destroy, update }', desc: '命令式弹出，异步 onOk 自动 loading' },
    { name: 'Modal.destroyAll', type: '() => void', desc: '销毁所有命令式弹窗' },
    { name: 'Modal.useModal', type: '() => [modal, holder]', desc: '返回命令式 api + holder，配合 <ModalContextHolder> 继承 context' },
  ],
  a11y: {
    hasRole: true,
    focusable: true,
    note: 'role=dialog + aria-modal=true；有 title 用 aria-labelledby 指向 Typography.Title，无则 aria-label；aria-describedby 指向 body；useFocusTrap 捕获 Tab 并在关闭时归还触发元素；closeOnEsc 控制 Esc；useScrollLock 锁背景滚动；背景 inert；关闭按钮 IconButton 有 aria-label；motion 关闭过渡受 prefers-reduced-motion 抑制。',
  },
  tokens: [
    '--cd-color-modal-bg',
    '--cd-color-modal-mask-bg',
    '--cd-color-modal-main-text',
    '--cd-color-modal-info-icon',
    '--cd-color-modal-primary-icon',
    '--cd-color-modal-success-icon',
    '--cd-color-modal-danger-icon',
    '--cd-color-modal-warning-icon',
    '--cd-color-modal-content-border',
    '--cd-spacing-modal-marginy',
    '--cd-spacing-modal-content-paddingx',
    '--cd-spacing-modal-header-marginy',
    '--cd-spacing-modal-footer-marginy',
    '--cd-spacing-modal-footer-button-marginleft',
    '--cd-width-modal-small',
    '--cd-width-modal-medium',
    '--cd-width-modal-large',
    '--cd-width-modal-full-width',
    '--cd-radius-modal-content',
    '--cd-font-modal-header-fontsize',
    '--cd-font-modal-header-fontweight',
    '--cd-shadow-modal-content',
  ],
  responsive: false,
  examples: [
    {
      title: '基本',
      code: '<Modal visible={visible} title="基本对话框" onOk={() => (visible = false)} onCancel={() => (visible = false)}>内容</Modal>',
    },
    {
      title: '命令式',
      code: "Modal.confirm({ title: 'Are you sure ?', content: '...', onOk: () => fetch('/api/do') });",
    },
    {
      title: '可拖拽',
      code: '<Modal visible={visible} title="可拖拽">\n  {#snippet modalRender(modal)}<DragMove>{@render modal()}</DragMove>{/snippet}\n  内容\n</Modal>',
    },
    {
      title: 'Hooks（继承 context）',
      code: 'const [modal, holder] = Modal.useModal();\n// <ModalContextHolder items={holder.items} /> 插入组件树',
    },
  ],
} as const;
