/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Rating',
  category: 'input',
  description: '评分组件（对齐 Semi）：支持半星、hover 预览、点击清零与键盘操作；每颗星为 role=radio 双层（roving tabindex），额外空评分项承载 0 分焦点。',
  props: [
    { name: 'value', type: 'number', default: 'undefined', desc: '受控值；提供则为受控（只回调不回写）' },
    { name: 'defaultValue', type: 'number', default: '0', desc: '非受控初始值' },
    { name: 'count', type: 'number', default: '5', desc: 'star 总数' },
    { name: 'allowHalf', type: 'boolean', default: 'false', desc: '允许半选（步进 0.5）' },
    { name: 'allowClear', type: 'boolean', default: 'true', desc: '再次点击当前值清零' },
    { name: 'character', type: 'string | Snippet<[{index,value}]>', default: 'undefined', desc: '自定义字符/图标；不传则默认星形' },
    { name: 'size', type: "'small'|'default'|number", default: "'default'", desc: "尺寸；number 为自定义尺寸（需配合 character）" },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用（只读，无法交互）' },
    { name: 'tooltips', type: 'string[]', default: 'undefined', desc: '逐项提示文案（复用 Tooltip 浮层），长度应等于 count' },
    { name: 'autoFocus', type: 'boolean', default: 'false', desc: '挂载时聚焦当前分值对应星' },
    { name: 'id', type: 'string', default: 'undefined', desc: '根元素 id' },
    { name: 'tabIndex', type: 'number', default: '-1', desc: '根 tabIndex；焦点实际落在星 radio 上' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根元素内联样式' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根元素追加类名' },
    { name: 'preventScroll', type: 'boolean', default: 'undefined', desc: 'autoFocus / focus() 聚焦时是否阻止滚动' },
    { name: 'aria-label', type: 'string', default: 'i18n 默认', desc: '无可视标签时的辅助名（优先于 string character）' },
    { name: 'aria-labelledby', type: 'string', default: 'undefined' },
    { name: 'aria-describedby', type: 'string', default: 'undefined' },
    { name: 'aria-errormessage', type: 'string', default: 'undefined' },
    { name: 'aria-invalid', type: 'boolean', default: 'undefined' },
    { name: 'aria-required', type: 'boolean', default: 'undefined' },
    { name: 'onChange', type: '(value: number) => void', default: 'undefined', desc: '选择时的回调' },
    { name: 'onHoverChange', type: '(value: number) => void', default: 'undefined', desc: '鼠标经过时数值变化；移出时回调 undefined' },
    { name: 'onClick', type: '(e, index: number) => void', default: 'undefined', desc: '点击某项的回调（index 为 0..count，count 为空项）' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined', desc: '获得焦点时的回调' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined', desc: '失去焦点时的回调' },
    { name: 'onKeyDown', type: '(e: KeyboardEvent) => void', default: 'undefined', desc: '按键回调（内部处理后透传）' },
  ],
  methods: [
    { name: 'focus()', desc: '命令式聚焦当前分值对应星（对齐 Semi focus()）' },
    { name: 'blur()', desc: '命令式失焦（对齐 Semi blur()）' },
  ],
  i18nKeys: ['Rating.ariaLabel', 'Rating.valueText', 'Rating.cleared', 'Rating.unrated'],
  a11y: {
    role: 'radio',
    keyboard: ['ArrowRight/Up', 'ArrowLeft/Down'],
    notes: [
      '每颗星两个 role=radio（first 半星 / second 整星）+ roving tabindex（对齐 Semi）',
      '额外渲染 index==count 的空评分项，承载 0 分焦点/停靠点',
      '方向键增减分值（RTL 镜像），越界环绕（>count→0，<0→count）',
      'hover 预览为纯本地状态，不影响受控值；移出回调 undefined',
      'allowHalf 时按指针落在星左/右半决定 .5',
    ],
  },
  tokens: [
    // 去中间层：组件 CSS 直接消费下列 Semi 对齐 token（variables.scss 12 + animation.scss 3）
    '--cd-color-rating-icon-active',
    '--cd-color-rating-bg-default',
    '--cd-color-rating-outline-focus',
    '--cd-font-rating-fontsize',
    '--cd-spacing-rating-margin',
    '--cd-spacing-rating-padding',
    '--cd-spacing-rating-item-marginright',
    '--cd-width-rating-item-small',
    '--cd-font-rating-item-small-fontsize',
    '--cd-width-rating-item-default',
    '--cd-font-rating-item-default-fontsize',
    '--cd-width-rating-outline-focus',
    '--cd-transition-duration-rating-color',
    '--cd-transition-function-rating-color',
    '--cd-transition-delay-rating-color',
  ],
} as const;
