/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Select',
  category: 'input',
  description: '下拉选择器，支持单选 / 多选 / 本地过滤 / 键盘导航 / 浮层。',
  props: [
    { name: 'value', type: 'string|number|(string|number)[]', default: 'undefined' },
    { name: 'defaultValue', type: 'string|number|(string|number)[]', default: 'undefined' },
    { name: 'options', type: 'OptionData[] | OptionGroup[]', default: '[]', desc: '选项；含 { label, options:[] } 即分组' },
    { name: 'multiple', type: 'boolean', default: 'false' },
    { name: 'filter', type: 'boolean', default: 'false' },
    { name: 'open', type: 'boolean', default: 'undefined' },
    { name: 'defaultOpen', type: 'boolean', default: 'false' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default' },
    { name: 'placeholder', type: 'string', default: "'请选择'" },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: 'combobox 触发器可访问名' },
    { name: 'ariaLabelledby', type: 'string', default: 'undefined', desc: '关联外部 label 的 id（优先于 ariaLabel）' },
    { name: 'id', type: 'string', default: 'undefined', desc: '触发器 id，用于关联外部 <label for="...">' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'clearable', type: 'boolean', default: 'false' },
    { name: 'borderless', type: 'boolean', default: 'false', desc: '无边框模式' },
    { name: 'autoFocus', type: 'boolean', default: 'false', desc: '挂载后自动聚焦触发器' },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '浮层被遮挡时自动翻转方向（映射 use:floating autoAdjust，对齐 Semi）' },
    { name: 'maxTagCount', type: 'number', default: '0', desc: '多选 tag 超出折叠为 +N（0=不折叠）' },
    { name: 'maxTagTextLength', type: 'number', default: 'undefined', desc: '单个 Tag 文本最大长度，超出截断为「前缀…」，完整文本经 title 查看' },
    { name: 'showRestTagsPopover', type: 'boolean', default: 'false', desc: '多选 maxTagCount 折叠出 +N 时，hover +N 用 Popover 浮层展示剩余全部 Tag（对齐 Semi restTagsPopover）' },
    { name: 'restTagsPopoverProps', type: 'object', default: 'undefined', desc: '透传给 +N 悬停 Popover 浮层的配置（spread 到 Popover，可覆盖 position/trigger/spacing 等）' },
    { name: 'expandRestTagsOnClick', type: 'boolean', default: 'false', desc: '多选 maxTagCount 折叠时，浮层打开态下点击 +N 就地展开剩余全部 Tag（纯展示，不改值）' },
    { name: 'ellipsisTrigger', type: 'boolean', default: 'false', desc: '多选且有 maxTagCount 时，对溢出可见 Tag 文本做单行省略（完整文本经 title 查看）' },
    { name: 'showArrow', type: 'boolean', default: 'true', desc: '是否显示触发器右侧下拉箭头；false 隐藏（suffix 存在时以 suffix 为准）' },
    { name: 'clickToHide', type: 'boolean', default: 'false', desc: '浮层已展开时，点击触发器是否收起浮层' },
    { name: 'defaultActiveFirstOption', type: 'boolean', default: 'true', desc: '打开浮层时默认高亮首个可用选项（键盘 Enter 可直接选中）' },
    { name: 'allowCreate', type: 'boolean', default: 'false', desc: 'filter 无匹配时可创建新选项' },
    { name: 'autoClearSearchValue', type: 'boolean', default: 'true', desc: '多选选中后自动清空搜索词' },
    { name: 'optionLabelProp', type: 'string', default: "'label'", desc: '用作回显的字段名' },
    { name: 'searchPosition', type: "'dropdown' | 'trigger'", default: "'dropdown'", desc: "搜索框位置（仅 filter=true 生效）：dropdown=浮层顶部搜索框（打开自动聚焦）；trigger=输入内联在触发器上就地过滤" },
    { name: 'inputProps', type: 'object', default: 'undefined', desc: '透传给搜索 input 的额外属性（勿传 value/onChange/onFocus 等覆盖内部搜索回调的键）' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: 'autoFocus/命令式聚焦触发器时传入 focus({ preventScroll })，避免页面跳动' },
    { name: 'insetLabel', type: 'string | Snippet', default: 'undefined', desc: '内嵌标签：浮入触发器左侧的常驻标签（纯展示，不影响值/过滤）' },
    { name: 'insetLabelId', type: 'string', default: 'undefined', desc: 'insetLabel 的 id，经 aria-labelledby 关联触发器 combobox（仅 insetLabel 存在时生效）' },
    { name: 'onSearch', type: '(query: string) => void', default: 'undefined', desc: '远程搜索（防抖回调，外部更新 options）' },
    { name: 'loading', type: 'boolean', default: 'false', desc: '远程加载中（显示 spinner）' },
    { name: 'searchDebounce', type: 'number', default: '300', desc: 'onSearch 防抖毫秒' },
    { name: 'virtualized', type: 'boolean', default: 'false', desc: '选项虚拟化：大数据下拉只渲染视口内 option（仅非分组生效，分组时回退全量）' },
    { name: 'optionHeight', type: 'number', default: '32', desc: '虚拟化选项行高（px），需与样式实际行高一致' },
    { name: 'maxHeight', type: 'number', default: '256', desc: '下拉最大高度（px）；虚拟化时同时作为视口高度' },
    { name: 'dropdownMatchSelectWidth', type: 'boolean', default: 'true', desc: '浮层宽度是否跟随触发器；false 时浮层自适应内容宽度' },
    { name: 'dropdownClassName', type: 'string', default: 'undefined', desc: '浮层根 div 追加的自定义 className（与内置 cd-select__dropdown 并存）' },
    { name: 'dropdownStyle', type: 'string', default: 'undefined', desc: '浮层根 div 合并的自定义内联样式（勿含 position/transform）' },
    { name: 'zIndex', type: 'number', default: 'undefined', desc: '浮层层级（z-index）；不传由 CSS 层级 token 控制' },
    { name: 'dropdownMargin', type: 'number | { top?, bottom?, left?, right? }', default: 'undefined', desc: '浮层与触发器间距(px)，映射到 floating offset；object 按 placement 主轴取值' },
    { name: 'destroyOnClose', type: 'boolean', default: 'false', desc: '关闭时销毁浮层 DOM' },
    { name: 'getPopupContainer', type: '() => HTMLElement', default: 'undefined', desc: '浮层挂载目标容器' },
    { name: 'onChange', type: '(v: string|number|(string|number)[]) => void', default: 'undefined' },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'onSelect', type: '(value, option) => void', default: 'undefined', desc: '选中某项时触发' },
    { name: 'onDeselect', type: '(value, option) => void', default: 'undefined', desc: '多选取消某项时触发' },
    { name: 'onClear', type: '() => void', default: 'undefined', desc: '点击清除按钮时触发' },
    { name: 'onCreate', type: '(value: string) => void', default: 'undefined', desc: 'allowCreate 创建新项时触发' },
    { name: 'onFocus', type: '() => void', default: 'undefined', desc: '触发器获焦时触发' },
    { name: 'onBlur', type: '() => void', default: 'undefined', desc: '触发器失焦时触发' },
    { name: 'onScrollToBottom', type: '() => void', default: 'undefined', desc: '浮层列表滚动触底时触发' },
    { name: 'onListScroll', type: '(e: Event) => void', default: 'undefined', desc: '浮层选项列表滚动时触发（携带原生 scroll 事件）' },
    { name: 'onExceed', type: '(option) => void', default: 'undefined', desc: '多选超出 maxTagCount 时触发（携带被隐藏的 option）' },
    { name: 'onChangeWithObject', type: '(option | option[]) => void', default: 'undefined', desc: '携带完整 option 对象的 change 回调' },
  ],
  snippets: [
    { name: 'prefix', desc: '触发器左侧前缀' },
    { name: 'suffix', desc: '触发器右侧后缀（覆盖默认箭头区域）' },
    { name: 'clearIcon', desc: '自定义清除按钮图标' },
    { name: 'arrowIcon', desc: '自定义下拉箭头图标' },
    { name: 'emptyContent', type: 'string | Snippet', desc: '自定义空态内容' },
    { name: 'empty', desc: '自定义空态 Snippet（与 emptyContent 等价）' },
    { name: 'dropdownHeader', desc: '浮层顶部固定区（inner：滚动列表内部顶端，随 optionList 滚动）' },
    { name: 'dropdownFooter', desc: '浮层底部固定区（inner：滚动列表内部底端，随 optionList 滚动）' },
    { name: 'outerTopSlot', desc: '浮层最外层顶部 slot（outer：与滚动列表平级、滚动区之外，始终固定展现）' },
    { name: 'outerBottomSlot', desc: '浮层最外层底部 slot（outer：与滚动列表平级、滚动区之外，始终固定展现）' },
    { name: 'option', params: '[{ option, selected, active }]', desc: '自定义单项渲染' },
    { name: 'label', params: '[{ option }]', desc: '自定义选中值/Tag 渲染' },
    { name: 'renderCreateItem', params: '[queryString]', desc: '自定义"创建xxx"项渲染' },
    { name: 'triggerRender', params: '[{ value, selectedOptions, placeholder, open, disabled, toggle, onTriggerKeydown }]', desc: '完全自定义触发器渲染（替换默认 combobox 触发框）；需自挂 aria/键盘保持可达' },
  ],
  methods: [
    { name: 'open()', desc: '命令式展开下拉列表（对齐 Semi）' },
    { name: 'close()', desc: '命令式收起下拉列表（对齐 Semi）' },
    { name: 'focus()', desc: '命令式聚焦触发器（尊重 preventScroll，对齐 Semi）' },
    { name: 'clearInput()', desc: '命令式清空搜索框（对齐 Semi）' },
    { name: 'deselectAll()', desc: '命令式清空所有已选项（对齐 Semi）' },
    { name: 'selectAll()', desc: '命令式选中所有可选 Option（仅多选，对齐 Semi）' },
    { name: 'search(value, event?)', desc: '命令式设置搜索值并触发搜索（对齐 Semi）' },
    { name: 'rePosition()', desc: '命令式触发浮层重新定位（对齐 Semi）' },
  ],
  a11y: {
    role: 'combobox',
    notes: [
      'combobox + listbox + option ARIA 模式',
      'aria-activedescendant 指向高亮项',
      '选中项 aria-selected；多选 aria-multiselectable',
      '键盘：↑↓ 移动、Enter 选中、Esc 关闭',
    ],
  },
  tokens: ['--cd-select-*', '--cd-focus-ring', '--cd-motion-*'],
} as const;
