/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 * 严格对齐 Semi timeline API（index.tsx / item.tsx）。
 */
export const meta = {
  name: 'Timeline',
  category: 'show',
  description:
    '时间轴，用于对一系列信息进行时间排序时垂直展示。两种用法择一：传 dataSource 数据驱动（支持 content 属性及 Timeline.Item 全部属性），或在 children 内写 <Timeline.Item> 声明式。通过 mode 设置时间轴与内容的相对位置：left（默认）/right/center/alternate。',
  props: [
    {
      name: 'mode',
      type: "'left'|'right'|'center'|'alternate'",
      default: 'left',
      desc: '通过设置 mode 可以改变时间轴和内容的相对位置',
    },
    { name: 'class', type: 'string', default: '-', desc: '类名' },
    { name: 'style', type: 'string', default: '-', desc: '样式' },
    {
      name: 'dataSource',
      type: 'TimelineItemData[]',
      default: '-',
      desc: '时间轴数据源，支持 content 属性及 Timeline.Item 的所有属性',
    },
    {
      name: 'aria-label',
      type: 'string',
      default: '-',
      desc: '无障碍标签',
    },
    {
      name: 'children',
      type: 'Snippet',
      default: '-',
      desc: '声明式用法：内嵌 <Timeline.Item> 列表（未传 dataSource 时生效）',
    },
  ],
  subComponents: [
    {
      name: 'Timeline.Item',
      desc: '时间轴单项，渲染节点圆点 / 连线 / 内容',
      props: [
        { name: 'class', type: 'string', default: '-', desc: '类名' },
        { name: 'color', type: 'string', default: '-', desc: '自定义的圆圈色值' },
        { name: 'dot', type: 'string | Snippet', default: '-', desc: '自定义时间轴点' },
        { name: 'extra', type: 'string | Snippet', default: '-', desc: '自定义辅助内容' },
        {
          name: 'position',
          type: "'left'|'right'",
          default: '-',
          desc: '自定义节点位置，可以覆盖 Timeline 的模式选项',
        },
        { name: 'style', type: 'string', default: '-', desc: '样式' },
        { name: 'time', type: 'string | Snippet', default: '-', desc: '时间文本' },
        {
          name: 'type',
          type: "'default'|'ongoing'|'success'|'warning'|'error'",
          default: 'default',
          desc: '当前圆圈的模式',
        },
        {
          name: 'onClick',
          type: '(e: MouseEvent) => void',
          default: '-',
          desc: '鼠标点击事件的回调',
        },
        { name: 'children', type: 'Snippet', default: '-', desc: '节点内容' },
      ],
    },
  ],
  a11y: {
    role: 'list',
    notes: [
      'ul/li 结构',
      '时间点的连线以及时间点本身被设置了 aria-hidden，不会响应 Accessibility API',
      '可通过传入 aria-label 设置 Timeline 组件的标签',
    ],
  },
  tokens: [
    // 严格对齐 semi-foundation/timeline/variables.scss（组件实际消费）
    '--cd-color-timeline-dot-default-bg-default',
    '--cd-color-timeline-dot-success-bg-default',
    '--cd-color-timeline-dot-warning-bg-default',
    '--cd-color-timeline-dot-error-bg-default',
    '--cd-color-timeline-dot-info-bg-default',
    '--cd-color-timeline-tail-border',
    '--cd-color-timeline-time-default-text-default',
    '--cd-color-timeline-item-head-bg',
    '--cd-color-timeline-item-content-text-default',
    '--cd-spacing-timeline-margin',
    '--cd-spacing-timeline-padding',
    '--cd-spacing-timeline-tail-top',
    '--cd-spacing-timeline-tail-left',
    '--cd-spacing-timeline-head-top',
    '--cd-spacing-timeline-head-custom-top',
    '--cd-spacing-timeline-head-custom-left',
    '--cd-spacing-timeline-content-marginleft',
    '--cd-spacing-timeline-time-margintop',
    '--cd-spacing-timeline-time-top',
    '--cd-spacing-timeline-item-margin',
    '--cd-spacing-timeline-item-paddingbottom',
    '--cd-spacing-timeline-item-content-time-marginleft',
    '--cd-spacing-timeline-item-right-item-left',
    '--cd-spacing-timeline-item-right-item-content',
    '--cd-spacing-timeline-item-left-item-content-left',
    '--cd-spacing-timeline-item-head-custom-left',
    '--cd-spacing-timeline-item-head-marginleft',
    '--cd-width-timeline',
    '--cd-width-timeline-dot',
    '--cd-width-timeline-head-custom',
    '--cd-width-timeline-tail-border',
    '--cd-width-timeline-head-custom-border',
    '--cd-width-timeline-item-content-time',
    '--cd-width-timeline-item-right-content',
    '--cd-width-timeline-item-left-item-content',
    '--cd-width-timeline-item-right-item-content',
    '--cd-height-timeline-tail',
    '--cd-height-timeline-head-custom',
    '--cd-radius-timeline-head',
    '--cd-radius-timeline-head-custom',
    '--cd-motion-timeline-head-custom-transform',
  ],
} as const;
