/**
 * Machine-readable component metadata for AI/docs consumption.
 * Chat — aligned to Semi Design Chat（消息流 + 输入区 + 提示区，headless 逻辑在 @chenzy-design/core）。
 */
export const meta = {
  name: 'Chat',
  category: 'plus',
  description:
    '对话/AI 聊天组件（严格对齐 Semi Chat）：DOM 对齐 Semi 结构 .cd-chat > -inner > -content > -container；消息流（Avatar 头像/标题/内容 MarkdownRender/操作区 Button+具名图标）+ 输入区（-inputBox > -inner > -clearButton + -container(-upload/-inputArea TextArea/-sendButton)）+ 提示区（-hints > -hint-item）。头像用本库 Avatar，操作/发送/上传/清除/回到底部/停止用本库 Button + 具名图标（copy=IconCopyStroked/like=IconLikeThumb·IconThumbUpStroked/reset=IconRedoStroked/delete=IconDeleteStroked/backBottom=IconChevronDown/stop=IconDisc/send=IconArrowUp旋转/upload=IconChainStroked/clear=IconDeleteStroked，对齐 Semi 非手写 svg）。loading 三点 flashing 动画。tokens 镜像 Semi variables.scss（~115 个）。框架无关逻辑在 @chenzy-design/core（buildSendContent/appendDivider/toggleLike/toggleDislike/resetLastMessage/shouldShowBackBottom/resolveEnableUpload/shouldSendOnEnter）。受控/非受控 chats，变换经 onChatsChange 回传。align(leftRight/leftAlign)、mode(bubble/noBubble/userBubble)、sendHotKey(enter/shift+enter)、enableUpload 三态、拖拽 dropArea。消息流 role=log/aria-live=polite；滚动出现回到底部悬浮按钮（SHOW_SCROLL_GAP=100）。ref 方法 resetMessage/scrollToBottom(animation)/clearContext/sendMessage。自定义渲染走 Svelte snippet（renderInputArea/renderChatBoxAvatar/Title/Content/Action/renderFullChatBox/renderHintBox/renderDivider）。',
  exports: ['Chat'],
  props: [
    { name: 'chats', type: 'Message[]', default: 'undefined', desc: '消息列表；传入即受控，否则内部维护' },
    { name: 'roleConfig', type: 'RoleConfig', default: 'undefined', desc: '角色元数据（名称/头像/色），按 message.role 取' },
    { name: 'align', type: "'leftRight'|'leftAlign'", default: "'leftRight'", desc: '布局对齐（左右分列 / 全左对齐）' },
    { name: 'mode', type: "'bubble'|'noBubble'|'userBubble'", default: "'bubble'", desc: '气泡模式' },
    { name: 'sendHotKey', type: "'enter'|'shift+enter'", default: "'enter'", desc: '发送快捷键' },
    { name: 'showClearContext', type: 'boolean', default: 'false', desc: '是否展示清除上下文按钮' },
    { name: 'showStopGenerate', type: 'boolean', default: 'false', desc: '是否展示停止生成按钮' },
    { name: 'hints', type: 'string[]', default: 'undefined', desc: '提示项列表（点击追加为一条 user 消息）' },
    { name: 'enableUpload', type: 'boolean|EnableUploadProps', default: 'true', desc: '上传能力（true/false 或 {pasteUpload,dragUpload,clickUpload} 三态）' },
    { name: 'uploadProps', type: 'UploadProps', default: 'undefined', desc: '透传内部 Upload 的 props' },
    { name: 'uploadTipProps', type: 'TooltipProps', default: 'undefined', desc: '上传按钮 Tooltip 提示（对齐 Semi uploadTipProps）；传对象则用 Tooltip 包裹上传触发器' },
    { name: 'markdownRenderProps', type: 'MarkdownRenderProps', default: 'undefined', desc: '透传消息内容 MarkdownRender 的 props' },
    { name: 'placeholder', type: 'string', default: 'undefined', desc: '输入框占位（缺省走 locale Chat.placeholder）' },
    { name: 'topSlot', type: 'Snippet', default: 'undefined', desc: '顶部插槽' },
    { name: 'bottomSlot', type: 'Snippet', default: 'undefined', desc: '底部插槽（列表与输入区之间）' },
    { name: 'class', type: 'string', default: "''", desc: '根类名透传' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根内联样式' },
    { name: 'onChatsChange', type: '(chats: Message[]) => void', default: 'undefined', desc: 'chats 变化回调（受控父级据此更新）' },
    { name: 'onMessageSend', type: '(content: string, attachment: UploadFileItem[]) => void', default: 'undefined', desc: '发送消息回调' },
    { name: 'onInputChange', type: '(props: { value: string; attachment: UploadFileItem[] }) => void', default: 'undefined', desc: '输入变化回调' },
    { name: 'onClear', type: '() => void', default: 'undefined', desc: '清除上下文回调' },
    { name: 'onHintClick', type: '(hint: string) => void', default: 'undefined', desc: '点击提示项回调' },
    { name: 'onStopGenerator', type: '() => void', default: 'undefined', desc: '停止生成回调' },
    { name: 'onMessageCopy', type: '(message: Message) => void', default: 'undefined', desc: '复制消息回调' },
    { name: 'onMessageDelete', type: '(message: Message) => void', default: 'undefined', desc: '删除消息回调' },
    { name: 'onMessageReset', type: '(message: Message) => void', default: 'undefined', desc: '重生成消息回调' },
    { name: 'onMessageGoodFeedback', type: '(message: Message) => void', default: 'undefined', desc: '点赞回调' },
    { name: 'onMessageBadFeedback', type: '(message: Message) => void', default: 'undefined', desc: '点踩回调' },
    { name: 'renderInputArea', type: 'Snippet<[RenderInputAreaProps]>', default: 'undefined', desc: '自定义整块输入区' },
    { name: 'renderChatBoxAvatar', type: 'Snippet<[RenderAvatarProps]>', default: 'undefined', desc: '自定义消息头像' },
    { name: 'renderChatBoxTitle', type: 'Snippet<[RenderTitleProps]>', default: 'undefined', desc: '自定义消息标题' },
    { name: 'renderChatBoxContent', type: 'Snippet<[RenderContentProps]>', default: 'undefined', desc: '自定义消息内容' },
    { name: 'renderChatBoxAction', type: 'Snippet<[RenderActionProps]>', default: 'undefined', desc: '自定义消息操作区' },
    { name: 'renderFullChatBox', type: 'Snippet<[RenderFullChatBoxProps]>', default: 'undefined', desc: '自定义整条消息（提供拆分节点）' },
    { name: 'renderHintBox', type: 'Snippet<[RenderHintBoxProps]>', default: 'undefined', desc: '自定义单个提示项' },
    { name: 'renderDivider', type: 'Snippet<[Message]>', default: 'undefined', desc: '自定义清除上下文分割线' },
  ],
  events: [
    { name: 'onChatsChange', desc: '消息列表变化' },
    { name: 'onMessageSend', desc: '发送消息' },
    { name: 'onInputChange', desc: '输入内容/附件变化' },
    { name: 'onClear', desc: '清除上下文' },
    { name: 'onHintClick', desc: '点击提示项' },
    { name: 'onStopGenerator', desc: '停止生成' },
    { name: 'onMessageCopy', desc: '复制消息' },
    { name: 'onMessageDelete', desc: '删除消息' },
    { name: 'onMessageReset', desc: '重生成消息' },
    { name: 'onMessageGoodFeedback', desc: '点赞' },
    { name: 'onMessageBadFeedback', desc: '点踩' },
  ],
  slots: [
    { name: 'topSlot', desc: '顶部插槽' },
    { name: 'bottomSlot', desc: '列表与输入区之间插槽' },
    { name: 'renderInputArea', desc: '自定义整块输入区' },
    { name: 'renderChatBoxAvatar', desc: '自定义头像' },
    { name: 'renderChatBoxTitle', desc: '自定义标题' },
    { name: 'renderChatBoxContent', desc: '自定义内容' },
    { name: 'renderChatBoxAction', desc: '自定义操作区' },
    { name: 'renderFullChatBox', desc: '自定义整条消息' },
    { name: 'renderHintBox', desc: '自定义提示项' },
    { name: 'renderDivider', desc: '自定义分割线' },
  ],
  methods: [
    { name: 'resetMessage', signature: '() => void', desc: '将最后一条消息重置为 loading（对齐 Semi resetMessage）' },
    { name: 'scrollToBottom', signature: '(animation?: boolean) => void', desc: '滚动到底部；animation=true 带缓动' },
    { name: 'clearContext', signature: '() => void', desc: '清除上下文（末尾追加 divider）' },
    { name: 'sendMessage', signature: '(content: string, attachment?: UploadFileItem[]) => void', desc: '以文本 + 附件发送一条消息' },
  ],
  a11y: {
    role: 'log',
    keyboard: ['Enter', 'Shift+Enter'],
    focusable: true,
    notes: [
      '消息流容器 role=log / aria-live=polite / aria-label 走 locale Chat.messageList，新消息被屏幕阅读器播报',
      '输入区 textarea，Enter/Shift+Enter 由 sendHotKey + core.shouldSendOnEnter 判定（组合输入 isComposing 时不发送）',
      '发送/上传/清除/复制/删除/重生成/赞/踩 均为原生 <button>，aria-label 走 locale；赞/踩 aria-pressed 反映激活态',
      '回到底部悬浮按钮为原生 <button>，滚动距底 > SHOW_SCROLL_GAP(100) 时出现，aria-label=Chat.backToBottom',
      '发送按钮 disabled 对齐 Semi getDisableSend：无文本且无附件 / 附件有未 success / 显式 disableSend',
    ],
  },
  tokens: [
    '--cd-chat-action-content-bg',
    '--cd-chat-action-content-bg-hover',
    '--cd-chat-action-content-border',
    '--cd-chat-action-content-border-width',
    '--cd-chat-action-content-bottom',
    '--cd-chat-action-stop-height',
    '--cd-chat-action-z',
    '--cd-chat-attachment-clear-icon',
    '--cd-chat-attachment-clear-right',
    '--cd-chat-attachment-clear-top',
    '--cd-chat-attachment-columnGap',
    '--cd-chat-attachment-fail',
    '--cd-chat-attachment-file-bg',
    '--cd-chat-attachment-file-columnGap',
    '--cd-chat-attachment-file-icon',
    '--cd-chat-attachment-file-metadata-font-size',
    '--cd-chat-attachment-file-metadata-text',
    '--cd-chat-attachment-file-padding',
    '--cd-chat-attachment-file-radius',
    '--cd-chat-attachment-file-title',
    '--cd-chat-attachment-file-title-font-size',
    '--cd-chat-attachment-file-title-width',
    '--cd-chat-attachment-file-width',
    '--cd-chat-attachment-img-radius',
    '--cd-chat-attachment-marginX',
    '--cd-chat-attachment-rowGap',
    '--cd-chat-backBottom-wrapper-width',
    '--cd-chat-chatBox-action-bg-hover',
    '--cd-chat-chatBox-action-btn-padding',
    '--cd-chat-chatBox-action-columnGap',
    '--cd-chat-chatBox-action-icon',
    '--cd-chat-chatBox-action-icon-hover',
    '--cd-chat-chatBox-action-marginX',
    '--cd-chat-chatBox-avatar-width',
    '--cd-chat-chatBox-code-content',
    '--cd-chat-chatBox-code-topSlot',
    '--cd-chat-chatBox-code-topSlot-bg',
    '--cd-chat-chatBox-code-topSlot-font-size',
    '--cd-chat-chatBox-code-topSlot-line-height',
    '--cd-chat-chatBox-code-topSlot-toCopy-bg-hover',
    '--cd-chat-chatBox-columnGap',
    '--cd-chat-chatBox-content-attachment-marginRight',
    '--cd-chat-chatBox-content-attachment-marginY',
    '--cd-chat-chatBox-content-bg',
    '--cd-chat-chatBox-content-code-radius',
    '--cd-chat-chatBox-content-code-topSlot-copy-columnGap',
    '--cd-chat-chatBox-content-code-topSlot-copy-padding',
    '--cd-chat-chatBox-content-code-topSlot-copy-radius',
    '--cd-chat-chatBox-content-code-topSlot-copy-width',
    '--cd-chat-chatBox-content-code-topSlot-paddingX',
    '--cd-chat-chatBox-content-code-topSlot-paddingY',
    '--cd-chat-chatBox-content-error-bg',
    '--cd-chat-chatBox-content-error-text',
    '--cd-chat-chatBox-content-paddingX',
    '--cd-chat-chatBox-content-paddingY',
    '--cd-chat-chatBox-content-radius',
    '--cd-chat-chatBox-content-text',
    '--cd-chat-chatBox-content-user-bg',
    '--cd-chat-chatBox-content-user-text',
    '--cd-chat-chatBox-loading-bg',
    '--cd-chat-chatBox-loading-item-gap',
    '--cd-chat-chatBox-loading-item-marginX',
    '--cd-chat-chatBox-loading-item-marginY',
    '--cd-chat-chatBox-loading-width',
    '--cd-chat-chatBox-marginY',
    '--cd-chat-chatBox-other-attachment-file-bg',
    '--cd-chat-chatBox-title',
    '--cd-chat-chatBox-title-font-size',
    '--cd-chat-chatBox-title-font-weight',
    '--cd-chat-chatBox-title-line-height',
    '--cd-chat-chatBox-user-attachment-file-bg',
    '--cd-chat-chatBox-wrap',
    '--cd-chat-container-paddingX',
    '--cd-chat-divider',
    '--cd-chat-divider-font-size',
    '--cd-chat-divider-font-weight',
    '--cd-chat-divider-marginY',
    '--cd-chat-dropArea-bg',
    '--cd-chat-dropArea-border',
    '--cd-chat-dropArea-border-width',
    '--cd-chat-dropArea-radius',
    '--cd-chat-dropArea-text-font-size',
    '--cd-chat-dropArea-z',
    '--cd-chat-hint-content-font-size',
    '--cd-chat-hint-content-text',
    '--cd-chat-hint-icon',
    '--cd-chat-hint-item-bg',
    '--cd-chat-hint-item-bg-hover',
    '--cd-chat-hint-item-border',
    '--cd-chat-hint-item-border-width',
    '--cd-chat-hint-item-columnGap',
    '--cd-chat-hint-item-marginX',
    '--cd-chat-hint-item-marginY',
    '--cd-chat-hint-item-radius',
    '--cd-chat-hint-marginLeft',
    '--cd-chat-hint-marginY',
    '--cd-chat-hint-rowGap',
    '--cd-chat-inputBottom-clearButton-icon',
    '--cd-chat-inputBottom-clearButton-icon-font-size',
    '--cd-chat-inputBottom-clearButton-width',
    '--cd-chat-inputBottom-sendButton-icon-disable',
    '--cd-chat-inputBottom-sendButton-width',
    '--cd-chat-inputBottom-uploadButton-icon',
    '--cd-chat-inputBottom-uploadButton-width',
    '--cd-chat-inputBox-container-border',
    '--cd-chat-inputBox-container-border-width',
    '--cd-chat-inputBox-container-padding',
    '--cd-chat-inputBox-container-radius',
    '--cd-chat-inputBox-inner-columnGap',
    '--cd-chat-inputBox-marginY',
    '--cd-chat-inputBox-paddingBottom',
    '--cd-chat-inputBox-paddingTop',
    '--cd-chat-inputBox-paddingX',
    '--cd-chat-max-width',
    '--cd-chat-paddingY',
  ],
  examples: [
    {
      title: '受控消息流',
      code: "<Chat\n  chats={chats}\n  roleConfig={{ user: { name: '我' }, assistant: { name: 'AI' } }}\n  onChatsChange={(next) => (chats = next)}\n  onMessageSend={(content) => reply(content)}\n/>",
    },
    {
      title: '提示区 + 清除上下文',
      code: "<Chat\n  chats={chats}\n  hints={['帮我写一封邮件', '总结这段文字']}\n  showClearContext\n  onHintClick={(h) => console.log(h)}\n  onChatsChange={(next) => (chats = next)}\n/>",
    },
    {
      title: 'shift+enter 发送 + 关闭上传',
      code: '<Chat chats={chats} sendHotKey="shift+enter" enableUpload={false} onChatsChange={(n) => (chats = n)} />',
    },
    {
      title: 'ref 命令式发送 / 滚动',
      code: '<Chat bind:this={chatRef} chats={chats} onChatsChange={(n) => (chats = n)} />\n<button onclick={() => chatRef.sendMessage(\'你好\')}>发送</button>\n<button onclick={() => chatRef.scrollToBottom(true)}>回到底部</button>',
    },
    {
      title: '自定义消息内容渲染',
      code: '{#snippet renderChatBoxContent({ message })}\n  <MyBubble text={message.content} />\n{/snippet}\n<Chat chats={chats} {renderChatBoxContent} onChatsChange={(n) => (chats = n)} />',
    },
  ],
} as const;
