/**
 * Machine-readable component metadata for AI/docs consumption.
 * Chat — aligned to Semi Design Chat（消息流 + 输入区 + 提示区，headless 逻辑在 @chenzy-design/core）。
 */
export const meta = {
  name: 'Chat',
  category: 'show',
  description:
    '对话/AI 聊天组件：消息流（头像/标题/内容/操作区，内容走 MarkdownRender）+ 输入区（textarea + Upload 附件 + 发送）+ 提示区（Hint）。框架无关逻辑在 @chenzy-design/core（buildSendContent/appendDivider/toggleLike/toggleDislike/resetLastMessage/shouldShowBackBottom/resolveEnableUpload/shouldSendOnEnter）。受控/非受控 chats（对齐 Upload value 模式），变换经 onChatsChange 回传。align(leftRight/leftAlign)、mode(bubble/noBubble/userBubble)、sendHotKey(enter/shift+enter)、enableUpload 三态。消息流 role=log/aria-live=polite；滚动出现回到底部悬浮按钮（SHOW_SCROLL_GAP=100）。ref 方法 resetMessage/scrollToBottom(animation)/clearContext/sendMessage。所有自定义渲染走 Svelte snippet（renderInputArea/renderChatBoxAvatar/Title/Content/Action/renderFullChatBox/renderHintBox/renderDivider）。',
  exports: ['Chat'],
  props: [
    { name: 'chats', type: 'Message[]', default: 'undefined', desc: '消息列表；传入即受控，否则内部维护' },
    { name: 'roleConfig', type: 'RoleConfig', default: 'undefined', desc: '角色元数据（名称/头像/色），按 message.role 取' },
    { name: 'align', type: "'leftRight'|'leftAlign'", default: "'leftRight'", desc: '布局对齐（左右分列 / 全左对齐）' },
    { name: 'mode', type: "'bubble'|'noBubble'|'userBubble'", default: "'bubble'", desc: '气泡模式' },
    { name: 'sendHotKey', type: "'enter'|'shift+enter'", default: "'enter'", desc: '发送快捷键' },
    { name: 'showClearContext', type: 'boolean', default: 'false', desc: '是否展示清除上下文按钮' },
    { name: 'showStopGenerate', type: 'boolean', default: 'false', desc: '是否展示停止生成按钮' },
    { name: 'hints', type: 'string[]', default: 'undefined', desc: '提示项列表（点击追加为一条 user 消息）' },
    { name: 'enableUpload', type: 'boolean|EnableUploadProps', default: 'true', desc: '上传能力（true/false 或 {pasteUpload,dragUpload,clickUpload} 三态）' },
    { name: 'uploadProps', type: 'UploadProps', default: 'undefined', desc: '透传内部 Upload 的 props' },
    { name: 'markdownRenderProps', type: 'MarkdownRenderProps', default: 'undefined', desc: '透传消息内容 MarkdownRender 的 props' },
    { name: 'placeholder', type: 'string', default: 'undefined', desc: '输入框占位（缺省走 locale Chat.placeholder）' },
    { name: 'topSlot', type: 'Snippet', default: 'undefined', desc: '顶部插槽' },
    { name: 'bottomSlot', type: 'Snippet', default: 'undefined', desc: '底部插槽（列表与输入区之间）' },
    { name: 'class', type: 'string', default: "''", desc: '根类名透传' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根内联样式' },
    { name: 'onChatsChange', type: '(chats: Message[]) => void', default: 'undefined', desc: 'chats 变化回调（受控父级据此更新）' },
    { name: 'onMessageSend', type: '(content: string, attachment: UploadFileItem[]) => void', default: 'undefined', desc: '发送消息回调' },
    { name: 'onInputChange', type: '(props: { value: string; attachment: UploadFileItem[] }) => void', default: 'undefined', desc: '输入变化回调' },
    { name: 'onClear', type: '() => void', default: 'undefined', desc: '清除上下文回调' },
    { name: 'onHintClick', type: '(hint: string) => void', default: 'undefined', desc: '点击提示项回调' },
    { name: 'onStopGenerator', type: '() => void', default: 'undefined', desc: '停止生成回调' },
    { name: 'onMessageCopy', type: '(message: Message) => void', default: 'undefined', desc: '复制消息回调' },
    { name: 'onMessageDelete', type: '(message: Message) => void', default: 'undefined', desc: '删除消息回调' },
    { name: 'onMessageReset', type: '(message: Message) => void', default: 'undefined', desc: '重生成消息回调' },
    { name: 'onMessageGoodFeedback', type: '(message: Message) => void', default: 'undefined', desc: '点赞回调' },
    { name: 'onMessageBadFeedback', type: '(message: Message) => void', default: 'undefined', desc: '点踩回调' },
    { name: 'renderInputArea', type: 'Snippet<[RenderInputAreaProps]>', default: 'undefined', desc: '自定义整块输入区' },
    { name: 'renderChatBoxAvatar', type: 'Snippet<[RenderAvatarProps]>', default: 'undefined', desc: '自定义消息头像' },
    { name: 'renderChatBoxTitle', type: 'Snippet<[RenderTitleProps]>', default: 'undefined', desc: '自定义消息标题' },
    { name: 'renderChatBoxContent', type: 'Snippet<[RenderContentProps]>', default: 'undefined', desc: '自定义消息内容' },
    { name: 'renderChatBoxAction', type: 'Snippet<[RenderActionProps]>', default: 'undefined', desc: '自定义消息操作区' },
    { name: 'renderFullChatBox', type: 'Snippet<[RenderFullChatBoxProps]>', default: 'undefined', desc: '自定义整条消息（提供拆分节点）' },
    { name: 'renderHintBox', type: 'Snippet<[RenderHintBoxProps]>', default: 'undefined', desc: '自定义单个提示项' },
    { name: 'renderDivider', type: 'Snippet<[Message]>', default: 'undefined', desc: '自定义清除上下文分割线' },
  ],
  events: [
    { name: 'onChatsChange', desc: '消息列表变化' },
    { name: 'onMessageSend', desc: '发送消息' },
    { name: 'onInputChange', desc: '输入内容/附件变化' },
    { name: 'onClear', desc: '清除上下文' },
    { name: 'onHintClick', desc: '点击提示项' },
    { name: 'onStopGenerator', desc: '停止生成' },
    { name: 'onMessageCopy', desc: '复制消息' },
    { name: 'onMessageDelete', desc: '删除消息' },
    { name: 'onMessageReset', desc: '重生成消息' },
    { name: 'onMessageGoodFeedback', desc: '点赞' },
    { name: 'onMessageBadFeedback', desc: '点踩' },
  ],
  slots: [
    { name: 'topSlot', desc: '顶部插槽' },
    { name: 'bottomSlot', desc: '列表与输入区之间插槽' },
    { name: 'renderInputArea', desc: '自定义整块输入区' },
    { name: 'renderChatBoxAvatar', desc: '自定义头像' },
    { name: 'renderChatBoxTitle', desc: '自定义标题' },
    { name: 'renderChatBoxContent', desc: '自定义内容' },
    { name: 'renderChatBoxAction', desc: '自定义操作区' },
    { name: 'renderFullChatBox', desc: '自定义整条消息' },
    { name: 'renderHintBox', desc: '自定义提示项' },
    { name: 'renderDivider', desc: '自定义分割线' },
  ],
  methods: [
    { name: 'resetMessage', signature: '() => void', desc: '将最后一条消息重置为 loading（对齐 Semi resetMessage）' },
    { name: 'scrollToBottom', signature: '(animation?: boolean) => void', desc: '滚动到底部；animation=true 带缓动' },
    { name: 'clearContext', signature: '() => void', desc: '清除上下文（末尾追加 divider）' },
    { name: 'sendMessage', signature: '(content: string, attachment?: UploadFileItem[]) => void', desc: '以文本 + 附件发送一条消息' },
  ],
  a11y: {
    role: 'log',
    keyboard: ['Enter', 'Shift+Enter'],
    focusable: true,
    notes: [
      '消息流容器 role=log / aria-live=polite / aria-label 走 locale Chat.messageList，新消息被屏幕阅读器播报',
      '输入区 textarea，Enter/Shift+Enter 由 sendHotKey + core.shouldSendOnEnter 判定（组合输入 isComposing 时不发送）',
      '发送/上传/清除/复制/删除/重生成/赞/踩 均为原生 <button>，aria-label 走 locale；赞/踩 aria-pressed 反映激活态',
      '回到底部悬浮按钮为原生 <button>，滚动距底 > SHOW_SCROLL_GAP(100) 时出现，aria-label=Chat.backToBottom',
      '发送按钮 disabled 对齐 Semi getDisableSend：无文本且无附件 / 附件有未 success / 显式 disableSend',
    ],
  },
  tokens: [
    '--cd-chat-bg',
    '--cd-chat-gap',
    '--cd-chat-bubble-user-bg',
    '--cd-chat-bubble-user-color',
    '--cd-chat-bubble-assistant-bg',
    '--cd-chat-bubble-assistant-color',
    '--cd-chat-bubble-radius',
    '--cd-chat-bubble-padding-y',
    '--cd-chat-bubble-padding-x',
    '--cd-chat-avatar-size',
    '--cd-chat-avatar-radius',
    '--cd-chat-avatar-bg',
    '--cd-chat-title-color',
    '--cd-chat-title-font-size',
    '--cd-chat-divider',
    '--cd-chat-divider-color',
    '--cd-chat-action-icon',
    '--cd-chat-action-icon-hover',
    '--cd-chat-action-icon-active',
    '--cd-chat-input-bg',
    '--cd-chat-input-color',
    '--cd-chat-input-radius',
    '--cd-chat-input-border',
    '--cd-chat-input-border-focus',
    '--cd-chat-hint-bg',
    '--cd-chat-hint-bg-hover',
    '--cd-chat-hint-color',
    '--cd-chat-hint-radius',
    '--cd-chat-back-bottom-bg',
    '--cd-chat-back-bottom-color',
    '--cd-chat-back-bottom-shadow',
    '--cd-chat-status-error-color',
    '--cd-chat-motion-duration',
  ],
  examples: [
    {
      title: '受控消息流',
      code: "<Chat\n  chats={chats}\n  roleConfig={{ user: { name: '我' }, assistant: { name: 'AI' } }}\n  onChatsChange={(next) => (chats = next)}\n  onMessageSend={(content) => reply(content)}\n/>",
    },
    {
      title: '提示区 + 清除上下文',
      code: "<Chat\n  chats={chats}\n  hints={['帮我写一封邮件', '总结这段文字']}\n  showClearContext\n  onHintClick={(h) => console.log(h)}\n  onChatsChange={(next) => (chats = next)}\n/>",
    },
    {
      title: 'shift+enter 发送 + 关闭上传',
      code: '<Chat chats={chats} sendHotKey="shift+enter" enableUpload={false} onChatsChange={(n) => (chats = n)} />',
    },
    {
      title: 'ref 命令式发送 / 滚动',
      code: '<Chat bind:this={chatRef} chats={chats} onChatsChange={(n) => (chats = n)} />\n<button onclick={() => chatRef.sendMessage(\'你好\')}>发送</button>\n<button onclick={() => chatRef.scrollToBottom(true)}>回到底部</button>',
    },
    {
      title: '自定义消息内容渲染',
      code: '{#snippet renderChatBoxContent({ message })}\n  <MyBubble text={message.content} />\n{/snippet}\n<Chat chats={chats} {renderChatBoxContent} onChatsChange={(n) => (chats = n)} />',
    },
  ],
} as const;
