/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Anchor',
  category: 'navigation',
  description:
    '锚点导航，垂直/水平链接列表。支持 scroll-spy 激活高亮、点击平滑滚动、ink 边框指示、自定义滚动容器、多级嵌套链接树，受控/非受控。',
  props: [
    {
      name: 'links',
      type: 'AnchorLink[]',
      default: '[]',
      desc: '锚点链接数据；link.children 形成多级嵌套树，渲染逐级缩进，父子皆参与滚动高亮（无 children 即平铺）',
    },
    {
      name: 'value',
      type: 'string',
      default: 'undefined',
      desc: '受控当前激活 key',
    },
    { name: 'defaultValue', type: 'string', default: 'undefined' },
    { name: 'offsetTop', type: 'number', default: '0', desc: '滚动判定/定位偏移' },
    { name: 'bounds', type: 'number', default: '5', desc: '激活判定边界容差' },
    { name: 'showInk', type: 'boolean', default: 'true', desc: '是否显示 ink 边框' },
    {
      name: 'scrollMotion',
      type: 'boolean',
      default: 'true',
      desc: '点击是否平滑滚动（reduced-motion 下强制即时）',
    },
    { name: 'affix', type: 'boolean', default: 'false', desc: 'position:sticky 吸顶' },
    { name: 'updateHash', type: 'boolean', default: 'false', desc: '激活变更时写 location.hash' },
    { name: 'targetOffset', type: 'number', default: 'offsetTop', desc: '点击滚动独立偏移' },
    {
      name: 'getContainer',
      type: '() => HTMLElement | null',
      default: 'undefined',
      desc: '自定义滚动容器（缺省 window）',
    },
    { name: 'horizontal', type: 'boolean', default: 'false', desc: '水平模式，ink 走底部下划线' },
    { name: 'onChange', type: '(key: string) => void', default: 'undefined' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
  ],
  a11y: {
    role: 'navigation',
    keyboard: ['Tab', 'Enter'],
    notes: [
      'nav[aria-label] 包裹原生 a 链接列表',
      '激活链接 aria-current=true',
      '键盘交互为原生锚链接行为',
      'scroll-spy 命令式监听 scroll（getContainer 时监听容器），rAF 节流，reduced-motion 下点击即时定位',
      'horizontal 水平模式仅改布局/ink 方向，激活态与键盘交互不变',
      '多级嵌套用嵌套 ul/li 表达层级树，子链接逐级缩进；扁平化树参与 scroll-spy，父子链接均可聚焦/跳转/高亮',
    ],
  },
  tokens: [
    // —— 组件消费的补充 token（Semi 无） ——
    '--cd-anchor-link-color',
    '--cd-anchor-link-color-active',
    '--cd-anchor-link-padding',
    '--cd-anchor-indent',
    '--cd-anchor-rail-color',
    '--cd-anchor-ink-color',
    '--cd-anchor-ink-width',
    // —— 全量对齐 Semi anchor/variables.scss（26 个） ——
    '--cd-color-anchor-slide-default-bg-default',
    '--cd-color-anchor-slide-primary-bg-active',
    '--cd-color-anchor-slide-tertiary-bg-active',
    '--cd-color-anchor-slide-muted-bg-active',
    '--cd-color-anchor-title-text-default',
    '--cd-color-anchor-title-text-hover',
    '--cd-color-anchor-title-active-text-hover',
    '--cd-color-anchor-title-text-active',
    '--cd-color-anchor-title-text-disabled',
    '--cd-color-anchor-title-bg-default',
    '--cd-color-anchor-title-bg-active',
    '--cd-color-anchor-title-outline-focus',
    '--cd-spacing-anchor-slide-left',
    '--cd-spacing-anchor-slide-top',
    '--cd-spacing-anchor-slide-default-y',
    '--cd-spacing-anchor-slide-small-y',
    '--cd-spacing-anchor-link-paddingleft',
    '--cd-spacing-anchor-link-title-paddingtop',
    '--cd-spacing-anchor-link-title-paddingbottom',
    '--cd-width-anchor-slide-default',
    '--cd-height-anchor-slide-default',
    '--cd-height-anchor-slide-small',
    '--cd-radius-anchor-slide',
    '--cd-width-anchor-outline',
    '--cd-width-anchor-outlineoffset',
    '--cd-width-anchor-outline-border-radius',
    // —— 全局/别名 token ——
    '--cd-focus-ring',
    '--cd-border-radius-small',
    '--cd-motion-*',
  ],
} as const;
