/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Anchor',
  category: 'navigation',
  description:
    '锚点导航，垂直/水平链接列表。支持 scroll-spy 激活高亮、点击平滑滚动、ink 边框指示、自定义滚动容器、多级嵌套链接树，受控/非受控。双 API：links 数组或声明式 <Anchor.Link>。',
  props: [
    {
      name: 'links',
      type: 'AnchorLink[]',
      default: '[]',
      desc: '锚点链接数据；link.children 形成多级嵌套树，渲染逐级缩进，父子皆参与滚动高亮（无 children 即平铺）。与声明式 <Anchor.Link> 二选一，links 优先',
    },
    {
      name: 'value',
      type: 'string',
      default: 'undefined',
      desc: '受控当前激活 key',
    },
    { name: 'defaultValue', type: 'string', default: 'undefined' },
    { name: 'offsetTop', type: 'number', default: '0', desc: '滚动判定/定位偏移' },
    { name: 'bounds', type: 'number', default: '5', desc: '激活判定边界容差' },
    { name: 'showInk', type: 'boolean', default: 'true', desc: '是否显示 ink 边框' },
    {
      name: 'scrollMotion',
      type: 'boolean',
      default: 'false',
      desc: '点击是否平滑滚动（默认 false 对齐 Semi；reduced-motion 下强制即时）',
    },
    { name: 'affix', type: 'boolean', default: 'false', desc: 'position:sticky 吸顶' },
    { name: 'updateHash', type: 'boolean', default: 'false', desc: '激活变更时写 location.hash' },
    { name: 'targetOffset', type: 'number', default: 'offsetTop', desc: '点击滚动独立偏移' },
    {
      name: 'getContainer',
      type: '() => HTMLElement | null',
      default: 'undefined',
      desc: '自定义滚动容器（缺省 window）',
    },
    { name: 'horizontal', type: 'boolean', default: 'false', desc: '水平模式，ink 走底部下划线' },
    {
      name: 'railTheme',
      type: "'primary' | 'tertiary' | 'muted'",
      default: "'primary'",
      desc: 'active ink 颜色主题（对齐 Semi）',
    },
    {
      name: 'size',
      type: "'small' | 'default'",
      default: "'default'",
      desc: '尺寸，影响选项高度与上下间距（对齐 Semi）',
    },
    {
      name: 'maxHeight',
      type: 'string | number',
      default: "'750px'",
      desc: '内容最大高度，超出滚动（数字转 px，对齐 Semi）',
    },
    {
      name: 'maxWidth',
      type: 'string | number',
      default: "'200px'",
      desc: '内容最大宽度，超出 ellipsis（数字转 px，对齐 Semi）',
    },
    { name: 'style', type: 'string', default: 'undefined', desc: '根 nav 自定义内联样式（与 affix inset 合并）' },
    {
      name: 'onClick',
      type: '(event: MouseEvent, link: AnchorLink) => void',
      default: 'undefined',
      desc: '点击链接回调（e.preventDefault 之后触发，对齐 Semi）',
    },
    {
      name: 'showTooltip',
      type: "boolean | { type: 'tooltip' | 'popover'; opts?: Record<string, unknown> }",
      default: 'false',
      desc: '链接文字缩略时 hover 显示完整标题（对齐 Semi）；对象形式指定浮层类型与透传配置',
    },
    {
      name: 'position',
      type: 'Placement',
      default: 'undefined',
      desc: '浮层弹出位置（12 方位）；仅 showTooltip 开启时生效（对齐 Semi）',
    },
    {
      name: 'onChange',
      type: '(currentLink: AnchorLink | null, previousLink: AnchorLink | null) => void',
      default: 'undefined',
      desc: '激活变更回调（对齐 Semi：传入当前/上一个 link 对象）',
    },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
  ],
  subComponents: [
    {
      name: 'Anchor.Link',
      description:
        '声明式锚点链接（对齐 Semi Anchor.Link）。无 children 为叶子，有 children 为分支（嵌套树）。与 links 数组二选一。',
      props: [
        { name: 'key', type: 'string', default: 'href', desc: '唯一标识，缺省用 href' },
        { name: 'href', type: 'string', default: '—', desc: "目标锚点，形如 '#section-1'" },
        { name: 'title', type: 'string', default: '—', desc: '链接标题文案' },
        { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用：不响应跳转、置灰、排除 roving' },
        { name: 'className', type: 'string', default: 'undefined', desc: 'Link 级自定义类名，透传到 <a>' },
        { name: 'style', type: 'string', default: 'undefined', desc: 'Link 级自定义内联样式，透传到 <a>' },
      ],
    },
  ],
  a11y: {
    role: 'navigation',
    keyboard: ['Tab', 'Enter'],
    notes: [
      'nav[aria-label] 包裹原生 a 链接列表',
      '激活链接 aria-current=true',
      '键盘交互为原生锚链接行为',
      'scroll-spy 命令式监听 scroll（getContainer 时监听容器），rAF 节流，reduced-motion 下点击即时定位',
      'horizontal 水平模式仅改布局/ink 方向，激活态与键盘交互不变',
      '多级嵌套用嵌套 ul/li 表达层级树，子链接逐级缩进；扁平化树参与 scroll-spy，父子链接均可聚焦/跳转/高亮',
    ],
  },
  tokens: [
    // —— 组件消费的补充 token（Semi 无） ——
    '--cd-anchor-link-color',
    '--cd-anchor-link-color-active',
    '--cd-anchor-link-padding',
    '--cd-anchor-indent',
    '--cd-anchor-rail-color',
    '--cd-anchor-ink-color',
    '--cd-anchor-ink-width',
    // —— 全量对齐 Semi anchor/variables.scss（26 个） ——
    '--cd-color-anchor-slide-default-bg-default',
    '--cd-color-anchor-slide-primary-bg-active',
    '--cd-color-anchor-slide-tertiary-bg-active',
    '--cd-color-anchor-slide-muted-bg-active',
    '--cd-color-anchor-title-text-default',
    '--cd-color-anchor-title-text-hover',
    '--cd-color-anchor-title-active-text-hover',
    '--cd-color-anchor-title-text-active',
    '--cd-color-anchor-title-text-disabled',
    '--cd-color-anchor-title-bg-default',
    '--cd-color-anchor-title-bg-active',
    '--cd-color-anchor-title-outline-focus',
    '--cd-spacing-anchor-slide-left',
    '--cd-spacing-anchor-slide-top',
    '--cd-spacing-anchor-slide-default-y',
    '--cd-spacing-anchor-slide-small-y',
    '--cd-spacing-anchor-link-paddingleft',
    '--cd-spacing-anchor-link-title-paddingtop',
    '--cd-spacing-anchor-link-title-paddingbottom',
    '--cd-width-anchor-slide-default',
    '--cd-height-anchor-slide-default',
    '--cd-height-anchor-slide-small',
    '--cd-radius-anchor-slide',
    '--cd-width-anchor-outline',
    '--cd-width-anchor-outlineoffset',
    '--cd-width-anchor-outline-border-radius',
    // —— 全局/别名 token ——
    '--cd-focus-ring',
    '--cd-border-radius-small',
    '--cd-motion-*',
  ],
} as const;
