/**
 * Machine-readable component metadata for AI/docs consumption.
 * SideBar — see specs/components/show/SideBar.spec.md
 *
 * 分阶段交付（P0～P5 全部落地）：本 meta 覆盖 P0（SideBarContainer 可伸缩浮层壳）+ P1（SideBar
 * 主壳 mode 路由 + Options 图标 tab 组）+ P2（Annotation 引用溯源）+ P3（SideBarMCPConfigure MCP
 * 工具配置）+ P4（SideBarCodeContent 代码/JSON 预览折叠列表）+ P5（SideBarFileContent 富文本查看/
 * 编辑折叠列表，含 SideBarFileItem tiptap 编辑器 + 内嵌 Upload 的 ImageUploadNode，全程动态 import）。
 * 全部 subComponents 已补齐（见下 subComponents），无留后项。
 */
export const meta = {
  name: 'SideBar',
  category: 'ai',
  stage: 'M4',
  semiEquivalent: 'Sidebar',
  aiScene: true,
  description:
    'AI 侧边信息栏套件（重量级组合，分阶段交付）：P0 SideBarContainer 为可伸缩浮层壳——贴视口右侧（RTL 贴左），role=dialog + aria-labelledby(title)，打开移焦 + focus-trap 焦点捕获/归还 + Esc 关闭，堆叠 z-index 与 Modal/SideSheet 统一层栈（后开者在上），resizable 时左边缘（RTL 右边缘）把手拖拽调宽——复用 core createResizeDrag（axis:x 单轴 + clamp minWidth/maxWidth）与 Resizable 同套把手 a11y（role=separator + aria-orientation=vertical + aria-valuenow + 键盘 ←→/Home/End），motion 展开/收起为 CSS transition（reduced-motion / motion=false 退化即时显隐）。P1 SideBar 主壳按 mode 路由：main 渲染顶部 Options 图标 tab 组（每项是本库 Button，图标 + name 可见文字，之上叠加 role=tablist + roving tabindex + 键盘）+ renderMainContent(activeKey)；detail（code/file/自定义）渲染 renderDetailHeader + 返回按钮（onBackWard 可异步，await 期间禁用防重触发）+ renderDetailContent(mode)。受控 visible / activeKey（不回写，仅回调通知）。P2 SideBarAnnotation 参考来源/引用溯源：外层复用 SideBarContainer 浮层壳（透传全部 Container props，title 默认走 i18n annotationTitle），内部渲染 SideBarAnnotationContent（对齐 Semi Annotation.AnnotationContent 静态属性，可脱离 Container 独立使用，例如嵌入 renderMainContent）——用 Collapse 渲染 info 分组（每组一折叠面板 + aria-expanded，clickHeaderToExpand=false），展开区渲染 video（封面/时长/具名 IconPlay 播放按钮贴右上角/时长徽标）/text（站点 logo/名称/引用序号）卡片；可点击卡片（url 或 onClick）用原生 button（键盘 Enter/Space + focus 环 + 时长/序号本地化可访问文本），renderItem 可整条覆盖。P4 SideBarCodeContent 代码/JSON 预览：Collapse 折叠列表（clickHeaderToExpand=false），每项按 isJson 分流 JsonViewer / CodeHighlight（透传 jsonViewerProps/codeHighlightProps），头部具名图标 + Button(theme=borderless type=tertiary) 展开（全屏）按钮，onExpand 回调。P3 SideBarMCPConfigure MCP 工具配置面板：外层复用 SideBarContainer（title 默认走 i18n mcpTitle），内部顶部已启用计数 + RadioGroup(type=button) 在内置/自定义两模式间切换（对齐 Semi，同一时刻只渲染一份列表）+ 搜索框（Input，前缀放大镜 + aria-label，headless filterMcpOptions 支持自定义 filter）；每项前置图标（string→img / Snippet）+ label + desc + 动作按钮（内置 Button+IconSetting 显示配置 / 自定义 Button+IconEdit 显示编辑，aria-label 含工具名）+ 启用开关（Button(theme=active?light:solid type=primary) + IconMinus/IconPlus，对齐 Semi renderStatusButton，非开关组件；disabled 预设项锁定 + Tooltip 提示），启用变化经 core toggleMcpOptionActive 产出「下一份数组 + custom 标记」上抛 onStatusChange 不回写；自定义组空态用 Empty + IllustrationNoContent(Dark) 插画 + 添加按钮，无搜索结果显示提示。P5 SideBarFileContent 富文本查看/编辑：Collapse 折叠列表（clickHeaderToExpand=false），每项 SideBarFileItem 一个 tiptap v3 编辑器（editable 控查看/编辑，编辑态渲染格式工具栏），默认扩展集对齐 Semi（StarterKit link openOnClick:false + TextStyleKit + Image + TextAlign + 自研 SelectionMark + 自研 ImageUploadNode，末尾拼接 extensions），onContentChange 回调 editor.getHTML()；ImageUploadNode 用 svelte-tiptap NodeViewRenderer 内嵌本库 Upload（draggable + getUploadImageSrc，默认 listType 不显式传，随 Upload 默认值）；tiptap 内核 + 3 官方扩展（text-style/image/text-align）+ svelte-tiptap 全程动态 import 不进主 bundle。',
  exports: ['SideBar', 'SideBarContainer', 'SideBarAnnotation', 'SideBarAnnotationContent', 'SideBarCodeContent', 'SideBarCodeItem', 'SideBarMCPConfigure', 'SideBarFileContent', 'SideBarFileItem'],
  a11yPattern: 'dialog + tablist',
  apgRef: 'dialog (modal) + tabs',
  relatedComponents: ['SideSheet', 'Resizable', 'Nav', 'Tabs'],
  stages: [
    { phase: 'P0', name: 'Container', done: true, desc: '可伸缩浮层壳（resizable 复用 Resizable + 动画 + header/close + Esc + a11y）' },
    { phase: 'P1', name: '主壳 + Options', done: true, desc: 'SideBar 主组件 mode 路由（main/detail）+ 顶部 Options 图标 tab 组（Button 渲染）' },
    { phase: 'P2', name: 'Annotation', done: true, desc: '参考来源/引用溯源折叠列表（video/text 卡片，复用 Collapse）；SideBarAnnotationContent 纯内容层可脱离 Container 独立使用' },
    { phase: 'P3', name: 'MCPConfigure', done: true, desc: 'MCP 工具配置面板（RadioGroup 单选切换内置/自定义 + 搜索 + 启用按钮，复用 Input/Button/Empty/Tooltip）' },
    { phase: 'P4', name: 'CodeContent', done: true, desc: '代码/JSON 预览折叠列表（复用 CodeHighlight/JsonViewer + Collapse + Button 展开按钮）' },
    { phase: 'P5', name: 'FileContent', done: true, desc: '富文本查看/编辑折叠列表（tiptap v3 + 3 官方扩展 + 自研 ImageUploadNode，全程动态 import）' },
  ],
  usageHints:
    '用于 AI 产品右侧信息/配置面板（工具配置、引用溯源、内容预览）。仅需可伸缩浮层用 SideBarContainer；通用抽屉用 SideSheet；侧边导航用 Nav。Container 与主壳分层解耦——SideBarContainer 提供浮层壳，SideBar 提供 mode 路由内容，通常内嵌 <SideBarContainer><SideBar/></SideBarContainer>。三个内容套件（Annotation/CodeContent/FileContent）均提供「纯内容层」可脱离 Container 独立使用（例如嵌入 SideBar 的 renderMainContent）：SideBarAnnotationContent、SideBarCodeContent、SideBarFileContent 本身即不含浮层壳；SideBarAnnotation 则是 SideBarContainer + SideBarAnnotationContent 的组合便捷层。',
  subComponents: [
    {
      name: 'SideBar',
      props: [
        { name: 'mode', type: "'main' | 'code' | 'file' | string", default: "'main'", desc: '展示模式，main 主视图，其余详情视图' },
        { name: 'activeKey', type: 'string', default: 'undefined', desc: '主视图激活 option（受控，不回写）' },
        { name: 'options', type: 'SideBarOption[]', default: '[]', desc: '顶部图标 tab 组（{ icon, name, key }）' },
        { name: 'onActiveOptionChange', type: '(e: Event, key: string) => void', default: 'undefined', desc: 'option 切换回调' },
        { name: 'renderMainContent', type: 'Snippet<[string | undefined]>', default: 'undefined', desc: '主视图内容（按 activeKey 渲染）' },
        { name: 'renderDetailContent', type: 'Snippet<[mode]>', default: 'undefined', desc: '详情内容（按 mode 渲染）' },
        { name: 'renderDetailHeader', type: 'Snippet<[mode, detailContent]>', default: 'undefined', desc: '详情头部（返回按钮之后）' },
        { name: 'detailContent', type: 'SideBarDetailContent', default: 'undefined', desc: "详情区域的内容（对齐 Semi detailContent）：mode='code' 走 CodeHighlight/JsonViewer，'file' 走可编辑富文本" },
        { name: 'fileEditable', type: 'boolean', default: 'true', desc: '文件内容是否可编辑（对齐 Semi fileEditable）' },
        { name: 'imgUploadProps', type: 'SideBarImageUploadOptions', default: 'undefined', desc: '图片上传相关配置，透传 FileItem（对齐 Semi imgUploadProps）' },
        { name: 'onFileContentChange', type: '(content: string) => void', default: 'undefined', desc: '文件内容变更回调（对齐 Semi onFileContentChange）' },
        { name: 'onDetailContentCopy', type: '(e: MouseEvent, content: string, res: boolean) => void', default: 'undefined', desc: '详情内容复制回调（对齐 Semi onDetailContentCopy）' },
        { name: 'onBackWard', type: '(e: Event, mode) => void | Promise<void>', default: 'undefined', desc: '详情返回主视图（可异步，await 期间禁用防重触发）' },
        { name: 'class', type: 'string', default: 'undefined', desc: '根自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '根自定义内联样式' },
      ],
    },
    {
      name: 'SideBarContainer',
      props: [
        { name: 'visible', type: 'boolean', default: 'false', desc: '是否可见（受控，不回写；仅经 onCancel 通知）' },
        { name: 'title', type: 'string | Snippet', default: 'undefined', desc: '标题' },
        { name: 'onCancel', type: '(e: Event) => void', default: 'undefined', desc: '关闭回调（Esc / 关闭按钮）' },
        { name: 'afterVisibleChange', type: '(v: boolean) => void', default: 'undefined', desc: '动画结束后（入场或出场）触发' },
        { name: 'motion', type: 'boolean', default: 'true', desc: '展开/收起动画；false 等价即时显隐' },
        { name: 'resizable', type: 'boolean', default: 'true', desc: '宽度可拖拽（复用 Resizable 把手 + 键盘 a11y）' },
        { name: 'minWidth', type: 'string | number', default: '150', desc: '最小宽度' },
        { name: 'maxWidth', type: 'string | number', default: 'undefined', desc: '最大宽度' },
        { name: 'defaultSize', type: '{ width?; height? }', default: 'undefined', desc: '默认尺寸（当前消费 width）' },
        { name: 'showClose', type: 'boolean', default: 'true', desc: '显示关闭按钮' },
        { name: 'renderHeader', type: 'Snippet', default: 'undefined', desc: '自定义头部（覆盖 title + 关闭按钮）' },
        { name: 'class', type: 'string', default: 'undefined', desc: '面板自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '面板自定义内联样式' },
      ],
    },
    {
      name: 'SideBarAnnotation',
      props: [
        { name: 'info', type: 'SideBarAnnotationGroup[]', default: '[]', desc: '分组数组（{ header, key, annotations }[]），每组一个折叠面板' },
        { name: 'activeKey', type: 'string | string[]', default: 'undefined', desc: '展开的分组 key（受控，不回写；透传 Collapse）' },
        { name: 'onChange', type: '(keys: string[]) => void', default: 'undefined', desc: '展开变更回调（当前展开 key 数组）' },
        { name: 'onClick', type: '(e: Event, item) => void', default: 'undefined', desc: '点击某条引用（url 存在先在新窗口打开来源）' },
        { name: 'renderItem', type: 'Snippet<[SideBarAnnotationItem]>', default: 'undefined', desc: '自定义单条渲染（覆盖默认 video/text 卡片）' },
        { name: '...Container', type: 'SideBarContainer props', default: '—', desc: '继承并透传全部 Container props（visible/title/onCancel/resizable/... ）；title 默认走 i18n annotationTitle。内部组合 SideBarContainer + SideBarAnnotationContent' },
      ],
    },
    {
      name: 'SideBarAnnotationContent',
      props: [
        { name: 'info', type: 'SideBarAnnotationGroup[]', default: '[]', desc: '同 SideBarAnnotation.info（对齐 Semi Annotation.AnnotationContent 静态属性）' },
        { name: 'activeKey', type: 'string | string[]', default: 'undefined', desc: '同 SideBarAnnotation.activeKey' },
        { name: 'onChange', type: '(keys: string[]) => void', default: 'undefined', desc: '同 SideBarAnnotation.onChange' },
        { name: 'onClick', type: '(e: Event, item) => void', default: 'undefined', desc: '同 SideBarAnnotation.onClick' },
        { name: 'renderItem', type: 'Snippet<[SideBarAnnotationItem]>', default: 'undefined', desc: '同 SideBarAnnotation.renderItem' },
        { name: 'class', type: 'string', default: 'undefined', desc: '根自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '根自定义内联样式' },
      ],
    },
    {
      name: 'SideBarCodeContent',
      props: [
        { name: 'codes', type: 'CodeItemProps[]', default: '[]', desc: '代码/JSON 预览项列表；每项按 isJson 分流 JsonViewer / CodeHighlight' },
        { name: 'activeKey', type: 'string | string[]', default: 'undefined', desc: '受控展开项 key（受控，不回写；仅经 onChange 通知，内部兜底非受控）' },
        { name: 'onChange', type: '(keys: string[]) => void', default: 'undefined', desc: '展开态变化回调（Collapse onChange）' },
        { name: 'onExpand', type: '(e: MouseEvent, code: CodeItemProps, mode: string) => void', default: 'undefined', desc: '点击某项展开（全屏）按钮回调；mode 固定 "code"（对齐 Semi onExpand）' },
        { name: 'class', type: 'string', default: 'undefined', desc: '根自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '根自定义内联样式' },
      ],
    },
    {
      name: 'SideBarCodeItem',
      props: [
        { name: 'code', type: 'CodeItemProps', default: '—', desc: '单条代码/JSON 内容（不含折叠头）：isJson 为 true 走 JsonViewer，否则走 CodeHighlight（对齐 Semi widget/code.tsx 导出的 CodeItem）' },
        { name: 'class', type: 'string', default: 'undefined', desc: '根自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '根自定义内联样式' },
      ],
    },
    {
      name: 'SideBarMCPConfigure',
      props: [
        { name: 'options', type: 'SideBarMCPOption[]', default: '[]', desc: '内置 MCP 工具列表（受控）；每项 { value, label, icon?, desc?, active?, disabled?, configure? }' },
        { name: 'customOptions', type: 'SideBarMCPOption[]', default: '[]', desc: '自定义 MCP 工具列表（受控）；空时显示添加入口' },
        { name: 'filter', type: '(input: string, option: SideBarMCPOption) => boolean', default: 'undefined', desc: '自定义搜索过滤谓词（覆盖默认 label/value 大小写不敏感包含匹配）' },
        { name: 'placeholder', type: 'string', default: 'undefined', desc: '搜索占位（覆盖 i18n mcpSearchPlaceholder，修 Semi 硬编码「请输入」）' },
        { name: 'onSearch', type: '(input: string, custom: boolean) => void', default: 'undefined', desc: '搜索输入回调（custom 恒 false）' },
        { name: 'onStatusChange', type: '(options: SideBarMCPOption[], custom: boolean) => void', default: 'undefined', desc: '启用/关闭变化：产出该组「下一份数组」+ custom 标记（不回写 prop）' },
        { name: 'onAddClick', type: '(e: MouseEvent) => void', default: 'undefined', desc: '自定义组「添加」按钮回调' },
        { name: 'onConfigureClick', type: '(e: MouseEvent, option: SideBarMCPOption) => void', default: 'undefined', desc: '内置工具（configure=true）「配置」按钮回调' },
        { name: 'onEditClick', type: '(e: MouseEvent, option: SideBarMCPOption) => void', default: 'undefined', desc: '自定义工具「编辑」按钮回调' },
        { name: 'renderItem', type: 'Snippet<[{ option; custom }]>', default: 'undefined', desc: '自定义单项渲染（覆盖默认项，custom 标记来自自定义组）' },
        { name: '...Container', type: 'SideBarContainer props', default: '—', desc: '继承并透传全部 Container props（visible/title/onCancel/resizable/... ）；title 默认走 i18n mcpTitle' },
      ],
    },
    {
      name: 'SideBarFileContent',
      props: [
        { name: 'files', type: 'FileItemProps[]', default: '[]', desc: '富文本文件项列表；每项 { key, name, content, editable, onContentChange, extensions, imgUploadProps }，一个 tiptap 编辑器（editable 控制查看/编辑，默认只读）' },
        { name: 'activeKey', type: 'string | string[]', default: 'undefined', desc: '受控展开项 key（受控，不回写；仅经 onChange 通知，内部兜底非受控）' },
        { name: 'onChange', type: '(keys: string[]) => void', default: 'undefined', desc: '展开态变化回调（Collapse onChange）' },
        { name: 'onExpand', type: '(e: MouseEvent, file: FileItemProps, mode: string) => void', default: 'undefined', desc: '点击某项展开（全屏）按钮回调；mode 固定 "file"（对齐 Semi onExpand）' },
        { name: 'class', type: 'string', default: 'undefined', desc: '根自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '根自定义内联样式' },
      ],
    },
    {
      name: 'SideBarFileItem',
      props: [
        { name: 'content', type: 'string', default: 'undefined', desc: '初始富文本内容（HTML）' },
        { name: 'editable', type: 'boolean', default: 'true', desc: '是否可编辑（false=只读查看，渲染工具栏与否由此决定）' },
        { name: 'onContentChange', type: '(html: string) => void', default: 'undefined', desc: '内容变更回调（editor.getHTML()）' },
        { name: 'extensions', type: 'Extension[]', default: '[]', desc: '追加到默认扩展集末尾的自定义 tiptap 扩展（对齐 Semi extensions）' },
        { name: 'imgUploadProps', type: 'SideBarImageUploadOptions', default: 'undefined', desc: '图片上传配置（透传 ImageUploadNode / 内嵌 Upload；含 action/accept/getUploadImageSrc 等）' },
        { name: 'class', type: 'string', default: 'undefined', desc: '根自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '根自定义内联样式' },
      ],
    },
  ],
  tokens: [
    '--cd-color-sidebar-annotation-video-border',
    '--cd-color-sidebar-collapse-item-border',
    '--cd-color-sidebar-collapse-item-content-border-top',
    '--cd-color-sidebar-container-border-left',
    '--cd-color-sidebar-container-header-border-bottom',
    '--cd-color-sidebar-file-blockquote-border-left',
    '--cd-color-sidebar-file-code-bg',
    '--cd-color-sidebar-file-hr-border-top',
    '--cd-color-sidebar-file-placeholder-text',
    '--cd-color-sidebar-file-pre-bg',
    '--cd-color-sidebar-file-pre-border',
    '--cd-color-sidebar-file-text',
    '--cd-color-sidebar-annotation-video-border',
    '--cd-color-sidebar-mcp-item-border-bottom',
    '--cd-color-sidebar-menu-bar-border-bottom',
    '--cd-color-sidebar-menu-bar-border-top',
    '--cd-color-sidebar-options-border-bottom',
    '--cd-font-sidebar-file-fontsize',
    '--cd-font-sidebar-file-lineheight',
    '--cd-font-sidebar-file-pre-fontsize',
    '--cd-font-sidebar-file-pre-lineheight',
    '--cd-height-sidebar-annotation-footer-order',
    '--cd-radius-sidebar-annotation-footer-order',
    '--cd-radius-sidebar-annotation-video-duration',
    '--cd-radius-sidebar-collapse-item',
    '--cd-radius-sidebar-file-pre',
    '--cd-sidebar-annotation-container-padding',
    '--cd-sidebar-annotation-content-gap',
    '--cd-sidebar-annotation-cover-bg',
    '--cd-sidebar-annotation-detail-color',
    '--cd-sidebar-annotation-detail-size',
    '--cd-sidebar-annotation-footer-color',
    '--cd-sidebar-annotation-footer-column-gap',
    '--cd-sidebar-annotation-footer-logo',
    '--cd-sidebar-annotation-footer-logo-font-size',
    '--cd-sidebar-annotation-footer-order-min-width',
    '--cd-sidebar-annotation-footer-order-padding-x',
    '--cd-sidebar-annotation-footer-order-padding-y',
    '--cd-sidebar-annotation-order-bg',
    '--cd-sidebar-annotation-order-color',
    '--cd-sidebar-annotation-text-padding-x',
    '--cd-sidebar-annotation-text-padding-y',
    '--cd-sidebar-annotation-video',
    '--cd-sidebar-annotation-video-content-padding-bottom',
    '--cd-sidebar-annotation-video-content-padding-left',
    '--cd-sidebar-annotation-video-content-padding-right',
    '--cd-sidebar-annotation-video-content-padding-top',
    '--cd-sidebar-annotation-video-duration-bg',
    '--cd-sidebar-annotation-video-duration-bottom',
    '--cd-sidebar-annotation-video-duration-padding-x',
    '--cd-sidebar-annotation-video-duration-padding-y',
    '--cd-sidebar-annotation-video-duration-right',
    '--cd-sidebar-annotation-video-duration-text',
    '--cd-sidebar-annotation-video-img-wrapper',
    '--cd-sidebar-annotation-video-item-title',
    '--cd-sidebar-annotation-video-play',
    '--cd-sidebar-annotation-video-play-icon-font-size',
    '--cd-sidebar-annotation-video-play-right',
    '--cd-sidebar-annotation-video-play-top',
    '--cd-sidebar-annotation-video-title-text',
    '--cd-sidebar-bg',
    '--cd-sidebar-body-padding',
    '--cd-sidebar-border',
    '--cd-sidebar-code-head-color',
    '--cd-sidebar-code-head-icon-color',
    '--cd-sidebar-collapse-code-content-padding',
    '--cd-sidebar-collapse-header-content-gap',
    '--cd-sidebar-collapse-header-content-padding-right',
    '--cd-sidebar-collapse-header-expand-btn',
    '--cd-sidebar-collapse-header-expand-btn-padding',
    '--cd-sidebar-collapse-header-padding-x',
    '--cd-sidebar-collapse-header-padding-y',
    '--cd-sidebar-collapse-item-margin-bottom',
    '--cd-sidebar-color',
    '--cd-sidebar-container-header-padding-left',
    '--cd-sidebar-container-header-padding-right',
    '--cd-sidebar-container-header-padding-y',
    '--cd-sidebar-detail-file-editor-padding-x',
    '--cd-sidebar-detail-file-editor-padding-y',
    '--cd-sidebar-detail-header-left-column-gap',
    '--cd-sidebar-detail-header-padding',
    '--cd-sidebar-detail-header-right-column-gap',
    '--cd-sidebar-detail-header-text',
    '--cd-sidebar-file-blockquote-margin-x',
    '--cd-sidebar-file-blockquote-margin-y',
    '--cd-sidebar-file-blockquote-padding-left',
    '--cd-sidebar-file-btn-active-bg',
    '--cd-sidebar-file-btn-color',
    '--cd-sidebar-file-btn-color-active',
    '--cd-sidebar-file-btn-color-hover',
    '--cd-sidebar-file-btn-hover-bg',
    '--cd-sidebar-file-btn-radius',
    '--cd-sidebar-file-code-padding-x',
    '--cd-sidebar-file-code-padding-y',
    '--cd-sidebar-file-editor-color',
    '--cd-sidebar-file-editor-line-height',
    '--cd-sidebar-file-editor-min-height',
    '--cd-sidebar-file-editor-size',
    '--cd-sidebar-file-gap',
    '--cd-sidebar-file-image-radius',
    '--cd-sidebar-file-image-slot-margin',
    '--cd-sidebar-file-menu-bar-codeblock-font-size',
    '--cd-sidebar-file-menu-bar-codeblock-line-height',
    '--cd-sidebar-file-menu-bar-codeblock-padding',
    '--cd-sidebar-file-menu-bar-gap',
    '--cd-sidebar-file-menu-bar-link-dropdown-padding',
    '--cd-sidebar-file-menu-bar-padding-x',
    '--cd-sidebar-file-menu-bar-padding-y',
    '--cd-sidebar-file-pre-padding-x',
    '--cd-sidebar-file-pre-padding-y',
    '--cd-sidebar-file-selection-bg',
    '--cd-sidebar-handle-color',
    '--cd-sidebar-handle-color-hover',
    '--cd-sidebar-handle-size',
    '--cd-sidebar-inner-hide-delay',
    '--cd-sidebar-inner-hide-duration',
    '--cd-sidebar-inner-hide-function',
    '--cd-sidebar-inner-show-delay',
    '--cd-sidebar-inner-show-duration',
    '--cd-sidebar-inner-show-function',
    '--cd-sidebar-main-collapse-code-content-max-height',
    '--cd-sidebar-main-collapse-file-content-max-height',
    '--cd-sidebar-main-content-padding',
    '--cd-sidebar-mcp-content-padding-x',
    '--cd-sidebar-mcp-content-padding-y',
    '--cd-sidebar-mcp-count-color',
    '--cd-sidebar-mcp-count-size',
    '--cd-sidebar-mcp-custom-empty-margin-top',
    '--cd-sidebar-mcp-desc-color',
    '--cd-sidebar-mcp-desc-size',
    '--cd-sidebar-mcp-gap',
    '--cd-sidebar-mcp-header-counter-text',
    '--cd-sidebar-mcp-item-button',
    '--cd-sidebar-mcp-item-button-configure-margin-right',
    '--cd-sidebar-mcp-item-content-margin-right',
    '--cd-sidebar-mcp-item-desc',
    '--cd-sidebar-mcp-item-label',
    '--cd-sidebar-mcp-item-padding-x',
    '--cd-sidebar-mcp-item-padding-y',
    '--cd-sidebar-mcp-item-sign',
    '--cd-sidebar-mcp-item-sign-icon-font-size',
    '--cd-sidebar-mcp-item-sign-margin-right',
    '--cd-sidebar-mcp-label-color',
    '--cd-sidebar-mcp-label-size',
    '--cd-sidebar-mcp-search-container-column-gap',
    '--cd-sidebar-mcp-search-margin-x',
    '--cd-sidebar-mcp-search-margin-y',
    '--cd-sidebar-menu-bar-btn-active-bg',
    '--cd-sidebar-menu-bar-divider-margin',
    '--cd-sidebar-menu-bar-dropdown-item-active-bg',
    '--cd-sidebar-menu-bar-dropdown-item-active-text',
    '--cd-sidebar-menu-bar-link-dropdown-btn-active',
    '--cd-sidebar-options-button-margin-left',
    '--cd-sidebar-options-button-text',
    '--cd-sidebar-options-gap',
    '--cd-sidebar-options-padding-x',
    '--cd-sidebar-options-padding-y',
    '--cd-sidebar-radius',
    '--cd-sidebar-shadow',
    '--cd-sidebar-title-color',
    '--cd-sidebar-title-size',
    '--cd-sidebar-title-weight',
    '--cd-sidebar-width',
    '--cd-sidebar-z',
    '--cd-width-sidebar-annotation-video-border',
    '--cd-width-sidebar-collapse-item-border',
    '--cd-width-sidebar-collapse-item-content-border-top',
    '--cd-width-sidebar-container-border-left',
    '--cd-width-sidebar-container-header-border-bottom',
    '--cd-width-sidebar-file-blockquote-border-left',
    '--cd-width-sidebar-file-hr-border',
    '--cd-width-sidebar-file-pre-border',
    '--cd-width-sidebar-mcp-item-border-bottom',
    '--cd-width-sidebar-menu-bar-border-bottom',
    '--cd-width-sidebar-menu-bar-border-top',
    '--cd-width-sidebar-options-border-bottom',
  ],
} as const;
