/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'InputNumber',
  category: 'input',
  description: '受约束的数值录入框，含步进按钮、键盘步进、精度与范围 clamp，复用 Input 视觉。',
  props: [
    { name: 'value', type: 'number | null', default: 'undefined', desc: '受控值；提供则为受控' },
    { name: 'defaultValue', type: 'number | null', default: 'null', desc: '非受控初始值' },
    { name: 'min', type: 'number', default: '-Infinity' },
    { name: 'max', type: 'number', default: 'Infinity' },
    { name: 'step', type: 'number', default: '1' },
    { name: 'shiftStep', type: 'number', default: 'step * 10', desc: 'Shift+↑↓ 步长' },
    { name: 'precision', type: 'number', default: 'undefined', desc: '失焦四舍五入保留小数位' },
    { name: 'boundaryMode', type: "'clamp'|'strict'", default: 'clamp', desc: '越界处理：钳制 / 拒绝回滚' },
    { name: 'formatter', type: '(n: number) => string', default: 'undefined', desc: '自定义显示格式化（仅非编辑态）' },
    { name: 'parser', type: '(s: string) => number', default: 'undefined', desc: '自定义解析' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'readonly', type: 'boolean', default: 'false' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default' },
    { name: 'controls', type: 'boolean', default: 'true', desc: '是否显示步进按钮' },
    { name: 'controlsPosition', type: "'right'|'sides'", default: 'right', desc: '步进按钮布局：右侧 stacked / 两侧' },
    { name: 'innerButtons', type: 'boolean', default: 'false', desc: '按钮内嵌悬浮（hover/focus 显形）' },
    { name: 'keyboard', type: 'boolean', default: 'true', desc: '是否启用 ↑↓/PageUp·Down 步进' },
    { name: 'mouseWheel', type: 'boolean', default: 'false', desc: '聚焦时滚轮步进' },
    { name: 'placeholder', type: 'string', default: 'undefined' },
    { name: 'prefix', type: 'string | Snippet', default: 'undefined', desc: '输入框前置内容（如货币符号、单位）' },
    { name: 'suffix', type: 'string | Snippet', default: 'undefined', desc: '输入框后置内容（如单位 %、kg）' },
    { name: 'name', type: 'string', default: 'undefined' },
    { name: 'id', type: 'string', default: '自动生成', desc: 'input 元素 id，关联外部 label' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'autofocus', type: 'boolean', default: 'false', desc: '挂载自动聚焦' },
    { name: 'selectOnFocus', type: 'boolean', default: 'false', desc: '聚焦时全选文本' },
    { name: 'locale', type: 'string', default: 'undefined', desc: '数字格式化 locale（仅未提供 formatter 时生效）' },
    { name: 'borderless', type: 'boolean', default: 'false', desc: '无边框模式' },
    { name: 'showClear', type: 'boolean', default: 'false', desc: '显示清除按钮（有值时出现 ×）' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除图标' },
    { name: 'keepFocus', type: 'boolean', default: 'false', desc: '点击 +/- 按钮后保持输入框聚焦' },
    { name: 'onChange', type: '(v: number | null) => void', default: 'undefined', desc: '归一化后值变化' },
    { name: 'onNumberChange', type: '(v: number | null) => void', default: 'undefined', desc: '携带 number 类型的变化回调（区别于 onChange）' },
    { name: 'onBoundaryHit', type: "(e: { boundary: 'min'|'max'; value: number }) => void", default: 'undefined', desc: '触达/试图越过边界' },
    { name: 'hideButtons', type: 'boolean', default: 'false', desc: '彻底隐藏步进按钮（对齐 Semi；优先于 controls）' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: '命令式 focus() 时是否阻止滚动文档（对齐 Semi）' },
    { name: 'pressTimeout', type: 'number', default: '250', desc: '长按后延迟多久开始连续步进（ms，对齐 Semi）' },
    { name: 'pressInterval', type: 'number', default: '250', desc: '长按连续步进的间隔（ms，对齐 Semi）' },
    { name: 'scientificNotation', type: 'boolean | { threshold?: number }', default: 'false', desc: '失焦时超阈值（默认 15 位）显示科学计数法，聚焦显示完整数字；仅影响显示，onChange/onNumberChange 仍为完整 number（对齐 Semi）' },
  ],
  methods: [
    { name: 'focus()', desc: '命令式聚焦输入框（尊重 preventScroll，对齐 Semi）' },
    { name: 'blur()', desc: '命令式移除焦点（对齐 Semi）' },
  ],
  events: [
    { name: 'change', payload: '{ value: number | null }', desc: '归一化后值变化（受控核心事件）' },
    { name: 'boundaryHit', payload: "{ boundary: 'min'|'max'; value: number }", desc: '触达/试图越过边界' },
    {
      name: 'step',
      payload: "{ value: number; direction: 'up'|'down'; source: 'button'|'keyboard'|'wheel' }",
      desc: '任一步进动作完成',
    },
    { name: 'focus', payload: 'FocusEvent', desc: '聚焦' },
    { name: 'blur', payload: 'FocusEvent', desc: '失焦（已完成 commit 归一化）' },
    { name: 'keydown', payload: 'KeyboardEvent', desc: '透传原生 keydown' },
  ],
  a11y: {
    role: 'spinbutton',
    keyboard: ['ArrowUp', 'ArrowDown', 'Shift+ArrowUp', 'Shift+ArrowDown', 'PageUp', 'PageDown', 'Enter'],
    notes: [
      'input role=spinbutton + aria-valuenow/valuemin/valuemax',
      '失焦按 precision 四舍五入并 clamp 到 [min,max]',
      '到 min/max 时对应步进按钮 disabled',
      '步进按钮 tabindex=-1，mousedown.preventDefault 不夺焦',
      'disabled→aria-disabled，readonly→aria-readonly，error→aria-invalid',
    ],
  },
  tokens: ['--cd-input-number-*', '--cd-input-*', '--cd-color-*', '--cd-spacing-*', '--cd-focus-ring', '--cd-motion-*'],
} as const;
