/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'InputNumber',
  category: 'input',
  description: '受约束的数值录入框，含步进按钮、键盘步进、精度与范围 clamp、货币/科学计数法展示。严格对齐 Semi。',
  props: [
    { name: 'value', type: 'number | null', default: 'undefined', desc: '受控值；提供则为受控' },
    { name: 'defaultValue', type: 'number | null', default: 'null', desc: '非受控初始值' },
    { name: 'min', type: 'number', default: '-Infinity' },
    { name: 'max', type: 'number', default: 'Infinity' },
    { name: 'step', type: 'number', default: '1' },
    { name: 'shiftStep', type: 'number', default: '10', desc: 'Shift+↑↓ / PageUp·Down 步长（对齐 Semi 恒 10）' },
    { name: 'precision', type: 'number', default: 'undefined', desc: '失焦四舍五入保留小数位' },
    { name: 'formatter', type: '(n: number) => string', default: 'undefined', desc: '自定义显示格式化（仅非编辑态）' },
    { name: 'parser', type: '(s: string) => number', default: 'undefined', desc: '自定义解析' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'readonly', type: 'boolean', default: 'false' },
    { name: 'validateStatus', type: "'default'|'error'|'warning'|'success'", default: 'default', desc: '校验状态（对齐 Semi InputProps validateStatus）' },
    { name: 'innerButtons', type: 'boolean', default: 'false', desc: '步进按钮内嵌悬浮（hover/focus 显形）' },
    { name: 'hideButtons', type: 'boolean', default: 'false', desc: '彻底隐藏步进按钮' },
    { name: 'placeholder', type: 'string', default: 'undefined' },
    { name: 'prefix', type: 'string | Snippet', default: 'undefined', desc: '输入框前置内容（如货币符号、单位）' },
    { name: 'suffix', type: 'string | Snippet', default: 'undefined', desc: '输入框后置内容（如单位 %、kg）' },
    { name: 'name', type: 'string', default: 'undefined' },
    { name: 'id', type: 'string', default: '自动生成', desc: 'input 元素 id，关联外部 label' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'autofocus', type: 'boolean', default: 'false', desc: '挂载自动聚焦' },
    { name: 'locale', type: 'string', default: 'undefined', desc: '数字格式化 locale（仅未提供 formatter 时生效）' },
    { name: 'borderless', type: 'boolean', default: 'false', desc: '无边框模式' },
    { name: 'showClear', type: 'boolean', default: 'false', desc: '显示清除按钮（有值时出现 ×）' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除图标' },
    { name: 'keepFocus', type: 'boolean', default: 'false', desc: '点击 +/- 按钮后保持输入框聚焦' },
    { name: 'onChange', type: '(value: number | string | null, e?: Event) => void', default: 'undefined', desc: '值变化：货币/formatter 模式回字符串，其余回 number，空回 null（对齐 Semi）' },
    { name: 'onNumberChange', type: '(value: number | null, e?: Event) => void', default: 'undefined', desc: '携带 number 类型的变化回调（对齐 Semi）' },
    { name: 'onUpClick', type: '(value: number | null, e: MouseEvent) => void', default: 'undefined', desc: '点击「+」按钮回调（对齐 Semi）' },
    { name: 'onDownClick', type: '(value: number | null, e: MouseEvent) => void', default: 'undefined', desc: '点击「-」按钮回调（对齐 Semi）' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined', desc: '聚焦' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined', desc: '失焦（已完成 commit 归一化）' },
    { name: 'onKeyDown', type: '(e: KeyboardEvent) => void', default: 'undefined', desc: '透传原生 keydown（对齐 Semi onKeyDown）' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: '命令式 focus() 时是否阻止滚动文档（对齐 Semi）' },
    { name: 'pressTimeout', type: 'number', default: '250', desc: '长按后延迟多久开始连续步进（ms，对齐 Semi）' },
    { name: 'pressInterval', type: 'number', default: '250', desc: '长按连续步进的间隔（ms，对齐 Semi）' },
    { name: 'scientificNotation', type: 'boolean | { threshold?: number }', default: 'false', desc: '失焦时超阈值（默认 15 位）显示科学计数法，聚焦显示完整数字；仅影响显示（对齐 Semi）' },
    { name: 'currency', type: 'boolean | string', default: 'false', desc: '货币展示：true 按 localeCode 推断币种，字符串指定 ISO 4217 币种码；仅显示层（对齐 Semi）' },
    { name: 'currencyDisplay', type: "'symbol'|'code'|'name'", default: "'symbol'", desc: '货币展示方式：符号 ￥ / 代码 CNY / 名称 人民币（对齐 Semi）' },
    { name: 'localeCode', type: 'string', default: 'undefined', desc: '货币格式化 BCP-47 locale；回退 locale 再回退 zh-CN（对齐 Semi）' },
    { name: 'showCurrencySymbol', type: 'boolean', default: 'true', desc: 'false 时隐藏内置货币符号/代码/名称（用 decimal 千分位）（对齐 Semi）' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根节点自定义类名（对齐 Semi className）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根节点自定义内联样式（对齐 Semi style）' },
  ],
  methods: [
    { name: 'focus()', desc: '命令式聚焦输入框（尊重 preventScroll，对齐 Semi）' },
    { name: 'blur()', desc: '命令式移除焦点（对齐 Semi）' },
  ],
  events: [
    { name: 'change', payload: '{ value: number | string | null, e?: Event }', desc: '归一化后值变化（受控核心事件）' },
    { name: 'numberChange', payload: '{ value: number | null, e?: Event }', desc: '携带 number 类型的变化回调' },
    { name: 'upClick', payload: '{ value: number | null, e: MouseEvent }', desc: '点击「+」按钮' },
    { name: 'downClick', payload: '{ value: number | null, e: MouseEvent }', desc: '点击「-」按钮' },
    { name: 'focus', payload: 'FocusEvent', desc: '聚焦' },
    { name: 'blur', payload: 'FocusEvent', desc: '失焦（已完成 commit 归一化）' },
    { name: 'keyDown', payload: 'KeyboardEvent', desc: '透传原生 keydown' },
  ],
  a11y: {
    role: 'spinbutton',
    keyboard: ['ArrowUp', 'ArrowDown', 'Shift+ArrowUp', 'Shift+ArrowDown', 'PageUp', 'PageDown', 'Enter'],
    notes: [
      'input role=spinbutton + aria-valuenow/valuemin/valuemax',
      '失焦按 precision 四舍五入并 clamp 到 [min,max]',
      '到 min/max 时对应步进按钮 not-allowed（aria-disabled）',
      '步进按钮 tabindex=-1，mousedown.preventDefault 不夺焦',
      'disabled→aria-disabled，readonly→aria-readonly，error→aria-invalid',
    ],
  },
  tokens: ['--cd-input-number-*', '--cd-color-input-number-button-*', '--cd-input-*', '--cd-focus-ring', '--cd-motion-*'],
} as const;
