/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'InputNumber',
  category: 'input',
  description: '受约束的数值录入框，含步进按钮、键盘步进、精度与范围 clamp，复用 Input 视觉。',
  props: [
    { name: 'value', type: 'number | null', default: 'undefined', desc: '受控值；提供则为受控' },
    { name: 'defaultValue', type: 'number | null', default: 'null', desc: '非受控初始值' },
    { name: 'min', type: 'number', default: '-Infinity' },
    { name: 'max', type: 'number', default: 'Infinity' },
    { name: 'step', type: 'number', default: '1' },
    { name: 'shiftStep', type: 'number', default: 'step * 10', desc: 'Shift+↑↓ 步长' },
    { name: 'precision', type: 'number', default: 'undefined', desc: '失焦四舍五入保留小数位' },
    { name: 'boundaryMode', type: "'clamp'|'strict'", default: 'clamp', desc: '越界处理：钳制 / 拒绝回滚' },
    { name: 'formatter', type: '(n: number) => string', default: 'undefined', desc: '自定义显示格式化（仅非编辑态）' },
    { name: 'parser', type: '(s: string) => number', default: 'undefined', desc: '自定义解析' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'readonly', type: 'boolean', default: 'false' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default' },
    { name: 'controls', type: 'boolean', default: 'true', desc: '是否显示步进按钮' },
    { name: 'controlsPosition', type: "'right'|'sides'", default: 'right', desc: '步进按钮布局：右侧 stacked / 两侧' },
    { name: 'innerButtons', type: 'boolean', default: 'false', desc: '按钮内嵌悬浮（hover/focus 显形）' },
    { name: 'keyboard', type: 'boolean', default: 'true', desc: '是否启用 ↑↓/PageUp·Down 步进' },
    { name: 'mouseWheel', type: 'boolean', default: 'false', desc: '聚焦时滚轮步进' },
    { name: 'placeholder', type: 'string', default: 'undefined' },
    { name: 'name', type: 'string', default: 'undefined' },
    { name: 'id', type: 'string', default: '自动生成', desc: 'input 元素 id，关联外部 label' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'autofocus', type: 'boolean', default: 'false', desc: '挂载自动聚焦' },
    { name: 'selectOnFocus', type: 'boolean', default: 'false', desc: '聚焦时全选文本' },
    { name: 'locale', type: 'string', default: 'undefined', desc: '数字格式化 locale（仅未提供 formatter 时生效）' },
    { name: 'onChange', type: '(v: number | null) => void', default: 'undefined', desc: '归一化后值变化' },
    { name: 'onBoundaryHit', type: "(e: { boundary: 'min'|'max'; value: number }) => void", default: 'undefined', desc: '触达/试图越过边界' },
  ],
  events: [
    { name: 'change', payload: '{ value: number | null }', desc: '归一化后值变化（受控核心事件）' },
    { name: 'boundaryHit', payload: "{ boundary: 'min'|'max'; value: number }", desc: '触达/试图越过边界' },
  ],
  a11y: {
    role: 'spinbutton',
    keyboard: ['ArrowUp', 'ArrowDown', 'Shift+ArrowUp', 'Shift+ArrowDown', 'PageUp', 'PageDown', 'Enter'],
    notes: [
      'input role=spinbutton + aria-valuenow/valuemin/valuemax',
      '失焦按 precision 四舍五入并 clamp 到 [min,max]',
      '到 min/max 时对应步进按钮 disabled',
      '步进按钮 tabindex=-1，mousedown.preventDefault 不夺焦',
      'disabled→aria-disabled，readonly→aria-readonly，error→aria-invalid',
    ],
  },
  tokens: ['--cd-input-*', '--cd-color-*', '--cd-spacing-*', '--cd-focus-ring', '--cd-motion-*'],
} as const;
