/**
 * Component tokens for AIChatDialogue —— 名/值/公式逐条镜像 Semi
 * `semi-foundation/aiChatDialogue/variables.scss`（194 条，由脚本从该文件生成）。
 *
 * 此前本组件**没有自己的 token 文件**：样式借用 chat 的 --cd-chat-*，另有三处写成
 * `--cd-color-aichatdialogue-annotation-*` —— 这个名字不对应任何 Semi 变量（Semi 的是
 * `$color-aiChatDialogue_annotation-*`，见其 variables.scss:20-22），且从未定义过，
 * 靠 `var(x, 兜底)` 的兜底值撑着。已改指本文件里镜像 Semi 的真 token。
 *
 * 与 Semi 双向核对过：194 对 194，无自造项、无遗漏项。
 *
 * 命名规则：Semi 的 `$类别-aiChatDialogue_a_b-c` → `ai-chat-dialogue-a-b-c`
 * （下划线转连字符、驼峰拆词、类别并入 category 字段）。
 * 例外：当去掉类别前缀后会与另一条重名时（如 $width-X 与 $height-X），保留类别前缀
 * 消歧，写成 `width-ai-chat-dialogue-x` / `height-ai-chat-dialogue-x`——与
 * ai-chat-input.ts 里既有的同类写法一致。共 19 组需要这样消歧。
 *
 * 另有 7 条文件类型图标底色，Semi 写作 `rgba(var(--semi-teal-4), 1)`——那是「裸三元组
 * + rgba 包一层」的存储格式，不是语义。本库色板存的是完整颜色，故转成
 * `var(--cd-color-teal-4)`（见 semi-rgba-var-is-format-not-semantics）。
 */
import type { TokenGroup } from './token-def.js';

export const aiChatDialogueTokens = {
  'ai-chat-dialogue-wrapper-selected-bg': {
    value: 'var(--cd-color-fill-0)',
    category: 'color',
    label: '外层选中背景色',
    usage: 'Semi $color-aiChatDialogue_wrapper-selected-bg',
  },
  'ai-chat-dialogue-loading-circle-first-bg': {
    value: 'rgba(83, 56, 255, 1)',
    category: 'color',
    label: '第一个加载圆点背景色',
    usage: 'Semi $color-aiChatDialogue_loading_circle_first-bg',
  },
  'ai-chat-dialogue-loading-circle-second-bg': {
    value: 'rgba(176, 48, 240, 1)',
    category: 'color',
    label: '第二个加载圆点背景色',
    usage: 'Semi $color-aiChatDialogue_loading_circle_second-bg',
  },
  'ai-chat-dialogue-loading-circle-third-bg': {
    value: 'rgba(231, 45, 255, 1)',
    category: 'color',
    label: '第三个加载圆点背景色',
    usage: 'Semi $color-aiChatDialogue_loading_circle_third-bg',
  },
  'ai-chat-dialogue-loading-text': {
    value: 'var(--cd-color-text-3)',
    category: 'color',
    label: '加载中文本颜色',
    usage: 'Semi $color-aiChatDialogue_loading_text',
  },
  'ai-chat-dialogue-bubble-bg': {
    value: 'var(--cd-color-fill-0)',
    category: 'color',
    label: '对话气泡背景色',
    usage: 'Semi $color-aiChatDialogue_bubble-bg',
  },
  'ai-chat-dialogue-file-bg': {
    value: 'var(--cd-color-fill-0)',
    category: 'color',
    label: '文件组件背景色',
    usage: 'Semi $color-aiChatDialogue_file-bg',
  },
  'ai-chat-dialogue-file-title-text': {
    value: 'var(--cd-color-text-0)',
    category: 'color',
    label: '文件标题文本颜色',
    usage: 'Semi $color-aiChatDialogue_file_title-text',
  },
  'ai-chat-dialogue-file-metadata-text': {
    value: 'var(--cd-color-text-2)',
    category: 'color',
    label: '文件元数据文本颜色',
    usage: 'Semi $color-aiChatDialogue_file_metadata-text',
  },
  'ai-chat-dialogue-tool-call-bg': {
    value: 'var(--cd-color-fill-0)',
    category: 'color',
    label: '工具调用组件背景色',
    usage: 'Semi $color-aiChatDialogue_tool_call-bg',
  },
  'ai-chat-dialogue-tool-call-text': {
    value: 'var(--cd-color-text-2)',
    category: 'color',
    label: '工具调用组件文本颜色',
    usage: 'Semi $color-aiChatDialogue_tool_call-text',
  },
  'ai-chat-dialogue-action-dropdown-text': {
    value: 'var(--cd-color-danger)',
    category: 'color',
    label: '操作区下拉菜单文本颜色',
    // 值本身仍需镜像 Semi 该变量（check:semi-parity 依赖），但组件层不直接消费它——
    // 删除项的红色改走 Dropdown.Item type="danger" 的语义色（同样是 --cd-color-danger），
    // 而非用这个 token 去外部覆盖 Dropdown.Item 自带的默认文字色（那条覆盖此前特异性
    // 不够、从未真正生效，见 DialogueAction.svelte）。
    usage: 'Semi $color-aiChatDialogue_action_dropdown-text',
  },
  'color-ai-chat-dialogue-reasoning-border': {
    value: 'var(--cd-color-border)',
    category: 'color',
    label: '推理组件边框色',
    usage: 'Semi $color-aiChatDialogue_reasoning-border',
  },
  'color-ai-chat-dialogue-step-border': {
    value: 'var(--cd-color-border)',
    category: 'color',
    label: '步骤组件边框色',
    usage: 'Semi $color-aiChatDialogue_step-border',
  },
  'ai-chat-dialogue-step-action-bg': {
    value: 'var(--cd-color-fill-0)',
    category: 'color',
    label: '步骤组件 action 背景色',
    usage: 'Semi $color-aiChatDialogue_step_action-bg',
  },
  'ai-chat-dialogue-step-completed-text': {
    value: 'var(--cd-color-success)',
    category: 'color',
    label: '步骤组件完成文本颜色',
    usage: 'Semi $color-aiChatDialogue_step_completed-text',
  },
  'ai-chat-dialogue-step-suffix-text': {
    value: 'var(--cd-color-text-1)',
    category: 'color',
    label: '步骤组件后缀文本颜色',
    usage: 'Semi $color-aiChatDialogue_step_suffix-text',
  },
  'ai-chat-dialogue-step-action-text': {
    value: 'var(--cd-color-text-2)',
    category: 'color',
    label: '步骤组件 action 文本颜色',
    usage: 'Semi $color-aiChatDialogue_step_action-text',
  },
  'color-ai-chat-dialogue-annotation-border': {
    value: 'var(--cd-color-border)',
    category: 'color',
    label: '参考来源组件边框色',
    usage: 'Semi $color-aiChatDialogue_annotation-border',
  },
  'ai-chat-dialogue-annotation-bg-hover': {
    value: 'var(--cd-color-fill-0)',
    category: 'color',
    label: '参考来源组件悬停背景色',
    usage: 'Semi $color-aiChatDialogue_annotation-bg-hover',
  },
  'ai-chat-dialogue-annotation-text': {
    value: 'var(--cd-color-text-2)',
    category: 'color',
    label: '参考来源组件文本颜色',
    usage: 'Semi $color-aiChatDialogue_annotation-text',
  },
  'ai-chat-dialogue-reference-bg': {
    value: 'var(--cd-color-fill-0)',
    category: 'color',
    label: '引用组件背景色',
    usage: 'Semi $color-aiChatDialogue_reference-bg',
  },
  'ai-chat-dialogue-reference-text': {
    value: 'var(--cd-color-text-2)',
    category: 'color',
    label: '引用组件文本颜色',
    usage: 'Semi $color-aiChatDialogue_reference-text',
  },
  'ai-chat-dialogue-icon-reference-text': {
    value: 'var(--cd-color-text-0)',
    category: 'color',
    label: '用户消息引用图标颜色',
    usage: 'Semi $color-aiChatDialogue_icon_reference-text',
  },
  'color-ai-chat-dialogue-code-border': {
    value: 'var(--cd-color-border)',
    category: 'color',
    label: '代码块边框色',
    usage: 'Semi $color-aiChatDialogue_code-border',
  },
  'ai-chat-dialogue-code-top-slot-bg': {
    value: 'var(--cd-color-fill-0)',
    category: 'color',
    label: '代码块顶部槽背景色',
    usage: 'Semi $color-aiChatDialogue_code_topSlot-bg',
  },
  'ai-chat-dialogue-code-top-slot-text': {
    value: 'var(--cd-color-text-0)',
    category: 'color',
    label: '代码块顶部槽文本颜色',
    usage: 'Semi $color-aiChatDialogue_code_topSlot-text',
  },
  'ai-chat-dialogue-hint-bg': {
    value: 'var(--cd-color-bg-0)',
    category: 'color',
    label: '提示项背景色',
    usage: 'Semi $color-aiChatDialogue_hint-bg',
  },
  'color-ai-chat-dialogue-hint-border': {
    value: 'var(--cd-color-border)',
    category: 'color',
    label: '提示项边框色',
    usage: 'Semi $color-aiChatDialogue_hint-border',
  },
  'ai-chat-dialogue-hint-bg-hover': {
    value: 'var(--cd-color-fill-0)',
    category: 'color',
    label: '提示项悬停背景色',
    usage: 'Semi $color-aiChatDialogue_hint-bg-hover',
  },
  'ai-chat-dialogue-hint-text': {
    value: 'var(--cd-color-text-0)',
    category: 'color',
    label: '提示项文本颜色',
    usage: 'Semi $color-aiChatDialogue_hint-text',
  },
  'ai-chat-dialogue-code-icon-bg': {
    value: 'var(--cd-color-teal-4)',
    category: 'color',
    label: 'code icon 背景色',
    usage: 'Semi $color-aiChatDialogue_code_icon-bg',
  },
  'ai-chat-dialogue-word-icon-bg': {
    value: 'var(--cd-color-blue-4)',
    category: 'color',
    label: 'word icon 背景色',
    usage: 'Semi $color-aiChatDialogue_word_icon-bg',
  },
  'ai-chat-dialogue-excel-icon-bg': {
    value: 'var(--cd-color-green-4)',
    category: 'color',
    label: 'excel icon 背景色',
    usage: 'Semi $color-aiChatDialogue_excel_icon-bg',
  },
  'ai-chat-dialogue-image-icon-bg': {
    value: 'var(--cd-color-purple-4)',
    category: 'color',
    label: 'image icon 背景色',
    usage: 'Semi $color-aiChatDialogue_image_icon-bg',
  },
  'ai-chat-dialogue-pdf-icon-bg': {
    value: 'var(--cd-color-red-4)',
    category: 'color',
    label: 'pdf icon 背景色',
    usage: 'Semi $color-aiChatDialogue_pdf_icon-bg',
  },
  'ai-chat-dialogue-video-icon-bg': {
    value: 'var(--cd-color-purple-4)',
    category: 'color',
    label: 'video icon 背景色',
    usage: 'Semi $color-aiChatDialogue_video_icon-bg',
  },
  'ai-chat-dialogue-default-icon-bg': {
    value: 'var(--cd-color-grey-4)',
    category: 'color',
    label: 'default icon 背景色',
    usage: 'Semi $color-aiChatDialogue_default_icon-bg',
  },
  'ai-chat-dialogue-icon-text': {
    value: 'var(--cd-color-white)',
    category: 'color',
    label: 'icon 文本颜色',
    usage: 'Semi $color-aiChatDialogue_icon-text',
  },
  'ai-chat-dialogue-failed': {
    value: 'var(--cd-color-danger)',
    category: 'color',
    label: '失败提示颜色',
    usage: 'Semi $color-aiChatDialogue_failed',
  },
  'ai-chat-dialogue-code-content-bg': {
    value: 'var(--cd-color-bg-0)',
    category: 'color',
    label: 'code content 背景色',
    usage: 'Semi $color-aiChatDialogue_code_content-bg',
  },
  'ai-chat-dialogue-wrapper': {
    value: '100%',
    category: 'width',
    label: '外层宽度',
    usage: 'Semi $width-aiChatDialogue_wrapper',
  },
  'ai-chat-dialogue-inner': {
    value: '100%',
    category: 'width',
    label: '气泡右侧展示内层宽度',
    usage: 'Semi $width-aiChatDialogue_inner',
  },
  'width-ai-chat-dialogue-back-bottom-button': {
    value: '42px',
    category: 'width',
    label: '返回按钮宽度',
    usage: 'Semi $width-aiChatDialogue_backBottom_button',
  },
  'height-ai-chat-dialogue-back-bottom-button': {
    value: '42px',
    category: 'height',
    label: '返回按钮高度',
    usage: 'Semi $height-aiChatDialogue_backBottom_button',
  },
  'width-ai-chat-dialogue-avatar': {
    value: '24px',
    category: 'width',
    label: '头像宽度',
    usage: 'Semi $width-aiChatDialogue_avatar',
  },
  'height-ai-chat-dialogue-avatar': {
    value: '24px',
    category: 'height',
    label: '头像高度',
    usage: 'Semi $height-aiChatDialogue_avatar',
  },
  'ai-chat-dialogue-content-editing': {
    value: '100%',
    category: 'width',
    label: '内容宽度 - 编辑状态',
    usage: 'Semi $width-aiChatDialogue_content_editing',
  },
  'ai-chat-dialogue-content-inner': {
    value: '100%',
    category: 'width',
    label: '内容内层宽度',
    usage: 'Semi $width-aiChatDialogue_content_inner',
  },
  'ai-chat-dialogue-content-max': {
    value: '100%',
    category: 'width',
    label: '内容最大宽度',
    usage: 'Semi $width-aiChatDialogue_content_max',
  },
  'ai-chat-dialogue-bubble-max': {
    value: '100%',
    category: 'width',
    label: '气泡最大宽度',
    usage: 'Semi $width-aiChatDialogue_bubble_max',
  },
  'width-ai-chat-dialogue-loading-circle': {
    value: '3px',
    category: 'width',
    label: '加载圆点宽度',
    usage: 'Semi $width-aiChatDialogue_loading_circle',
  },
  'height-ai-chat-dialogue-loading-circle': {
    value: '3px',
    category: 'height',
    label: '加载圆点高度',
    usage: 'Semi $height-aiChatDialogue_loading_circle',
  },
  'width-ai-chat-dialogue-img': {
    value: '256px',
    category: 'width',
    label: '图片宽度',
    usage: 'Semi $width-aiChatDialogue_img',
  },
  'height-ai-chat-dialogue-img': {
    value: '256px',
    category: 'height',
    label: '图片高度',
    usage: 'Semi $height-aiChatDialogue_img',
  },
  'width-ai-chat-dialogue-img-list': {
    value: '128px',
    category: 'width',
    label: '图片列表项宽度',
    usage: 'Semi $width-aiChatDialogue_img_list',
  },
  'height-ai-chat-dialogue-img-list': {
    value: '128px',
    category: 'height',
    label: '图片列表项高度',
    usage: 'Semi $height-aiChatDialogue_img_list',
  },
  'width-ai-chat-dialogue-file': {
    value: '224px',
    category: 'width',
    label: '文件组件宽度',
    usage: 'Semi $width-aiChatDialogue_file',
  },
  'height-ai-chat-dialogue-file': {
    value: '36px',
    category: 'height',
    label: '文件组件高度',
    usage: 'Semi $height-aiChatDialogue_file',
  },
  'width-ai-chat-dialogue-file-icon-wrapper': {
    value: '36px',
    category: 'width',
    label: '文件图标外层宽度',
    usage: 'Semi $width-aiChatDialogue_file_icon_wrapper',
  },
  'height-ai-chat-dialogue-file-icon-wrapper': {
    value: '36px',
    category: 'height',
    label: '文件图标外层高度',
    usage: 'Semi $height-aiChatDialogue_file_icon_wrapper',
  },
  'width-ai-chat-dialogue-action-btn': {
    value: '24px',
    category: 'width',
    label: '操作按钮宽度',
    usage: 'Semi $width-aiChatDialogue_action_btn',
  },
  'height-ai-chat-dialogue-action-btn': {
    value: '24px',
    category: 'height',
    label: '操作按钮高度',
    usage: 'Semi $height-aiChatDialogue_action_btn',
  },
  // 注：Semi 有 $width-aiChatDialogue_reasoning（对应 scss 的 &-reasoning），
  // 但它的 tsx 从不渲染 -reasoning 这个类名，属上游死 CSS，本库不再镜像该变量。
  'width-ai-chat-dialogue-reasoning-wrapper': {
    value: '100%',
    category: 'width',
    label: '推理组件外层宽度',
    usage: 'Semi $width-aiChatDialogue_reasoning_wrapper',
  },
  'width-ai-chat-dialogue-reasoning-border': {
    value: '1px',
    category: 'width',
    label: '推理组件 border 宽度',
    usage: 'Semi $width-aiChatDialogue_reasoning-border',
  },
  'width-ai-chat-dialogue-reasoning-prefix': {
    value: '20px',
    category: 'width',
    label: '推理前缀图标宽度',
    usage: 'Semi $width-aiChatDialogue_reasoning_prefix',
  },
  'height-ai-chat-dialogue-reasoning-prefix': {
    value: '20px',
    category: 'height',
    label: '推理前缀图标高度',
    usage: 'Semi $height-aiChatDialogue_reasoning_prefix',
  },
  'width-ai-chat-dialogue-step-border': {
    value: '1px',
    category: 'width',
    label: '步骤组件 border 宽度',
    usage: 'Semi $width-aiChatDialogue_step-border',
  },
  'width-ai-chat-dialogue-step-prefix': {
    value: '20px',
    category: 'width',
    label: '步骤前缀图标宽度',
    usage: 'Semi $width-aiChatDialogue_step_prefix',
  },
  'height-ai-chat-dialogue-step-prefix': {
    value: '20px',
    category: 'height',
    label: '步骤前缀图标高度',
    usage: 'Semi $height-aiChatDialogue_step_prefix',
  },
  'width-ai-chat-dialogue-step-suffix': {
    value: '20px',
    category: 'width',
    label: '步骤后缀图标宽度',
    usage: 'Semi $width-aiChatDialogue_step_suffix',
  },
  'height-ai-chat-dialogue-step-suffix': {
    value: '20px',
    category: 'height',
    label: '步骤后缀图标高度',
    usage: 'Semi $height-aiChatDialogue_step_suffix',
  },
  'ai-chat-dialogue-step-line': {
    value: '1px',
    category: 'width',
    label: '步骤左侧线宽度',
    usage: 'Semi $width-aiChatDialogue_step_line',
  },
  'ai-chat-dialogue-annotation': {
    value: '100%',
    category: 'width',
    label: '参考来源宽度',
    usage: 'Semi $width-aiChatDialogue_annotation',
  },
  'width-ai-chat-dialogue-annotation-border': {
    value: '1px',
    category: 'width',
    label: '参考来源组件 border 宽度',
    usage: 'Semi $width-aiChatDialogue_annotation-border',
  },
  'width-ai-chat-dialogue-annotation-logo': {
    value: '16px',
    category: 'width',
    label: '参考来源logo宽度',
    usage: 'Semi $width-aiChatDialogue_annotation_logo',
  },
  'height-ai-chat-dialogue-annotation-logo': {
    value: '16px',
    category: 'height',
    label: '参考来源logo高度',
    usage: 'Semi $height-aiChatDialogue_annotation_logo',
  },
  'width-ai-chat-dialogue-reference-icon': {
    value: '16px',
    category: 'width',
    label: '引用图标宽度',
    usage: 'Semi $width-aiChatDialogue_reference_icon',
  },
  'height-ai-chat-dialogue-reference-icon': {
    value: '16px',
    category: 'height',
    label: '引用图标高度',
    usage: 'Semi $height-aiChatDialogue_reference_icon',
  },
  'ai-chat-dialogue-reference-max': {
    value: '200px',
    category: 'width',
    label: '引用组件最大宽度',
    usage: 'Semi $width-aiChatDialogue_reference_max',
  },
  'ai-chat-dialogue-reference-name-max': {
    value: '130px',
    category: 'width',
    label: '引用名称最大宽度',
    usage: 'Semi $width-aiChatDialogue_reference_name_max',
  },
  'width-ai-chat-dialogue-code-border': {
    value: '1px',
    category: 'width',
    label: '代码块组件 border 宽度',
    usage: 'Semi $width-aiChatDialogue_code-border',
  },
  'width-ai-chat-dialogue-hint-border': {
    value: '1px',
    category: 'width',
    label: '提示项组件 border 宽度',
    usage: 'Semi $width-aiChatDialogue_hint-border',
  },
  'ai-chat-dialogue-file-title-max': {
    value: '180px',
    category: 'width',
    label: '文件标题最大宽度',
    usage: 'Semi $width-aiChatDialogue_file_title_max',
  },
  'ai-chat-dialogue-file-title-max-hover': {
    value: '140px',
    category: 'width',
    label: '用户消息悬停时文件标题最大宽度(显示引用图标时)',
    usage: 'Semi $width-aiChatDialogue_file_title_max-hover',
  },
  'ai-chat-dialogue-action-copy': {
    value: '24px',
    category: 'width',
    label: '复制按钮宽度',
    usage: 'Semi $width-aiChatDialogue_action_copy',
  },
  'ai-chat-dialogue-wrapper-padding-y': {
    value: '8px',
    category: 'spacing',
    label: '最外层垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_wrapper-paddingY',
  },
  'ai-chat-dialogue-wrapper-padding-x': {
    value: '16px',
    category: 'spacing',
    label: '最外层水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_wrapper-paddingX',
  },
  'ai-chat-dialogue-wrapper-margin-top': {
    value: '2px',
    category: 'spacing',
    label: '最外层顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_wrapper-marginTop',
  },
  'ai-chat-dialogue-wrapper-column-gap': {
    value: '16px',
    category: 'spacing',
    label: '最外层列间距',
    usage: 'Semi $spacing-aiChatDialogue_wrapper-columnGap',
  },
  'ai-chat-dialogue-container-column-gap': {
    value: '12px',
    category: 'spacing',
    label: 'container 容器列间距',
    usage: 'Semi $spacing-aiChatDialogue_container-columnGap',
  },
  'ai-chat-dialogue-content-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '内容顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_content-marginTop',
  },
  'ai-chat-dialogue-content-failed-margin-right': {
    value: '8px',
    category: 'spacing',
    label: '内容失败提示右外边距',
    usage: 'Semi $spacing-aiChatDialogue_content_failed-marginRight',
  },
  'ai-chat-dialogue-content-bubble-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '内容气泡顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_content_bubble-marginTop',
  },
  'ai-chat-dialogue-content-no-bubble-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '内容无气泡顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_content_noBubble-marginTop',
  },
  'ai-chat-dialogue-bubble-padding-y': {
    value: '12px',
    category: 'spacing',
    label: '气泡垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_bubble-paddingY',
  },
  'ai-chat-dialogue-bubble-padding-x': {
    value: '16px',
    category: 'spacing',
    label: '气泡水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_bubble-paddingX',
  },
  'ai-chat-dialogue-content-loading-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '内容加载顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_content_loading-marginTop',
  },
  'ai-chat-dialogue-loading-item-margin-y': {
    value: '1px',
    category: 'spacing',
    label: '加载项垂直外边距',
    usage: 'Semi $spacing-aiChatDialogue_loading_item-marginY',
  },
  'ai-chat-dialogue-loading-item-margin-x': {
    value: '1px',
    category: 'spacing',
    label: '加载项水平外边距',
    usage: 'Semi $spacing-aiChatDialogue_loading_item-marginX',
  },
  'ai-chat-dialogue-loading-text-margin-left': {
    value: '8px',
    category: 'spacing',
    label: '加载文本左外边距',
    usage: 'Semi $spacing-aiChatDialogue_loading_text-marginLeft',
  },
  'ai-chat-dialogue-loading-item-before-left': {
    value: '-15px',
    category: 'spacing',
    label: '加载项 before 左外边距',
    usage: 'Semi $spacing-aiChatDialogue_loading_item_before-left',
  },
  'ai-chat-dialogue-loading-item-after-left': {
    value: '15px',
    category: 'spacing',
    label: '加载项 after 左外边距',
    usage: 'Semi $spacing-aiChatDialogue_loading_item_after-left',
  },
  'ai-chat-dialogue-img-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '图片顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_img-marginTop',
  },
  'ai-chat-dialogue-img-list-margin-right': {
    value: '4px',
    category: 'spacing',
    label: '图片列表右外边距',
    usage: 'Semi $spacing-aiChatDialogue_img_list-marginRight',
  },
  'ai-chat-dialogue-file-padding-y': {
    value: '8px',
    category: 'spacing',
    label: '文件组件垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_file-paddingY',
  },
  'ai-chat-dialogue-file-padding-x': {
    value: '8px',
    category: 'spacing',
    label: '文件组件水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_file-paddingX',
  },
  'ai-chat-dialogue-file-column-gap': {
    value: '8px',
    category: 'spacing',
    label: '文件组件列间距',
    usage: 'Semi $spacing-aiChatDialogue_file-columnGap',
  },
  'ai-chat-dialogue-file-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '文件组件顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_file-marginTop',
  },
  'ai-chat-dialogue-file-margin-right': {
    value: '8px',
    category: 'spacing',
    label: '文件组件右外边距',
    usage: 'Semi $spacing-aiChatDialogue_file-marginRight',
  },
  'ai-chat-dialogue-tool-call-padding-y': {
    value: '6px',
    category: 'spacing',
    label: '工具调用垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_tool_call-paddingY',
  },
  'ai-chat-dialogue-tool-call-padding-x': {
    value: '8px',
    category: 'spacing',
    label: '工具调用水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_tool_call-paddingX',
  },
  'ai-chat-dialogue-tool-call-column-gap': {
    value: '4px',
    category: 'spacing',
    label: '工具调用列间距',
    usage: 'Semi $spacing-aiChatDialogue_tool_call-columnGap',
  },
  'ai-chat-dialogue-tool-call-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '工具调用顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_tool_call-marginTop',
  },
  'ai-chat-dialogue-custom-renderer-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '自定义渲染器顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_custom_renderer-marginTop',
  },
  'ai-chat-dialogue-action-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '操作顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_action-marginTop',
  },
  'ai-chat-dialogue-reasoning-wrapper-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '推理组件外层顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_reasoning_wrapper-marginTop',
  },
  'ai-chat-dialogue-reasoning-header-padding': {
    value: '16px',
    category: 'spacing',
    label: '推理头部内边距',
    usage: 'Semi $spacing-aiChatDialogue_reasoning_header-padding',
  },
  'ai-chat-dialogue-reasoning-content-padding-y': {
    value: '12px',
    category: 'spacing',
    label: '推理内容垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_reasoning_content-paddingY',
  },
  'ai-chat-dialogue-reasoning-content-padding-x': {
    value: '16px',
    category: 'spacing',
    label: '推理内容水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_reasoning_content-paddingX',
  },
  'ai-chat-dialogue-step-wrapper-margin-top': {
    value: '4px',
    category: 'spacing',
    label: '步骤外层顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_step_wrapper-marginTop',
  },
  'ai-chat-dialogue-step-padding-y': {
    value: '6px',
    category: 'spacing',
    label: '步骤垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_step-paddingY',
  },
  'ai-chat-dialogue-step-padding-x': {
    value: '12px',
    category: 'spacing',
    label: '步骤水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_step-paddingX',
  },
  'ai-chat-dialogue-step-margin-top': {
    value: '12px',
    category: 'spacing',
    label: '步骤顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_step-marginTop',
  },
  'ai-chat-dialogue-step-prefix-margin-right': {
    value: '6px',
    category: 'spacing',
    label: '步骤前缀右外边距',
    usage: 'Semi $spacing-aiChatDialogue_step_prefix-marginRight',
  },
  'ai-chat-dialogue-step-suffix-margin-left': {
    value: '8px',
    category: 'spacing',
    label: '步骤后缀左外边距',
    usage: 'Semi $spacing-aiChatDialogue_step_suffix-marginLeft',
  },
  'ai-chat-dialogue-step-panel-gap': {
    value: '12px',
    category: 'spacing',
    label: '步骤面板间距',
    usage: 'Semi $spacing-aiChatDialogue_step_panel-gap',
  },
  'ai-chat-dialogue-step-line-margin-left': {
    value: '20px',
    category: 'spacing',
    label: '步骤连接线左外边距',
    usage: 'Semi $spacing-aiChatDialogue_step_line-marginLeft',
  },
  'ai-chat-dialogue-step-action-margin-top': {
    value: '12px',
    category: 'spacing',
    label: '步骤 action 顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_step_action-marginTop',
  },
  'ai-chat-dialogue-step-action-summary-margin-bottom': {
    value: '4px',
    category: 'spacing',
    label: '步骤 action 摘要底部外边距',
    usage: 'Semi $spacing-aiChatDialogue_step_action_summary-marginBottom',
  },
  'ai-chat-dialogue-step-action-desc-padding-y': {
    value: '6px',
    category: 'spacing',
    label: '步骤 action 描述垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_step_action_desc-paddingY',
  },
  'ai-chat-dialogue-step-action-desc-padding-x': {
    value: '8px',
    category: 'spacing',
    label: '步骤 action 描述水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_step_action_desc-paddingX',
  },
  'ai-chat-dialogue-step-action-desc-column-gap': {
    value: '4px',
    category: 'spacing',
    label: '步骤 action 描述列间距',
    usage: 'Semi $spacing-aiChatDialogue_step_action_desc-columnGap',
  },
  'ai-chat-dialogue-annotation-wrapper-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '参考来源外层顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_annotation_wrapper-marginTop',
  },
  'ai-chat-dialogue-annotation-wrapper-padding-y': {
    value: '8px',
    category: 'spacing',
    label: '参考来源外层垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_annotation_wrapper-paddingY',
  },
  'ai-chat-dialogue-annotation-wrapper-padding-x': {
    value: '12px',
    category: 'spacing',
    label: '参考来源外层水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_annotation_wrapper-paddingX',
  },
  'ai-chat-dialogue-annotation-content-column-gap': {
    value: '8px',
    category: 'spacing',
    label: '参考来源内容列间距',
    usage: 'Semi $spacing-aiChatDialogue_annotation_content-columnGap',
  },
  'ai-chat-dialogue-references-margin-top': {
    value: '8px',
    category: 'spacing',
    label: '引用顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_references-marginTop',
  },
  'ai-chat-dialogue-references-column-gap': {
    value: '4px',
    category: 'spacing',
    label: '引用列间距',
    usage: 'Semi $spacing-aiChatDialogue_references-columnGap',
  },
  'ai-chat-dialogue-references-row-gap': {
    value: '4px',
    category: 'spacing',
    label: '引用行间距',
    usage: 'Semi $spacing-aiChatDialogue_references-rowGap',
  },
  'ai-chat-dialogue-reference-padding-y': {
    value: '8px',
    category: 'spacing',
    label: '引用垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_reference-paddingY',
  },
  'ai-chat-dialogue-reference-padding-x': {
    value: '12px',
    category: 'spacing',
    label: '引用水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_reference-paddingX',
  },
  'ai-chat-dialogue-reference-column-gap': {
    value: '8px',
    category: 'spacing',
    label: '引用列间距',
    usage: 'Semi $spacing-aiChatDialogue_reference-columnGap',
  },
  'ai-chat-dialogue-reference-icon-margin-right': {
    value: '4px',
    category: 'spacing',
    label: '引用图标右外边距',
    usage: 'Semi $spacing-aiChatDialogue_reference_icon-marginRight',
  },
  'ai-chat-dialogue-reference-img-margin-right': {
    value: '4px',
    category: 'spacing',
    label: '引用图片右外边距',
    usage: 'Semi $spacing-aiChatDialogue_reference_img-marginRight',
  },
  'ai-chat-dialogue-icon-reference-padding-y': {
    value: '0px',
    category: 'spacing',
    label: '用户消息引用图标垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_icon_reference-paddingY',
  },
  'ai-chat-dialogue-icon-reference-padding-x': {
    value: '8px',
    category: 'spacing',
    label: '用户消息引用图标水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_icon_reference-paddingX',
  },
  'ai-chat-dialogue-code-top-slot-padding-y': {
    value: '8px',
    category: 'spacing',
    label: '代码块顶部槽垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_code_topSlot-paddingY',
  },
  'ai-chat-dialogue-code-top-slot-padding-x': {
    value: '16px',
    category: 'spacing',
    label: '代码块顶部槽水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_code_topSlot-paddingX',
  },
  'ai-chat-dialogue-hints-row-gap': {
    value: '8px',
    category: 'spacing',
    label: '提示行间距',
    usage: 'Semi $spacing-aiChatDialogue_hints-rowGap',
  },
  'ai-chat-dialogue-hints-margin-top': {
    value: '4px',
    category: 'spacing',
    label: '提示顶部外边距',
    usage: 'Semi $spacing-aiChatDialogue_hints-marginTop',
  },
  'ai-chat-dialogue-hints-margin-bottom': {
    value: '12px',
    category: 'spacing',
    label: '提示底部外边距',
    usage: 'Semi $spacing-aiChatDialogue_hints-marginBottom',
  },
  'ai-chat-dialogue-hints-margin-left': {
    value: '52px',
    category: 'spacing',
    label: '提示左外边距',
    usage: 'Semi $spacing-aiChatDialogue_hints-marginLeft',
  },
  'ai-chat-dialogue-hint-item-padding-y': {
    value: '8px',
    category: 'spacing',
    label: '提示项垂直内边距',
    usage: 'Semi $spacing-aiChatDialogue_hint_item-paddingY',
  },
  'ai-chat-dialogue-hint-item-padding-x': {
    value: '16px',
    category: 'spacing',
    label: '提示项水平内边距',
    usage: 'Semi $spacing-aiChatDialogue_hint_item-paddingX',
  },
  'ai-chat-dialogue-hints-selecting-margin-left': {
    value: '68px',
    category: 'spacing',
    label: '提示项选择状态下左外边距',
    usage: 'Semi $spacing-aiChatDialogue_hints_selecting-marginLeft',
  },
  'radius-ai-chat-dialogue-back-bottom-button': {
    value: '50%',
    category: 'radius',
    label: '返回按钮圆角',
    usage: 'Semi $radius-aiChatDialogue_backBottom_button',
  },
  'ai-chat-dialogue-wrapper-selected': {
    value: '16px',
    category: 'radius',
    label: '外层选中圆角',
    usage: 'Semi $radius-aiChatDialogue_wrapper_selected',
  },
  'radius-ai-chat-dialogue-loading-circle': {
    value: 'var(--cd-border-radius-circle)',
    category: 'radius',
    label: '加载圆点圆角',
    usage: 'Semi $radius-aiChatDialogue_loading_circle',
  },
  'ai-chat-dialogue-bubble': {
    value: 'var(--cd-border-radius-large)',
    category: 'radius',
    label: '对话气泡圆角',
    usage: 'Semi $radius-aiChatDialogue_bubble',
  },
  'radius-ai-chat-dialogue-img': {
    value: 'var(--cd-border-radius-medium)',
    category: 'radius',
    label: '图片圆角',
    usage: 'Semi $radius-aiChatDialogue_img',
  },
  'radius-ai-chat-dialogue-file': {
    value: 'var(--cd-border-radius-medium)',
    category: 'radius',
    label: '文件组件圆角',
    usage: 'Semi $radius-aiChatDialogue_file',
  },
  'ai-chat-dialogue-icon-wrapper': {
    value: 'var(--cd-border-radius-extra-small)',
    category: 'radius',
    label: '图标外层圆角',
    usage: 'Semi $radius-aiChatDialogue_icon_wrapper',
  },
  'ai-chat-dialogue-tool-call': {
    value: 'var(--cd-border-radius-medium)',
    category: 'radius',
    label: '工具调用组件圆角',
    usage: 'Semi $radius-aiChatDialogue_tool_call',
  },
  'radius-ai-chat-dialogue-reasoning-wrapper': {
    value: 'var(--cd-border-radius-large)',
    category: 'radius',
    label: '推理组件外层圆角',
    usage: 'Semi $radius-aiChatDialogue_reasoning_wrapper',
  },
  'ai-chat-dialogue-step': {
    value: 'var(--cd-border-radius-medium)',
    category: 'radius',
    label: '步骤组件圆角',
    usage: 'Semi $radius-aiChatDialogue_step',
  },
  'ai-chat-dialogue-action-desc': {
    value: 'var(--cd-border-radius-medium)',
    category: 'radius',
    label: '操作描述圆角',
    usage: 'Semi $radius-aiChatDialogue_action_desc',
  },
  'ai-chat-dialogue-annotation-wrapper': {
    value: 'var(--cd-border-radius-medium)',
    category: 'radius',
    label: '参考来源外层圆角',
    usage: 'Semi $radius-aiChatDialogue_annotation_wrapper',
  },
  'ai-chat-dialogue-reference': {
    value: 'var(--cd-border-radius-medium)',
    category: 'radius',
    label: '引用组件圆角',
    usage: 'Semi $radius-aiChatDialogue_reference',
  },
  'radius-ai-chat-dialogue-reference-icon': {
    value: '2px',
    category: 'radius',
    label: '引用图标圆角',
    usage: 'Semi $radius-aiChatDialogue_reference_icon',
  },
  'ai-chat-dialogue-code': {
    value: 'var(--cd-border-radius-large)',
    category: 'radius',
    label: '代码块圆角',
    usage: 'Semi $radius-aiChatDialogue_code',
  },
  'ai-chat-dialogue-hint-item': {
    value: 'var(--cd-border-radius-medium)',
    category: 'radius',
    label: '提示项圆角',
    usage: 'Semi $radius-aiChatDialogue_hint_item',
  },
  'ai-chat-dialogue-title-font-size': {
    value: '$font-size-header-6',
    category: 'font',
    label: '标题字体大小',
    usage: 'Semi $font-aiChatDialogue_title-fontSize',
  },
  'ai-chat-dialogue-title-font-weight': {
    value: '$font-weight-regular',
    category: 'font',
    label: '标题字体粗细',
    usage: 'Semi $font-aiChatDialogue_title-fontWeight',
  },
  'ai-chat-dialogue-title-line-height': {
    value: '20px',
    category: 'font',
    label: '标题行高',
    usage: 'Semi $font-aiChatDialogue_title-lineHeight',
  },
  'ai-chat-dialogue-content-font-size': {
    value: '$font-size-regular',
    category: 'font',
    label: '内容字体大小',
    usage: 'Semi $font-aiChatDialogue_content-fontSize',
  },
  'ai-chat-dialogue-loading-text-font-size': {
    value: '$font-size-regular',
    category: 'font',
    label: '加载文本字体大小',
    usage: 'Semi $font-aiChatDialogue_loading_text-fontSize',
  },
  'ai-chat-dialogue-file-title-font-size': {
    value: '$font-size-header-6',
    category: 'font',
    label: '文件标题字体大小',
    usage: 'Semi $font-aiChatDialogue_file_title-fontSize',
  },
  'ai-chat-dialogue-file-metadata-font-size': {
    value: '$font-size-regular',
    category: 'font',
    label: '文件元数据字体大小',
    usage: 'Semi $font-aiChatDialogue_file_metadata-fontSize',
  },
  'ai-chat-dialogue-reasoning-header-title-font-weight': {
    value: '$font-weight-bold',
    category: 'font',
    label: '推理头部标题字体粗细',
    usage: 'Semi $font-aiChatDialogue_reasoning_header_title-fontWeight',
  },
  'ai-chat-dialogue-reasoning-header-title-line-height': {
    value: '22px',
    category: 'font',
    label: '推理头部标题行高',
    usage: 'Semi $font-aiChatDialogue_reasoning_header_title-lineHeight',
  },
  'ai-chat-dialogue-dropdown-icon-font-size': {
    value: '$font-size-header-6',
    category: 'font',
    label: '下拉菜单图标字体大小',
    usage: 'Semi $font-aiChatDialogue_dropdown_icon-fontSize',
  },
  'ai-chat-dialogue-step-font-size': {
    value: '$font-size-regular',
    category: 'font',
    label: '步骤字体大小',
    usage: 'Semi $font-aiChatDialogue_step-fontSize',
  },
  'ai-chat-dialogue-step-line-height': {
    value: '20px',
    category: 'font',
    label: '步骤行高',
    usage: 'Semi $font-aiChatDialogue_step-lineHeight',
  },
  'ai-chat-dialogue-step-action-font-size': {
    value: '$font-size-regular',
    category: 'font',
    label: '步骤 action 字体大小',
    usage: 'Semi $font-aiChatDialogue_step_action-fontSize',
  },
  'ai-chat-dialogue-step-action-line-height': {
    value: '20px',
    category: 'font',
    label: '步骤 action 行高',
    usage: 'Semi $font-aiChatDialogue_step_action-lineHeight',
  },
  'ai-chat-dialogue-annotation-content-font-size': {
    value: '$font-size-regular',
    category: 'font',
    label: '参考来源内容字体大小',
    usage: 'Semi $font-aiChatDialogue_annotation_content-fontSize',
  },
  'ai-chat-dialogue-references-font-size': {
    value: '12px',
    category: 'font',
    label: '引用字体大小',
    usage: 'Semi $font-aiChatDialogue_references-fontSize',
  },
  'ai-chat-dialogue-references-line-height': {
    value: '$font-size-header-6',
    category: 'font',
    label: '引用行高',
    usage: 'Semi $font-aiChatDialogue_references-lineHeight',
  },
  'ai-chat-dialogue-code-top-slot-font-size': {
    value: '$font-size-regular',
    category: 'font',
    label: '代码块顶部槽字体大小',
    usage: 'Semi $font-aiChatDialogue_code_topSlot-fontSize',
  },
  'ai-chat-dialogue-code-line-height': {
    value: '32px',
    category: 'font',
    label: '代码块行高',
    usage: 'Semi $font-aiChatDialogue_code-lineHeight',
  },
  'ai-chat-dialogue-hint-content-font-size': {
    value: '$font-size-regular',
    category: 'font',
    label: '提示内容字体大小',
    usage: 'Semi $font-aiChatDialogue_hint_content-fontSize',
  },
  'z-ai-chat-dialogue-back-bottom': {
    value: '1',
    category: 'other',
    label: '返回按钮z-index',
    usage: 'Semi $z-aiChatDialogue_backBottom',
  },
} satisfies TokenGroup;
