/** Component tokens for Drawer / SideSheet (M5 Feedback). 回退 Alias，禁写死。 */
export const drawerTokens = {
  'drawer-bg': 'var(--cd-color-bg-0)',
  'drawer-color-text': 'var(--cd-color-text-0)',
  'drawer-color-title': 'var(--cd-color-text-0)',
  'drawer-border': 'var(--cd-color-border)',
  'drawer-mask-bg': 'rgba(0, 0, 0, 0.45)',
  'drawer-shadow': 'var(--cd-shadow-elevated)',
  'drawer-width': '448px',
  'drawer-width-small': '320px',
  'drawer-width-large': '720px',
  'drawer-height': '320px',
  'drawer-height-small': '240px',
  'drawer-height-large': '480px',
  'drawer-header-padding': 'var(--cd-spacing-base-loose)',
  'drawer-body-padding': 'var(--cd-spacing-base-loose)',
  'drawer-footer-padding': 'var(--cd-spacing-base) var(--cd-spacing-base-loose)',
  'drawer-title-color': 'var(--cd-color-text-0)',
  'drawer-title-size': 'var(--cd-font-size-header-6)',
  'drawer-close-color': 'var(--cd-color-text-2)',
  'drawer-close-color-hover': 'var(--cd-color-text-0)',
  'drawer-close-hover-bg': 'var(--cd-color-fill-1)',
  'drawer-z': '1000',
  'drawer-motion-duration': 'var(--cd-motion-duration-mid)',
} as const;
