/** Component tokens for Notification (M5 Feedback). 回退 Alias，禁写死。 */
export const notificationTokens = {
  'notification-width': '360px',
  'notification-bg': 'var(--cd-color-bg-0)',
  'notification-color-title': 'var(--cd-color-text-0)',
  'notification-color-content': 'var(--cd-color-text-1)',
  'notification-border': 'var(--cd-color-border)',
  'notification-radius': 'var(--cd-border-radius-large)',
  'notification-shadow': 'var(--cd-shadow-3)',
  'notification-padding': 'var(--cd-spacing-base)',
  'notification-gap': 'var(--cd-spacing-base-tight)',
  'notification-icon-success': 'var(--cd-color-success)',
  'notification-icon-info': 'var(--cd-color-primary)',
  'notification-icon-warning': 'var(--cd-color-warning)',
  'notification-icon-error': 'var(--cd-color-danger)',
  'notification-close-color': 'var(--cd-color-text-2)',
  'notification-close-color-hover': 'var(--cd-color-text-0)',
  'notification-title-size': 'var(--cd-font-size-regular)',
  'notification-content-size': 'var(--cd-font-size-small)',
  'notification-z': '1100',
  'notification-offset': 'var(--cd-spacing-loose)',
  'notification-motion-duration': 'var(--cd-motion-duration-mid)',
  // showProgress 倒计时进度条
  'notification-progress-height': '3px',
  'notification-progress-color': 'var(--cd-color-primary)',
  // dark 主题卡片
  'notification-bg-dark': 'var(--cd-color-text-0)',
  'notification-border-dark': 'var(--cd-color-text-0)',
  'notification-color-title-dark': 'var(--cd-color-bg-0)',
  'notification-color-content-dark': 'var(--cd-color-bg-1)',
  'notification-close-color-dark': 'var(--cd-color-bg-2)',
  'notification-close-color-hover-dark': 'var(--cd-color-bg-0)',
} as const;
