/** Component tokens for SideSheet (M5 Feedback). 回退 Alias，禁写死。 */
export const sideSheetTokens = {
  'sidesheet-bg': 'var(--cd-color-bg-0)',
  'sidesheet-color': 'var(--cd-color-text-0)',
  'sidesheet-mask-bg': 'rgba(0, 0, 0, 0.6)',
  'sidesheet-border': 'var(--cd-color-border)',
  'sidesheet-radius': 'var(--cd-border-radius-large)',
  'sidesheet-shadow': 'var(--cd-shadow-3)',
  'sidesheet-padding': 'var(--cd-spacing-base-loose)',
  'sidesheet-header-padding': 'var(--cd-spacing-base) var(--cd-spacing-base-loose)',
  'sidesheet-footer-padding': 'var(--cd-spacing-base) var(--cd-spacing-base-loose)',
  'sidesheet-title-color': 'var(--cd-color-text-0)',
  'sidesheet-title-size': 'var(--cd-font-size-header-6)',
  'sidesheet-close-color': 'var(--cd-color-text-2)',
  'sidesheet-close-color-hover': 'var(--cd-color-text-0)',
  'sidesheet-close-hover-bg': 'var(--cd-color-fill-1)',
  'sidesheet-width-small': '448px',
  'sidesheet-width': '60%',
  'sidesheet-width-large': '90%',
  'sidesheet-height-small': '40%',
  'sidesheet-height': '60%',
  'sidesheet-height-large': '90%',
  'sidesheet-z': '1000',
  'sidesheet-motion-duration': 'var(--cd-motion-duration-mid)',
} as const;
