/**
 * 纯逻辑：校验主题配置 + 生成主题 CSS。与文件 I/O、config 加载解耦，便于单测。
 */
import type { ThemeConfig } from './config.js';
import { allTokenKeys, overridableKeys } from './tokens.js';

export interface ValidationIssue {
  /** 出问题的无前缀 key。 */
  key: string;
  /** 所在段。 */
  section: 'alias' | 'dark';
  /**
   * 'unknown'：manifest 里根本不存在此 token（大概率拼错）。
   * 'not-overridable'：token 存在但属组件层，主题包不建议覆写。
   */
  kind: 'unknown' | 'not-overridable';
}

export interface ValidationResult {
  /** 阻断性错误：unknown key（拼错）。 */
  errors: ValidationIssue[];
  /** 非阻断警告：覆写了非 alias/global 层的合法 token。 */
  warnings: ValidationIssue[];
}

function collect(
  map: Record<string, string> | undefined,
  section: 'alias' | 'dark',
  errors: ValidationIssue[],
  warnings: ValidationIssue[],
): void {
  if (!map) return;
  for (const key of Object.keys(map)) {
    if (!allTokenKeys.has(key)) {
      errors.push({ key, section, kind: 'unknown' });
    } else if (!overridableKeys.has(key)) {
      warnings.push({ key, section, kind: 'not-overridable' });
    }
  }
}

/** 校验 config 里每个 key 是否为真实存在的、可覆写的 token。 */
export function validateConfig(config: ThemeConfig): ValidationResult {
  const errors: ValidationIssue[] = [];
  const warnings: ValidationIssue[] = [];
  collect(config.alias, 'alias', errors, warnings);
  collect(config.dark, 'dark', errors, warnings);
  return { errors, warnings };
}

function block(selector: string, map: Record<string, string>): string {
  const lines = Object.entries(map).map(([k, v]) => `  --cd-${k}: ${v};`);
  return `${selector} {\n${lines.join('\n')}\n}`;
}

/**
 * 生成主题 CSS：
 *   :root{ --cd-<k>: v }              // alias 段
 *   [data-theme="dark"]{ --cd-<k>: v } // dark 段（若有）
 * 空段跳过。
 */
export function generateCss(config: ThemeConfig): string {
  const parts: string[] = ['/* Generated by @chenzy-design/theme-cli. Do not edit by hand. */'];
  const alias = config.alias ?? {};
  const dark = config.dark ?? {};
  if (Object.keys(alias).length > 0) parts.push(block(':root', alias));
  if (Object.keys(dark).length > 0) parts.push(block('[data-theme="dark"]', dark));
  return parts.join('\n\n') + '\n';
}
