/**
 * Machine-readable component metadata for AI/docs consumption.
 * ScrollList / ScrollItem — 严格对齐 Semi Design（semi-ui/scrollList）。
 */
export const meta = {
  name: 'ScrollList',
  category: 'show',
  description:
    '滚动列表，类似 iOS 的滚动选择模式。ScrollList 是纯容器（header/footer/bodyHeight），内部放若干 ScrollItem 组成多列。ScrollItem 有 wheel（滚轮，滚动/点击将候选吸附到中央选区居中）与 normal（普通列表，点击选中并高亮）两种模式；wheel 支持 cycled 无限循环、motion 缓动、transform 选中项文案变换、disabled 跳过。选择通过 selectedIndex 受控 + onSelect(data) 回调（data 含 value/index/type）。复用 @chenzy-design/core 纯函数（resolveItemText/centerOffset/nearestIndex/wrapIndex/scrollFrame/shouldPrepend/shouldAppend）。',
  exports: ['ScrollList', 'ScrollItem'],
  // ScrollList（容器）props 放顶层；ScrollItem（列）props 放 subComponents。
  props: [
    { name: 'header', type: 'Snippet | string', default: 'undefined', desc: '头部 addon（对齐 Semi header）' },
    { name: 'footer', type: 'Snippet | string', default: 'undefined', desc: '底部 addon（对齐 Semi footer）' },
    { name: 'bodyHeight', type: 'number | string', default: 'undefined', desc: 'body 高度；数字按 px（对齐 Semi bodyHeight）' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根节点类名（对齐 Semi className）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根节点内联样式（对齐 Semi style）' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '列内容：若干 <ScrollItem>' },
  ],
  subComponents: [
    {
      name: 'ScrollItem',
      usage: '<ScrollItem mode="wheel" list={data} selectedIndex={i} onSelect={fn} /> 作为 ScrollList 的子列',
      desc: '单列滚动选择：wheel（滚轮吸附居中）/ normal（点击选中并高亮）。对齐 Semi ScrollItem。',
      props: [
        { name: 'mode', type: "'wheel' | 'normal'", default: "'wheel'", desc: '模式：wheel 吸附居中 / normal 点击选中' },
        { name: 'cycled', type: 'boolean', default: 'false', desc: '无限循环（仅 wheel 生效）' },
        { name: 'list', type: 'ScrollItemData[]', default: '[]', desc: '列表数据，项 = { value; text?; disabled?; transform? }' },
        { name: 'selectedIndex', type: 'number', default: '0', desc: '选中项索引（受控）' },
        { name: 'motion', type: 'boolean', default: 'true', desc: '是否开启滚动缓动动画' },
        { name: 'transform', type: '(value, text) => string', default: 'undefined', desc: '选中项文案变换（列级公共）' },
        { name: 'type', type: 'string | number', default: 'undefined', desc: '列标识，透传回 onSelect 供外层区分列' },
        { name: 'onSelect', type: '(data: ScrollItemSelectPayload) => void', default: 'undefined', desc: '选中回调，data 含 value/index/type' },
        { name: 'class', type: 'string', default: 'undefined', desc: '列样式类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '列内联样式' },
        { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '列无障碍标签' },
      ],
    },
  ],
  events: [
    { name: 'onSelect', desc: '选中项变化（wheel 滚动落定/点击、normal 点击）；载荷 {...item, value, index, type}' },
  ],
  slots: [
    { name: 'header', desc: 'ScrollList 头部 addon' },
    { name: 'footer', desc: 'ScrollList 底部 addon' },
  ],
  a11y: {
    hasRole: true,
    focusable: false,
    note: '每列 ul role=listbox + aria-label + aria-multiselectable=false；每项 li role=option + aria-selected；disabled 项 aria-disabled。',
  },
  tokens: [
    // —— Semi 全量对齐（semi-foundation/scrollList/variables.scss 39 变量 + animation.scss 3 变量）——
    '--cd-color-scroll-list-bg',
    '--cd-color-scroll-list-border',
    '--cd-color-scroll-list-header-bg',
    '--cd-color-scroll-list-header-title',
    '--cd-color-scroll-list-item-bg',
    '--cd-color-scroll-list-item-text',
    '--cd-color-scroll-list-disabled-item-text',
    '--cd-color-scroll-list-item-text-hover',
    '--cd-color-scroll-list-item-bg-active',
    '--cd-color-scroll-list-selected-item-bg',
    '--cd-color-scroll-list-selected-item-text',
    '--cd-color-scroll-list-selected-item-icon',
    '--cd-color-scroll-list-footer-border',
    '--cd-height-scroll-list',
    '--cd-height-scroll-list-item',
    '--cd-width-scroll-list-item-border',
    '--cd-width-scroll-list-item-sel-svg',
    '--cd-width-scroll-list-item-wheel-border',
    '--cd-width-scroll-list-item-wheel-selector-border',
    '--cd-height-scroll-list-line',
    '--cd-width-scroll-list-footer-border',
    '--cd-spacing-scroll-list-header-paddingy',
    '--cd-spacing-scroll-list-header-paddingx',
    '--cd-spacing-scroll-list-header-title-paddingy',
    '--cd-spacing-scroll-list-header-title-paddingx',
    '--cd-spacing-scroll-list-body-paddingy',
    '--cd-spacing-scroll-list-body-paddingx',
    '--cd-spacing-scroll-list-item-ul-padding',
    '--cd-spacing-scroll-list-item-ul-margin',
    '--cd-spacing-scroll-list-item-ul-paddingbottom',
    '--cd-spacing-scroll-list-item-sel-svg-marginright',
    '--cd-spacing-scroll-list-item-wheel-list-outer-paddingright',
    '--cd-spacing-scroll-list-item-wheel-list-shade-pre-margintop',
    '--cd-spacing-scroll-list-item-wheel-list-shade-post-margintop',
    '--cd-spacing-scroll-list-footer-padding',
    '--cd-radius-scroll-list',
    '--cd-font-scroll-list-header-title-fontweight',
    '--cd-font-scroll-list-item-wheel-item-selected-fontweight',
    '--cd-transition-duration-scroll-list-selected-item-bg',
    '--cd-transition-function-scroll-list-selected-item-bg',
    '--cd-transition-delay-scroll-list-selected-item-bg',
    '--cd-shadow-scroll-list',
  ],
  responsive: false,
  examples: [
    {
      title: '滚轮多列（时/分）',
      code: '<ScrollList header="时间"><ScrollItem mode="wheel" cycled list={hours} selectedIndex={h} onSelect={(d) => (h = d.index)} /><ScrollItem mode="wheel" cycled list={minutes} selectedIndex={m} onSelect={(d) => (m = d.index)} /></ScrollList>',
    },
    {
      title: '普通列表点击选中',
      code: '<ScrollList><ScrollItem mode="normal" list={items} selectedIndex={i} onSelect={(d) => (i = d.index)} /></ScrollList>',
    },
    {
      title: '选中项文案变换',
      code: '<ScrollItem mode="wheel" list={hours} selectedIndex={h} transform={(v) => `${v} 时`} onSelect={(d) => (h = d.index)} />',
    },
  ],
} as const;
