/**
 * Machine-readable component metadata for AI/docs consumption.
 * AudioPlayer — 严格对齐 Semi AudioPlayer（semi-ui/audioPlayer）。基于原生 <audio>，无第三方媒体库。
 * DOM 单行布局镜像 Semi；复用 Button/Dropdown/Popover/Tooltip/Image + 具名图标；40 token 镜像 Semi variables.scss。
 */
export const meta = {
  name: 'AudioPlayer',
  category: 'plus',
  stage: 'M6',
  semiEquivalent: 'AudioPlayer',
  description:
    '基于原生 <audio> 的音频播放器（严格对齐 Semi，无第三方媒体库）。audioUrl 接受 string | AudioInfo | (string|AudioInfo)[] 四形态；数组时启用播放列表（上/下曲、ended 自动切下一曲、取模循环连播）。工具栏含音量(Popover 竖向 slider)、快退/快进(按 skipDuration)、倍速(Dropdown 5 档 0.5/0.75/1/1.5/2)、刷新；播放控制含上/下曲(多曲)+播放/暂停(圆形)。进度/音量用自建 AudioSlider(hover 变粗+拖拽圆点+Tooltip 时间预览)。深/浅双主题(默认 dark)。静音切换 0↔50%(照搬 Semi)。',
  exports: ['AudioPlayer'],
  props: [
    {
      name: 'audioUrl',
      type: 'string | AudioInfo | (string | AudioInfo)[]',
      default: '—',
      desc: '音频地址（四形态，AudioInfo = { src; title?; cover? }）；数组启用播放列表',
    },
    { name: 'autoPlay', type: 'boolean', default: 'false', desc: '自动播放（对齐 Semi）' },
    { name: 'showToolbar', type: 'boolean', default: 'true', desc: '是否显示工具栏（音量/快退/快进/倍速/刷新）' },
    { name: 'skipDuration', type: 'number', default: '10', desc: '快进/快退步长（秒），注入 backward/forward Tooltip 文案' },
    { name: 'theme', type: "'dark' | 'light'", default: "'dark'", desc: '主题（对齐 Semi 默认 dark）' },
    { name: 'class', type: 'string', default: "''", desc: '根节点类名（对齐 Semi className）' },
    { name: 'style', type: 'string', default: "''", desc: '根节点内联样式（对齐 Semi style）' },
  ],
  events: [],
  slots: [],
  a11y: {
    role: 'group',
    focusable: false,
    notes: [
      '各控制按钮为本库 Button，外包 Tooltip（走 i18n 文案：prev/next/backward/forward/volume）',
      '倍速触发器 role=button + tabindex=0（Dropdown 附加 aria-haspopup/expanded，补 role 使其合法可键盘聚焦）',
      '自建 AudioSlider role=slider + aria-valuemin/max/now + aria-orientation + aria-label（进度/音量）',
      '多曲取模循环（对齐 Semi，无边界 disabled；末曲 next 绕回首曲）',
      '播放出错时工具栏仅保留刷新按钮（对齐 Semi error 分支）；错误块图标 + 硬编码文案(照搬 Semi)',
    ],
  },
  // 40 token 严格镜像 Semi variables.scss（深/浅双主题各一套色 + 尺寸/间距/圆角）。
  tokens: [
    '--cd-color-audio-player-background',
    '--cd-color-audio-player-control-icon',
    '--cd-color-audio-player-control-icon-play',
    '--cd-color-audio-player-font-color',
    '--cd-color-audio-player-font-color-speed',
    '--cd-color-audio-player-background-light',
    '--cd-color-audio-player-control-icon-light',
    '--cd-color-audio-player-control-icon-play-light',
    '--cd-color-audio-player-font-color-light',
    '--cd-font-size-audio-player-text',
    '--cd-gap-audio-player-small',
    '--cd-gap-audio-player-medium',
    '--cd-gap-audio-player-large',
    '--cd-width-audio-player-max',
    '--cd-height-audio-player',
    '--cd-width-audio-player-slider',
    '--cd-width-audio-player-speed',
    '--cd-height-audio-player-speed',
    '--cd-width-audio-player-speed-menu',
    '--cd-width-audio-player-volume',
    '--cd-height-audio-player-volume',
    '--cd-height-audio-player-time',
    '--cd-border-radius-audio-player-speed',
    '--cd-border-radius-audio-player-volume',
    '--cd-border-radius-audio-player-slider',
    '--cd-font-size-audio-player-small',
    '--cd-line-height-audio-player-small',
    '--cd-width-audio-player-slider-bar',
    '--cd-size-audio-player-slider-dot',
    '--cd-color-audio-player-disabled-bg',
    '--cd-color-audio-player-slider-bg',
    '--cd-color-audio-player-slider-bg-light',
    '--cd-color-audio-player-slider-progress',
    '--cd-color-audio-player-slider-dot-bg',
    '--cd-color-audio-player-disabled-text',
    '--cd-color-audio-player-text-default',
    '--cd-color-audio-player-light-disabled-bg',
    '--cd-color-audio-player-light-disabled-text',
    '--cd-color-audio-player-light-text',
    '--cd-color-audio-player-light-hover-bg',
  ],
  examples: [
    { title: '基本用法(字符串)', code: '<AudioPlayer audioUrl="/audio/song.mp3" />' },
    {
      title: '带封面/标题',
      code: '<AudioPlayer audioUrl={{ src: "/a.mp3", title: "标题", cover: "/cover.png" }} />',
    },
    {
      title: '播放列表(数组)',
      code: '<AudioPlayer audioUrl={[{ src: "/a.mp3", title: "A" }, { src: "/b.mp3", title: "B" }]} />',
    },
    { title: '隐藏工具栏', code: '<AudioPlayer audioUrl="/a.mp3" showToolbar={false} />' },
    { title: '浅色主题', code: '<AudioPlayer audioUrl="/a.mp3" theme="light" />' },
  ],
} as const;
