/**
 * Token CSS build: source TS → dist/tokens.css.
 * TS entrypoints (index.ts, uno-theme.ts) are real source files compiled by tsc.
 * Run via `pnpm --filter @chenzy-design/tokens build`.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { palette } from './global/color.js';
import * as scales from './global/scales.js';
import { aliasLight, aliasDark } from './alias/index.js';
import { buttonTokens } from './components/button.js';

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(here, '../dist');
mkdirSync(dist, { recursive: true });

const PREFIX = '--cd-';

function vars(group: Record<string, string>, category = ''): string[] {
  const cat = category ? `${category}-` : '';
  return Object.entries(group).map(([k, v]) => `  ${PREFIX}${cat}${k}: ${v};`);
}

const globalVars = [
  ...vars(palette, 'color'),
  ...vars(scales.spacing, 'spacing'),
  ...vars(scales.radius, 'radius'),
  ...vars(scales.fontSize, 'font-size'),
  ...vars(scales.fontWeight, 'font-weight'),
  ...vars(scales.lineHeight, 'line-height'),
  ...vars(scales.shadow, 'shadow'),
  ...vars(scales.motion, 'motion'),
  ...vars(scales.zIndex, 'z'),
];
const aliasVars = vars(aliasLight);
const componentVars = vars(buttonTokens);
const darkVars = vars(aliasDark as Record<string, string>);

const css = `/* AUTO-GENERATED by @chenzy-design/tokens build — do not edit */
:root {
  /* --- Global --- */
${globalVars.join('\n')}
  /* --- Alias (semantic) --- */
${aliasVars.join('\n')}
  /* --- Component --- */
${componentVars.join('\n')}
}

[data-theme='dark'] {
${darkVars.join('\n')}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    ${PREFIX}motion-duration-fast: 0ms;
    ${PREFIX}motion-duration-mid: 0ms;
    ${PREFIX}motion-duration-slow: 0ms;
  }
}
`;
writeFileSync(resolve(dist, 'tokens.css'), css);
console.log('[tokens] built dist/tokens.css');
