/**
 * Token CSS build: source TS → dist/tokens.css.
 * TS entrypoints (index.ts, uno-theme.ts) are real source files compiled by tsc.
 * Run via `pnpm --filter @chenzy-design/tokens build`.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { palette } from './global/color.js';
import * as scales from './global/scales.js';
import { aliasLight, aliasDark } from './alias/index.js';
import { componentTokens } from './components/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(here, '../dist');
mkdirSync(dist, { recursive: true });

const PREFIX = '--cd-';

function vars(group: Record<string, string>, category = ''): string[] {
  const cat = category ? `${category}-` : '';
  return Object.entries(group).map(([k, v]) => `  ${PREFIX}${cat}${k}: ${v};`);
}

const globalVars = [
  ...vars(palette, 'color'),
  ...vars(scales.spacing, 'spacing'),
  ...vars(scales.radius, 'radius'),
  ...vars(scales.fontSize, 'font-size'),
  ...vars(scales.fontWeight, 'font-weight'),
  ...vars(scales.lineHeight, 'line-height'),
  ...vars(scales.shadow, 'shadow'),
  ...vars(scales.motion, 'motion'),
  ...vars(scales.zIndex, 'z'),
  ...vars(scales.breakpoint, 'breakpoint'),
  ...vars(scales.sizing),
];
const aliasVars = vars(aliasLight);
const componentVars = vars(componentTokens);
const darkVars = vars(aliasDark as Record<string, string>);

const css = `/* AUTO-GENERATED by @chenzy-design/tokens build — do not edit */
:root {
  /* --- Global --- */
${globalVars.join('\n')}
  /* --- Alias (semantic) --- */
${aliasVars.join('\n')}
  /* --- Component --- */
${componentVars.join('\n')}
}

[data-theme='dark'] {
${darkVars.join('\n')}
}

/* Base：把页面背景/前景绑到主题 token，使暗色模式开箱即用（对齐 Semi —— Semi 同样
   在 body 上应用主题背景）。消费方若要自管 body 背景，可不引入此规则（见 base 单独导出）
   或用更高优先级覆盖。过渡令亮/暗切换平滑，prefers-reduced-motion 下自动归零。 */
body {
  background-color: var(${PREFIX}color-bg-0);
  color: var(${PREFIX}color-text-0);
  transition:
    background-color var(${PREFIX}motion-duration-mid) var(${PREFIX}motion-ease-standard),
    color var(${PREFIX}motion-duration-mid) var(${PREFIX}motion-ease-standard);
}

@media (prefers-reduced-motion: reduce) {
  :root {
    ${PREFIX}motion-duration-fast: 0ms;
    ${PREFIX}motion-duration-mid: 0ms;
    ${PREFIX}motion-duration-slow: 0ms;
  }
}

/* JS 驱动的全局降级标记：ConfigProvider reducedMotion 显式开启时由 JS 写入，
   优先于系统媒体查询，令依赖 motion-duration token 的动画退化为 0ms。 */
[data-reduced-motion] {
  ${PREFIX}motion-duration-fast: 0ms;
  ${PREFIX}motion-duration-mid: 0ms;
  ${PREFIX}motion-duration-slow: 0ms;
}

/* 屏幕阅读器专用文本工具类（a11y.spec §全局规则）：
   视觉隐藏但屏幕阅读器可读。不可用 display:none / visibility:hidden，
   否则辅助技术也读不到。WCAG 1.4.1 等场景下令颜色/图标非唯一信息载体。 */
.cd-sr-only {
  position: absolute;
  inline-size: 1px;
  block-size: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
`;
writeFileSync(resolve(dist, 'tokens.css'), css);
console.log('[tokens] built dist/tokens.css');
