/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Slider',
  category: 'input',
  description: '在连续/离散区间内选值的滑块，支持单值与 range、刻度、垂直方向与全键盘操作。',
  props: [
    { name: 'value', type: 'number | [number, number]', default: 'undefined', desc: '受控值；range 时为二元组' },
    { name: 'defaultValue', type: 'number | [number, number]', default: 'min / [min,min]', desc: '非受控初始值' },
    { name: 'min', type: 'number', default: '0' },
    { name: 'max', type: 'number', default: '100' },
    { name: 'step', type: 'number | null', default: '1', desc: 'null 时仅停靠 marks 键' },
    { name: 'range', type: 'boolean', default: 'false', desc: '双滑块区间模式' },
    { name: 'marks', type: 'Record<number, string | { label: string; style?: string }>', default: 'undefined', desc: '刻度标记；对象形式可带自定义 style' },
    { name: 'dots', type: 'boolean', default: 'false', desc: '在每个 step 处显示圆点（段内激活色）' },
    { name: 'included', type: 'boolean', default: 'true', desc: '是否填充已选轨道段' },
    { name: 'vertical', type: 'boolean', default: 'false' },
    { name: 'verticalReverse', type: 'boolean', default: 'false', desc: '垂直时反向（顶部为 min）' },
    { name: 'height', type: 'number', default: '200', desc: '垂直模式高度（px）' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'clickable', type: 'boolean', default: 'true', desc: '是否允许点击轨道跳转到最近合法值' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default', desc: '校验态，影响已选轨道与手柄边框色' },
    { name: 'tooltipVisible', type: 'boolean | undefined', default: 'undefined', desc: '强制控制数值气泡显隐（受控）' },
    { name: 'alwaysShowTip', type: 'boolean', default: 'false', desc: '始终显示数值气泡' },
    { name: 'tipFormatter', type: '(value: number) => string | null', default: 'String', desc: '自定义气泡文案；返回 null 隐藏' },
    { name: 'getAriaValueText', type: '(value: number, index: number) => string', default: 'undefined', desc: '自定义 aria-valuetext（如带单位）' },
    { name: 'railStyle', type: 'string', default: 'undefined', desc: '透传轨道内联样式' },
    {
      name: 'trackStyle',
      type: 'Record<string, string> | Record<string, string>[]',
      default: 'undefined',
      desc: '已选轨道段自定义样式（range 时为数组，各段对应一个样式对象）',
    },
    { name: 'handleStyle', type: 'string', default: 'undefined', desc: '透传手柄内联样式' },
    {
      name: 'pushable',
      type: 'boolean | number',
      default: 'false',
      desc: 'range 模式下两手柄是否可相互推动（true=最小间距 0，number=最小间距值）',
    },
    {
      name: 'allowCross',
      type: 'boolean',
      default: 'true',
      desc: 'range 模式下是否允许交叉（false 时强制 left <= right）',
    },
    { name: 'id', type: 'string', default: 'undefined', desc: '根节点 id，关联表单 label' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'ariaLabelledby', type: 'string', default: 'undefined', desc: 'group 与各手柄 aria-labelledby（指向外部 label id）' },
    { name: 'onChange', type: '(v: number | [number, number]) => void', default: 'undefined', desc: '值变化（拖拽落定/键盘/点击）' },
    { name: 'onChangeComplete', type: '(v: number | [number, number]) => void', default: 'undefined', desc: '拖拽结束或键盘落定时触发，适合请求节流' },
    { name: 'onAfterChange', type: '(v: number | [number, number]) => void', default: 'undefined', desc: '拖拽/点击结束时触发（onChangeComplete 的别名）' },
    { name: 'onInput', type: '(v: number | [number, number]) => void', default: 'undefined', desc: '与 change 同步的低级输入信号（拖动中实时触发）' },
    { name: 'onFocus', type: '(detail: { index: number }) => void', default: 'undefined', desc: '手柄获得焦点，附带手柄索引' },
    { name: 'onBlur', type: '(detail: { index: number }) => void', default: 'undefined', desc: '手柄失焦，附带手柄索引' },
    { name: 'showBoundary', type: 'boolean', default: 'false', desc: '显示轨道两端边界值标签' },
    { name: 'showArrow', type: 'boolean', default: 'true', desc: 'tooltip 是否显示箭头' },
    { name: 'showMarkLabel', type: 'boolean', default: 'true', desc: '显示标记文本标签' },
    { name: 'tooltipOnMark', type: 'boolean', default: 'false', desc: 'tooltip 跟随标记位置' },
    { name: 'handleDot', type: '{ color: string; size: string } | { color: string; size: string }[]', default: 'undefined', desc: '自定义手柄圆点样式，range 时为数组' },
    { name: 'onMouseUp', type: '(e: MouseEvent) => void', default: 'undefined', desc: 'pointerup 时触发' },
    { name: 'ariaValuetext', type: 'string', default: 'undefined', desc: '覆盖 getAriaValueText 的 aria-valuetext 文案' },
  ],
  slots: [
    { name: 'mark', type: 'Snippet<[{ value: number; label: string; active: boolean }]>', desc: '自定义单个刻度标签渲染' },
    { name: 'handle', type: 'Snippet<[{ value: number; index: number; dragging: boolean; focused: boolean }]>', desc: '自定义手柄内容（如带数字徽标）' },
    { name: 'tooltip', type: 'Snippet<[{ value: number; index: number }]>', desc: '自定义数值气泡内部内容' },
  ],
  a11y: {
    role: 'slider',
    keyboard: ['ArrowUp/Right', 'ArrowDown/Left', 'PageUp', 'PageDown', 'Home', 'End'],
    notes: [
      '根容器 role=group，每个手柄 role=slider + tabindex=0',
      '手柄 aria-valuemin/valuemax/valuenow/aria-orientation',
      'range 模式两手柄不交叉（越过自动交换）',
      '拖拽命令式：pointerdown 读一次 rail rect，document 监听 pointermove/up',
      'disabled→aria-disabled，手柄 tabindex=-1',
      'aria-valuetext 优先 getAriaValueText，其次 tipFormatter 输出（带单位可读文案）',
      '数值气泡：hover/focus/拖拽显示，alwaysShowTip 常驻，tooltipVisible 强制受控',
    ],
  },
  tokens: [
    '--cd-slider-rail-height',
    '--cd-slider-rail-bg',
    '--cd-slider-track-bg',
    '--cd-slider-track-disabled-bg',
    '--cd-slider-handle-size',
    '--cd-slider-handle-bg',
    '--cd-slider-handle-border',
    '--cd-slider-handle-border-width',
    '--cd-slider-handle-radius',
    '--cd-slider-handle-shadow-hover',
    '--cd-slider-handle-focus-ring',
    '--cd-slider-handle-transition-duration',
    '--cd-slider-handle-transition-easing',
    '--cd-slider-radius',
    '--cd-slider-mark-color',
    '--cd-slider-mark-color-active',
    '--cd-slider-mark-font-size',
    '--cd-slider-dot-size',
    '--cd-slider-dot-bg',
    '--cd-slider-dot-border',
    '--cd-slider-dot-border-active',
    '--cd-slider-tip-bg',
    '--cd-slider-tip-color',
    '--cd-slider-tip-radius',
    '--cd-slider-tip-font-size',
    '--cd-slider-boundary-color',
    '--cd-slider-boundary-font-size',
    '--cd-slider-boundary-gap',
    '--cd-slider-padding',
    '--cd-slider-gap',
    '--cd-slider-status-warning',
    '--cd-slider-status-error',
  ],
} as const;
