/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Slider',
  category: 'input',
  description: '在连续/离散区间内选值的滑块，支持单值与 range、刻度、垂直方向与全键盘操作。',
  props: [
    { name: 'value', type: 'number | [number, number]', default: 'undefined', desc: '受控值；range 时为二元组' },
    { name: 'defaultValue', type: 'number | [number, number]', default: 'min / [min,min]', desc: '非受控初始值' },
    { name: 'min', type: 'number', default: '0' },
    { name: 'max', type: 'number', default: '100' },
    { name: 'step', type: 'number | null', default: '1', desc: 'null 时仅停靠 marks 键' },
    { name: 'range', type: 'boolean', default: 'false', desc: '双滑块区间模式' },
    { name: 'marks', type: 'Record<number, string>', default: 'undefined', desc: '刻度标记' },
    { name: 'dots', type: 'boolean', default: 'false', desc: '在每个 step 处显示圆点（段内激活色）' },
    { name: 'included', type: 'boolean', default: 'true', desc: '是否填充已选轨道段' },
    { name: 'vertical', type: 'boolean', default: 'false' },
    { name: 'verticalReverse', type: 'boolean', default: 'false', desc: '垂直时反向（顶部为 min）' },
    { name: 'height', type: 'number', default: '200', desc: '垂直模式高度（px）' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'clickable', type: 'boolean', default: 'true', desc: '是否允许点击轨道跳转到最近合法值' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default', desc: '校验态，影响已选轨道与手柄边框色' },
    { name: 'tooltipVisible', type: 'boolean | undefined', default: 'undefined', desc: '强制控制数值气泡显隐（受控）' },
    { name: 'alwaysShowTip', type: 'boolean', default: 'false', desc: '始终显示数值气泡' },
    { name: 'tipFormatter', type: '(value: number) => string | null', default: 'String', desc: '自定义气泡文案；返回 null 隐藏' },
    { name: 'getAriaValueText', type: '(value: number, index: number) => string', default: 'undefined', desc: '自定义 aria-valuetext（如带单位）' },
    { name: 'railStyle', type: 'string', default: 'undefined', desc: '透传轨道内联样式' },
    { name: 'handleStyle', type: 'string', default: 'undefined', desc: '透传手柄内联样式' },
    { name: 'id', type: 'string', default: 'undefined', desc: '根节点 id，关联表单 label' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'onChange', type: '(v: number | [number, number]) => void', default: 'undefined', desc: '值变化（拖拽落定/键盘/点击）' },
    { name: 'onChangeComplete', type: '(v: number | [number, number]) => void', default: 'undefined', desc: '拖拽结束或键盘落定时触发，适合请求节流' },
    { name: 'onInput', type: '(v: number | [number, number]) => void', default: 'undefined', desc: '与 change 同步的低级输入信号（拖动中实时触发）' },
    { name: 'onFocus', type: '(detail: { index: number }) => void', default: 'undefined', desc: '手柄获得焦点，附带手柄索引' },
    { name: 'onBlur', type: '(detail: { index: number }) => void', default: 'undefined', desc: '手柄失焦，附带手柄索引' },
  ],
  a11y: {
    role: 'slider',
    keyboard: ['ArrowUp/Right', 'ArrowDown/Left', 'PageUp', 'PageDown', 'Home', 'End'],
    notes: [
      '根容器 role=group，每个手柄 role=slider + tabindex=0',
      '手柄 aria-valuemin/valuemax/valuenow/aria-orientation',
      'range 模式两手柄不交叉（越过自动交换）',
      '拖拽命令式：pointerdown 读一次 rail rect，document 监听 pointermove/up',
      'disabled→aria-disabled，手柄 tabindex=-1',
      'aria-valuetext 优先 getAriaValueText，其次 tipFormatter 输出（带单位可读文案）',
      '数值气泡：hover/focus/拖拽显示，alwaysShowTip 常驻，tooltipVisible 强制受控',
    ],
  },
  tokens: ['--cd-slider-*', '--cd-color-text-3', '--cd-spacing-*', '--cd-radius-full', '--cd-shadow-1', '--cd-focus-ring', '--cd-motion-*'],
} as const;
