/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 * 严格对齐 Semi Slider API（semi-ui/slider）。
 */
export const meta = {
  name: 'Slider',
  category: 'input',
  description: '在连续/离散区间内选值的滑块，支持单值与 range、刻度、垂直方向与全键盘操作。严格对齐 Semi。',
  props: [
    { name: 'value', type: 'number | [number, number]', default: 'undefined', desc: '受控值；range 时为二元组' },
    { name: 'defaultValue', type: 'number | [number, number]', default: 'min / [min,min]', desc: '非受控初始值' },
    { name: 'min', type: 'number', default: '0' },
    { name: 'max', type: 'number', default: '100' },
    { name: 'step', type: 'number', default: '1', desc: '步长' },
    { name: 'range', type: 'boolean', default: 'false', desc: '双滑块区间模式' },
    { name: 'marks', type: 'Record<number, string>', default: 'undefined', desc: '刻度标记' },
    { name: 'included', type: 'boolean', default: 'true', desc: '是否填充已选轨道段' },
    { name: 'vertical', type: 'boolean', default: 'false' },
    { name: 'verticalReverse', type: 'boolean', default: 'false', desc: '垂直时反向（顶部为 min）' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'tooltipVisible', type: 'boolean | undefined', default: 'undefined', desc: '强制控制数值气泡显隐（受控）' },
    { name: 'tooltipOnMark', type: 'boolean', default: 'false', desc: '气泡跟随刻度显示' },
    { name: 'tipFormatter', type: '(value: number) => string | number | null | undefined', default: '(v) => v', desc: '自定义气泡文案；返回 null/undefined 隐藏气泡' },
    { name: 'getAriaValueText', type: '(value: number, index?: number) => string', default: 'undefined', desc: '自定义 aria-valuetext（如带单位）' },
    { name: 'railStyle', type: 'string', default: 'undefined', desc: '透传轨道内联样式' },
    { name: 'showArrow', type: 'boolean', default: 'true', desc: 'tooltip 是否显示箭头' },
    { name: 'showMarkLabel', type: 'boolean', default: 'true', desc: '显示标记文本标签' },
    { name: 'showBoundary', type: 'boolean', default: 'false', desc: 'hover 时展示轨道两端边界值标签' },
    { name: 'handleDot', type: '{ color?: string; size?: string } | { color?: string; size?: string }[]', default: 'undefined', desc: '自定义手柄圆点样式，range 时为数组' },
    { name: 'id', type: 'string', default: 'undefined', desc: '根节点 id' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根节点自定义类名' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根节点自定义内联样式' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'ariaLabelledby', type: 'string', default: 'undefined', desc: 'group 与各手柄 aria-labelledby（指向外部 label id）' },
    { name: 'ariaValuetext', type: 'string', default: 'undefined', desc: '覆盖 getAriaValueText 的 aria-valuetext 文案' },
    { name: 'onChange', type: '(value: number | [number, number]) => void', default: 'undefined', desc: '值变化（拖拽中实时/键盘），range 时回传已排序数组' },
    { name: 'onAfterChange', type: '(value: number | [number, number]) => void', default: 'undefined', desc: '拖拽结束/点击/键盘落定时触发' },
    { name: 'onMouseUp', type: '(e: MouseEvent) => void', default: 'undefined', desc: 'pointerup 时触发' },
  ],
  a11y: {
    role: 'slider',
    keyboard: ['ArrowUp/Right', 'ArrowDown/Left', 'PageUp', 'PageDown', 'Home', 'End'],
    notes: [
      '根容器 role=group，每个手柄 role=slider + tabindex=0',
      '手柄 aria-valuemin/valuemax/valuenow/aria-orientation',
      'range 模式两手柄不交叉（越过自动交换）',
      '拖拽命令式：pointerdown 读一次 rail rect，document 监听 pointermove/up',
      'disabled→aria-disabled，手柄 tabindex=-1',
      'aria-valuetext 优先 getAriaValueText，其次 ariaValuetext，再次 tipFormatter 输出',
      '数值气泡复用 Tooltip 组件：hover/focus/拖拽显示，tooltipVisible 强制受控',
    ],
  },
  tokens: [
    '--cd-color-slider-text-default',
    '--cd-color-slider-dot-bg-default',
    '--cd-color-slider-dot-border-active',
    '--cd-color-slider-handle-bg-default',
    '--cd-color-slider-handle-bg-hover',
    '--cd-color-slider-handle-border-focus',
    '--cd-color-slider-handle-disabled-border',
    '--cd-color-slider-mark-text-default',
    '--cd-color-slider-rail-bg-default',
    '--cd-color-slider-track-bg-default',
    '--cd-color-slider-track-disabled-bg',
    '--cd-color-slider-handle-focus',
    '--cd-color-slider-handle-dot',
    '--cd-radius-slider-rail',
    '--cd-radius-slider-track',
    '--cd-height-slider-wrapper',
    '--cd-height-slider-rail',
    '--cd-height-slider-track',
    '--cd-width-slider-handle',
    '--cd-width-slider-handle-clicked',
    '--cd-width-slider-dot',
    '--cd-width-slider-handle-border-disabled',
    '--cd-width-slider-handle-focus',
    '--cd-width-slider-handle-dot',
    '--cd-spacing-slider-paddingx',
    '--cd-spacing-slider-rail-top',
    '--cd-spacing-slider-marks-top',
    '--cd-spacing-slider-boundary-top',
    '--cd-font-slider-marks-fontsize',
    '--cd-shadow-slider-knob',
  ],
} as const;
