/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Steps',
  category: 'navigation',
  description:
    '步骤条，引导用户按流程完成任务。组合式 API（<Steps><Steps.Step/></Steps>），严格对齐 Semi Design：支持横向/纵向、fill/basic/nav 三型、迷你尺寸、每步独立图标/状态、连接线开关（hasLine）与 onChange 切换。',
  props: [
    { name: 'current', type: 'number', default: 'undefined', desc: '受控当前步（从 0 计数）' },
    { name: 'defaultCurrent', type: 'number', default: '0', desc: '非受控初始当前步' },
    {
      name: 'direction',
      type: "'horizontal'|'vertical'",
      default: 'horizontal',
      desc: '步骤条方向',
    },
    {
      name: 'type',
      type: "'fill'|'basic'|'nav'",
      default: 'fill',
      desc: 'fill 为块状（旧版默认）、basic 为简洁型、nav 为导航型（不可交互）',
    },
    {
      name: 'status',
      type: "'wait'|'process'|'finish'|'error'|'warning'",
      default: 'process',
      desc: '当前步状态',
    },
    { name: 'size', type: "'small'|'default'", default: 'default', desc: '尺寸（basic/nav 型生效）' },
    { name: 'initial', type: 'number', default: '0', desc: '起始序号偏移' },
    {
      name: 'hasLine',
      type: 'boolean',
      default: 'true',
      desc: 'basic 型是否显示连接线（对齐 Semi hasLine）',
    },
    {
      name: 'onChange',
      type: '(current: number) => void',
      default: 'undefined',
      desc: '切换步骤回调（参数为 initial + index）；传入时 fill/basic 型步骤可点击',
    },
    { name: 'class', type: 'string', default: "''" },
    { name: 'style', type: 'string', default: 'undefined', desc: '容器内联样式（对齐 Semi style）' },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '容器 aria-label（对齐 Semi aria-label）' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '内嵌 <Steps.Step> 列表' },
  ],
  // <Steps.Step> 子组件 props（对齐 Semi Steps.Step）。
  stepProps: [
    { name: 'title', type: 'string | Snippet', default: 'undefined', desc: '步骤标题' },
    { name: 'description', type: 'string | Snippet', default: 'undefined', desc: '步骤描述（次要信息）' },
    {
      name: 'status',
      type: "'wait'|'process'|'finish'|'error'|'warning'",
      default: 'undefined',
      desc: '显式覆盖该步状态；不传时由 current 推断',
    },
    {
      name: 'icon',
      type: 'string | Snippet',
      default: 'undefined',
      desc: '该步自定义图标（字符串或 Snippet），替代默认序号/✓/✕/⚠（对齐 Semi Steps.Step.icon）',
    },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '该步 aria-label（对齐 Semi Steps.Step.aria-label）' },
    { name: 'role', type: 'string', default: 'undefined', desc: '该步 role（对齐 Semi Steps.Step.role）' },
    { name: 'class', type: 'string', default: 'undefined', desc: '该步根节点类名（对齐 Semi Steps.Step.className）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '该步根节点内联样式（对齐 Semi Steps.Step.style）' },
    {
      name: 'onClick',
      type: '(e: MouseEvent) => void',
      default: 'undefined',
      desc: '该步点击回调（对齐 Semi Steps.Step.onClick）',
    },
    {
      name: 'onKeyDown',
      type: '(e: KeyboardEvent) => void',
      default: 'undefined',
      desc: '该步键盘按下回调（对齐 Semi Steps.Step.onKeyDown）',
    },
  ],
  a11y: {
    role: 'list',
    keyboard: ['Tab', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Home', 'End', 'Enter', 'Space'],
    notes: [
      'ol/li 结构',
      '可点击（fill/basic + onChange）时每步为原生 button，roving tabindex 单 Tab 停靠点',
      '当前步 aria-current=step',
      '图标 ✓/✕/⚠ 用 aria-hidden；状态靠视觉隐藏文本（.cd-sr-only）与 aria-current 表达（WCAG 1.4.1）',
      '连接线 aria-hidden=true；nav 型外包 nav[aria-label]',
    ],
  },
  // Component token 全量对齐 Semi steps/variables.scss（Color/Width/Height/Spacing/Radius/Font
  // 六族，共 84 个）。组件直接消费这些 --cd-*-steps-*，无中间语义变量。
  // 见 packages/tokens/src/components/steps.ts。
  tokens: [
    // —— Color ——
    '--cd-color-steps-bg-active',
    '--cd-color-steps-bg-default',
    '--cd-color-steps-bg-hover',
    '--cd-color-steps-border-default',
    '--cd-color-steps-danger-text-active',
    '--cd-color-steps-danger-text-default',
    '--cd-color-steps-danger-text-hover',
    '--cd-color-steps-icon-after-bg',
    '--cd-color-steps-icon-default',
    '--cd-color-steps-item-description-text-hover',
    '--cd-color-steps-item-done-after-bg',
    '--cd-color-steps-item-done-icon-after-bg',
    '--cd-color-steps-item-error-left-icon',
    '--cd-color-steps-item-error-left-number-icon',
    '--cd-color-steps-item-finish-icon',
    '--cd-color-steps-item-finish-number-icon',
    '--cd-color-steps-item-left-number-icon-bg',
    '--cd-color-steps-item-left-number-icon-icon',
    '--cd-color-steps-item-process-left-icon',
    '--cd-color-steps-item-process-left-number-icon',
    '--cd-color-steps-item-title-text-hover',
    '--cd-color-steps-item-wait-left-icon-icon',
    '--cd-color-steps-item-wait-left-number-icon-bg',
    '--cd-color-steps-item-wait-left-number-icon-bg-hover',
    '--cd-color-steps-item-wait-left-number-icon-icon',
    '--cd-color-steps-item-wait-left-number-icon-icon-hover',
    '--cd-color-steps-item-wait-title-text',
    '--cd-color-steps-item-warning-left-icon',
    '--cd-color-steps-item-warning-left-number-icon',
    '--cd-color-steps-main-text-default',
    '--cd-color-steps-minor-text-default',
    '--cd-color-steps-nav-item-container-text',
    '--cd-color-steps-nav-item-icon',
    '--cd-color-steps-nav-item-title-text-active',
    '--cd-color-steps-primary-bg-default',
    '--cd-color-steps-primary-icon-default',
    '--cd-color-steps-process-bg-default',
    '--cd-color-steps-success-text-active',
    '--cd-color-steps-success-text-default',
    '--cd-color-steps-success-text-hover',
    '--cd-color-steps-text-default',
    '--cd-color-steps-title-after-bg',
    '--cd-color-steps-warning-text-active',
    '--cd-color-steps-warning-text-default',
    '--cd-color-steps-warning-text-hover',
    // —— Width / Height ——
    '--cd-width-steps-basic-item-description',
    '--cd-width-steps-basic-item-description-maxwidth',
    '--cd-width-steps-basic-item-left-number-icon',
    '--cd-width-steps-basic-item-title-maxwidth',
    '--cd-width-steps-basic-small-item-left-number-icon',
    '--cd-width-steps-basic-vertical-item-description',
    '--cd-width-steps-basic-vertical-item-title-maxwidth',
    '--cd-width-steps-item-border',
    '--cd-width-steps-item-description',
    '--cd-width-steps-item-left',
    '--cd-width-steps-item-left-icon',
    '--cd-width-steps-item-title',
    '--cd-width-steps-nav-item-icon-minwidth',
    '--cd-width-steps-nav-item-title-maxwidth',
    '--cd-width-steps-title-after',
    '--cd-width-steps-vertical-icon-after',
    '--cd-height-steps-basic-item',
    '--cd-height-steps-basic-item-left-icon',
    '--cd-height-steps-basic-item-left-number-icon',
    '--cd-height-steps-basic-small-item-left-icon',
    '--cd-height-steps-basic-vertical-icon-content-minheight',
    '--cd-height-steps-basic-vertical-small-item-content-minheight',
    '--cd-height-steps-item',
    '--cd-height-steps-item-left',
    '--cd-height-steps-title-after',
    '--cd-height-steps-vertical-icon-after',
    // —— Spacing ——
    '--cd-spacing-steps-basic-item-left-marginright',
    '--cd-spacing-steps-basic-item-marginright',
    '--cd-spacing-steps-basic-item-paddingleft',
    '--cd-spacing-steps-basic-item-title-paddingbottom',
    '--cd-spacing-steps-basic-item-title-paddingright',
    '--cd-spacing-steps-basic-vertical-item-content-paddingbottom',
    '--cd-spacing-steps-basic-vertical-item-icon-paddingbottom',
    '--cd-spacing-steps-basic-vertical-item-paddingtop',
    '--cd-spacing-steps-item-content-marginleft',
    '--cd-spacing-steps-item-marginright',
    '--cd-spacing-steps-item-paddingx',
    '--cd-spacing-steps-item-paddingy',
    // —— Radius ——
    '--cd-radius-steps-basic-item-left-number-icon',
    '--cd-radius-steps-item',
    '--cd-radius-steps-item-left',
    // —— Font ——
    '--cd-font-steps-basic-item-left-number-icon-fontweight',
    '--cd-font-steps-basic-item-title-fontweight',
    '--cd-font-steps-basic-item-title-lineheight',
    '--cd-font-steps-item-left-fontweight',
    '--cd-font-steps-item-left-lineheight',
    '--cd-font-steps-item-title-fontweight',
    '--cd-font-steps-nav-item-title-active-fontweight',
    '--cd-font-steps-nav-item-title-fontweight',
    // —— 全局/别名（结构性消费）——
    '--cd-focus-ring',
    '--cd-border-radius-small',
    '--cd-spacing-base',
    '--cd-font-size-small',
  ],
} as const;
