/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 * 全面对齐 Semi Design（semi-ui/dropdown）API 表面。
 */
export const meta = {
  name: 'Dropdown',
  category: 'navigation',
  description:
    '向下弹出的菜单，通过触发元素唤起一组可操作命令项。对齐 Semi：children 为触发器，render/menu 定义浮层内容（Dropdown.Menu/Item/Title/Divider）；hover/focus/click/custom/contextMenu 触发；12 方位；嵌套子菜单（手动嵌套 Dropdown）；showTick 勾选、type 五色语义、icon、active、disabled；键盘导航与 Esc 关闭。',
  props: [
    { name: 'render', type: 'Snippet', default: 'undefined', desc: '弹出层内容，由 Dropdown.Menu / Item / Title / Divider 构成（对齐 Semi render）' },
    { name: 'menu', type: 'DropdownMenuItem[]', default: 'undefined', desc: '通过 JSON Array 快速配置内容（node=item/title/divider）；render 存在时忽略（对齐 Semi menu）' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '触发弹出层的 Trigger 元素（对齐 Semi children）' },
    { name: 'trigger', type: "'hover'|'focus'|'click'|'custom'|'contextMenu'", default: 'hover', desc: '触发方式；custom 需配 visible 受控，contextMenu 右键定位光标' },
    { name: 'visible', type: 'boolean', default: 'undefined', desc: '受控显隐，需配合 trigger=custom（对齐 Semi visible）' },
    { name: 'defaultVisible', type: 'boolean', default: 'false', desc: '非受控初始显隐' },
    { name: 'position', type: 'Placement', default: 'bottom', desc: '弹出位置（12 方位，语义对齐 Semi position：bottomStart≈bottomLeft、rightStart≈rightTop）' },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '弹出层被遮挡时自动调整方向（对齐 Semi）' },
    { name: 'mouseEnterDelay', type: 'number', default: '50', desc: '移入 Trigger 后延迟显示(ms)，仅 hover/focus 生效（对齐 Semi）' },
    { name: 'mouseLeaveDelay', type: 'number', default: '100', desc: '移出弹出层后延迟消失(ms)，仅 hover/focus 生效（对齐 Semi）' },
    { name: 'spacing', type: 'number | { x: number; y: number }', default: '4（嵌套 2）', desc: '弹出层与 Trigger 距离(px)（对齐 Semi spacing）' },
    { name: 'margin', type: 'number', default: 'undefined', desc: '弹出层计算溢出的冗余值(px)（对齐 Semi margin）' },
    { name: 'zIndex', type: 'number', default: '1050', desc: '弹出层 z-index（对齐 Semi zIndex）' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '下拉动画开关（对齐 Semi motion）' },
    { name: 'className', type: 'string', default: 'undefined', desc: '下拉弹层外层样式类名（作用于 div.cd-dropdown，对齐 Semi className）' },
    { name: 'contentClassName', type: 'string', default: 'undefined', desc: '下拉菜单根元素类名（作用于 div.cd-dropdown-content，对齐 Semi contentClassName）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '弹出层内联样式（作用于 div.cd-dropdown-content，对齐 Semi style）' },
    { name: 'showTick', type: 'boolean', default: 'false', desc: '自动在 active 的 Dropdown.Item 左侧展示对勾（对齐 Semi showTick）' },
    { name: 'stopPropagation', type: 'boolean', default: 'false', desc: '阻止弹出层上的点击事件冒泡（对齐 Semi stopPropagation）' },
    { name: 'closeOnEsc', type: 'boolean', default: 'true', desc: '在 trigger 或弹出层按 Esc 是否关闭，受控时不生效（对齐 Semi closeOnEsc）' },
    { name: 'rePosKey', type: 'string | number', default: 'undefined', desc: '更新该值手动触发弹出层重新定位（对齐 Semi rePosKey）' },
    { name: 'disableFocusListener', type: 'boolean', default: 'false', desc: 'hover 时不响应键盘聚焦弹出事件（对齐 Semi，issue#977）' },
    { name: 'clickToHide', type: 'boolean', default: 'true', desc: '弹出层内点击时是否自动关闭弹出层（对齐 Semi clickToHide）' },
    { name: 'keepDOM', type: 'boolean', default: 'false', desc: '关闭时是否保留内部组件 DOM 不销毁（对齐 Semi keepDOM）' },
    { name: 'getPopupContainer', type: '() => HTMLElement', default: '() => document.body', desc: '指定父级 DOM 挂载弹层（对齐 Semi getPopupContainer）' },
    { name: 'onVisibleChange', type: '(visible: boolean) => void', default: 'undefined', desc: '弹出层显示状态改变时的回调（对齐 Semi onVisibleChange）' },
    { name: 'onEscKeyDown', type: '(e: KeyboardEvent) => void', default: 'undefined', desc: '在 trigger 或弹出层按 Esc 时调用，关闭逻辑之前（对齐 Semi onEscKeyDown）' },
    { name: 'onClickOutSide', type: '(e: PointerEvent) => void', default: 'undefined', desc: '展示状态下点击外部区域回调，仅 custom/click 有效（对齐 Semi onClickOutSide）' },
  ],
  subComponents: [
    {
      name: 'Dropdown.Menu',
      usage: '<Dropdown.Menu> 包裹 Item / Title / Divider',
      desc: '下拉弹层菜单容器（对齐 Semi dropdownMenu）：ul[role=menu][aria-orientation=vertical]。',
      props: [
        { name: 'class', type: 'string', default: 'undefined', desc: '菜单 ul 样式类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '菜单 ul 内联样式' },
        { name: 'children', type: 'Snippet', default: 'undefined', desc: 'Dropdown.Item / Title / Divider' },
      ],
    },
    {
      name: 'Dropdown.Item',
      usage: '<Dropdown.Item key type icon active disabled onClick>文本</Dropdown.Item>',
      desc: '单个菜单项（对齐 Semi dropdownItem）：li[role=menuitem]。showTick 时 active 项左侧对勾。',
      props: [
        { name: 'key', type: 'string | number', default: 'undefined', desc: '项键，onClick 携带' },
        { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用菜单项（对齐 Semi disabled）' },
        { name: 'active', type: 'boolean', default: 'false', desc: '激活态：showTick 时左侧对勾、字重加粗（对齐 Semi active）' },
        { name: 'type', type: "'primary'|'secondary'|'tertiary'|'warning'|'danger'", default: 'undefined', desc: '语义色（对齐 Semi type）' },
        { name: 'icon', type: 'Snippet', default: 'undefined', desc: '前置图标（对齐 Semi icon）' },
        { name: 'onClick', type: '(e: MouseEvent) => void', default: 'undefined', desc: '单击回调（对齐 Semi onClick）' },
        { name: 'onMouseEnter', type: '(e: MouseEvent) => void', default: 'undefined', desc: 'MouseEnter 回调（对齐 Semi）' },
        { name: 'onMouseLeave', type: '(e: MouseEvent) => void', default: 'undefined', desc: 'MouseLeave 回调（对齐 Semi）' },
        { name: 'onContextMenu', type: '(e: MouseEvent) => void', default: 'undefined', desc: '右键回调（对齐 Semi）' },
        { name: 'children', type: 'Snippet', default: 'undefined', desc: '菜单项内容' },
      ],
    },
    {
      name: 'Dropdown.Title',
      usage: '<Dropdown.Title>分组名</Dropdown.Title>',
      desc: '分组标题（对齐 Semi dropdownTitle）：div.cd-dropdown-title，不可点击/聚焦。',
      props: [
        { name: 'children', type: 'Snippet', default: 'undefined', desc: '分组标题内容' },
      ],
    },
    {
      name: 'Dropdown.Divider',
      usage: '<Dropdown.Divider />',
      desc: '分隔线（对齐 Semi dropdownDivider）：div.cd-dropdown-divider。',
      props: [],
    },
  ],
  a11y: {
    role: 'menu',
    keyboard: ['Enter', 'Space', 'ArrowDown', 'ArrowUp', 'Escape'],
    notes: [
      '触发器 role=button + aria-haspopup=menu + aria-expanded + aria-controls（嵌套触发器为 Dropdown.Item 自身承担 menuitem 语义）',
      '浮层 ul role=menu + aria-orientation=vertical，项 li role=menuitem（tabindex=-1，方向键移动焦点漫游）',
      'click 触发打开后焦点自动落首个非禁用项（对齐 Semi foundation）',
      'divider role=separator；title 组标题不可聚焦',
      'Esc 关闭并归还触发器焦点（受控时不生效）；外部点击关闭并回调 onClickOutSide',
    ],
  },
  tokens: [
    // 组件 DOM 直接消费的 Dropdown token（全名对齐 Semi variables.scss；定义于 @chenzy-design/tokens dropdown.ts）
    '--cd-radius-dropdown',
    '--cd-radius-dropdown-item',
    '--cd-color-dropdown-bg-default',
    '--cd-color-dropdown-title-text-default',
    '--cd-color-dropdown-item-text-default',
    '--cd-color-dropdown-item-bg-hover',
    '--cd-color-dropdown-item-bg-active',
    '--cd-color-dropdown-item-danger-text-default',
    '--cd-color-dropdown-item-secondary-text-default',
    '--cd-color-dropdown-item-warning-text-default',
    '--cd-color-dropdown-item-tertiary-text-default',
    '--cd-color-dropdown-item-primary-text-default',
    '--cd-color-dropdown-item-disabled-text-default',
    '--cd-color-dropdown-item-disabled-bg-default',
    '--cd-color-dropdown-seperator-bg-default',
    '--cd-spacing-dropdown-menu-paddingy',
    '--cd-spacing-dropdown-menu-paddingx',
    '--cd-spacing-dropdown-title-paddingtop',
    '--cd-spacing-dropdown-title-paddingbottom',
    '--cd-spacing-dropdown-title-paddingleft',
    '--cd-spacing-dropdown-title-paddingright',
    '--cd-spacing-dropdown-title-withtick-paddingleft',
    '--cd-spacing-dropdown-item-withtick-paddingleft',
    '--cd-spacing-dropdown-item-paddingy',
    '--cd-spacing-dropdown-item-paddingx',
    '--cd-spacing-dropdown-icon-marginright',
    '--cd-spacing-dropdown-seperator-marginy',
    '--cd-spacing-dropdown-seperator-marginx',
    '--cd-width-dropdown',
    '--cd-size-dropdown-icon-width',
    '--cd-size-dropdown-icon-height',
    '--cd-height-dropdown-seperator',
    '--cd-font-dropdown-item-active-fontweight',
    '--cd-transition-dropdown-item-bg-duration',
    '--cd-transition-dropdown-item-bg-function',
    '--cd-transition-dropdown-item-bg-delay',
    '--cd-filter-dropdown-bg',
    // wrapper 阴影/层级（Semi dropdown-wrapper @include shadow-elevated + z-dropdown）
    '--cd-shadow-elevated',
    '--cd-z-dropdown',
    // 复用的全局 token
    '--cd-font-size-regular',
    '--cd-line-height-regular',
    '--cd-font-size-small',
    '--cd-line-height-small',
    '--cd-spacing-tight',
    '--cd-motion-duration-fast',
    '--cd-motion-ease-standard',
  ],
} as const;
