/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Dropdown',
  category: 'navigation',
  description:
    '下拉菜单，通过触发元素唤起一组可操作命令项。支持 hover/click/contextMenu 触发、嵌套子菜单、divider 分隔符、group 分组、useDismiss 关闭、键盘导航与危险项。',
  props: [
    {
      name: 'items',
      type: 'DropdownItem[]',
      default: '[]',
      desc: '菜单项数据；判别联合：普通项含 children 即可展开子菜单，type=divider 分隔符，type=group 分组标题',
    },
    {
      name: 'trigger',
      type: "'hover'|'click'|'contextMenu'",
      default: 'hover',
      desc: "触发方式；contextMenu 为右键唤起并定位到光标",
    },
    { name: 'open', type: 'boolean', default: 'undefined', desc: '受控显隐' },
    { name: 'defaultOpen', type: 'boolean', default: 'false', desc: '非受控初始显隐' },
    {
      name: 'position',
      type: "'bottomStart'|'bottomEnd'|'topStart'",
      default: 'bottomStart',
      desc: '浮层位置',
    },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用整个触发' },
    { name: 'closeOnSelect', type: 'boolean', default: 'true', desc: '点击项后自动关闭' },
    { name: 'closeOnEsc', type: 'boolean', default: 'true', desc: 'Esc 是否关闭' },
    { name: 'mouseEnterDelay', type: 'number', default: '150', desc: 'hover 进入延迟(ms)' },
    { name: 'mouseLeaveDelay', type: 'number', default: '150', desc: 'hover 离开延迟(ms)' },
    {
      name: 'spacing',
      type: 'number | { x: number; y: number }',
      default: '4',
      desc: '浮层与触发元素间距(px)，映射到 floating 主轴 offset；{ x, y } 按 position 主轴方向取值（上下取 y、左右取 x）',
    },
    {
      name: 'clickToHide',
      type: 'boolean',
      default: 'true',
      desc: 'hover 模式下点击菜单项是否关闭浮层；false 时点击项不关闭（仅移出/Esc/外部点击收起），仅影响 hover 触发',
    },
    { name: 'zIndex', type: 'number', default: '1050', desc: '浮层层级（写入浮层内联 z-index）' },
    {
      name: 'autoAdjustOverflow',
      type: 'boolean',
      default: 'true',
      desc: '空间不足时自动翻转/移位到可视区（透传 floating autoAdjust）；false 时严格按 position 定位不翻转',
    },
    {
      name: 'destroyOnClose',
      type: 'boolean',
      default: 'false',
      desc: '关闭即卸载浮层内容（{#if}）重开重建；默认 false 首开后保留 DOM 仅隐藏',
    },
    {
      name: 'lazyRender',
      type: 'boolean',
      default: 'true',
      desc: '首次打开前不渲染浮层内容（惰性）；false 时即使从未打开也预渲染浮层 DOM（仅隐藏）',
    },
    {
      name: 'keepDOM',
      type: 'boolean',
      default: 'false',
      desc: '关闭后保留浮层 DOM（与 destroyOnClose 互斥；true 时强制保留，忽略 destroyOnClose）',
    },
    {
      name: 'getPopupContainer',
      type: '() => HTMLElement',
      default: '() => document.body',
      desc: '浮层挂载容器；非 body 容器时改 absolute 相对该容器定位，嵌套子菜单与右键浮层同容器',
    },
    { name: 'showTick', type: 'boolean', default: 'false', desc: '选中项显示对勾（经 context 透传给 DropdownItemNode）' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '下拉动画开关；false 禁用展开/收起过渡' },
    {
      name: 'stopPropagation',
      type: 'boolean',
      default: 'true',
      desc: '阻断下拉框内点击事件冒泡，防止触发上层监听器',
    },
    { name: 'onSelect', type: '(key: string|number) => void', default: 'undefined' },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'triggerContent', type: 'Snippet', default: 'undefined', desc: '触发元素内容' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '自定义浮层内容（提供则忽略 items）' },
  ],
  a11y: {
    role: 'menu',
    keyboard: ['Enter', 'Space', 'ArrowDown', 'ArrowUp', 'ArrowRight', 'ArrowLeft', 'Escape'],
    notes: [
      '触发器 aria-haspopup=menu + aria-expanded + aria-controls',
      '浮层 role=menu，项 role=menuitem，焦点式 roving（tabindex=-1 + 方向键移动焦点）',
      '子菜单父项 aria-haspopup=menu + aria-expanded；→ 进入子菜单首项，← / Esc 逐层返回',
      'divider role=separator；group 组标题不可聚焦，组内项始终展开（role=group）',
      'useDismiss 处理外部点击与 Escape 关闭',
    ],
  },
  tokens: [
    // 组件消费的 Dropdown token（定义于 @chenzy-design/tokens dropdown.ts，全量对齐 Semi）
    '--cd-dropdown-bg',
    '--cd-dropdown-radius',
    '--cd-dropdown-shadow',
    '--cd-dropdown-min-width',
    '--cd-dropdown-z',
    '--cd-dropdown-item-padding',
    '--cd-dropdown-item-bg-hover',
    '--cd-dropdown-item-color-disabled',
    '--cd-dropdown-motion-duration',
    '--cd-dropdown-motion-easing',
    // 复用的全局 / alias token
    '--cd-focus-ring',
    '--cd-border-radius-small',
    '--cd-font-size-small',
    '--cd-spacing-tight',
    '--cd-spacing-extra-tight',
    '--cd-color-border',
    '--cd-color-text-2',
    '--cd-color-text-3',
    '--cd-color-danger',
    '--cd-color-primary',
  ],
} as const;
