/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'TagInput',
  category: 'input',
  description: '标签输入框，支持回车 / 分隔符提交、退格删除、去重、上限与失焦提交。',
  props: [
    { name: 'value', type: 'string[]', default: 'undefined' },
    { name: 'defaultValue', type: 'string[]', default: '[]' },
    { name: 'inputValue', type: 'string', default: 'undefined' },
    { name: 'defaultInputValue', type: 'string', default: "''" },
    { name: 'placeholder', type: 'string', default: 'undefined' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'readonly', type: 'boolean', default: 'false' },
    { name: 'max', type: 'number', default: 'undefined' },
    { name: 'maxLength', type: 'number', default: 'undefined' },
    { name: 'maxTagTextLength', type: 'number', default: 'undefined' },
    { name: 'separator', type: 'string|string[]', default: "['Enter']" },
    { name: 'addOnBlur', type: 'boolean', default: 'false' },
    { name: 'allowDuplicates', type: 'boolean', default: 'false' },
    { name: 'trimWhitespace', type: 'boolean', default: 'true' },
    { name: 'draggable', type: 'boolean', default: 'false' },
    { name: 'split', type: '(value: string, separator: string) => string[]', default: 'undefined', desc: '自定义分隔处理函数（对齐 Semi，优先于内置拆分）' },
    { name: 'prefix', type: 'string | Snippet', default: 'undefined', desc: '输入框前缀（string/图标自动带间隔）' },
    { name: 'suffix', type: 'string | Snippet', default: 'undefined', desc: '输入框后缀' },
    { name: 'maxTagCount', type: 'number', default: 'undefined', desc: '标签最大展示数量，超出折叠为 +N' },
    { name: 'showRestTagsPopover', type: 'boolean', default: 'true', desc: 'hover +N 是否用 Popover 展示剩余标签' },
    { name: 'expandRestTagsOnClick', type: 'boolean', default: 'true', desc: '点击 +N 是否展开剩余标签' },
    { name: 'showClear', type: 'boolean', default: 'false', desc: '显示清除全部按钮' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除图标' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: 'focus 时阻止滚动' },
    { name: 'autoFocus', type: 'boolean', default: 'false', desc: '挂载自动聚焦' },
    { name: 'inputProps', type: 'Record<string, unknown>', default: 'undefined', desc: '透传给内部 input 的额外属性' },
    {
      name: 'renderTagItem',
      type: 'Snippet<[{ value: string; index: number; onClose: () => void }]>',
      default: 'undefined',
      desc: '完全自定义 tag 渲染',
    },
    { name: 'onChange', type: '(tags: string[]) => void', default: 'undefined' },
    { name: 'onInputChange', type: '(value: string) => void', default: 'undefined' },
    { name: 'onAdd', type: '(addedValue: string[]) => void', default: 'undefined', desc: '新增标签后触发，传当前完整数组（对齐 Semi）' },
    { name: 'onRemove', type: '(removedValue: string, index: number) => void', default: 'undefined', desc: '移除单个标签时触发（对齐 Semi）' },
    { name: 'onKeyDown', type: '(e: KeyboardEvent) => void', default: 'undefined', desc: '输入框 keydown 透传（对齐 Semi）' },
    { name: 'onExceed', type: '(value: string[]) => void', default: 'undefined', desc: '超出 max 时触发，传当前标签数组（对齐 Semi）' },
    { name: 'onInputExceed', type: '(value: string) => void', default: 'undefined', desc: '单 tag 超出 maxLength 时触发' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined', desc: '输入框聚焦' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined', desc: '输入框失焦' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
  ],
  methods: [
    { name: 'focus()', desc: '命令式聚焦输入框（尊重 preventScroll，对齐 Semi）' },
    { name: 'blur()', desc: '命令式移除焦点（对齐 Semi）' },
  ],
  a11y: {
    role: 'group',
    notes: [
      '容器 role=group + aria-label',
      '每个标签删除按钮含 aria-label，文案取自 locale（TagInput.remove，默认中文「删除」）',
      '键盘：分隔符（默认 Enter）提交、输入为空时 Backspace 删除末尾标签',
      'draggable 仅为鼠标增强（HTML5 DnD）；键盘增删标签交互不受影响',
      'error 状态时 aria-invalid 标注于内部输入',
    ],
  },
  i18nKeys: ['TagInput.remove'],
  tokens: ['--cd-tag-input-*', '--cd-input-*', '--cd-focus-ring', '--cd-motion-*', '--cd-color-fill-*'],
} as const;
