/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 * 严格对齐 Semi tagInput props（去超集，补 insetLabel/validateStatus）。
 */
export const meta = {
  name: 'TagInput',
  category: 'input',
  description: '标签输入框，复用 Tag 渲染标签，支持回车 / 分隔符提交、退格删除、去重、上限与失焦提交。',
  props: [
    { name: 'value', type: 'string[]', default: 'undefined', desc: '受控标签数组（不回写，仅 onChange）' },
    { name: 'defaultValue', type: 'string[]', default: '[]', desc: '非受控初始标签' },
    { name: 'inputValue', type: 'string', default: 'undefined', desc: '受控输入框文本（不回写，仅 onInputChange）' },
    { name: 'placeholder', type: 'string', default: 'undefined' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'validateStatus', type: "'default'|'warning'|'error'", default: 'default', desc: '校验状态样式（对齐 Semi）' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'max', type: 'number', default: 'undefined', desc: '标签数量上限，超出触发 onExceed 并截断' },
    { name: 'maxLength', type: 'number', default: 'undefined', desc: '单个标签最大字符数' },
    { name: 'separator', type: 'string|string[]', default: "','", desc: 'Enter 提交时按此拆分输入为多标签（对齐 Semi 默认逗号）' },
    { name: 'addOnBlur', type: 'boolean', default: 'false', desc: '失焦时自动提交输入' },
    { name: 'allowDuplicates', type: 'boolean', default: 'true', desc: '是否允许重复标签（对齐 Semi 默认 true）' },
    { name: 'draggable', type: 'boolean', default: 'false', desc: '标签可拖拽重排' },
    { name: 'split', type: '(value: string, separator: string | string[]) => string[]', default: 'undefined', desc: '自定义分隔处理函数（对齐 Semi，优先于内置拆分）' },
    { name: 'prefix', type: 'string | Snippet', default: 'undefined', desc: '输入框前缀（string/图标自动带间隔）' },
    { name: 'insetLabel', type: 'string | Snippet', default: 'undefined', desc: '内嵌 label（前缀位，对齐 Semi）' },
    { name: 'insetLabelId', type: 'string', default: 'undefined', desc: '内嵌 label 的 id（对齐 Semi）' },
    { name: 'suffix', type: 'string | Snippet', default: 'undefined', desc: '输入框后缀' },
    { name: 'maxTagCount', type: 'number', default: 'undefined', desc: '标签最大展示数量，超出折叠为 +N' },
    { name: 'showRestTagsPopover', type: 'boolean', default: 'true', desc: 'hover +N 是否用 Popover 展示剩余标签' },
    { name: 'restTagsPopoverProps', type: 'Record<string, unknown>', default: 'undefined', desc: '+N Popover 配置透传（对齐 Semi）' },
    { name: 'expandRestTagsOnClick', type: 'boolean', default: 'true', desc: '点击 +N 是否展开剩余标签' },
    { name: 'showContentTooltip', type: 'boolean | { type?: string; opts?: object }', default: 'true', desc: '标签文本截断时 hover 显示全文（对齐 Semi，可传 Popover 配置）' },
    { name: 'showClear', type: 'boolean', default: 'false', desc: '显示清除全部按钮' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除图标' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: 'focus 时阻止滚动' },
    { name: 'autoFocus', type: 'boolean', default: 'false', desc: '挂载自动聚焦' },
    {
      name: 'renderTagItem',
      type: 'Snippet<[{ value: string; index: number; onClose: () => void }]>',
      default: 'undefined',
      desc: '完全自定义 tag 渲染（对齐 Semi renderTagItem(value, index, onClose)）',
    },
    { name: 'onChange', type: '(tags: string[]) => void', default: 'undefined' },
    { name: 'onInputChange', type: '(value: string) => void', default: 'undefined' },
    { name: 'onAdd', type: '(addedValue: string[]) => void', default: 'undefined', desc: '新增标签后触发，传当前完整数组（对齐 Semi）' },
    { name: 'onRemove', type: '(removedValue: string, index: number) => void', default: 'undefined', desc: '移除单个标签时触发（对齐 Semi）' },
    { name: 'onKeyDown', type: '(e: KeyboardEvent) => void', default: 'undefined', desc: '输入框 keydown 透传（对齐 Semi）' },
    { name: 'onExceed', type: '(value: string[]) => void', default: 'undefined', desc: '超出 max 时触发，传当前标签数组（对齐 Semi）' },
    { name: 'onInputExceed', type: '(value: string) => void', default: 'undefined', desc: '单 tag 超出 maxLength 时触发' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined', desc: '输入框聚焦' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined', desc: '输入框失焦' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
  ],
  methods: [
    { name: 'focus()', desc: '命令式聚焦输入框（尊重 preventScroll，对齐 Semi）' },
    { name: 'blur()', desc: '命令式移除焦点（对齐 Semi）' },
  ],
  a11y: {
    role: 'group',
    notes: [
      '容器 role=group + aria-label',
      '标签复用 Tag 组件，关闭按钮由 Tag 提供（closable）',
      '键盘：Enter 提交（按 separator 拆分）、输入为空时 Backspace 删除末尾标签',
      'draggable 仅为鼠标增强（HTML5 DnD）；键盘交互不受影响',
      'error 状态时 aria-invalid 标注于容器',
    ],
  },
  i18nKeys: ['TagInput.clear'],
  tokens: ['--cd-tag-input-*'],
} as const;
