/**
 * Machine-readable component metadata for AI/docs consumption.
 * Avatar — 1:1 对齐 Semi Design Avatar / AvatarGroup。
 */
export const meta = {
  name: 'Avatar',
  category: 'show',
  description:
    '头像：支持图片(src/srcSet)、加载失败降级到 children/alt 首字，circle/square 形状，7 档尺寸(默认 medium)或自定义 width，16 档语义色 + white(默认 grey)，字符按 gap 自适应缩放，hoverMask 悬浮遮罩，topSlot/bottomSlot 对象配置的顶部/底部标记，border 额外描边环 + contentMotion 内容动效。Avatar.Group 把多个头像层叠排列，maxCount 折叠出「+N」溢出头像，overlapFrom 控制压盖方向，组级 shape/size 强制下发(对齐 Semi cloneElement)。',
  exports: ['Avatar', 'AvatarGroup'],
  props: [
    { name: 'src', type: 'string', default: 'undefined', desc: '图片地址；加载失败自动降级' },
    { name: 'srcSet', type: 'string', default: 'undefined', desc: '响应式图片源集' },
    { name: 'alt', type: 'string', default: 'undefined', desc: 'a11y 文本，也作文字降级来源' },
    { name: 'shape', type: "'circle'|'square'", default: "'circle'" },
    {
      name: 'size',
      type: "'extra-extra-small'|'extra-small'|'small'|'default'|'medium'|'large'|'extra-large'|number|string",
      default: "'medium'",
      desc: '7 档枚举映射 token，number/合法 width 值内联',
    },
    {
      name: 'color',
      type: "'amber'|'blue'|'cyan'|'green'|'grey'|'indigo'|'light-blue'|'light-green'|'lime'|'orange'|'pink'|'purple'|'red'|'teal'|'violet'|'yellow'|'white'",
      default: "'grey'",
      desc: '16 档语义色 + white；图片头像不上色；也可用 style 自定义',
    },
    {
      name: 'border',
      type: 'boolean | { color?: string; motion?: boolean }',
      default: 'false',
      desc: '额外描边环：true 用默认主色；对象可定制 color 并用 motion 开启呼吸动画',
    },
    { name: 'contentMotion', type: 'boolean', default: 'false', desc: '头像内容区域动效' },
    { name: 'gap', type: 'number', default: '3', desc: '字符头像距左右两侧像素(用于自适应缩放)' },
    { name: 'hoverMask', type: 'Snippet', default: 'undefined', desc: 'hover 时头像内容覆盖层(无默认样式)' },
    {
      name: 'topSlot',
      type: '{ render?; gradientStart?: string; gradientEnd?: string; text?; textColor?: string; className?: string; style?: string }',
      default: 'undefined',
      desc: '顶部渐变标记(仅 circle 且枚举尺寸)',
    },
    {
      name: 'bottomSlot',
      type: "{ render?; shape?: 'circle'|'square'; text?; bgColor?: string; textColor?: string; className?: string; style?: string }",
      default: 'undefined',
      desc: '底部圆形/方形标记(仅枚举尺寸)',
    },
    { name: 'imgAttr', type: 'Record<string, unknown>', default: 'undefined', desc: '额外传给 img 的原生属性' },
    { name: 'onError', type: '() => boolean|void', default: 'undefined', desc: 'img 加载失败回调；返回 false 关闭默认降级' },
    {
      name: 'onClick',
      type: '(e: MouseEvent|KeyboardEvent) => void',
      default: 'undefined',
      desc: '单击回调；提供时头像可聚焦并响应键盘 Enter(对齐 Semi clickable)',
    },
    { name: 'onMouseEnter', type: '(e: MouseEvent) => void', default: 'undefined' },
    { name: 'onMouseLeave', type: '(e: MouseEvent) => void', default: 'undefined' },
    { name: 'class', type: 'string', default: 'undefined', desc: '附加类名(对齐 Semi className)' },
    { name: 'style', type: 'string', default: 'undefined', desc: '内联样式(对齐 Semi style)' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '文字/图标内容' },
  ],
  subComponents: [
    {
      name: 'AvatarGroup',
      usage: '<Avatar.Group> 层叠排列多个头像；items+maxCount 折叠出「+N」溢出头像',
      desc: '把多个头像层叠排列。可用 items 数据驱动(配合 maxCount 折叠)，或用 children 自由传入 <Avatar>。组级 shape/size 经 context 强制下发(对齐 Semi cloneElement)。',
      props: [
        { name: 'items', type: 'AvatarGroupItem[]', default: 'undefined', desc: '数据驱动成员；启用 maxCount 折叠' },
        { name: 'maxCount', type: 'number', default: 'undefined', desc: '最多显示 N 个，其余折叠为「+N」' },
        { name: 'shape', type: "'circle'|'square'", default: "'circle'", desc: '组级形状，强制下发给子头像' },
        { name: 'size', type: 'AvatarSizeEnum | number', default: "'medium'", desc: '组级尺寸，强制下发给子头像' },
        { name: 'overlapFrom', type: "'start'|'end'", default: "'start'", desc: '层叠压盖方向：start=前压后，end=后压前' },
        {
          name: 'renderMore',
          type: 'Snippet<[{ restNumber: number; restAvatars: AvatarGroupItem[] }]>',
          default: 'undefined',
          desc: '自定义「+N」溢出头像渲染',
        },
        { name: 'children', type: 'Snippet', default: 'undefined', desc: '不用 items 时自由传入的头像' },
      ],
    },
  ],
  events: [
    { name: 'click', desc: 'onClick：头像被点击或键盘 Enter 激活' },
    { name: 'mouseenter', desc: 'onMouseEnter' },
    { name: 'mouseleave', desc: 'onMouseLeave' },
    { name: 'error', desc: 'onError：图片加载失败' },
  ],
  slots: [
    { name: 'children', desc: '文字或图标降级内容' },
    { name: 'hoverMask', desc: 'hover 覆盖层' },
  ],
  a11y: {
    hasRole: true,
    focusable: false,
    note: '图片头像用 <img alt>；纯文字头像 role=img + aria-label(alt 或文字)。提供 onClick 时内部 img/label 加 tabindex=0 + 键盘 Enter/Escape(对齐 Semi clickable Avatar)；纯展示头像不可聚焦。',
  },
  tokens: [
    '--cd-avatar-size-extra-extra-small',
    '--cd-avatar-size-extra-small',
    '--cd-avatar-size-small',
    '--cd-avatar-size-default',
    '--cd-avatar-size-medium',
    '--cd-avatar-size-large',
    '--cd-avatar-size-extra-large',
    '--cd-avatar-bg',
    '--cd-avatar-color',
    '--cd-avatar-border',
    '--cd-avatar-more-bg',
    '--cd-avatar-outline-color',
    '--cd-avatar-outline-width',
    '--cd-avatar-radius-default',
    '--cd-avatar-radius-large',
    '--cd-avatar-radius-extra-large',
    '--cd-avatar-palette-text',
    '--cd-avatar-white-bg',
    '--cd-avatar-amber-bg',
    '--cd-avatar-blue-bg',
    '--cd-avatar-cyan-bg',
    '--cd-avatar-green-bg',
    '--cd-avatar-grey-bg',
    '--cd-avatar-indigo-bg',
    '--cd-avatar-light-blue-bg',
    '--cd-avatar-light-green-bg',
    '--cd-avatar-lime-bg',
    '--cd-avatar-orange-bg',
    '--cd-avatar-pink-bg',
    '--cd-avatar-purple-bg',
    '--cd-avatar-red-bg',
    '--cd-avatar-teal-bg',
    '--cd-avatar-violet-bg',
    '--cd-avatar-yellow-bg',
    '--cd-avatar-additional-border-width',
    '--cd-avatar-additional-border-color',
    '--cd-avatar-additional-border-gap',
    '--cd-avatar-additional-border-duration',
    '--cd-avatar-additional-border-scale-end',
    '--cd-avatar-content-motion-duration',
    '--cd-avatar-content-motion-scale-middle',
    '--cd-avatar-top-slot-gradient-start',
    '--cd-avatar-top-slot-gradient-end',
    '--cd-avatar-top-slot-text',
    '--cd-avatar-bottom-slot-bg',
    '--cd-avatar-bottom-slot-text',
    '--cd-avatar-group-medium-border',
    '--cd-avatar-group-medium-margin',
  ],
  responsive: false,
  examples: [
    { title: '图片', code: '<Avatar src="/u.png" alt="用户" />' },
    { title: '文字', code: '<Avatar color="blue" alt="陈">陈</Avatar>' },
    { title: '尺寸', code: '<Avatar size="large" alt="U">U</Avatar>' },
    { title: '额外边框', code: '<Avatar alt="T" border={{ motion: true }}>T</Avatar>' },
    {
      title: '顶部标记',
      code: '<Avatar color="amber" topSlot={{ text: "直播", gradientStart: "#ff1764", gradientEnd: "#ed3494" }}>T</Avatar>',
    },
    {
      title: '头像组折叠',
      code: '<Avatar.Group maxCount={3} items={[{content:"陈"},{content:"李"},{content:"王"},{content:"赵"}]} />',
    },
    {
      title: '头像组自由排列',
      code: '<Avatar.Group size="small"><Avatar color="red" alt="陈">陈</Avatar></Avatar.Group>',
    },
  ],
} as const;
