/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Pagination',
  category: 'navigation',
  description:
    '分页器，用于切换大量数据的页码。支持 default 与 simple 两种模式，页码使用 Intl.NumberFormat 本地化。越界的当前页/每页条数与快速跳页输入均会被钳制到有效范围（纯函数实现，受控 prop 仅经 onChange 上报）。',
  props: [
    { name: 'total', type: 'number', default: '0', desc: '数据总条数' },
    { name: 'currentPage', type: 'number', default: 'undefined', desc: '受控当前页（越界自动钳制显示，不回写）' },
    { name: 'defaultCurrentPage', type: 'number', default: '1' },
    { name: 'pageSize', type: 'number', default: 'undefined', desc: '受控每页条数；非法或不在 pageSizeOptions 内时回退 defaultPageSize' },
    { name: 'defaultPageSize', type: 'number', default: '10', desc: '非受控每页条数初始值' },
    { name: 'pageSizeOptions', type: 'number[]', default: '[10,20,50,100]', desc: 'size changer 选项' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'mode', type: "'default'|'simple'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default', desc: '快速跳页输入校验态（透传 Input）' },
    {
      name: 'showTotal',
      type: 'boolean | ((total: number, range: [number, number]) => string)',
      default: 'false',
      desc: '显示总条数文案；传函数时接收 (total, [start, end]) 并返回自定义字符串',
    },
    { name: 'showSizeChanger', type: 'boolean', default: 'false', desc: '显示每页条数选择器' },
    { name: 'showQuickJumper', type: 'boolean', default: 'false', desc: '显示快速跳页输入（越界静默钳制，非数字忽略）' },
    { name: 'hideOnSinglePage', type: 'boolean', default: 'false', desc: '仅一页时隐藏整个分页器' },
    { name: 'siblingCount', type: 'number', default: '1', desc: '当前页两侧保留的页码数（省略号折叠参数）' },
    { name: 'boundaryCount', type: 'number', default: '1', desc: '首尾固定显示的页码数（省略号折叠参数）' },
    { name: 'popoverPosition', type: "'top'|'bottom'", default: 'bottom', desc: 'size changer 下拉浮层位置（透传 Select）' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'locale', type: 'string', default: "'zh-CN'", desc: '数字本地化区域' },
    { name: 'onChange', type: '(page: number, pageSize: number) => void', default: 'undefined' },
    { name: 'onPageSizeChange', type: '(pageSize: number) => void', default: 'undefined' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    {
      name: 'renderPage',
      type: 'Snippet<[{ page: number; isCurrent: boolean }]>',
      default: 'undefined',
      desc: '自定义页码按钮内容，接收 { page, isCurrent }，替换默认的 Intl 格式化数字',
    },
    {
      name: 'popoverZIndex',
      type: 'number',
      default: 'undefined',
      desc: 'size-changer 下拉浮层的层叠顺序，透传为 CSS 变量 --cd-select-dropdown-z',
    },
    {
      name: 'prevText',
      type: 'string | Snippet',
      default: 'undefined',
      desc: '上一页按钮内容；缺省显示 ‹；可传字符串或 Snippet 自定义',
    },
    {
      name: 'nextText',
      type: 'string | Snippet',
      default: 'undefined',
      desc: '下一页按钮内容；缺省显示 ›；可传字符串或 Snippet 自定义',
    },
  ],
  a11y: {
    role: 'navigation',
    keyboard: ['Tab', 'Enter', 'Space'],
    notes: [
      'nav[aria-label] 包裹',
      '页码为原生 button，当前页 aria-current=page',
      '上一页/下一页在边界禁用',
      '省略号 aria-hidden=true 不可交互',
    ],
  },
  tokens: [
    // 全量对齐 Semi pagination/variables.scss（41 个）
    '--cd-color-pagination-text-default',
    '--cd-color-pagination-item-text-default',
    '--cd-color-pagination-item-bg-default',
    '--cd-color-pagination-item-icon-default',
    '--cd-color-pagination-item-text-hover',
    '--cd-color-pagination-item-bg-hover',
    '--cd-color-pagination-item-text-active',
    '--cd-color-pagination-item-bg-active',
    '--cd-color-pagination-item-text-disabled',
    '--cd-color-pagination-item-icon-disabled',
    '--cd-color-pagination-item-bg-disabled',
    '--cd-color-pagination-item-bg-selected-disabled',
    '--cd-color-pagination-item-text-selected',
    '--cd-color-pagination-item-bg-selected',
    '--cd-color-pagination-quickjump-text-disabled',
    '--cd-color-pagination-item-border-default',
    '--cd-color-pagination-item-border-hover',
    '--cd-color-pagination-item-border-active',
    '--cd-color-pagination-item-border-selected',
    '--cd-color-pagination-item-border-disabled',
    '--cd-height-pagination-item',
    '--cd-width-pagination-item-minwidth',
    '--cd-width-pagination-item-small-minwidth',
    '--cd-width-pagination-quickjump-input-width',
    '--cd-width-pagination-item-border',
    '--cd-spacing-pagination-padding',
    '--cd-spacing-pagination-small-paddingy',
    '--cd-spacing-pagination-small-paddingx',
    '--cd-spacing-pagination-item-marginleft',
    '--cd-spacing-pagination-item-marginright',
    '--cd-spacing-pagination-item-small-margin',
    '--cd-spacing-pagination-reset-list-paddingtop',
    '--cd-spacing-pagination-reset-list-paddingbottom',
    '--cd-spacing-pagination-quickjump-marginleft',
    '--cd-spacing-pagination-quickjump-input-marginleft',
    '--cd-spacing-pagination-quickjump-input-marginright',
    '--cd-radius-pagination-item',
    '--cd-font-pagination-small-fontweight',
    '--cd-font-pagination-item-fontweight',
    '--cd-font-pagination-item-active-fontweight',
    '--cd-font-pagination-quickjump-fontweight',
    // 直引 alias / global（Semi 无对应组件 token）
    '--cd-focus-ring',
    '--cd-spacing-tight',
    '--cd-spacing-extra-tight',
    '--cd-font-size-small',
    '--cd-font-size-header-6',
    '--cd-motion-duration-fast',
    '--cd-motion-ease-standard',
    // 每页条数下拉复用 Select（--cd-select-*）
  ],
} as const;
