/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Pagination',
  category: 'navigation',
  description:
    '分页器，用于切换大量数据的页码。严格对齐 Semi Design：default（完整页码 + 省略号折叠，7 格上限）与 small（current/total 紧凑视图，可 hoverShowPageSelect 悬停弹全部页码切页）两类布局。showTotal 显示总页数；省略号 hover 弹出隐藏页码。越界的当前页/每页条数与快速跳页输入均会被钳制到有效范围（纯函数实现，受控 prop 仅经回调上报）。',
  props: [
    { name: 'total', type: 'number', default: '1', desc: '数据总条数（对齐 Semi）' },
    { name: 'showTotal', type: 'boolean', default: 'false', desc: '是否显示总页数文案（对齐 Semi）' },
    { name: 'pageSize', type: 'number', default: 'undefined', desc: '每页条数；缺省取 pageSizeOpts[0]（对齐 Semi，默认 null）' },
    { name: 'pageSizeOpts', type: 'number[]', default: '[10,20,40,100]', desc: 'size changer 可选每页条数（对齐 Semi）' },
    { name: 'size', type: "'small'|'default'", default: 'default', desc: "small 为紧凑视图（current/total）（对齐 Semi）" },
    { name: 'currentPage', type: 'number', default: 'undefined', desc: '受控当前页（越界自动钳制显示，不回写；对齐 Semi）' },
    { name: 'defaultCurrentPage', type: 'number', default: '1', desc: '默认当前页（非受控；对齐 Semi）' },
    { name: 'onPageChange', type: '(currentPage: number) => void', default: 'undefined', desc: '仅页码变化回调（对齐 Semi）' },
    { name: 'onPageSizeChange', type: '(newPageSize: number) => void', default: 'undefined', desc: '每页容量变化回调（对齐 Semi）' },
    { name: 'onChange', type: '(currentPage: number, pageSize: number) => void', default: 'undefined', desc: '页码或每页容量变化回调（对齐 Semi）' },
    { name: 'prevText', type: 'string | Snippet', default: 'undefined', desc: '上一页内容；缺省显示 ‹（对齐 Semi prevText）' },
    { name: 'nextText', type: 'string | Snippet', default: 'undefined', desc: '下一页内容；缺省显示 ›（对齐 Semi nextText）' },
    { name: 'showSizeChanger', type: 'boolean', default: 'false', desc: '显示每页条数选择器；size=small 时不生效（对齐 Semi）' },
    { name: 'showQuickJumper', type: 'boolean', default: 'false', desc: '显示快速跳页输入（越界静默钳制，非数字忽略；对齐 Semi）' },
    { name: 'popoverZIndex', type: 'number', default: '1030', desc: '浮层 z-index（对齐 Semi），透传 Select/Popover' },
    { name: 'popoverPosition', type: "PopoverPosition", default: "'bottomLeft'", desc: 'size changer / 省略号 / hover 浮层方位（对齐 Semi，透传 Select/Popover）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '透传根元素内联样式（对齐 Semi style）' },
    { name: 'class', type: 'string', default: 'undefined', desc: '透传根元素类名（对齐 Semi className）' },
    { name: 'hideOnSinglePage', type: 'boolean', default: 'false', desc: '仅一页时隐藏整个分页器；showSizeChanger 为 true 时此开关失效（对齐 Semi）' },
    { name: 'hoverShowPageSelect', type: 'boolean', default: 'false', desc: 'size=small 时 hover 页码弹出全部页码快速切换（对齐 Semi，v1.27）' },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用（对齐 Semi）' },
    { name: 'preventPageChangeOnPageSizeChange', type: 'boolean', default: 'false', desc: '切换 pageSize 时阻止自动调整 currentPage（对齐 Semi）' },
  ],
  a11y: {
    role: 'navigation',
    keyboard: ['Tab', 'Enter', 'Space', 'ArrowLeft', 'ArrowRight', 'Home', 'End'],
    notes: [
      'nav[aria-label] 包裹；页码列表 ul/li，页码为 li 内 <button>，当前页 aria-current=page',
      '页码组 roving tabindex：仅当前/聚焦页 tabindex=0，方向键漫游移动焦点不切页，Enter/Space 切页',
      '上一页/下一页在边界原生 disabled 且移出 Tab 序列',
      '省略号可 hover 弹出隐藏页码（disabled 时降级为 aria-hidden 静态 …）',
    ],
  },
  tokens: [
    // 全量对齐 Semi pagination/variables.scss（41 个）
    '--cd-color-pagination-text-default',
    '--cd-color-pagination-item-text-default',
    '--cd-color-pagination-item-bg-default',
    '--cd-color-pagination-item-icon-default',
    '--cd-color-pagination-item-text-hover',
    '--cd-color-pagination-item-bg-hover',
    '--cd-color-pagination-item-text-active',
    '--cd-color-pagination-item-bg-active',
    '--cd-color-pagination-item-text-disabled',
    '--cd-color-pagination-item-icon-disabled',
    '--cd-color-pagination-item-bg-disabled',
    '--cd-color-pagination-item-bg-selected-disabled',
    '--cd-color-pagination-item-text-selected',
    '--cd-color-pagination-item-bg-selected',
    '--cd-color-pagination-quickjump-text-disabled',
    '--cd-color-pagination-item-border-default',
    '--cd-color-pagination-item-border-hover',
    '--cd-color-pagination-item-border-active',
    '--cd-color-pagination-item-border-selected',
    '--cd-color-pagination-item-border-disabled',
    '--cd-height-pagination-item',
    '--cd-width-pagination-item-minwidth',
    '--cd-width-pagination-item-small-minwidth',
    '--cd-width-pagination-quickjump-input-width',
    '--cd-width-pagination-item-border',
    '--cd-spacing-pagination-padding',
    '--cd-spacing-pagination-small-paddingy',
    '--cd-spacing-pagination-small-paddingx',
    '--cd-spacing-pagination-item-marginleft',
    '--cd-spacing-pagination-item-marginright',
    '--cd-spacing-pagination-item-small-margin',
    '--cd-spacing-pagination-reset-list-paddingtop',
    '--cd-spacing-pagination-reset-list-paddingbottom',
    '--cd-spacing-pagination-quickjump-marginleft',
    '--cd-spacing-pagination-quickjump-input-marginleft',
    '--cd-spacing-pagination-quickjump-input-marginright',
    '--cd-radius-pagination-item',
    '--cd-font-pagination-small-fontweight',
    '--cd-font-pagination-item-fontweight',
    '--cd-font-pagination-item-active-fontweight',
    '--cd-font-pagination-quickjump-fontweight',
    // 直引 alias / global（Semi 无对应组件 token）
    '--cd-focus-ring',
    '--cd-spacing-tight',
    '--cd-motion-duration-fast',
    '--cd-motion-ease-standard',
    // 每页条数下拉复用 Select（--cd-select-*）；hover 弹层复用 Popover
  ],
} as const;
