/**
 * Machine-readable component metadata for AI/docs consumption.
 * Image — 全面对齐 Semi Image / ImagePreview（semi-ui/image）。
 * props 表逐条镜像 Semi API（spec §4 契约）。
 */
export const meta = {
  name: 'Image',
  category: 'show',
  description:
    '图片：加载态机（loading 骨架/自定义占位 → success → error 降级图/自定义/默认破图），success 且 preview 时 hover 蒙层 + 点击进全屏预览。预览浮层（ImagePreview）对齐 Semi：底部工具栏含上一张/页码/下一张、缩放 Slider、放大/缩小、原始尺寸↔适应页面切换、旋转、下载，支持鼠标滚轮以指针为锚缩放、超出容器拖拽平移、无限循环、预加载、无操作自动隐藏工具栏、renderHeader/renderPreviewMenu(menuItems)/renderCloseIcon/renderLeftIcon/renderRightIcon 自定义槽。ImagePreview 既可包裹多个 <Image> 做组预览，也可独立传 src 编程式控制。',
  exports: ['Image', 'ImagePreview'],
  props: [
    { name: 'src', type: 'string', default: 'undefined', desc: '图片获取地址' },
    { name: 'alt', type: 'string', default: "''", desc: '图像描述' },
    { name: 'width', type: 'number|string', default: 'undefined', desc: '图片显示宽度，number 视为 px' },
    { name: 'height', type: 'number|string', default: 'undefined', desc: '图片显示高度，number 视为 px' },
    { name: 'placeholder', type: 'Snippet', default: 'undefined', desc: '加载中占位内容（不传用 SkeletonImage 骨架）' },
    {
      name: 'fallback',
      type: 'string|Snippet',
      default: 'undefined',
      desc: '加载失败：string=降级图 src；Snippet=自定义内容；不传=默认破图 icon',
    },
    {
      name: 'preview',
      type: 'boolean|PreviewProps',
      default: 'true',
      desc: '预览：false 禁用；true 开启；对象=预览参数（含 src 覆盖预览图、visible 受控等）',
    },
    { name: 'crossorigin', type: "'anonymous'|'use-credentials'", default: 'undefined', desc: '透传给原生 img 的 crossorigin' },
    { name: 'imgCls', type: 'string', default: 'undefined', desc: '透传给 img 节点的自定义类名（对齐 Semi imgCls）' },
    { name: 'imgStyle', type: 'string', default: 'undefined', desc: '透传给 img 节点的自定义内联样式（对齐 Semi imgStyle）' },
    { name: 'setDownloadName', type: '(src: string) => string', default: 'undefined', desc: '设置预览下载文件名' },
    { name: 'onClick', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击图片回调' },
    { name: 'onError', type: '(e: Event) => void', default: 'undefined', desc: '加载错误回调' },
    { name: 'onLoad', type: '(e: Event) => void', default: 'undefined', desc: '加载成功回调' },
    { name: 'class', type: 'string', default: "''", desc: '根类名透传' },
    { name: 'style', type: 'string', default: "''", desc: '根内联样式透传' },
  ],
  events: [],
  subComponents: [
    {
      name: 'ImagePreview',
      desc: '预览组 / 独立可编程预览：包裹多个 <Image> 做组预览可左右切换；或独立传 src=string|string[] + visible/onVisibleChange 编程式控制。',
      props: [
        { name: 'src', type: 'string|string[]', default: 'undefined', desc: '预览图源列表（独立用法）' },
        { name: 'visible', type: 'boolean', default: 'undefined', desc: '受控：是否预览（不回写，仅 onVisibleChange）' },
        { name: 'defaultVisible', type: 'boolean', default: 'false', desc: '首次是否开启预览' },
        { name: 'currentIndex', type: 'number', default: 'undefined', desc: '受控：当前预览图下标（不回写，仅 onChange）' },
        { name: 'defaultCurrentIndex', type: 'number', default: '0', desc: '首次展示图片下标' },
        { name: 'maskClosable', type: 'boolean', default: 'true', desc: '点击遮罩是否可关闭' },
        { name: 'closable', type: 'boolean', default: 'true', desc: '是否显示关闭按钮' },
        { name: 'closeOnEsc', type: 'boolean', default: 'true', desc: '点击 esc 关闭预览' },
        { name: 'infinite', type: 'boolean', default: 'false', desc: '是否无限循环切换' },
        { name: 'zoomStep', type: 'number', default: '0.1', desc: '每次缩小/放大比例' },
        { name: 'maxZoom', type: 'number', default: '5', desc: '最大缩放比例' },
        { name: 'minZoom', type: 'number', default: '0.1', desc: '最小缩放比例' },
        { name: 'initialZoom', type: 'number', default: 'undefined', desc: '初始缩放比例（每图首帧生效一次，受 min/maxZoom 限制）' },
        { name: 'lazyLoad', type: 'boolean', default: 'true', desc: '组内子图是否懒加载（IntersectionObserver）' },
        { name: 'lazyLoadMargin', type: 'string', default: "'0px 100px 100px 0px'", desc: 'observer rootMargin' },
        { name: 'preLoad', type: 'boolean', default: 'true', desc: '是否预加载相邻图片' },
        { name: 'preLoadGap', type: 'number', default: '2', desc: '预加载步长' },
        { name: 'showTooltip', type: 'boolean', default: 'false', desc: '是否展示底部操作区 Tooltip 提示' },
        { name: 'disableDownload', type: 'boolean', default: 'false', desc: '禁用下载（含右键）' },
        { name: 'viewerVisibleDelay', type: 'number', default: '10000', desc: '隐藏操作按钮前的无操作时长(ms)' },
        { name: 'zIndex', type: 'number', default: '1070', desc: '预览层层级' },
        { name: 'getPopupContainer', type: '() => HTMLElement', default: 'undefined', desc: '指定预览浮层父级 DOM（需 position:relative）' },
        { name: 'setDownloadName', type: '(src: string) => string', default: 'undefined', desc: '设置下载文件名' },
        { name: 'prevTip / nextTip / zoomInTip / zoomOutTip / rotateTip / downloadTip / adaptiveTip / originTip', type: 'string', default: 'locale', desc: '各操作按钮 Tooltip 文案（缺省走 locale）' },
        { name: 'renderHeader', type: 'Snippet<[title]>', default: 'undefined', desc: '自定义预览顶部区（收到当前 title）' },
        { name: 'renderPreviewMenu', type: 'Snippet<[MenuProps]>', default: 'undefined', desc: '自定义底部菜单（MenuProps.menuItems 为默认按钮 Snippet 数组）' },
        { name: 'renderCloseIcon / renderLeftIcon / renderRightIcon', type: 'Snippet', default: 'undefined', desc: '自定义关闭/左切换/右切换图标' },
        { name: 'onVisibleChange', type: '(visible: boolean) => void', default: 'undefined', desc: '预览开关变化' },
        { name: 'onChange', type: '(index: number) => void', default: 'undefined', desc: '切换图片' },
        { name: 'onClose', type: '() => void', default: 'undefined', desc: '关闭回调' },
        { name: 'onPrev / onNext', type: '(index: number) => void', default: 'undefined', desc: '向前/向后切换回调' },
        { name: 'onZoomIn / onZoomOut', type: '(zoom: number) => void', default: 'undefined', desc: '放大/缩小回调' },
        { name: 'onRotateLeft', type: '(angle: number) => void', default: 'undefined', desc: '旋转回调' },
        { name: 'onRatioChange', type: '(type: "adaptation"|"realSize") => void', default: 'undefined', desc: '原始尺寸/适应切换回调' },
        { name: 'onDownload', type: '(src, index) => void', default: 'undefined', desc: '下载回调' },
        { name: 'onDownloadError', type: '(src) => void', default: 'undefined', desc: '下载失败回调' },
      ],
    },
  ],
  slots: [
    { name: 'placeholder', desc: '加载中自定义占位内容' },
    { name: 'fallback', desc: '加载失败自定义内容（fallback 为 Snippet 时）' },
  ],
  a11y: {
    role: 'img',
    keyboard: ['Escape', 'ArrowLeft', 'ArrowRight'],
    focusable: true,
    notes: [
      'img 必传 alt 语义；默认破图占位用 role=img + aria-label',
      '预览遮罩 role=dialog、aria-modal=true，portal 到 getPopupContainer/body；useFocusTrap 锁定焦点、Esc 关闭、useScrollLock 锁背景滚动',
      '组/独立预览左右切换：中部 ← → 按钮 + 键盘左右箭头（到边界按钮隐藏，infinite 时循环）',
      '翻页经 LiveAnnouncer polite 播报「第 m 张，共 n 张」',
    ],
  },
  tokens: [
    '--cd-image-radius',
    '--cd-image-mask-bg',
    '--cd-image-mask-info-text',
    '--cd-image-status-bg',
    '--cd-image-status-color',
    '--cd-image-preview-bg',
    '--cd-image-preview-icon-color',
    '--cd-image-preview-icon-bg',
    '--cd-image-preview-icon-size',
    '--cd-image-preview-icon-offset-x',
    '--cd-image-preview-header-color',
    '--cd-image-preview-header-height',
    '--cd-image-preview-footer-bg',
    '--cd-image-preview-footer-icon-color',
    '--cd-image-preview-footer-radius',
    '--cd-image-preview-footer-slider-width',
    '--cd-image-preview-divider-bg',
    '--cd-image-preview-disabled-color',
    '--cd-image-preview-image-spin-color',
    '--cd-image-preview-z',
  ],
  examples: [
    { title: '基础', code: '<Image src="/a.jpg" alt="示例" width={360} height={200} />' },
    {
      title: '加载失败降级图',
      code: '<Image src="/broken.jpg" width={200} height={200} fallback="/placeholder.png" />',
    },
    {
      title: '自定义预览图',
      code: '<Image src="/small.jpg" width={300} preview={{ src: "/big.jpg" }} />',
    },
    {
      title: '多图预览组',
      code: '<ImagePreview>\n  <Image src="/a.jpg" alt="A" width={200} />\n  <Image src="/b.jpg" alt="B" width={200} />\n</ImagePreview>',
    },
    {
      title: '独立编程式预览',
      code: '<ImagePreview src={["/a.jpg", "/b.jpg"]} visible={open} onVisibleChange={(v) => (open = v)} />',
    },
  ],
} as const;
