/**
 * Machine-readable component metadata for AI/docs consumption.
 * SideSheet — 严格镜像 Semi Design（semi-foundation/sideSheet + semi-ui/sideSheet）。
 */
export const meta = {
  name: 'SideSheet',
  category: 'show',
  stage: 'M5',
  semiEquivalent: 'SideSheet',
  description:
    '滑动侧边栏：从视口四边（left/right/top/bottom）滑入的浮层容器，承载二级操作页面 / 详情 / 表单 / 筛选，比 Modal 提供更大可滚动内容区。DOM 结构与类名严格对齐 Semi：wrapper(.cd-sidesheet-{placement}) > mask + inner(.cd-sidesheet-inner.cd-sidesheet-inner-wrap.cd-sidesheet-size-{size}, role=dialog tabindex=-1) > content > header(role=heading aria-level=1)+body+footer。Portal 到 getPopupContainer()/body 脱离父层叠上下文；role=dialog，mask 时加 aria-modal；closeOnEsc（默认 false）时 window 监听 Esc 关闭；mask=true 默认锁 body 滚动（disableScroll），getPopupContainer 指向非 body 时为 popup 模式（wrapper position:static）。mask=false 为可操作外部区域形态（无遮罩、面板 box-shadow: --cd-shadow-elevated、宽度落在 wrapper）。size(small448/medium684/large920，默认 small) 仅 left/right 生效；width（默认 448，left/right）/ height（默认 400，top/bottom）显式覆盖。进出场动画对齐 Semi CSSAnimation：mask 淡入淡出 + inner 按 placement 滑入滑出，animationend 后卸载；motion=false 或 prefers-reduced-motion 退化即时显隐。关闭按钮用 IconButton（type=tertiary theme=borderless size=small）+ IconClose。受控 visible（不回写），仅经 onCancel(e) 通知；afterVisibleChange 于动画结束回调可见状态。keepDOM 关闭保留 DOM。',
  exports: ['SideSheet'],
  a11yPattern: 'dialog-modal',
  apgRef: 'dialog (modal)',
  relatedComponents: ['Modal', 'Popover', 'Notification'],
  usageHints:
    '承载二级操作页面 / 详情 / 筛选 / 表单；模态用 mask=true，可操作外部区域用 mask=false。承载单一确认/决策用 Modal，不要混用。',
  dangerousActions:
    'footer 危险操作（删除/清空等不可逆）使用 --cd-color-danger 与具体动词文案，并由业务侧在 onCancel 对未保存内容做二次确认。',
  props: [
    { name: 'visible', type: 'boolean', default: 'false', desc: '面板是否可见（受控，不回写）' },
    { name: 'placement', type: "'left'|'right'|'top'|'bottom'", default: "'right'", desc: '滑出位置' },
    { name: 'size', type: "'small'|'medium'|'large'", default: "'small'", desc: '尺寸（448/684/920px），仅 left/right 生效' },
    { name: 'width', type: 'number|string', default: '448', desc: 'left/right 宽度，数字按 px' },
    { name: 'height', type: 'number|string', default: '400', desc: 'top/bottom 高度，数字按 px' },
    { name: 'title', type: 'string', default: 'undefined', desc: '面板标题' },
    { name: 'titleSnippet', type: 'Snippet', default: 'undefined', desc: '自定义标题区（覆盖 title）；对齐 Semi title(ReactNode)' },
    { name: 'closable', type: 'boolean', default: 'true', desc: '是否显示右上角关闭按钮' },
    { name: 'closeIcon', type: 'Snippet|null', default: 'IconClose', desc: '关闭按钮 icon' },
    { name: 'closeOnEsc', type: 'boolean', default: 'false', desc: '是否允许 Esc 关闭' },
    { name: 'mask', type: 'boolean', default: 'true', desc: '是否显示遮罩；false 时允许操作外部区域' },
    { name: 'maskClosable', type: 'boolean', default: 'true', desc: '是否允许点击遮罩关闭' },
    { name: 'disableScroll', type: 'boolean', default: 'true', desc: '渲染在 body 层时是否禁止 body 滚动' },
    { name: 'keepDOM', type: 'boolean', default: 'false', desc: '关闭时是否保留内部组件不销毁' },
    { name: 'getPopupContainer', type: '() => HTMLElement | null', default: 'undefined', desc: '指定父级 DOM，弹层渲染至该 DOM' },
    { name: 'zIndex', type: 'number', default: '1000', desc: '弹层 z-index' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '是否允许动画' },
    { name: 'style', type: 'string', default: 'undefined', desc: '面板根内联样式' },
    { name: 'bodyStyle', type: 'string', default: 'undefined', desc: '内容区域内联样式' },
    { name: 'headerStyle', type: 'string', default: 'undefined', desc: 'Header 区域内联样式' },
    { name: 'maskStyle', type: 'string', default: 'undefined', desc: '遮罩内联样式' },
    { name: 'footer', type: 'Snippet<[{ close: () => void }]>|null', default: 'undefined', desc: 'Footer 操作区；提供 close() 关闭面板；未提供不渲染' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: 'Body 主内容区（可滚动）' },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '无可见标题时提供 aria-label' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根元素自定义类名' },
    { name: 'afterVisibleChange', type: '(isVisible: boolean) => void', default: 'undefined', desc: '展示/隐藏动画结束触发' },
    { name: 'onCancel', type: '(e: MouseEvent | KeyboardEvent) => void', default: 'undefined', desc: '取消面板时的回调' },
  ],
  events: [
    { name: 'onCancel', desc: '取消面板（关闭按钮 / 遮罩 / Esc），payload 为触发事件' },
    { name: 'afterVisibleChange', desc: '面板展示/隐藏动画结束触发，payload 为当前是否可见' },
  ],
  slots: [
    { name: 'children', desc: 'Body 主内容区（可滚动）' },
    { name: 'titleSnippet', desc: '自定义标题区，覆盖 title' },
    { name: 'footer', desc: 'Footer 操作区，提供 close()' },
    { name: 'closeIcon', desc: '自定义关闭图标' },
  ],
  a11y: {
    hasRole: true,
    focusable: true,
    note: 'wrapper > inner role=dialog tabindex=-1（mask=true 加 aria-modal=true）；内部 header role=heading aria-level=1；有 title 用 aria-labelledby，无则 ariaLabel；closeOnEsc 控制 Esc 关闭；关闭按钮 aria-label 经 SideSheet.closeAriaLabel；reduced-motion / motion=false 退化即时显隐。',
  },
  tokens: [
    '--cd-color-side-sheet-mask-bg',
    '--cd-color-side-sheet-bg',
    '--cd-color-side-sheet-main-text',
    '--cd-color-side-sheet-header-border-bottom',
    '--cd-spacing-side-sheet-margin',
    '--cd-spacing-side-sheet-title-margin',
    '--cd-spacing-side-sheet-header-padding',
    '--cd-spacing-side-sheet-header-padding-bottom',
    '--cd-spacing-side-sheet-body-paddingy',
    '--cd-spacing-side-sheet-body-paddingx',
    '--cd-spacing-side-sheet-footer-padding',
    '--cd-width-side-sheet-header-border-bottom',
    '--cd-width-side-sheet-size-small',
    '--cd-width-side-sheet-size-medium',
    '--cd-width-side-sheet-size-large',
    '--cd-font-side-sheet-title-fontweight',
    '--cd-font-side-sheet-title-fontsize',
    '--cd-filter-side-sheet-mask-bg',
    '--cd-filter-side-sheet-bg',
    '--cd-animation-duration-side-sheet-mask-show',
    '--cd-animation-function-side-sheet-mask-show',
    '--cd-animation-delay-side-sheet-mask-show',
    '--cd-animation-duration-side-sheet-mask-hide',
    '--cd-animation-function-side-sheet-mask-hide',
    '--cd-animation-delay-side-sheet-mask-hide',
    '--cd-animation-duration-side-sheet-inner-show',
    '--cd-animation-function-side-sheet-inner-show',
    '--cd-animation-delay-side-sheet-inner-show',
    '--cd-animation-duration-side-sheet-inner-hide',
    '--cd-animation-function-side-sheet-inner-hide',
    '--cd-animation-delay-side-sheet-inner-hide',
  ],
  responsive: true,
  examples: [
    {
      title: '基本',
      code: '<SideSheet title="滑动侧边栏" visible={visible} onCancel={() => (visible = false)}>内容</SideSheet>',
    },
    {
      title: '自定义位置',
      code: '<SideSheet placement="left" title="菜单" visible={visible} onCancel={() => (visible = false)}>导航</SideSheet>',
    },
    {
      title: '自定义尺寸',
      code: '<SideSheet size="medium" title="滑动侧边栏" visible={visible} onCancel={() => (visible = false)}>内容</SideSheet>',
    },
    {
      title: '可操作的外部区域',
      code: '<SideSheet mask={false} disableScroll={false} title="可操作外部" visible={visible} onCancel={() => (visible = false)}>内容</SideSheet>',
    },
  ],
} as const;
