/**
 * Machine-readable component metadata for AI/docs consumption.
 * SideSheet — see specs/components/feedback/SideSheet.spec.md
 */
export const meta = {
  name: 'SideSheet',
  category: 'feedback',
  stage: 'M5',
  semiEquivalent: 'SideSheet',
  description:
    '侧边滑出浮层：从视口四边（left/right/top/bottom）滑入的容器，承载次要任务流/详情/筛选/表单，比 Modal 提供更大可滚动内容区。与 Modal 同构复用浮层基建——portal 到 body（或 getContainer）脱离父层叠上下文；role=dialog，mask 时加 aria-modal；useFocusTrap 焦点捕获与归还（仅 mask=true）、useDismiss Esc 关闭（closeOnEsc），mask 时 useScrollLock 锁背景滚动（可 disableScrollLock 关闭）。mask=true 模态（遮罩+锁滚+陷阱），mask=false 非模态（无遮罩、不锁滚动、不抢焦点，outsideClosable 时点外部关闭）。size(small/default/large) 预设宽（横向）/高（纵向），width/height 显式覆盖；窄视口近铺满。Header/Body/Footer 三段式，footer 暴露 close()。滑入过渡为 CSS transform/opacity（token 时长缓动，reduced-motion 与 motionDisabled 退化为即时显隐）。lazyMount 首开前惰性挂载，destroyOnClose 关闭即卸载内容（出场过渡结束后 onAfterClose）。堆叠 z-index 复用 modal/z-stack 模块级计数器，与 Modal 统一层栈、后开者在上、Esc 仅关栈顶。受控 open（不回写），仅经 onOpenChange({open, reason}) 通知，reason 覆盖 esc/mask/outside/closeButton/programmatic。',
  exports: ['SideSheet'],
  a11yPattern: 'dialog-modal',
  apgRef: 'dialog (modal)',
  replaces: ['Drawer'],
  relatedComponents: ['Modal', 'Popover', 'Notification'],
  usageHints:
    '承载次要任务流/详情/筛选；模态用 mask=true，协作式（打开仍可操作主页面）用 mask=false。承载单一确认/决策用 Modal，不要混用。',
  dangerousActions:
    'footer 危险操作（删除/清空等不可逆）使用 --cd-color-danger 与具体动词文案，并由业务侧拦截 onOpenChange 对未保存内容做二次确认。',
  props: [
    { name: 'open', type: 'boolean', default: 'false', desc: '受控显隐；受控时不回写，仅 onOpenChange 通知' },
    { name: 'placement', type: "'left'|'right'|'top'|'bottom'", default: "'right'", desc: '滑出方向（贴附边缘）；RTL 下 left/right 镜像' },
    { name: 'size', type: "'small'|'default'|'large'", default: "'default'", desc: '预设尺度（横向→宽度，纵向→高度）' },
    { name: 'width', type: 'number|string', default: 'undefined', desc: 'left/right 显式宽度，覆盖 size；数字按 px' },
    { name: 'height', type: 'number|string', default: 'undefined', desc: 'top/bottom 显式高度，覆盖 size；数字按 px' },
    { name: 'title', type: 'string', default: 'undefined', desc: '标题文案' },
    { name: 'titleSnippet', type: 'Snippet', default: 'undefined', desc: '自定义标题区，覆盖 title' },
    { name: 'headerExtra', type: 'Snippet', default: 'undefined', desc: 'Header 右侧额外操作（关闭按钮之前）' },
    { name: 'closeIcon', type: 'Snippet', default: 'undefined', desc: '自定义关闭图标' },
    { name: 'mask', type: 'boolean', default: 'true', desc: '显示遮罩并以模态呈现（锁滚动+focus trap）；false 非模态' },
    { name: 'maskClosable', type: 'boolean', default: 'true', desc: '点击遮罩是否关闭（mask=true 生效）' },
    { name: 'outsideClosable', type: 'boolean', default: 'false', desc: 'mask=false 时点击面板外部是否关闭' },
    { name: 'closeOnEsc', type: 'boolean', default: 'true', desc: '按 Esc 是否关闭（仅作用于浮层栈顶）' },
    { name: 'closable', type: 'boolean', default: 'true', desc: 'Header 是否显示关闭按钮' },
    { name: 'lazyMount', type: 'boolean', default: 'true', desc: '首次打开前是否惰性挂载内容' },
    { name: 'keepDOM', type: 'boolean', default: 'undefined', desc: 'true 时保留 DOM（禁用惰性挂载）；lazyMount 优先' },
    { name: 'destroyOnClose', type: 'boolean', default: 'false', desc: '关闭后是否销毁内部内容（出场过渡结束后卸载），重开重建' },
    { name: 'getContainer', type: '() => HTMLElement | null', default: '() => document.body', desc: 'Portal 挂载容器' },
    { name: 'zIndex', type: 'number', default: '1000', desc: '浮层基准层级（栈内自动递增）' },
    { name: 'disableScrollLock', type: 'boolean', default: 'false', desc: '强制不锁背景滚动（即便 mask=true）' },
    { name: 'returnFocusTo', type: 'HTMLElement | (() => HTMLElement | null) | null', default: '触发元素', desc: '关闭后焦点返回目标' },
    { name: 'motionDisabled', type: 'boolean', default: 'false', desc: '关闭进出动效（独立于 reduced-motion）' },
    { name: 'footer', type: 'Snippet<[{ close: () => void }]>|null', default: 'undefined', desc: 'Footer 操作区；提供 close() 关闭面板；未提供不渲染' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: 'Body 主内容区（可滚动）' },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '无可见标题时提供 aria-label' },
    { name: 'class', type: 'string', default: 'undefined', desc: '面板自定义类名' },
    { name: 'bodyClass', type: 'string', default: 'undefined', desc: 'Body 自定义类名' },
    { name: 'maskClass', type: 'string', default: 'undefined', desc: '遮罩自定义类名' },
    { name: 'onOpenChange', type: '(e: { open: boolean; reason: Reason }) => void', default: 'undefined', desc: '显隐意图变化（受控，需外部回写 open）' },
    { name: 'onAfterOpen', type: '() => void', default: 'undefined', desc: '进入动效结束、内容完全可见后触发' },
    { name: 'onAfterClose', type: '() => void', default: 'undefined', desc: '退出动效结束、DOM 卸载后触发' },
    { name: 'onCancel', type: '(e: { reason: Reason }) => void', default: 'undefined', desc: '用户主动取消（Esc/遮罩/外部/关闭按钮）' },
  ],
  events: [
    { name: 'onOpenChange', desc: '显隐意图变化，payload { open, reason: esc|mask|outside|closeButton|programmatic }' },
    { name: 'onAfterOpen', desc: '进入动效结束后触发' },
    { name: 'onAfterClose', desc: '退出动效结束、DOM 卸载后触发' },
    { name: 'onCancel', desc: '用户主动取消，payload { reason }' },
  ],
  slots: [
    { name: 'children', desc: 'Body 主内容区（可滚动）' },
    { name: 'titleSnippet', desc: '自定义标题区，覆盖 title' },
    { name: 'headerExtra', desc: 'Header 右侧额外操作（关闭按钮之前）' },
    { name: 'footer', desc: 'Footer 操作区，提供 close()' },
    { name: 'closeIcon', desc: '自定义关闭图标' },
  ],
  a11y: {
    hasRole: true,
    focusable: true,
    note: 'role=dialog；mask=true 加 aria-modal=true（非模态不设，避免误导锁定语义）；有 title 用 aria-labelledby，无则 ariaLabel；mask 时 useFocusTrap 捕获 Tab 焦点循环并在关闭归还 returnFocusTo/触发元素；closeOnEsc 控制 Esc（仅栈顶）；mask 时 useScrollLock 锁背景滚动；关闭按钮 aria-label 经 SideSheet.closeAriaLabel；reduced-motion / motionDisabled 退化即时显隐。',
  },
  tokens: [
    '--cd-sidesheet-bg',
    '--cd-sidesheet-color',
    '--cd-sidesheet-mask-bg',
    '--cd-sidesheet-border',
    '--cd-sidesheet-radius',
    '--cd-sidesheet-shadow',
    '--cd-sidesheet-padding',
    '--cd-sidesheet-header-padding',
    '--cd-sidesheet-footer-padding',
    '--cd-sidesheet-title-color',
    '--cd-sidesheet-title-size',
    '--cd-sidesheet-close-color',
    '--cd-sidesheet-close-color-hover',
    '--cd-sidesheet-close-hover-bg',
    '--cd-sidesheet-width-small',
    '--cd-sidesheet-width',
    '--cd-sidesheet-width-large',
    '--cd-sidesheet-height-small',
    '--cd-sidesheet-height',
    '--cd-sidesheet-height-large',
    '--cd-sidesheet-z',
    '--cd-sidesheet-motion-duration',
  ],
  responsive: true,
  examples: [
    {
      title: '右侧模态面板',
      code: '<SideSheet open={visible} title="编辑用户" onOpenChange={(e) => (visible = e.open)}>表单</SideSheet>',
    },
    {
      title: '左侧导航面板',
      code: '<SideSheet open={visible} placement="left" title="菜单" onOpenChange={(e) => (visible = e.open)}>导航</SideSheet>',
    },
    {
      title: '非模态协作面板',
      code: '<SideSheet open={visible} mask={false} outsideClosable title="通知中心" onOpenChange={(e) => (visible = e.open)}>列表</SideSheet>',
    },
    {
      title: 'Footer 操作区',
      code: '<SideSheet open={visible} title="筛选" onOpenChange={(e) => (visible = e.open)}>{#snippet footer({ close })}<Button onclick={close}>取消</Button><Button type="primary">应用筛选</Button>{/snippet}内容</SideSheet>',
    },
  ],
} as const;
