/**
 * @chenzy-design/core — framework-agnostic headless primitives.
 * ZERO framework dependencies. Render layers (svelte, future vue/react) bind these.
 * See specs/00-foundation/mvvm-adapter.spec.md.
 */
export { useId, __resetIdCounter } from './id.js';
export {
  clampWithMode,
  boundaryHitOf,
  roundToPrecision,
  decimalsOf as decimalsOfNumber,
  addStep as addNumberStep,
  formatWithLocale,
  __resetNumberFormatCache,
  type BoundaryMode,
} from './input-number.js';
export { useFocusTrap, type FocusTrap } from './focus-trap.js';
export {
  useLiveAnnouncer,
  __resetLiveAnnouncer,
  type LiveAnnouncer,
  type Politeness,
} from './live-announcer.js';
export { useDismiss, type DismissOptions, type DismissReason } from './dismiss.js';
export { useScrollLock, __resetScrollLock } from './scroll-lock.js';
export {
  useInertBackground,
  __resetInertBackground,
} from './inert-background.js';
export {
  createSider,
  type SiderApi,
  type SiderOptions,
  type SiderTrigger,
} from './sider.js';
export {
  createForm,
  type FormApi,
  type FormOptions,
  type FormState,
  type FormValues,
  type FieldConfig,
  type FieldErrors,
  type Rule,
  type MessageDescriptor,
  type ValidateTrigger,
} from './form.js';
export {
  findRanges,
  mergeRanges,
  chunksFromRanges,
  highlightChunks,
  type HighlightRange,
  type HighlightChunk,
  type FindRangesOptions,
} from './highlight.js';
export {
  isSameDay,
  startOfDay,
  addMonths,
  addWeeks,
  addDays,
  getMonthGrid,
  getWeekGrid,
  getDayHours,
  weekdayOrder,
  daysBetween,
  formatDate,
  parseDateString,
  gridFocusMove,
  type DayCell,
  type GridFocusKey,
} from './date.js';
export {
  flattenVisible,
  findNode,
  collectExpandable,
  collectExpandableToDepth,
  conduct,
  toggleCheck,
  normalizeToLeaves,
  computeFilteredKeys,
  computeDropPosition,
  isAncestorOrSelf,
  collectCheckedByStrategy,
  siblingKeys,
  accordionExpand,
  type CheckedStrategy,
  type TreeKey,
  type TreeNodeData,
  type FlatNode,
  type CheckState,
  type DropPosition,
} from './tree.js';
export {
  flattenCascaderPaths,
  filterCascaderPaths,
  resolveColumnWidth,
  type CascaderKey,
  type CascaderPathNode,
  type CascaderFlatPath,
  type CascaderFilterFn,
} from './cascader.js';
export {
  nextSortOrder,
  toggleSort,
  applySort,
  paginate,
  pageCount,
  selectAllState,
  toggleSelectAll,
  toggleRow,
  flattenTreeRows,
  conductRows,
  normalizeRowsToLeaves,
  toggleRowCheck,
  type RowKey,
  type SortOrder,
  type SortState,
  type SelectAllState,
  type FlatRow,
} from './table.js';
export {
  eventCoversDay,
  eventsForDay,
  groupEventsByDays,
  timelineForDay,
  dayKey,
  isPastDay,
  type CalendarEvent,
  type CalendarEventKey,
  type DayEvents,
  type DayTimeline,
} from './calendar.js';
export {
  offsetToIndex,
  indexToOffset,
  indexOfValue,
  nextEnabledIndex,
  firstEnabledIndex,
  lastEnabledIndex,
  keyboardTarget,
  wrapIndex,
  cyclicVirtualCount,
  cyclicCenterIndex,
  cyclicRecenter,
  momentumStep,
  projectSettleIndex,
  type ScrollListValue,
  type ScrollListItem,
  type ScrollListKey,
  type MomentumStep,
} from './scroll-list.js';
export {
  computeVisibleCount,
  computeOverflowPartition,
  applyHysteresis,
  computeTabOverflow,
  type OverflowComputeInput,
  type OverflowComputeResult,
  type OverflowPartitionInput,
  type OverflowPartitionResult,
  type CollapseFrom,
  type TabOverflowInput,
  type TabOverflowResult,
} from './overflow-list.js';
export {
  createSpinController,
  type SpinController,
  type SpinOptions,
} from './spin.js';
export {
  clampPercent,
  resolveStatus,
  getCirclePathProps,
  getRootAriaProps,
  type ProgressStatus,
  type ProgressType,
  type GapPosition,
  type CirclePathProps,
  type RootAriaProps,
} from './progress.js';
export {
  resolveBannerRole,
  type BannerType,
  type BannerRoleProps,
} from './banner.js';
export {
  resolveCodeClassName,
  type ResolveCodeClassNameOptions,
} from './code-highlight.js';
export {
  compileToHast,
  type HastRoot,
  type CompileToHastOptions,
  type UnifiedPluginEntry,
} from './markdown-render.js';
export {
  createToastStore,
  type ToastStore,
  type ToastItem,
  type ToastOptions,
  type ToastType,
  type ToastPosition,
  type ToastTheme,
  type ToastCloseReason,
} from './toast.js';
export {
  createNotificationStore,
  type NotificationStore,
  type NotificationItem,
  type NotificationOptions,
  type NotificationType,
  type NotificationPlacement,
  type NotificationCloseReason,
  type NotificationTheme,
  type NotificationDirection,
} from './notification.js';
export { easeInOutCubic, isAboveThreshold, scrollPositionAt } from './back-top.js';
export {
  createAudioPlayer,
  normalizeAudioUrl,
  clampVolume as clampAudioVolume,
  clampTime as clampAudioTime,
  type AudioInfo,
  type AudioUrl,
  type AudioTrack,
  type PlaybackRate,
  type AudioPlayerAdapter,
  type AudioPlayerState,
  type AudioPlayerOptions,
  type AudioPlayerApi,
} from './audio-player.js';
export {
  createCropperFoundation,
  getMiddle as getCropperMiddle,
  getAspectHW,
  getMoveParamByDir,
  CROPPER_CORNERS,
  CROPPER_ROUND_CORNERS,
  CROPPER_SHAPES,
  type CropperFoundation,
  type CropperAdapter,
  type CropperFoundationProps,
  type CropperFoundationState,
  type CropperImageData,
  type CropperImageState,
  type CropperBox,
  type ContainerData as CropperContainerData,
  type CropperCorner,
  type CropperShape,
  type Point as CropperPoint,
} from './cropper.js';
export {
  mergeConfig,
  DEFAULT_CONFIG,
  resolveAppliedTheme,
  resolveReducedMotion,
  type ConfigInput,
  type ResolvedConfig,
  type ConfigTheme,
  type AppliedTheme,
  type ConfigDir,
  type ConfigSize,
  type ReducedMotionInput,
} from './config-provider.js';
export {
  createResizeObserver,
  normalizeEntry,
  isResizeObserverSupported,
  resolveSchedule,
  createScheduler,
  advanceResizePhase,
  endResizePhase,
  getGlobalResizeObserver,
  type ResizeBox,
  type ResizeSchedule,
  type CDResizeEntry,
  type ResizeObserverApi,
  type ResizeObserverOptions,
} from './resize-observer.js';
export {
  resolveSize,
  resolveAnimated,
  shouldAutoplay,
  resolveSegments,
  isLottieSrc,
  resolveRenderer,
  type LottieTrigger,
  type LottieSize,
  type LottieSegments,
  type LottieRenderer,
  type LottiePlayerAdapter,
  type LottiePlayerFactory,
} from './lottie-icon.js';
export {
  computePosition,
  parsePlacement,
  makePlacement,
  type Placement,
  type Side,
  type Align,
  type Rect,
  type Viewport,
  type ComputePositionInput,
  type ComputePositionResult,
} from './floating.js';
export {
  BREAKPOINTS,
  BREAKPOINT_ORDER,
  resolveActiveBreakpoint,
  resolveResponsiveValue,
  type Breakpoint,
} from './breakpoints.js';
export {
  computeAutosizeHeight,
  countCharacters,
  type AutosizeInput,
  type AutosizeResult,
} from './textarea.js';
export {
  createCopyable,
  writeClipboard,
  type CopyableApi,
  type CopyableOptions,
} from './copyable.js';
export {
  createEditable,
  clampLength,
  resolveEditableKey,
  type EditableApi,
  type EditableOptions,
  type EditableSnapshot,
  type EditableTrigger,
  type EditableKeyEvent,
  type EditableKeyAction,
} from './editable.js';
export {
  createEllipsis,
  isOverflowing,
  truncateText,
  type EllipsisApi,
  type EllipsisOptions,
  type EllipsisSnapshot,
  type EllipsisMeasureInput,
  type EllipsisPos,
} from './ellipsis.js';
export {
  computeUploadPercent,
  isUploadOk,
  createUploadQueue,
  resolveBeforeUpload,
  validateFileSize,
} from './upload.js';
export type {
  UploadTask,
  UploadQueue,
  BeforeUploadResult,
  BeforeUploadDecision,
  UploadSizeError,
} from './upload.js';
export {
  fixedRange,
  buildOffsets,
  totalFromOffsets,
  offsetToIndex as virtualOffsetToIndex,
  dynamicRange,
  scrollOffsetForIndex,
  windowScrollTop,
  type VirtualRange,
  type ScrollAlign,
} from './virtual-list.js';
export {
  rovingKeyFromEvent,
  nextRovingIndex,
  type RovingKey,
} from './roving.js';
export {
  toggleSelection,
  rangeSelection,
  type ListKey,
  type SelectionMode,
} from './list-selection.js';
export {
  pageCount as paginationPageCount,
  clampPage,
  isPageInRange,
  clampPageSize,
  parseJumpInput,
  pageRange,
  type PageCell,
} from './pagination.js';
export {
  clamp01 as colorClamp01,
  parseHex,
  rgbToHex,
  rgbToHsv,
  hsvToRgb,
  hsvToHsl,
  hslToHsv,
  rgbToHsl,
  hslToRgb,
  hexToHsv,
  hsvToHex,
  formatColor,
  parseColor,
  type Rgb,
  type Hsv,
  type Hsl,
  type ColorFormat,
  type RgbToHexOptions,
  type FormatOptions,
} from './color.js';
export {
  createVideoPlayerFoundation,
  progressValueFromPointer,
  segmentValueWidth,
  buildMarkerSegments,
  formatTimeDisplay,
  DEFAULT_CONTROLS_LIST,
  DEFAULT_PLAYBACK_RATE_LIST,
  VIDEO_PLAYER_NUMBERS,
  type VideoPlayerFoundation,
  type VideoPlayerFoundationOptions,
  type VideoPlayerAdapter,
  type VideoPlayerState,
  type VideoPlayerProps,
  type VideoPlayerLocale,
  type PlaybackRateOption,
  type LabeledOption,
  type VideoMarker,
} from './video-player.js';
export {
  buildRange as buildTimeRange,
  to12Hour,
  meridiemOf,
  from12Hour,
  buildHourOptions,
  buildMinuteOptions,
  buildSecondOptions,
  applyHideDisabled,
  isTimeDisabled,
  parseFormatSpec,
  formatTime,
  parseTimeString,
  type Meridiem,
  type TimeOption,
  type DisabledTime,
  type TimeParts,
  type FormatSpec,
} from './time.js';
export {
  CHAT_ROLE,
  CHAT_ALIGN,
  CHAT_MODE,
  MESSAGE_STATUS,
  SEND_HOT_KEY,
  PIC_SUFFIX_ARRAY,
  PIC_PREFIX,
  SHOW_SCROLL_GAP,
  SCROLL_ANIMATION_TIME,
  shouldShowBackBottom,
  resolveEnableUpload,
  shouldSendOnEnter,
  isImageAttachment,
  buildSendContent,
  appendDivider,
  makeUserMessage,
  deleteMessageFrom,
  toggleLike,
  toggleDislike,
  resetLastMessage,
  type ChatRole,
  type ChatAlign,
  type ChatMode,
  type MessageStatus,
  type SendHotKey,
  type Content,
  type Message,
  type Metadata,
  type RoleConfig,
  type EnableUploadProps,
  type ChatAttachment,
} from './chat.js';
export {
  responseToMessage,
  chatCompletionToMessage,
  streamingResponseToMessage,
  streamingChatCompletionToMessage,
  dialogueMessageToInput,
  formatToolArguments,
  toolCallStatus,
  toolCallView,
  contentItemType,
  normalizeDialogueContent,
  type ResponseStreamChunk,
  type StreamingResponseState,
  type ChatCompletionStreamChunk,
  type StreamingChatCompletionState,
  type ToolCallStatus,
  type ToolCallView,
  type AIMessageStatus,
  type ContentItem,
  type AIDialogueMessage,
  type AIDialogueMetadata,
  type AIDialogueRoleConfig,
  type AIDialogueReference,
  type OpenAIResponseObject,
  type ChatCompletionObject,
  type ChatCompletionMessage,
  type OutputMessage,
  type OutputText,
  type Reasoning,
  type Annotation,
  type ToolCallContentItem,
  type InputMessage,
  type InputText,
  type InputImage,
  type InputFile,
} from './ai-chat-dialogue.js';
export {
  validateChar,
  inputModeForFormat,
  toValueList,
  fromValueList,
  isComplete,
  completeSingleInput,
  handleKeyDown as pinCodeHandleKeyDown,
  distributePaste,
  type PinCodeFormat,
  type CompleteSingleResult,
  type PinCodeKeyAction,
  type DistributePasteResult,
} from './pincode.js';
export {
  isSendHotKey,
  resolveCanSend,
  buildMessageContent,
  transformDocToContents,
  suggestionContent,
  nextSuggestionIndex,
  referenceLabel,
  isImageReference,
  skillLabel,
  getSkillSlotHTML,
  getSelectSlotHTML,
  getInputSlotHTML,
  AI_CHAT_INPUT_ZERO_WIDTH,
  shouldOpenSkillPanel,
  setConfigureField,
  removeConfigureField,
  messageToChatInput,
  chatInputToChatCompletion,
  type AIChatInputContent,
  type AIChatInputAttachment,
  type AIChatInputReference,
  type AIChatInputMessageContent,
  type AIChatInputSendHotKey,
  type AIChatInputChangePayload,
  type AIChatInputSuggestion,
  type AIChatInputSkill,
  type AIChatInputConfigureValue,
  type ChatCompletionInputMessage,
} from './ai-chat-input.js';
