/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Button',
  category: 'basic',
  description: '触发即时操作的按钮，最基础的交互原子（严格对齐 Semi Button）。',
  props: [
    { name: 'type', type: "'primary'|'secondary'|'tertiary'|'warning'|'danger'", default: 'primary', desc: '语义类型' },
    { name: 'theme', type: "'solid'|'borderless'|'light'|'outline'", default: 'light', desc: '视觉变体：有背景/无背景/浅背景/边框' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default', desc: '尺寸' },
    { name: 'block', type: 'boolean', default: 'false', desc: '撑满容器宽度' },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用状态（底灰 + 灰字，优先级高于 loading）' },
    { name: 'loading', type: 'boolean', default: 'false', desc: '加载态（带旋转图标，禁用点击）' },
    { name: 'colorful', type: 'boolean', default: 'false', desc: 'AI 多彩按钮：type 仅 primary/tertiary 有意义（对齐 Semi）' },
    { name: 'circle', type: 'boolean', default: 'false', desc: '圆形按钮（border-radius:50%），配合 icon-only 呈正圆' },
    { name: 'htmlType', type: "'button'|'submit'|'reset'", default: 'button', desc: '原生 button 的 type 值' },
    { name: 'icon', type: 'Snippet', default: 'undefined', desc: '图标插槽；纯图标按钮需提供 ariaLabel' },
    { name: 'iconPosition', type: "'left'|'right'", default: 'left', desc: '图标相对文字位置' },
    { name: 'noHorizontalPadding', type: "boolean|'left'|'right'|('left'|'right')[]", default: 'false', desc: '仅设置 icon 时去单/双侧水平内距（inline padding）' },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '无障碍名（透传 aria-label）；纯图标按钮必填' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根元素自定义类名' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根元素自定义内联样式' },
    { name: 'contentClassName', type: 'string', default: 'undefined', desc: '内容区（.cd-button-content）自定义类名' },
    { name: '...rest', type: 'HTMLButtonAttributes', default: '-', desc: '其余原生属性透传到根 button：data-*/name/value/form/title/tabindex/aria-controls/aria-expanded 等' },
  ],
  events: [
    { name: 'onclick', payload: 'MouseEvent', desc: 'disabled/loading 时不触发（原生 disabled 阻断）' },
    { name: 'onmousedown', payload: 'MouseEvent', desc: '鼠标按下' },
    { name: 'onmouseenter', payload: 'MouseEvent', desc: '鼠标移入' },
    { name: 'onmouseleave', payload: 'MouseEvent', desc: '鼠标移出' },
  ],
  slots: [
    { name: 'children', desc: '按钮文本' },
    { name: 'icon', desc: '图标' },
  ],
  subComponents: [
    {
      name: 'ButtonGroup',
      usage: '<ButtonGroup> 包裹多个 <Button>，组级默认经 context 透传',
      desc: '横向拼接多个 Button；组级 size/type/theme/disabled/colorful 经 context 透传，组内 Button 显式 prop 始终优先。相邻按钮间以 1px 分隔条区隔（outline 主题走 border 叠边）。',
      props: [
        { name: 'type', type: "'primary'|'secondary'|'tertiary'|'warning'|'danger'", default: 'undefined', desc: '组级语义类型' },
        { name: 'theme', type: "'solid'|'borderless'|'light'|'outline'", default: 'undefined', desc: '组级视觉变体' },
        { name: 'size', type: "'small'|'default'|'large'", default: 'undefined', desc: '组级尺寸' },
        { name: 'disabled', type: 'boolean', default: 'undefined', desc: '组级禁用，整组一并禁用' },
        { name: 'colorful', type: 'boolean', default: 'undefined', desc: '组级多彩，透传给组内 Button' },
        { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '按钮组语义标签（aria-label）' },
        { name: 'class', type: 'string', default: 'undefined', desc: '根元素自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '根元素自定义内联样式' },
      ],
    },
    {
      name: 'SplitButtonGroup',
      usage: '<SplitButtonGroup> 包裹 Button + Dropdown(箭头 Button)，纯容器（对齐 Semi）',
      desc: '分裂按钮：纯 role=group 容器，为内部首/末 button 加圆角并添加按钮间隔。典型用法为左侧主 Button + 右侧 Dropdown 触发的箭头 Button。',
      props: [
        { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '分裂按钮组语义标签（root aria-label）' },
        { name: 'class', type: 'string', default: 'undefined', desc: '根元素自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '根元素自定义内联样式' },
        { name: 'children', type: 'Snippet', default: 'undefined', desc: '分裂按钮内容（Button + Dropdown 等）' },
      ],
    },
  ],
  a11y: { role: 'button', keyboard: ['Enter', 'Space'] },
  tokens: [
    '--cd-color-button-*',
    '--cd-height-button-*',
    '--cd-width-button-*',
    '--cd-spacing-button-*',
    '--cd-radius-button',
    '--cd-radius-button-group',
    '--cd-radius-button-splitbuttongroup-*',
    '--cd-color-button-group-*',
    '--cd-width-button-group-border',
    '--cd-height-button-group-line-default',
    '--cd-font-button-*',
    '--cd-transition-*-button-*',
    '--cd-transform-scale-button-*',
    '--cd-animation-duration-button-icon-*',
    '--cd-button-colorful-*',
  ],
  examples: [{ title: '基础', code: '<Button type="primary">确定</Button>' }],
} as const;
