/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Button',
  category: 'basic',
  description: '触发即时操作的按钮，最基础的交互原子。',
  props: [
    { name: 'type', type: "'primary'|'secondary'|'tertiary'|'warning'|'danger'", default: 'secondary', desc: '语义类型' },
    { name: 'theme', type: "'solid'|'borderless'|'light'|'outline'", default: 'light', desc: '视觉变体：有背景/无背景/浅背景/边框' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default', desc: '尺寸' },
    { name: 'block', type: 'boolean', default: 'false', desc: '撑满容器宽度' },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用状态' },
    { name: 'loading', type: 'boolean', default: 'false', desc: '加载态（带 Spin，禁用点击）' },
    { name: 'colorful', type: 'boolean', default: 'false', desc: 'AI 多彩按钮：所有 theme 下品牌蓝→紫渐变；type 仅 primary/tertiary 有意义' },
    { name: 'circle', type: 'boolean', default: 'false', desc: '圆形按钮（border-radius:50%），配合 icon-only 呈正圆' },
    { name: 'htmlType', type: "'button'|'submit'|'reset'", default: 'button', desc: '原生 button 的 type 值' },
    { name: 'icon', type: 'Snippet', default: 'undefined', desc: '图标插槽；纯图标按钮需提供 ariaLabel' },
    { name: 'iconPosition', type: "'left'|'right'", default: 'left', desc: '图标相对文字位置' },
    { name: 'noHorizontalPadding', type: "boolean|'left'|'right'|('left'|'right')[]", default: 'false', desc: '仅设置 icon 时去单/双侧水平内距' },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '无障碍名；纯图标按钮必填' },
    { name: 'ariaControls', type: 'string', default: 'undefined', desc: '控制的元素 id（透传 aria-controls，配合 Collapsible 等被控元素 id）' },
    { name: 'ariaExpanded', type: 'boolean', default: 'undefined', desc: '展开态语义（透传 aria-expanded，折叠/展开触发器用）' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根元素自定义类名' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根元素自定义内联样式' },
    { name: 'contentClassName', type: 'string', default: 'undefined', desc: '内容区自定义类名' },
  ],
  events: [
    { name: 'onclick', payload: 'MouseEvent', desc: 'disabled/loading 时不触发' },
    { name: 'onmousedown', payload: 'MouseEvent', desc: '鼠标按下' },
    { name: 'onmouseenter', payload: 'MouseEvent', desc: '鼠标移入' },
    { name: 'onmouseleave', payload: 'MouseEvent', desc: '鼠标移出' },
  ],
  slots: [
    { name: 'children', desc: '按钮文本' },
    { name: 'icon', desc: '图标' },
  ],
  subComponents: [
    {
      name: 'ButtonGroup',
      usage: '<ButtonGroup> 包裹多个 <Button>，组级默认经 context 透传',
      desc: '横向拼接多个 Button；组级 size/type/theme/disabled/colorful 经 context 透传，组内 Button 显式 prop 始终优先。',
      props: [
        { name: 'type', type: "'primary'|'secondary'|'tertiary'|'warning'|'danger'", default: 'undefined', desc: '组级语义类型' },
        { name: 'theme', type: "'solid'|'borderless'|'light'|'outline'", default: 'undefined', desc: '组级视觉变体' },
        { name: 'size', type: "'small'|'default'|'large'", default: 'undefined', desc: '组级尺寸' },
        { name: 'disabled', type: 'boolean', default: 'undefined', desc: '组级禁用，整组一并禁用' },
        { name: 'colorful', type: 'boolean', default: 'undefined', desc: '组级多彩，透传给组内 Button' },
        { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '按钮组语义标签（aria-label）' },
        { name: 'class', type: 'string', default: 'undefined', desc: '根元素自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '根元素自定义内联样式' },
      ],
    },
    {
      name: 'SplitButtonGroup',
      usage: '<SplitButtonGroup items={...}>，左侧主操作 + 右侧箭头触发下拉',
      desc: '分裂按钮：左侧主 Button + 右侧箭头按钮，点击箭头弹出 Dropdown（复用 items API 或 menu snippet）。',
      props: [
        { name: 'type', type: "'primary'|'secondary'|'tertiary'|'warning'|'danger'", default: 'primary', desc: '两侧按钮语义类型' },
        { name: 'theme', type: "'solid'|'borderless'|'light'|'outline'", default: 'solid', desc: '两侧按钮视觉变体' },
        { name: 'size', type: "'small'|'default'|'large'", default: 'default', desc: '两侧按钮尺寸' },
        { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用整个分裂按钮' },
        { name: 'loading', type: 'boolean', default: 'false', desc: '主按钮加载态' },
        { name: 'items', type: 'DropdownItem[]', default: '[]', desc: '下拉菜单数据项（透传给 Dropdown.items）' },
        { name: 'position', type: 'Placement', default: 'bottomEnd', desc: '下拉浮层位置' },
        { name: 'triggerAriaLabel', type: 'string', default: '更多操作', desc: '下拉箭头按钮的 aria-label' },
        { name: 'onSelect', type: '(key: string|number) => void', default: 'undefined', desc: '选中下拉项回调' },
        { name: 'onclick', type: '(e: MouseEvent) => void', default: 'undefined', desc: '主按钮点击回调' },
        { name: 'menu', type: 'Snippet', default: 'undefined', desc: '自定义下拉菜单体（替代 items）' },
        { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '分裂按钮组语义标签（root aria-label）' },
        { name: 'class', type: 'string', default: 'undefined', desc: '根元素自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '根元素自定义内联样式' },
      ],
    },
  ],
  a11y: { role: 'button', keyboard: ['Enter', 'Space'] },
  tokens: [
    '--cd-color-button-*',
    '--cd-height-button-*',
    '--cd-width-button-*',
    '--cd-spacing-button-*',
    '--cd-radius-button',
    '--cd-radius-button-group',
    '--cd-radius-button-splitbuttongroup',
    '--cd-font-button-*',
    '--cd-transition-*-button-*',
    '--cd-transform-scale-button-*',
    '--cd-button-colorful-*',
  ],
  examples: [{ title: '基础', code: '<Button type="primary">确定</Button>' }],
} as const;
