/**
 * Machine-readable component metadata for AI/docs consumption.
 * Notification — 严格对齐 Semi Design（semi-ui/notification）。
 */
export const meta = {
  name: 'Notification',
  category: 'feedback',
  description:
    '通知提醒框：命令式全局反馈 API（notification.open/success/info/warning/error/close/destroyAll/config + useNotification）。严格对齐 Semi——标题 + 内容 + 图标；六方位独立堆叠；单例容器惰性挂载到 getPopupContainer()（默认 body）；duration 秒自动关闭（0 常驻）+ hover 暂停/重启定时器 + 同 id 原地更新；role=alert + aria-labelledby 关联标题；theme(normal/light) 填充样式；icon 自定义图标；onClick 点击回调；onCloseClick 关闭按钮回调；notification.config({ top/bottom/left/right/position/duration/zIndex/direction/getPopupContainer }) 全局配置（首次生效）。useNotification() 返回 [api, holderStore]，配合 <NotificationHolder store={holderStore}> 让通知继承组件树上下文。',
  exports: ['notification', 'useNotification', 'NotificationHolder'],
  imperative: true,
  config: {
    top: '弹出位置 top（number | string），首次生效',
    bottom: '弹出位置 bottom（number | string），首次生效',
    left: '弹出位置 left（number | string），首次生效',
    right: '弹出位置 right（number | string），首次生效',
    position: "默认弹出位置 'topLeft'|'top'|'topRight'|'bottomLeft'|'bottom'|'bottomRight'（默认 topRight）",
    duration: '默认自动关闭秒数（默认 3，0 常驻）',
    zIndex: '通知列表 z-index（默认 1010，首次生效）',
    direction: "默认书写方向 'ltr'|'rtl'（per-item direction 优先）",
    getPopupContainer: '() => HTMLElement，容器宿主挂载目标（默认 body）；须在首条通知前生效',
  },
  props: [
    { name: 'id', type: 'string', default: 'undefined', desc: '指定 id；已存在则原地更新（对齐 Semi）' },
    { name: 'title', type: 'string | Snippet', default: "''", desc: '通知标题（string 文本或 Snippet）' },
    { name: 'content', type: 'string | Snippet', default: "''", desc: '通知内容（string 文本或 Snippet）' },
    {
      name: 'type',
      type: "'default'|'success'|'info'|'warning'|'error'",
      default: "'default'",
      desc: '语义类型，决定内置图标与强调色',
    },
    { name: 'duration', type: 'number', default: '3', desc: '自动关闭秒数，单位 s，0 时不自动关闭' },
    {
      name: 'position',
      type: "'top'|'bottom'|'topLeft'|'topRight'|'bottomLeft'|'bottomRight'",
      default: "'topRight'",
      desc: '弹出位置，每方位独立堆叠',
    },
    { name: 'showClose', type: 'boolean', default: 'true', desc: '是否展示关闭按钮' },
    {
      name: 'theme',
      type: "'normal'|'light'",
      default: "'normal'",
      desc: '填充样式；light 为多色浅填充（提高与界面对比）',
    },
    { name: 'icon', type: 'Snippet', default: 'undefined', desc: '左上角自定义图标（覆盖类型内置图标）' },
    { name: 'zIndex', type: 'number', default: '1010', desc: '弹层 z-index，首次设置一次生效' },
    {
      name: 'direction',
      type: "'ltr'|'rtl'",
      default: "'ltr'（可经 notification.config 改默认）",
      desc: 'RTL 时镜像卡片布局（图标/内容 margin 方向翻转）',
    },
    {
      name: 'getPopupContainer',
      type: '() => HTMLElement',
      default: '() => document.body',
      desc: '指定父级 DOM，容器将渲染至该 DOM（首条通知生效）',
    },
    { name: 'onClick', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击通知的回调' },
    {
      name: 'onClose',
      type: '() => void',
      default: 'undefined',
      desc: '通知关闭回调（主动关闭、延时到达关闭都会触发）',
    },
    {
      name: 'onCloseClick',
      type: '(id: string) => void',
      default: 'undefined',
      desc: '主动点击关闭按钮时的回调',
    },
  ],
  events: [
    { name: 'onClose', desc: '通知关闭时触发（主动关闭 / 延时到达 / destroyAll）' },
    { name: 'onClick', desc: '点击通知卡片时触发' },
    { name: 'onCloseClick', desc: '主动点击关闭按钮时触发，带 id' },
  ],
  slots: [],
  a11y: {
    hasRole: true,
    focusable: false,
    note: 'role=alert（对齐 Semi）；标题经 aria-labelledby 关联；关闭按钮为 IconButton，带 ariaLabel「关闭」。不抢焦点、不锁滚动。',
  },
  tokens: [
    '--cd-color-notification-bg-default',
    '--cd-color-notification-info-icon',
    '--cd-color-notification-warning-icon',
    '--cd-color-notification-danger-icon',
    '--cd-color-notification-success-icon',
    '--cd-color-notification-title-text',
    '--cd-color-notification-content-text',
    '--cd-color-notification-closebtn-icon',
    '--cd-color-notification-warning-light-bg',
    '--cd-color-notification-warning-light-border',
    '--cd-color-notification-success-light-bg',
    '--cd-color-notification-success-light-border',
    '--cd-color-notification-info-light-bg',
    '--cd-color-notification-info-light-border',
    '--cd-color-notification-danger-light-bg',
    '--cd-color-notification-danger-light-border',
    '--cd-color-notification-ambient-bg',
    '--cd-width-notification-notice',
    '--cd-width-notification-notice-minwidth',
    '--cd-width-notification-notice-icon',
    '--cd-width-notification-notice-border',
    '--cd-spacing-notification-list-margin',
    '--cd-spacing-notification-list-padding',
    '--cd-spacing-notification-notice-paddingtop',
    '--cd-spacing-notification-notice-paddingright',
    '--cd-spacing-notification-notice-paddingbottom',
    '--cd-spacing-notification-notice-paddingleft',
    '--cd-spacing-notification-notice-margin',
    '--cd-spacing-notification-notice-marginright',
    '--cd-spacing-notification-notice-title-marginbottom',
    '--cd-spacing-notification-notice-content-wrapper-marginright',
    '--cd-spacing-notification-notice-icon-marginright',
    '--cd-radius-notification-notice',
    '--cd-font-notification-notice-title-fontweight',
    '--cd-font-notification-notice-content-fontweight',
  ],
  responsive: false,
  examples: [
    { title: '普通通知', code: "notification.open({ title: 'Hi, Bytedance', content: 'ies dance dance dance', duration: 3 })" },
    { title: '成功', code: "notification.success({ title: '上传完成', content: '文件已保存' })" },
    { title: '多色', code: "notification.info({ title: 'Hi', content: '…', theme: 'light' })" },
    { title: '常驻 + 手动关闭', code: "const id = notification.info({ content: 'Not auto close', duration: 0 }); notification.close(id)" },
    { title: '更新内容', code: "const id = notification.open({ content: 'v1' }); notification.open({ id, content: 'v2' })" },
  ],
} as const;
