/**
 * Machine-readable component metadata for AI/docs consumption.
 * Notification — see specs/components/feedback/Notification.spec.md
 */
export const meta = {
  name: 'Notification',
  category: 'feedback',
  description:
    '通知提醒框：命令式全局反馈 API（notification.open/success/info/warning/error/close/update/destroyAll）。比 Toast 更丰富——标题 + 内容 + 图标；6 方位独立堆叠；单例容器惰性挂载到 body；自动关闭 + 悬停暂停 + maxCount 按方位 FIFO 淘汰 + 同 id 去重更新；error/warning role=alert(assertive)、其余 role=status(polite)；可选 showProgress 倒计时进度条（命令式 rAF + 悬停同步暂停）、footer 操作区 Snippet、theme(light/dark)；RTL（direction=rtl 镜像卡片布局并左右互换方位）、Esc 关闭最近一条（window keydown + cleanup）、notification.config({ direction, getPopupContainer }) 配置全局方向与容器挂载点（默认 ltr + body，对齐 Modal/Dropdown getContainer）。',
  exports: ['notification'],
  imperative: true,
  config: {
    direction: "全局默认书写方向 'ltr'|'rtl'（per-item direction 优先）",
    getPopupContainer:
      '() => HTMLElement，容器宿主挂载目标（默认 body）；须在首条通知前调用方生效',
  },
  props: [
    { name: 'id', type: 'string', default: 'undefined', desc: '指定 id；已存在则原地更新' },
    { name: 'title', type: 'string', default: '—', desc: '通知标题' },
    { name: 'content', type: 'string', default: '—', desc: '通知正文' },
    {
      name: 'type',
      type: "'default'|'success'|'info'|'warning'|'error'",
      default: "'default'",
      desc: '语义类型，决定图标与强调色',
    },
    {
      name: 'duration',
      type: 'number',
      default: '4.5',
      desc: '自动关闭秒数；0 持久',
    },
    {
      name: 'placement',
      type: "'topLeft'|'top'|'topRight'|'bottomLeft'|'bottom'|'bottomRight'",
      default: "'topRight'",
      desc: '弹出位置，每方位独立堆叠',
    },
    { name: 'closable', type: 'boolean', default: 'true', desc: '是否显示关闭按钮' },
    { name: 'pauseOnHover', type: 'boolean', default: 'true', desc: '悬停/聚焦时暂停定时器' },
    {
      name: 'showProgress',
      type: 'boolean',
      default: 'false',
      desc: '底部倒计时进度条，随 duration 递减；悬停/聚焦时与定时器同步暂停（duration=0 时不显示）',
    },
    {
      name: 'theme',
      type: "'light'|'dark'",
      default: "'light'",
      desc: '卡片主题；dark 为深色卡片',
    },
    {
      name: 'direction',
      type: "'ltr'|'rtl'",
      default: "'ltr'（可经 notification.config 改默认）",
      desc: 'RTL 时镜像卡片布局（关闭按钮/图标/文案/进度方向翻转）并左右互换方位',
    },
    {
      name: 'footer',
      type: 'Snippet',
      default: 'undefined',
      desc: '底部操作区插槽（按钮等），渲染在内容下方',
    },
    {
      name: 'onClose',
      type: "(id: string, reason: 'timeout'|'manual'|'replace'|'destroyAll') => void",
      default: 'undefined',
      desc: '关闭回调，附关闭原因',
    },
  ],
  events: [{ name: 'onClose', desc: '单条关闭（超时/手动/被替换/清空）时触发，带 id 与 reason' }],
  slots: [],
  a11y: {
    hasRole: true,
    focusable: false,
    note: 'error/warning 用 role=alert + aria-live=assertive，其余 role=status + aria-live=polite；标题 aria-labelledby、内容 aria-describedby；关闭按钮 button + aria-label「关闭」。不抢焦点、不锁滚动。',
  },
  tokens: [
    '--cd-notification-width',
    '--cd-notification-bg',
    '--cd-notification-color-title',
    '--cd-notification-color-content',
    '--cd-notification-border',
    '--cd-notification-radius',
    '--cd-notification-shadow',
    '--cd-notification-padding',
    '--cd-notification-gap',
    '--cd-notification-icon-success',
    '--cd-notification-icon-info',
    '--cd-notification-icon-warning',
    '--cd-notification-icon-error',
    '--cd-notification-close-color',
    '--cd-notification-close-color-hover',
    '--cd-notification-title-size',
    '--cd-notification-content-size',
    '--cd-notification-z',
    '--cd-notification-offset',
    '--cd-notification-motion-duration',
    '--cd-notification-progress-height',
    '--cd-notification-progress-color',
    '--cd-notification-bg-dark',
    '--cd-notification-border-dark',
    '--cd-notification-color-title-dark',
    '--cd-notification-color-content-dark',
    '--cd-notification-close-color-dark',
    '--cd-notification-close-color-hover-dark',
  ],
  responsive: false,
  examples: [
    { title: '成功', code: "notification.success({ title: '已上传', content: '文件保存成功' })" },
    { title: '错误', code: "notification.error({ title: '保存失败', content: '网络中断' })" },
    { title: '常驻', code: "notification.open({ title: '提醒', duration: 0 })" },
    { title: 'RTL', code: "notification.info({ title: 'مرحبا', content: 'نص', direction: 'rtl' })" },
    {
      title: '全局配置',
      code: "notification.config({ direction: 'rtl', getPopupContainer: () => document.getElementById('app')! })",
    },
  ],
} as const;
