/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Switch',
  category: 'input',
  description: '开关选择器，表示两种互斥状态的即时切换，支持加载态与自定义文案。',
  props: [
    { name: 'value', type: 'boolean', default: 'undefined', desc: '受控值；提供则为受控（对齐 Semi checked）' },
    { name: 'defaultValue', type: 'boolean', default: 'false', desc: '非受控初始值（对齐 Semi defaultChecked）' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'loading', type: 'boolean', default: 'false', desc: '加载态，锁定交互并展示 spinner' },
    { name: 'checkedText', type: 'string | Snippet', default: 'undefined', desc: '开态内嵌文字/图标（size=small 时不渲染）' },
    { name: 'uncheckedText', type: 'string | Snippet', default: 'undefined', desc: '关态内嵌文字/图标（size=small 时不渲染）' },
    { name: 'onChange', type: '(checked: boolean, event: Event) => void', default: 'undefined', desc: '变更回调（对齐 Semi (checked, e)）' },
    { name: 'onMouseEnter', type: '(e: MouseEvent) => void', default: 'undefined', desc: '鼠标进入' },
    { name: 'onMouseLeave', type: '(e: MouseEvent) => void', default: 'undefined', desc: '鼠标离开' },
    { name: 'style', type: 'string', default: 'undefined', desc: '透传根元素内联样式' },
    { name: 'class', type: 'string', default: 'undefined', desc: '透传根元素 class（对齐 Semi className）' },
    { name: 'id', type: 'string', default: 'undefined' },
    { name: 'aria-label', type: 'string', default: 'undefined' },
    { name: 'aria-labelledby', type: 'string', default: 'undefined', desc: '关联外部可见文本 id（优先于 aria-label）' },
    { name: 'aria-describedby', type: 'string', default: 'undefined' },
    { name: 'aria-errormessage', type: 'string', default: 'undefined' },
    { name: 'aria-invalid', type: 'boolean', default: 'undefined', desc: '校验失败态（外层 Form 表达）' },
  ],
  i18nKeys: [],
  a11y: {
    role: 'switch',
    keyboard: ['Enter', 'Space'],
    notes: [
      '根元素 <button role="switch">（APG Switch Pattern；较 Semi 的 div+隐藏 input 更优，故保留）',
      'aria-checked 反映状态；loading 时 aria-busy',
    ],
  },
  tokens: [
    '--cd-switch-width-default',
    '--cd-switch-width-small',
    '--cd-switch-width-large',
    '--cd-switch-height-default',
    '--cd-switch-height-small',
    '--cd-switch-height-large',
    '--cd-switch-radius',
    '--cd-switch-border-width',
    '--cd-switch-bg-off',
    '--cd-switch-bg-off-hover',
    '--cd-switch-bg-off-active',
    '--cd-switch-bg-on',
    '--cd-switch-bg-on-hover',
    '--cd-switch-bg-on-active',
    '--cd-switch-bg-on-disabled',
    '--cd-switch-border-off',
    '--cd-switch-knob-bg',
    '--cd-switch-knob-shadow',
    '--cd-switch-knob-size',
    '--cd-switch-knob-size-large',
    '--cd-switch-knob-size-small',
    '--cd-switch-knob-padding',
    '--cd-switch-knob-padding-large',
    '--cd-switch-knob-padding-small',
    '--cd-switch-knob-tx-off',
    '--cd-switch-knob-tx-on',
    '--cd-switch-knob-tx-off-large',
    '--cd-switch-knob-tx-on-large',
    '--cd-switch-knob-tx-off-small',
    '--cd-switch-knob-tx-on-small',
    '--cd-switch-text-width',
    '--cd-switch-text-width-large',
    '--cd-switch-text-font-size',
    '--cd-switch-text-font-size-large',
    '--cd-switch-checked-text-color',
    '--cd-switch-unchecked-text-color',
    '--cd-switch-bg-spin-off',
    '--cd-switch-bg-spin-on',
    '--cd-switch-spin-track',
    '--cd-switch-spin-indicator',
    '--cd-switch-spin-duration',
    '--cd-switch-outline-focus',
    '--cd-switch-outline-width',
    '--cd-switch-transition-duration',
    '--cd-switch-transition-easing',
  ],
} as const;
