/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Switch',
  category: 'input',
  description: '开关选择器，表示两种互斥状态的即时切换，支持加载态与自定义文案。',
  props: [
    { name: 'value', type: 'boolean', default: 'undefined', desc: '受控值；提供则为受控' },
    { name: 'defaultValue', type: 'boolean', default: 'false', desc: '非受控初始值' },
    { name: 'checkedValue', type: 'string | number | boolean', default: 'true', desc: '开态映射的实际值（onChange.nativeValue 与表单提交值）' },
    { name: 'uncheckedValue', type: 'string | number | boolean', default: 'false', desc: '关态映射的实际值' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'loading', type: 'boolean', default: 'false' },
    { name: 'checkedChildren', type: 'string | Snippet', default: 'undefined', desc: '开态内嵌文字/图标（size=small 时无效）' },
    { name: 'uncheckedChildren', type: 'string | Snippet', default: 'undefined', desc: '关态内嵌文字/图标（size=small 时无效）' },
    { name: 'checkedText', type: 'string', default: 'undefined', desc: 'checked 时显示的文字（checkedChildren 的字符串别名；size=small 时无效）' },
    { name: 'uncheckedText', type: 'string', default: 'undefined', desc: 'unchecked 时显示的文字（size=small 时无效）' },
    { name: 'checkedContent', type: 'Snippet', default: 'undefined', desc: 'checked 时的 Snippet（checkedChildren 的 Snippet 别名；size=small 时无效）' },
    { name: 'uncheckedContent', type: 'Snippet', default: 'undefined', desc: 'unchecked 时的 Snippet（size=small 时无效）' },
    { name: 'name', type: 'string', default: 'undefined' },
    { name: 'required', type: 'boolean', default: 'false', desc: '表单必填校验（须为开态）' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'ariaLabelledby', type: 'string', default: 'undefined', desc: '关联外部可见文本 id（优先于 ariaLabel）' },
    { name: 'announceOnChange', type: 'boolean', default: 'false', desc: '切换后用 live region 播报新状态' },
    { name: 'autofocus', type: 'boolean', default: 'false', desc: '挂载后自动聚焦' },
    { name: 'onChange', type: '(v: boolean, detail?: { value: boolean; nativeValue: string|number|boolean; event: Event }) => void', default: 'undefined' },
    { name: 'onFocus', type: '(event: FocusEvent) => void', default: 'undefined', desc: '获得焦点' },
    { name: 'onBlur', type: '(event: FocusEvent) => void', default: 'undefined', desc: '失去焦点' },
    { name: 'onKeydown', type: '(event: KeyboardEvent) => void', default: 'undefined', desc: '键盘按下（自定义快捷键扩展）' },
    { name: 'onMouseEnter', type: '(e: MouseEvent) => void', default: 'undefined', desc: '鼠标进入' },
    { name: 'onMouseLeave', type: '(e: MouseEvent) => void', default: 'undefined', desc: '鼠标离开' },
  ],
  i18nKeys: [
    'Switch.on',
    'Switch.off',
    'Switch.loading',
    'Switch.announceChecked',
    'Switch.announceUnchecked',
  ],
  a11y: {
    role: 'switch',
    keyboard: ['Enter', 'Space'],
    notes: ['原生 button role=switch', 'aria-checked 反映状态', 'loading 时 aria-busy'],
  },
  tokens: [
    '--cd-switch-width-default',
    '--cd-switch-width-small',
    '--cd-switch-width-large',
    '--cd-switch-height-default',
    '--cd-switch-height-small',
    '--cd-switch-height-large',
    '--cd-switch-radius',
    '--cd-switch-bg-off',
    '--cd-switch-bg-on',
    '--cd-switch-bg-on-warning',
    '--cd-switch-bg-on-error',
    '--cd-switch-knob-bg',
    '--cd-switch-label-color',
    '--cd-switch-label-font-size',
    '--cd-switch-label-padding',
    '--cd-switch-label-padding-start',
    '--cd-switch-label-padding-end',
    '--cd-switch-outline-focus',
    '--cd-switch-transition-duration',
    '--cd-switch-transition-easing',
    '--cd-switch-spinner-track',
    '--cd-switch-spinner-indicator',
    '--cd-switch-spinner-duration',
  ],
} as const;
