/**
 * Aggregate every component `meta.ts` into a single machine-readable
 * `dist/components.json` (+ a `dist/components.d.ts` type declaration),
 * so IDE plugins / doc generators / AI tools have one entry point.
 *
 * See specs/00-foundation/ai-friendly.spec.md §2.
 *
 * Run via `pnpm --filter @chenzy-design/svelte build:meta`
 * (chained after `svelte-package` in the package `build` script).
 *
 * This script only reads the plain `as const` meta objects; it pulls in no
 * Svelte runtime, so it runs cleanly under `tsx`.
 */
import { mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');
const srcDir = resolve(pkgRoot, 'src');
const outDir = resolve(pkgRoot, 'dist');

/**
 * Auto-discover every component meta by scanning `src/<comp>/*meta.ts` and
 * collecting all exports that look like a component meta (an object with a
 * string `name`). This captures both the default `meta` export and secondary
 * metas in the same file (e.g. `inputGroupMeta`, `cardGroupMeta`) as well as
 * sibling meta files (`taggroup-meta.ts`, `range-meta.ts`), with zero manual
 * upkeep — a new component's `meta.ts` shows up automatically, so it can never
 * silently go missing from docs (which previously caused 404 detail pages).
 */
function isComponentMeta(value: unknown): value is { name: string } {
  return (
    typeof value === 'object' &&
    value !== null &&
    typeof (value as { name?: unknown }).name === 'string' &&
    // meta objects carry a `category`; this excludes unrelated string-named exports.
    typeof (value as { category?: unknown }).category === 'string'
  );
}

/** Every `*meta.ts` file under `src/<comp>/`, sorted for deterministic output. */
function findMetaFiles(): string[] {
  const files: string[] = [];
  for (const comp of readdirSync(srcDir, { withFileTypes: true })) {
    if (!comp.isDirectory()) continue;
    const compDir = resolve(srcDir, comp.name);
    for (const entry of readdirSync(compDir, { withFileTypes: true })) {
      if (entry.isFile() && /meta\.ts$/.test(entry.name)) {
        files.push(resolve(compDir, entry.name));
      }
    }
  }
  return files.sort();
}

const metaFiles = findMetaFiles();
const metas: Array<{ name: string }> = [];
for (const file of metaFiles) {
  const mod = (await import(pathToFileURL(file).href)) as Record<string, unknown>;
  for (const exported of Object.values(mod)) {
    if (isComponentMeta(exported)) metas.push(exported);
  }
}

/** Aggregate keyed by the component's display name (e.g. `Button`). */
const components: Record<string, unknown> = {};
for (const m of metas) {
  const name = (m as { name: string }).name;
  if (!name) throw new Error('Encountered a meta without a `name` field.');
  if (name in components) {
    throw new Error(`Duplicate component name in metas: ${name}`);
  }
  components[name] = m;
}

const manifest = {
  version: '1',
  generatedFrom: '@chenzy-design/svelte component meta.ts files',
  generatedAt: new Date().toISOString(),
  count: Object.keys(components).length,
  components,
};

mkdirSync(outDir, { recursive: true });

const jsonPath = resolve(outDir, 'components.json');
writeFileSync(jsonPath, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

/**
 * Emit a `.d.ts` so consumers get type-safe access. The literal component-name
 * union and token-key union are the parts AI/IDE tooling cares about most.
 */
const componentNames = Object.keys(components).sort();
const tokenKeys = Array.from(
  new Set(
    metas.flatMap((m) =>
      Array.isArray((m as { tokens?: unknown }).tokens)
        ? ((m as { tokens: string[] }).tokens)
        : [],
    ),
  ),
).sort();

const dtsLines: string[] = [
  '// Generated by scripts/build-components-json.ts. Do not edit by hand.',
  '',
  '/** Single prop entry in a component meta. */',
  'export interface ComponentPropMeta {',
  '  name: string;',
  '  type: string;',
  '  default?: string;',
  '  desc?: string;',
  '}',
  '',
  '/** Aggregated metadata for one component. Mirrors `src/<comp>/meta.ts`. */',
  'export interface ComponentMeta {',
  '  name: string;',
  "  category: 'ai' | 'basic' | 'plus' | 'input' | 'navigation' | 'show' | 'feedback' | 'other';",
  '  description: string;',
  '  props?: ComponentPropMeta[];',
  '  subComponents?: Array<{ name?: string; props?: ComponentPropMeta[]; [k: string]: unknown }>;',
  '  events?: Array<{ name: string; payload?: string; desc?: string }>;',
  '  slots?: Array<{ name: string; desc?: string }>;',
  '  a11y?: Record<string, unknown>;',
  '  tokens?: string[];',
  '  examples?: Array<{ title: string; code: string }>;',
  '  [k: string]: unknown;',
  '}',
  '',
  '/** Display names of every component in the manifest. */',
  `export type ComponentName =\n${componentNames.map((n) => `  | '${n}'`).join('\n')};`,
  '',
  '/** Design-token key prefixes referenced across all component metas. */',
  `export type TokenKey =\n${tokenKeys.map((t) => `  | '${t}'`).join('\n')};`,
  '',
  '/** Shape of the generated `components.json` manifest. */',
  'export interface ComponentsManifest {',
  '  version: string;',
  '  generatedFrom: string;',
  '  generatedAt: string;',
  '  count: number;',
  '  components: Record<ComponentName, ComponentMeta>;',
  '}',
  '',
  'declare const manifest: ComponentsManifest;',
  'export default manifest;',
  '',
];

const dtsPath = resolve(outDir, 'components.d.ts');
writeFileSync(dtsPath, dtsLines.join('\n'), 'utf8');

console.log(
  `[build:meta] wrote ${manifest.count} components -> ${jsonPath}\n` +
    `[build:meta] wrote types -> ${dtsPath}`,
);
