/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 * 严格对齐 Semi Design semi-ui/tooltip 的 API 表。
 */
export const meta = {
  name: 'Tooltip',
  category: 'show',
  description:
    '文字提示，鼠标悬停/聚焦/点击触发元素时展示简短说明。固定深色浮层，支持 12 方位 position、SVG 箭头、延迟、custom 完全受控触发与 condition 条件触发，浮层命令式定位（对齐 Semi）。',
  props: [
    { name: 'content', type: 'string | Snippet', default: 'undefined', desc: '提示内容，为空不显示' },
    { name: 'visible', type: 'boolean', default: 'undefined', desc: '受控显隐（配合 trigger=custom）' },
    { name: 'defaultVisible', type: 'boolean', default: 'false', desc: '非受控初始显隐' },
    {
      name: 'trigger',
      type: "'hover'|'focus'|'click'|'custom'|Array<...>",
      default: "'hover'",
      desc: "触发方式，可组合；'custom' 完全受控（仅 visible + onVisibleChange）",
    },
    {
      name: 'position',
      type: "'top'|'topLeft'|'topRight'|'left'|'leftTop'|'leftBottom'|'right'|'rightTop'|'rightBottom'|'bottom'|'bottomLeft'|'bottomRight'|'leftTopOver'|'rightTopOver'",
      default: "'top'",
      desc: '弹出方位（Semi 12 方位命名 + 2 Over）',
    },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '视口溢出时翻转到对侧' },
    { name: 'spacing', type: 'number | { x: number; y: number }', default: '8', desc: '浮层与触发器距离(px)' },
    {
      name: 'margin',
      type: 'number | { marginLeft; marginTop; marginRight; marginBottom }',
      default: '0',
      desc: '计算溢出翻转时增加的冗余安全边距',
    },
    { name: 'mouseEnterDelay', type: 'number', default: '50', desc: 'hover 进入延迟(ms)' },
    { name: 'mouseLeaveDelay', type: 'number', default: '50', desc: 'hover 离开延迟(ms)' },
    { name: 'showArrow', type: 'boolean | Snippet', default: 'true', desc: '是否显示箭头，或传自定义箭头 Snippet' },
    {
      name: 'arrowPointAtCenter',
      type: 'boolean',
      default: 'true',
      desc: '箭头是否指向触发元素中心（需 showArrow）',
    },
    {
      name: 'arrowStyle',
      type: '{ borderColor?; backgroundColor?; borderOpacity? }',
      default: 'undefined',
      desc: '箭头颜色定制（border/bg/opacity）',
    },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用触发' },
    {
      name: 'condition',
      type: 'boolean',
      default: 'true',
      desc: 'false 时不响应 hover/click/focus 触发（custom 不受影响）',
    },
    { name: 'clickToHide', type: 'boolean', default: 'false', desc: 'hover 触发下点击浮层内部即关闭' },
    { name: 'keepDOM', type: 'boolean', default: 'false', desc: '关闭时保留浮层 DOM 不销毁（--hidden 隐藏）' },
    { name: 'disableFocusListener', type: 'boolean', default: 'false', desc: 'hover 触发时不响应键盘 focus 显隐' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '是否展示进出场动画，reduced-motion 退化' },
    { name: 'zIndex', type: 'number', default: 'undefined', desc: '浮层 z-index（覆盖 token --cd-tooltip-z）' },
    { name: 'class', type: 'string', default: "''", desc: '浮层自定义类名' },
    { name: 'style', type: 'string', default: "''", desc: '浮层自定义内联样式（如覆盖 max-width）' },
    { name: 'stopPropagation', type: 'boolean', default: 'false', desc: '阻止浮层上的点击事件冒泡' },
    { name: 'closeOnEsc', type: 'boolean', default: 'true', desc: 'Esc 关闭浮层（WCAG 1.4.13）' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: '显示时阻止页面滚动' },
    { name: 'rePosKey', type: 'string | number', default: 'undefined', desc: '更新该值手动触发浮层重新定位' },
    {
      name: 'getPopupContainer',
      type: '() => HTMLElement | null | undefined',
      default: 'undefined',
      desc: '自定义浮层挂载容器（缺省回退 ConfigProvider 全局，再回退 body）',
    },
    { name: 'onVisibleChange', type: '(visible: boolean) => void', default: 'undefined', desc: '显隐切换回调' },
    { name: 'onClickOutSide', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击浮层与触发器外部的回调（仅 custom/click）' },
    { name: 'afterClose', type: '() => void', default: 'undefined', desc: '浮层完全关闭后的回调' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '触发元素（必填）' },
  ],
  a11y: {
    role: 'tooltip',
    keyboard: ['Escape'],
    notes: [
      '浮层 role=tooltip，使用 useId 生成唯一 id',
      '触发元素 visible 时加 aria-describedby 指向浮层',
      'focus 触发支持键盘聚焦展示；closeOnEsc 时 click/custom 触发用 useDismiss 处理 Escape 与外部点击',
      'custom 触发不绑定 hover/click/focus，显隐完全由受控 visible + onVisibleChange 控制',
      'condition=false 时禁止一切自动触发（custom 不受影响）',
    ],
  },
  tokens: [
    '--cd-tooltip-bg',
    '--cd-tooltip-color',
    '--cd-tooltip-radius',
    '--cd-tooltip-padding',
    '--cd-tooltip-font-size',
    '--cd-tooltip-line-height',
    '--cd-tooltip-max-width',
    '--cd-tooltip-z',
    '--cd-tooltip-motion-duration',
    '--cd-tooltip-motion-easing',
    // Semi 全量对齐 token（semi-foundation/tooltip/variables.scss）
    '--cd-color-tooltip-bg-default',
    '--cd-color-tooltip-text-default',
    '--cd-width-tooltip',
    '--cd-width-tooltip-arrow',
    '--cd-height-tooltip-arrow',
    '--cd-width-tooltip-arrow-vertical',
    '--cd-height-tooltip-arrow-vertical',
    '--cd-radius-tooltip',
    '--cd-tooltip-*',
    '--cd-motion-*',
  ],
} as const;
