/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 * 严格对齐 Semi Design semi-ui/tooltip 的 API 表。
 */
export const meta = {
  name: 'Tooltip',
  category: 'show',
  description:
    '文字提示，鼠标悬停/聚焦/点击/右键触发元素时展示简短说明。固定深色浮层（grey-7），DOM 严格对齐 Semi：.cd-tooltip-wrapper[x-placement] > .cd-tooltip-content + 单 path 箭头 .cd-tooltip-icon-arrow（fill=currentColor）。支持 12 方位 position、hover/focus/click/custom/contextMenu 触发、延迟、custom 完全受控、condition 条件触发，浮层命令式定位（对齐 Semi）。prefixCls 机制供 Popover/Popconfirm 复用切换前缀。',
  props: [
    { name: 'content', type: 'string | Snippet', default: 'undefined', desc: '提示内容，为空不显示' },
    { name: 'visible', type: 'boolean', default: 'undefined', desc: '受控显隐（配合 trigger=custom）' },
    { name: 'defaultVisible', type: 'boolean', default: 'false', desc: '非受控初始显隐' },
    {
      name: 'trigger',
      type: "'hover'|'focus'|'click'|'custom'|'contextMenu'|Array<...>",
      default: "'hover'",
      desc: "触发方式，可组合；'custom' 完全受控（仅 visible + onVisibleChange）；'contextMenu' 右键触发",
    },
    {
      name: 'position',
      type: "'top'|'topLeft'|'topRight'|'left'|'leftTop'|'leftBottom'|'right'|'rightTop'|'rightBottom'|'bottom'|'bottomLeft'|'bottomRight'|'leftTopOver'|'rightTopOver'",
      default: "'top'",
      desc: '弹出方位（Semi 12 方位命名 + 2 Over）',
    },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '视口溢出时翻转到对侧' },
    { name: 'spacing', type: 'number | { x: number; y: number }', default: '8', desc: '浮层与触发器距离(px)' },
    {
      name: 'margin',
      type: 'number | { marginLeft; marginTop; marginRight; marginBottom }',
      default: '0',
      desc: '计算溢出翻转时增加的冗余安全边距',
    },
    { name: 'mouseEnterDelay', type: 'number', default: '50', desc: 'hover 进入延迟(ms)' },
    { name: 'mouseLeaveDelay', type: 'number', default: '50', desc: 'hover 离开延迟(ms)' },
    { name: 'showArrow', type: 'boolean | Snippet', default: 'true', desc: '是否显示箭头，或传自定义箭头 Snippet' },
    {
      name: 'arrowPointAtCenter',
      type: 'boolean',
      default: 'true',
      desc: '箭头是否指向触发元素中心（需 showArrow）',
    },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用触发' },
    {
      name: 'condition',
      type: 'boolean',
      default: 'true',
      desc: 'false 时不响应 hover/click/focus 触发（custom 不受影响）',
    },
    { name: 'clickToHide', type: 'boolean', default: 'false', desc: 'hover 触发下点击浮层内部即关闭' },
    { name: 'keepDOM', type: 'boolean', default: 'false', desc: '关闭时保留浮层 DOM 不销毁（--hidden 隐藏）' },
    { name: 'disableFocusListener', type: 'boolean', default: 'false', desc: 'hover 触发时不响应键盘 focus 显隐' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '是否展示进出场动画，reduced-motion 退化' },
    { name: 'transformFromCenter', type: 'boolean', default: 'true', desc: '是否从触发元素中心处变换（仅影响动效 transform-origin，一般无需改动）' },
    { name: 'zIndex', type: 'number', default: 'undefined', desc: '浮层 z-index（覆盖 token --cd-z-tooltip，=1060）' },
    { name: 'prefixCls', type: 'string', default: "'cd-tooltip'", desc: '浮层 wrapper 类名前缀（对齐 Semi prefixCls）；Popover 传 cd-popover 切换整套前缀与视觉' },
    { name: 'wrapperClassName', type: 'string', default: "''", desc: '触发器包裹 span 的类名（对齐 Semi wrapperClassName）' },
    { name: 'wrapperId', type: 'string', default: 'undefined', desc: '浮层 wrapper 节点 id（对齐 Semi wrapperId）；不设则自动生成，trigger 的 aria 指向它' },
    { name: 'class', type: 'string', default: "''", desc: '浮层自定义类名' },
    { name: 'style', type: 'string', default: "''", desc: '浮层自定义内联样式（如覆盖 max-width）' },
    { name: 'stopPropagation', type: 'boolean', default: 'false', desc: '阻止浮层上的点击事件冒泡' },
    { name: 'closeOnEsc', type: 'boolean', default: 'true', desc: 'Esc 关闭浮层（WCAG 1.4.13）' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: '显示时阻止页面滚动' },
    { name: 'rePosKey', type: 'string | number', default: 'undefined', desc: '更新该值手动触发浮层重新定位' },
    {
      name: 'getPopupContainer',
      type: '() => HTMLElement | null | undefined',
      default: 'undefined',
      desc: '自定义浮层挂载容器（缺省回退 ConfigProvider 全局，再回退 body）',
    },
    { name: 'onVisibleChange', type: '(visible: boolean) => void', default: 'undefined', desc: '显隐切换回调' },
    { name: 'onClickOutSide', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击浮层与触发器外部的回调（仅 custom/click）' },
    { name: 'onEscKeyDown', type: '(e: KeyboardEvent) => void', default: 'undefined', desc: '浮层展示时按 Esc 键的回调（与 closeOnEsc 相互独立）' },
    { name: 'afterClose', type: '() => void', default: 'undefined', desc: '浮层完全关闭后的回调' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '触发元素（必填）' },
  ],
  a11y: {
    role: 'tooltip',
    keyboard: ['Escape'],
    notes: [
      '浮层 role=tooltip，使用 useId 生成唯一 id',
      '触发元素 visible 时加 aria-describedby 指向浮层',
      'focus 触发支持键盘聚焦展示；closeOnEsc 时 click/custom 触发用 useDismiss 处理 Escape 与外部点击',
      'custom 触发不绑定 hover/click/focus，显隐完全由受控 visible + onVisibleChange 控制',
      'condition=false 时禁止一切自动触发（custom 不受影响）',
    ],
  },
  tokens: [
    // 严格对齐 Semi（semi-foundation/tooltip/variables.scss + animation.scss），
    // 组件 CSS 直接消费，无中间变量层（已移除 tooltip-bg/color/radius/padding… 中间变量）。
    '--cd-color-tooltip-bg-default',
    '--cd-color-tooltip-text-default',
    '--cd-color-tooltip-icon-default',
    '--cd-color-tooltip-arrow-icon-default',
    '--cd-radius-tooltip',
    '--cd-font-tooltip-fontsize',
    '--cd-width-tooltip',
    '--cd-width-tooltip-arrow',
    '--cd-height-tooltip-arrow',
    '--cd-width-tooltip-arrow-vertical',
    '--cd-height-tooltip-arrow-vertical',
    '--cd-spacing-tooltip-content-paddingtop',
    '--cd-spacing-tooltip-content-paddingright',
    '--cd-spacing-tooltip-content-paddingbottom',
    '--cd-spacing-tooltip-content-paddingleft',
    '--cd-spacing-tooltip-arrow-offset-x',
    '--cd-spacing-tooltip-arrow-offset-y',
    '--cd-spacing-tooltip-arrow-adjusted-offset-x',
    '--cd-spacing-tooltip-arrow-adjusted-offset-y',
    '--cd-filter-tooltip-bg',
    '--cd-z-tooltip',
    // 进出场动画（Semi animation.scss，100ms + cubic-bezier）+ zoom 关键帧参数
    '--cd-animation-duration-tooltip-in',
    '--cd-animation-duration-tooltip-out',
    '--cd-animation-function-tooltip-in',
    '--cd-animation-function-tooltip-out',
    '--cd-tooltip-motion-zoom-scale-from',
    '--cd-tooltip-motion-zoom-opacity-from',
    '--cd-tooltip-motion-zoom-opacity-to',
    '--cd-tooltip-horizontal-rate',
    '--cd-tooltip-vertical-rate',
  ],
} as const;
