/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Breadcrumb',
  category: 'navigation',
  description:
    '面包屑导航，展示当前页面在层级结构中的位置。字段/API 对齐 Semi：routes 元素为 Route 对象（{name, path, href, icon}）或纯字符串。支持数据驱动 routes 与声明式 Item 两种用法。',
  props: [
    {
      name: 'routes',
      type: '(BreadcrumbRoute | string)[]',
      default: '[]',
      desc: '数据驱动的路由项，元素为 Route 对象或纯字符串（字符串即 name）；最后一项为当前页（aria-current=page）',
    },
    { name: 'separator', type: 'string', default: "'/'", desc: '分隔符文本' },
    { name: 'maxItemCount', type: 'number', default: '4', desc: '超出时中间折叠（对齐 Semi；<=0 不折叠）' },
    {
      name: 'showTooltip',
      type: "boolean | { width?: number|string; ellipsisPos?: 'end'|'middle'; opts?: object }",
      default: 'false',
      desc: '项文本超出 width（默认 150）被截断时，hover 用 Tooltip 展示完整名；对象配置 width/ellipsisPos（对齐 Semi showToolTipProps）',
    },
    {
      name: 'moreType',
      type: "'default'|'popover'",
      default: "'default'",
      desc: '折叠 … 的浮层类型（对齐 Semi）：default 点击三点图标就地展开全部；popover 悬浮弹出可点击跳转的折叠项菜单',
    },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    {
      name: 'ariaLabel',
      type: 'string',
      default: 'undefined',
      desc: '无障碍标签，默认取 i18n Breadcrumb.ariaLabel；传入覆盖（对齐 Semi aria-label）',
    },
    { name: 'style', type: 'string', default: 'undefined', desc: '根节点内联样式（对齐 Semi style）' },
    {
      name: 'compact',
      type: 'boolean',
      default: 'true',
      desc: '紧凑模式；false 时根元素附加 cd-breadcrumb--loose 类（更大字号/间距）',
    },
    {
      name: 'autoCollapse',
      type: 'boolean',
      default: 'true',
      desc: '超出 maxItemCount 时是否自动折叠；false 时始终展示全部项',
    },
    {
      name: 'activeIndex',
      type: 'number',
      default: 'undefined',
      desc: '受控选中项索引（配合 onClick 使用，令对应项高亮）',
    },
    {
      name: 'renderItem',
      type: '(route: BreadcrumbRoute, index: number, isLast: boolean) => Snippet',
      default: 'undefined',
      desc: '自定义路由项渲染（routes 模式）；传入时替换默认的链接/文本/当前页渲染逻辑',
    },
    {
      name: 'renderMore',
      type: '(restItems: CollapsedRoute[]) => Snippet',
      default: 'undefined',
      desc: '自定义折叠 … 区域渲染；传入时接管折叠展示（替代 moreType 内置浮层），参数为被折叠路由列表',
    },
    { name: 'class', type: 'string', default: "''" },
    {
      name: 'children',
      type: 'Snippet',
      default: 'undefined',
      desc: '声明式 <Breadcrumb.Item> 列表；项间分隔符按 separator 纯 CSS 自动插入，最后一项后无分隔符',
    },
    {
      name: 'onClick',
      type: '(route: BreadcrumbRoute, index: number) => void',
      default: 'undefined',
    },
  ],
  subComponents: [
    {
      name: 'BreadcrumbItem',
      usage: '<Breadcrumb.Item> 或 <BreadcrumbItem>，置于 <Breadcrumb> 的 children 内',
      desc: '声明式面包屑项；项间分隔符由父级纯 CSS 自动插入，最后一项自动渲染为当前页（不可点 + aria-current=page）',
      props: [
        { name: 'href', type: 'string', default: 'undefined', desc: '链接地址；最后一项忽略 href' },
        {
          name: 'separator',
          type: 'string',
          default: 'undefined',
          desc: '覆盖父级 separator，仅对本项末尾分隔符生效（通过内联 CSS 变量实现）',
        },
        {
          name: 'noLink',
          type: 'boolean',
          default: 'false',
          desc: '禁止链接/按钮行为，渲染为普通 span（不可点击）；忽略 href 和 onClick；末项始终无链接',
        },
        {
          name: 'icon',
          type: 'Snippet',
          default: 'undefined',
          desc: '项前置图标 snippet，渲染在 children 之前',
        },
        { name: 'class', type: 'string', default: "''" },
        { name: 'children', type: 'Snippet', default: 'undefined' },
        {
          name: 'onClick',
          type: '(e: MouseEvent) => void',
          default: 'undefined',
          desc: '点击/键盘激活回调；最后一项及 noLink=true 时不触发',
        },
      ],
    },
  ],
  a11y: {
    role: 'navigation',
    keyboard: ['Enter', 'Space'],
    notes: [
      'nav[aria-label] 包裹 ol 有序列表',
      '最后一项 aria-current=page，不可点击',
      '无 href 的中间项用 role=link + tabindex=0 + 键盘可激活',
      '分隔符 aria-hidden=true',
    ],
  },
  tokens: [
    // 全量对齐 Semi breadcrumb/variables.scss（16 个）
    '--cd-spacing-breadcrumb-item-wrap-marginy',
    '--cd-spacing-breadcrumb-item-wrap-marginright',
    '--cd-spacing-breadcrumb-item-marginright',
    '--cd-spacing-breadcrumb-item-text-marginleft',
    '--cd-spacing-breadcrumb-restitem-marginright',
    '--cd-color-breadcrumb-default-text-default',
    '--cd-color-breadcrumb-default-text-hover',
    '--cd-color-breadcrumb-default-text-active',
    '--cd-color-breadcrumb-active-text-default',
    '--cd-color-breadcrumb-active-text-active',
    '--cd-color-breadcrumb-sepearator-default-icon-default',
    '--cd-color-breadcrumb-restitem-text-default',
    '--cd-font-breadcrumb-default-fontweight',
    '--cd-font-breadcrumb-active-fontweight',
    '--cd-font-breadcrumb-compact-fontsize',
    '--cd-font-breadcrumb-loose-fontsize',
    // chenzy-design 组件消费的补充 token
    '--cd-breadcrumb-color',
    '--cd-breadcrumb-color-link',
    '--cd-breadcrumb-color-link-hover',
    '--cd-breadcrumb-color-link-active',
    '--cd-breadcrumb-color-active',
    '--cd-breadcrumb-restitem-color',
    '--cd-breadcrumb-active-weight',
    '--cd-breadcrumb-separator-color',
    '--cd-breadcrumb-gap',
    '--cd-breadcrumb-font-size',
    '--cd-breadcrumb-font-size-compact',
    '--cd-breadcrumb-loose-font-size',
    '--cd-breadcrumb-loose-letter-spacing',
    '--cd-breadcrumb-loose-gap',
    '--cd-breadcrumb-item-max-width',
    // 通用
    '--cd-focus-ring',
    '--cd-border-radius-small',
  ],
} as const;
