/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 * 严格对齐 Semi Design（fileList/defaultFileList 受控、listType list/picture/none、FileCard 双分支）。
 */
export const meta = {
  name: 'Upload',
  category: 'input',
  description: '文件上传，严格对齐 Semi Design：点击/拖拽选择、文件卡片列表（list）与照片墙（picture）、真实 XHR 上传、裁切、目录上传。',
  props: [
    { name: 'fileList', type: 'UploadFileItem[]', default: 'undefined', desc: "受控文件列表（对齐 Semi fileList）；提供则受控。UploadFileItem.status：'wait'|'validating'|'uploading'|'success'|'validateFail'|'uploadFail'；preview?:boolean 控制缩略图；file 即 Semi fileInstance；项级 showReplace/showRetry 覆盖组件级；response/event/validateMessage 对齐 Semi FileItem" },
    { name: 'defaultFileList', type: 'UploadFileItem[]', default: '[]', desc: '非受控初始文件列表（对齐 Semi defaultFileList）' },
    { name: 'accept', type: 'string', default: 'undefined', desc: '接受的文件类型（input accept）' },
    { name: 'multiple', type: 'boolean', default: 'false' },
    { name: 'directory', type: 'boolean', default: 'false', desc: '上传整个目录（webkitdirectory），递归选择目录下所有文件，保留 relativePath（对齐 Semi directory）' },
    { name: 'limit', type: 'number', default: 'undefined', desc: '最大文件数；超出触发 onExceed；limit=1 替换语义' },
    { name: 'maxSize', type: 'number', default: 'undefined', desc: '单文件最大体积（KB）；超限标 validateFail（对齐 Semi maxSize）' },
    { name: 'minSize', type: 'number', default: 'undefined', desc: '单文件最小体积（KB）；过小标 validateFail（对齐 Semi minSize）' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'validateStatus', type: "'default'|'error'|'warning'|'success'", default: "'default'", desc: '组件级校验态（表单联动，影响上传区/边框色）。对齐 Semi validateStatus，枚举含 success' },
    { name: 'listType', type: "'list'|'picture'|'none'", default: "'list'", desc: '文件列表展示类型（对齐 Semi listType）：list 文本卡片、picture 照片墙、none 不渲染列表' },
    { name: 'draggable', type: 'boolean', default: 'false', desc: 'true 渲染拖拽区，false 渲染按钮（对齐 Semi draggable）' },
    { name: 'action', type: 'string', default: 'undefined', desc: '上传地址；有则选文件后自动 XHR 上传' },
    { name: 'name', type: 'string', default: "'file'", desc: '表单字段名（对齐 Semi name）' },
    { name: 'fileName', type: 'string', default: 'undefined', desc: '同 name，避免 Form.Upload 中 props 冲突（对齐 Semi fileName）；优先于 name' },
    { name: 'headers', type: 'Record<string,string> | ((file: File) => Record<string,string>)', default: 'undefined', desc: '额外请求头；静态对象或按当前 file 求值的函数（对齐 Semi headers）' },
    { name: 'data', type: 'Record<string,string> | ((file: File) => Record<string,string>)', default: 'undefined', desc: '额外表单字段；静态对象或按当前 file 求值的函数（对齐 Semi data）' },
    { name: 'beforeUpload', type: '(props: { file, fileList }) => boolean | BeforeUploadObjectResult | Promise<...>', default: 'undefined', desc: '上传前钩子（对齐 Semi beforeUpload）：入参 { file, fileList }。返回 false 拒绝；true/undefined 上传；返回富对象 BeforeUploadObjectResult（shouldUpload/autoRemove/status/validateMessage/fileInstance）精细控制。支持异步' },
    { name: 'customRequest', type: '(item: UploadFileItem) => void | Promise<void>', default: 'undefined', desc: '自定义上传实现（对齐 Semi customRequest，优先于 action）' },
    { name: 'afterUpload', type: '(props: { response, file, fileList }) => AfterUploadResult | void', default: 'undefined', desc: '上传成功后钩子（同步返回）：据返回值改该项 status/validateMessage/name/url 或 autoRemove（对齐 Semi afterUpload）' },
    { name: 'onChange', type: '(props: { fileList, currentFile }) => void', default: 'undefined', desc: '文件列表变化回调（对齐 Semi onChange，入参 { fileList, currentFile }）' },
    { name: 'onExceed', type: '(files: File[]) => void', default: 'undefined' },
    { name: 'onSuccess', type: '(responseBody, file, fileList) => void', default: 'undefined', desc: '上传成功回调（对齐 Semi onSuccess(responseBody, file, fileList)）' },
    { name: 'onError', type: '(error, file, fileList, xhr) => void', default: 'undefined', desc: '上传失败回调（对齐 Semi onError(error, file, fileList, xhr)）' },
    { name: 'onProgress', type: '(percent, file, fileList) => void', default: 'undefined', desc: '上传进度回调（仅内置 XHR 上传，对齐 Semi onProgress(percent, file, fileList)）' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '自定义触发器/拖拽区内容' },
    { name: 'showRetry', type: 'boolean', default: 'true', desc: '上传失败是否显示重试按钮（对齐 Semi showRetry）' },
    { name: 'showReplace', type: 'boolean', default: 'false', desc: '已上传（success）项显示替换按钮（对齐 Semi showReplace）；list/picture 均支持' },
    { name: 'showUploadList', type: 'boolean', default: 'true', desc: '是否渲染文件列表（对齐 Semi showUploadList）' },
    { name: 'showClear', type: 'boolean', default: 'true', desc: '是否显示批量清除按钮（对齐 Semi showClear 默认 true）' },
    { name: 'onClear', type: '() => void', default: 'undefined', desc: '清除按钮点击回调' },
    { name: 'beforeClear', type: '(fileList) => boolean | Promise<boolean>', default: 'undefined', desc: '批量清除前钩子（对齐 Semi beforeClear）' },
    { name: 'fileListTitle', type: 'string | false | Snippet<[{ fileList, onClear, clearText }]>', default: 'undefined', desc: '文件列表标题：string=替换标题文字；false=不渲染；Snippet=完全自定义（对齐 Semi fileListTitle）' },
    { name: 'showTooltip', type: "boolean | { type?: 'tooltip'|'popover'; opts?; renderTooltip? }", default: 'true', desc: '文件名超长提示（对齐 Semi showTooltip），经 Typography.Text ellipsis 消费' },
    { name: 'prompt', type: 'string | Snippet', default: 'undefined', desc: '上传区提示内容（对齐 Semi prompt）' },
    { name: 'promptPosition', type: "'left'|'right'|'bottom'", default: "'right'", desc: '提示位置（对齐 Semi promptPosition，默认 right）' },
    { name: 'onDrop', type: '(e, files, fileList) => void', default: 'undefined', desc: '拖拽放下回调（对齐 Semi onDrop(e, files, fileList)）' },
    { name: 'onOpenFileDialog', type: '() => void', default: 'undefined' },
    { name: 'onPreviewClick', type: '(fileItem: UploadFileItem) => void', default: 'undefined', desc: '预览图/卡片点击回调' },
    { name: 'onAcceptInvalid', type: '(files: File[]) => void', default: 'undefined', desc: 'accept 校验失败回调（对齐 Semi onAcceptInvalid）' },
    { name: 'onRetry', type: '(fileItem: UploadFileItem) => void', default: 'undefined' },
    { name: 'onSizeError', type: '(file, fileList) => void', default: 'undefined', desc: '大小校验失败回调（对齐 Semi onSizeError(file, fileList)）' },
    { name: 'validateMessage', type: 'string', default: 'undefined', desc: '校验失败统一文案（对齐 Semi validateMessage）' },
    { name: 'withCredentials', type: 'boolean', default: 'false' },
    { name: 'transformFile', type: '(file: File) => File | Promise<File>', default: 'undefined', desc: '上传前文件转换（对齐 Semi transformFile）' },
    { name: 'dragIcon', type: 'Snippet', default: 'undefined', desc: '拖拽区自定义图标；未传默认云上传图标' },
    { name: 'dragMainText', type: 'string | Snippet', default: 'undefined', desc: '拖拽区主文案' },
    { name: 'dragSubText', type: 'string | Snippet', default: 'undefined', desc: '拖拽区副文案' },
    { name: 'addOnPasting', type: 'boolean', default: 'false', desc: '粘贴添加文件（对齐 Semi addOnPasting）' },
    { name: 'onPastingError', type: '(error: unknown) => void', default: 'undefined', desc: '粘贴上传出错回调（对齐 Semi onPastingError）' },
    { name: 'hotSpotLocation', type: "'start'|'end'", default: "'end'", desc: '照片墙添加瓦片位置（对齐 Semi hotSpotLocation，默认 end）' },
    { name: 'onFileChange', type: '(files: File[]) => void', default: 'undefined', desc: '选中原始 File 列表变化回调（对齐 Semi onFileChange）' },
    { name: 'beforeRemove', type: '(file, fileList) => boolean | Promise<boolean>', default: 'undefined', desc: '移除前钩子（对齐 Semi beforeRemove）' },
    { name: 'onRemove', type: '(currentFile, fileList, currentFileItem) => void', default: 'undefined', desc: '移除后回调（对齐 Semi onRemove）' },
    { name: 'timeout', type: 'number', default: '0', desc: '单文件上传超时（毫秒），>0 启用' },
    { name: 'uploadTrigger', type: "'auto' | 'custom'", default: "'auto'", desc: "上传触发时机（对齐 Semi uploadTrigger）：auto 选即传；custom 停 wait 需 upload() 触发" },
    { name: 'itemStyle', type: 'string | Record<string, string | number>', default: 'undefined', desc: '每个文件卡片自定义 style（对齐 Semi itemStyle）' },
    { name: 'picWidth', type: 'number | string', default: 'undefined', desc: '照片墙缩略图宽度（对齐 Semi picWidth，number→px）' },
    { name: 'picHeight', type: 'number | string', default: 'undefined', desc: '照片墙缩略图高度（对齐 Semi picHeight，number→px）' },
    { name: 'capture', type: "boolean | 'user' | 'environment'", default: 'undefined', desc: '透传给 file input 的 capture 属性（对齐 Semi capture）' },
    { name: 'crop', type: 'boolean | UploadCropProps', default: 'false', desc: '启用图片裁切：image/* 文件先进裁切弹窗（Modal+Cropper）（对齐 Semi crop）' },
    { name: 'beforeCrop', type: '(file: File, fileList: File[]) => boolean | Promise<boolean>', default: 'undefined', desc: '裁切前钩子（对齐 Semi beforeCrop(file, fileList)）' },
    { name: 'onCropError', type: '(err: unknown) => void', default: 'undefined', desc: '裁切失败回调（对齐 Semi onCropError）' },
    { name: 'cropModalProps', type: 'Record<string, unknown>', default: 'undefined', desc: '透传给裁切 Modal 的额外 props（对齐 Semi cropModalProps）' },
    { name: 'renderFileItem', type: 'Snippet<[RenderFileItemProps]>', default: 'undefined', desc: '完全自定义单个文件项渲染（替换 FileCard）。入参对齐 Semi RenderFileItemProps（index/listType/onRemove/onRetry/onReplace/onPreviewClick…）' },
    { name: 'previewFile', type: 'Snippet<[RenderFileItemProps]>', default: 'undefined', desc: '自定义缩略图预览内容（对齐 Semi previewFile）' },
    { name: 'renderThumbnail', type: 'Snippet<[RenderFileItemProps]>', default: 'undefined', desc: '自定义整个缩略图容器（picture，对齐 Semi renderThumbnail）' },
    { name: 'showPicInfo', type: 'boolean', default: 'false', desc: '照片墙图片信息浮层（序号，对齐 Semi showPicInfo）' },
    { name: 'renderPicInfo', type: 'Snippet<[RenderFileItemProps]>', default: 'undefined', desc: '自定义照片墙信息浮层（对齐 Semi renderPicInfo）' },
    { name: 'renderPicPreviewIcon', type: 'Snippet<[RenderFileItemProps]>', default: 'undefined', desc: '自定义照片墙 hover 预览图标（对齐 Semi renderPicPreviewIcon）' },
    { name: 'renderPicClose', type: 'Snippet<[{ className, remove }]>', default: 'undefined', desc: '自定义照片墙关闭按钮（对齐 Semi renderPicClose）' },
    { name: 'renderFileOperation', type: 'Snippet<[RenderFileItemProps]>', default: 'undefined', desc: '自定义文件条操作区（list，对齐 Semi renderFileOperation）' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根容器额外 class（对齐 Semi className）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根容器 style（对齐 Semi style）' },
  ],
  subComponents: [
    {
      name: 'FileCard',
      usage: '内部组件，由 Upload 按 listType 渲染（对齐 Semi fileCard.tsx 分层，非独立对外 API）',
      desc: '单个上传文件项渲染：靠 listType 分 renderPic（picture 照片墙）/renderFile（list 文本卡片）双分支。组件化调用 Button（移除/替换）、Spin（validating）、Progress circle（照片墙上传中）、Typography.Text（文件名 ellipsis）；含三个手写 svg（ErrorSvg/DirectorySvg/ReplaceSvg）。严格对齐 Semi FileCard。',
      props: [],
    },
  ],
  methods: [
    { name: 'upload', type: '() => void', desc: '命令式手动触发上传（配合 uploadTrigger="custom"），批量上传所有 wait 文件（对齐 Semi ref.upload）' },
    { name: 'addFiles', type: '(fileList: FileList | File[]) => void', desc: '命令式添加文件，走完整 accept/limit/校验/上传管线' },
    { name: 'insert', type: '(files: File[], index?: number) => void', desc: '命令式插入文件到指定 index（对齐 Semi insert）' },
    { name: 'openFileDialog', type: '() => void', desc: '命令式打开文件选择器（对齐 Semi openFileDialog）' },
  ],
  a11y: {
    role: 'button',
    keyboard: ['Enter', 'Space'],
    notes: ['隐藏的 file input', '添加区/拖拽区 role=button + 键盘 Enter/Space', 'FileCard 移除/替换/重试按钮有 aria-label', 'uploading Progress 有可访问名'],
  },
  tokens: ['--cd-color-upload-*', '--cd-width-upload-*', '--cd-height-upload-*', '--cd-spacing-upload-*', '--cd-radius-upload-*', '--cd-font-upload-*', '--cd-focus-ring', '--cd-color-warning', '--cd-color-danger', '--cd-spacing-*', '--cd-font-size-*', '--cd-border-radius-*'],
} as const;
