/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Upload',
  category: 'input',
  description: '文件上传，支持点击与拖拽选择、文件列表（名称/大小/状态/移除）。本轮不做真实网络上传。',
  props: [
    { name: 'value', type: 'UploadFileItem[]', default: 'undefined', desc: "受控文件列表；提供则为受控。UploadFileItem.status 对齐 Semi：'wait'|'uploading'|'success'|'validateFail'|'uploadFail'（validateFail=校验失败不可重试，uploadFail=网络失败可重试）；preview?:boolean 控制缩略图预览；file 即 Semi fileInstance" },
    { name: 'defaultValue', type: 'UploadFileItem[]', default: '[]', desc: '非受控初始文件列表' },
    { name: 'accept', type: 'string', default: 'undefined', desc: '接受的文件类型（input accept）' },
    { name: 'multiple', type: 'boolean', default: 'false' },
    { name: 'directory', type: 'boolean', default: 'false', desc: '上传整个目录（webkitdirectory），递归选择目录下所有文件，保留 relativePath' },
    { name: 'limit', type: 'number', default: 'undefined', desc: '最大文件数；超出触发 onExceed' },
    { name: 'maxSize', type: 'number', default: 'undefined', desc: '单文件最大体积（KB）；超限标记 validateFail（校验失败，不可重试）' },
    { name: 'minSize', type: 'number', default: 'undefined', desc: '单文件最小体积（KB）；过小标记 validateFail（校验失败，不可重试）' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'size', type: "'small'|'default'|'large'", default: "'default'", desc: '组件级尺寸（触发按钮/拖拽区/列表项），区别于文件项的 file.size 体积' },
    { name: 'status', type: "'default'|'warning'|'error'", default: "'default'", desc: '组件级校验态（表单联动，影响上传区/边框色），区别于文件项的 file.status 上传进度态' },
    { name: 'listType', type: "'text'|'image'|'picture-card'|'none'", default: 'text', desc: 'image/picture-card 显示缩略图网格' },
    { name: 'drag', type: 'boolean', default: 'false', desc: 'true 渲染拖拽区，false 渲染按钮' },
    { name: 'action', type: 'string', default: 'undefined', desc: '上传地址；有则选文件后自动 XHR 上传' },
    { name: 'uploadName', type: 'string', default: "'file'", desc: '表单字段名' },
    { name: 'headers', type: 'Record<string,string> | ((file: File) => Record<string,string>)', default: 'undefined', desc: '额外请求头；静态对象或按当前 file 求值的函数。对标 Semi headers' },
    { name: 'uploadData', type: 'Record<string,string> | ((file: File) => Record<string,string>)', default: 'undefined', desc: '额外表单字段；静态对象或按当前 file 求值的函数。对标 Semi data' },
    { name: 'concurrency', type: 'number', default: '0', desc: '同时进行的上传数上限；0/不传=不限，超出排队、完成补位' },
    { name: 'beforeUpload', type: '(file: File, fileList: File[]) => boolean | File | Promise<boolean | File>', default: 'undefined', desc: '上传前异步校验/转换：false/reject 跳过该文件，返回 File 替换，true 正常上传' },
    { name: 'customRequest', type: '(item: UploadFileItem) => void | Promise<void>', default: 'undefined', desc: '提供则由外部接管上传（优先于 action）；返回 Promise 时受 concurrency 调度' },
    { name: 'onChange', type: '(list: UploadFileItem[]) => void', default: 'undefined' },
    { name: 'onExceed', type: '(files: File[]) => void', default: 'undefined' },
    { name: 'onSuccess', type: '(response: string, item: UploadFileItem) => void', default: 'undefined' },
    { name: 'onError', type: '(item: UploadFileItem) => void', default: 'undefined' },
    { name: 'onProgress', type: '(percent: number, item: UploadFileItem) => void', default: 'undefined', desc: '单文件上传进度回调（仅内置 XHR 上传触发，customRequest 外部自管）。对标 Semi onProgress' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '自定义触发器内容' },
    { name: 'showRetry', type: 'boolean', default: 'true', desc: '上传失败是否显示重试按钮' },
    { name: 'showReplace', type: 'boolean', default: 'false', desc: '已上传（success）文件项显示"替换"按钮，点击重选文件替换该项；text/picture-card 均支持。对标 Semi showReplace' },
    { name: 'showUploadList', type: 'boolean', default: 'true', desc: '是否渲染文件列表（text 列表/picture 网格）；false 时不渲染列表区但触发器/上传照常。对标 Semi showUploadList' },
    { name: 'showClear', type: 'boolean', default: 'false', desc: '是否显示批量清除按钮（注：Semi 默认 true，本仓库为不破坏现有行为保持 false）' },
    { name: 'onClear', type: '() => void', default: 'undefined', desc: '清除按钮点击回调' },
    { name: 'fileListTitle', type: 'string | false | Snippet<[{ fileList, onClear, clearText }]>', default: 'undefined', desc: '文件列表标题：string=仅替换标题文字（保留默认清空按钮）；false=不渲染；Snippet=完全自定义标题区。对标 Semi fileListTitle' },
    { name: 'showTooltip', type: "boolean | { type?: 'tooltip'|'popover'; opts?: Record<string, unknown>; renderTooltip?: Snippet<[{ content, children }]> }", default: 'true', desc: '文件名提示：boolean=原生 title 属性；对象 type=用 Tooltip/Popover 包裹文件名；renderTooltip 完全接管浮层（对标 Semi (content, children) => ReactNode，传 renderTooltip 时不再套内置组件）。对标 Semi showTooltip' },
    { name: 'prompt', type: 'string | Snippet', default: 'undefined', desc: '上传区提示内容（文字或 Snippet）' },
    { name: 'promptPosition', type: "'left'|'right'|'bottom'", default: "'bottom'", desc: '提示位置：left/right 水平排列，bottom 下方' },
    { name: 'onDrop', type: '(e: DragEvent, files: File[], rejectFiles: File[]) => void', default: 'undefined', desc: '拖拽放下回调' },
    { name: 'onOpenFileDialog', type: '() => void', default: 'undefined', desc: '打开文件选择弹窗时回调' },
    { name: 'onPreviewClick', type: '(fileItem: UploadFileItem) => void', default: 'undefined', desc: '预览图点击回调（image/picture-card listType）' },
    { name: 'onAcceptInvalid', type: '(files: File[]) => void', default: 'undefined', desc: 'accept 校验失败（文件类型不符）的回调' },
    { name: 'onRetry', type: '(file: UploadFileItem) => void', default: 'undefined', desc: '重试回调' },
    { name: 'onSizeError', type: "(file: UploadFileItem, validResult: 'max' | 'min') => void", default: 'undefined', desc: '大小校验失败回调' },
    { name: 'validateMessage', type: 'string', default: 'undefined', desc: '校验失败统一文案（覆盖 i18n 默认文案）' },
    { name: 'withCredentials', type: 'boolean', default: 'false', desc: 'XHR withCredentials（跨域凭证）' },
    { name: 'transformFile', type: '(file: File) => Promise<File>', default: 'undefined', desc: '上传前文件转换（async，返回转换后的 File）' },
    { name: 'dragIcon', type: 'Snippet', default: 'undefined', desc: '拖拽区自定义图标 Snippet；未传时默认渲染云上传图标（对齐 Semi）' },
    { name: 'dragMainText', type: 'string | Snippet', default: 'undefined', desc: '拖拽区主文案' },
    { name: 'dragSubText', type: 'string | Snippet', default: 'undefined', desc: '拖拽区副文案' },
    { name: 'addOnPasting', type: 'boolean', default: 'false', desc: '粘贴添加文件（监听 document paste）' },
    { name: 'hotSpotLocation', type: "'start'|'end'|'none'", default: "'start'", desc: "触发热点位置：'start'=前置，'end'=后置，'none'=隐藏触发器" },
    { name: 'crop', type: 'boolean | UploadCropProps', default: 'false', desc: '启用图片裁切：image/* 文件先进裁切弹窗（Modal+Cropper），确认后用裁切结果替换原文件再上传；传对象自定义宽高比/形状/质量等' },
    { name: 'beforeCrop', type: '(file: File) => boolean | Promise<boolean>', default: 'undefined', desc: '裁切前钩子：返回 false 跳过裁切直接上传，支持异步' },
    { name: 'onCropError', type: '(err: unknown) => void', default: 'undefined', desc: '裁切失败回调' },
    { name: 'cropModalProps', type: 'Record<string, unknown>', default: 'undefined', desc: '透传给裁切 Modal 的额外 props（样式/宽度等）' },
    { name: 'renderFileItem', type: 'Snippet<[{ fileItem, remove, retry, preview }]>', default: 'undefined', desc: '完全自定义单个文件项渲染（替换默认列表项，list/text listType）。fileItem 上另挂 onRemove/onRetry/onPreview 方法（对标 Semi fileItem.onRemove() 直接可调）' },
    { name: 'previewFile', type: 'Snippet<[{ fileItem }]>', default: 'undefined', desc: '自定义缩略图预览内容：替换默认缩略图 <img>（image/picture-card），对标 Semi previewFile' },
    { name: 'renderThumbnail', type: 'Snippet<[{ fileItem }]>', default: 'undefined', desc: '自定义整个缩略图容器（picture-card），接管图片本身，常配合 Image 实现点击放大；对标 Semi renderThumbnail' },
    { name: 'showPicInfo', type: 'boolean', default: 'false', desc: '是否显示 picture-card 图片信息浮层（文件名等），只在 picture-card 有效' },
    { name: 'renderPicInfo', type: 'Snippet<[{ fileItem }]>', default: 'undefined', desc: '自定义 picture-card 图片信息浮层渲染（showPicInfo 为 true 时生效）' },
    { name: 'beforeRemove', type: '(file: UploadFileItem, fileList: UploadFileItem[]) => boolean | Promise<boolean>', default: 'undefined', desc: '移除文件前钩子：返回 false/reject 阻止移除，支持异步。对标 Semi beforeRemove' },
    { name: 'onRemove', type: '(currentFile: File | undefined, fileList: UploadFileItem[], currentFileItem: UploadFileItem) => void', default: 'undefined', desc: '文件被移除后的回调。对标 Semi onRemove' },
    { name: 'timeout', type: 'number', default: '0', desc: '单文件上传超时（毫秒），>0 启用；超时中止 XHR 并标 error。仅对内置 XHR 上传生效' },
    { name: 'uploadTrigger', type: "'auto' | 'custom'", default: "'auto'", desc: "上传触发时机：'auto'=选文件即传；'custom'=选文件后停 ready，需命令式 upload() 触发。对标 Semi uploadTrigger" },
    { name: 'beforeClear', type: '(fileList: UploadFileItem[]) => boolean | Promise<boolean>', default: 'undefined', desc: '批量清除前钩子：返回 false/Promise.resolve(false)/reject 阻止清除，支持异步。对标 Semi beforeClear' },
    { name: 'afterUpload', type: '(payload: { response, file, fileList }) => { autoRemove?, status?, validateMessage?, name?, url? } | void', default: 'undefined', desc: '单文件上传成功后钩子（同步返回，不支持异步）：据返回值改该项状态/文案/名称/预览地址，或 autoRemove 自动移除。对标 Semi afterUpload' },
    { name: 'onPastingError', type: '(error: unknown) => void', default: 'undefined', desc: '粘贴上传出错回调（addOnPasting 场景，读取剪贴板失败）。对标 Semi onPastingError' },
    { name: 'renderPicPreviewIcon', type: 'Snippet<[{ fileItem, remove, retry, preview }]>', default: 'undefined', desc: '自定义照片墙 hover 预览图标（picture-card），常配合 onPreviewClick。fileItem 上另挂 onRemove/onRetry/onPreview 方法。对标 Semi renderPicPreviewIcon' },
    { name: 'renderPicClose', type: 'Snippet<[{ className, remove }]>', default: 'undefined', desc: '自定义照片墙关闭（移除）按钮（picture-card）。对标 Semi renderPicClose' },
    { name: 'renderFileOperation', type: 'Snippet<[{ fileItem, remove, retry, preview }]>', default: 'undefined', desc: '自定义文件列表项操作区（text/list，替换默认重试/移除）。fileItem 上另挂 onRemove/onRetry/onPreview 方法（对标 Semi fileItem.onRemove() 直接可调）。对标 Semi renderFileOperation' },
    { name: 'picHeight', type: 'number | string', default: 'undefined', desc: '照片墙缩略图高度（number 视为 px），写入卡片 inline style。对标 Semi picHeight' },
    { name: 'picWidth', type: 'number | string', default: 'undefined', desc: '照片墙缩略图宽度（number 视为 px），写入卡片 inline style。对标 Semi picWidth' },
    { name: 'capture', type: "boolean | 'user' | 'environment'", default: 'undefined', desc: '透传给 file input 的 capture 属性（移动端拍照/录像来源），命令式设置。对标 Semi capture' },
    { name: 'itemStyle', type: 'string | Record<string, string | number>', default: 'undefined', desc: '每个文件列表项/卡片的自定义 style（合并进容器；对象值为 number 时补 px，如 { width: 300 } → 300px）。对标 Semi itemStyle' },
    { name: 'onFileChange', type: '(files: File[]) => void', default: 'undefined', desc: '选中原始 File 列表变化回调（经 accept/limit 过滤后），区别于 onChange 的 UploadFileItem 列表。对标 Semi onFileChange' },
  ],
  methods: [
    { name: 'upload', type: '() => void', desc: '命令式手动触发上传（配合 uploadTrigger="custom"），批量上传所有 ready 文件。对标 Semi ref.upload' },
    { name: 'addFiles', type: '(fileList: FileList | File[]) => void', desc: '命令式添加文件，走完整 accept/limit/校验/上传管线' },
    { name: 'insert', type: '(files: File[], index?: number) => void', desc: '命令式插入文件到指定 index（不传则末尾），走完整 accept/limit/校验/上传管线。对标 Semi insert' },
    { name: 'openFileDialog', type: '() => void', desc: '命令式打开文件选择器（等价点击触发器）。对标 Semi openFileDialog' },
  ],
  a11y: {
    role: 'button',
    keyboard: ['Enter', 'Space'],
    notes: ['隐藏的 file input（visually-hidden）', '触发器为 button', '移除按钮 aria-label「移除」', 'dragger role=button + tabindex + 键盘 Enter/Space'],
  },
  tokens: ['--cd-color-upload-*', '--cd-width-upload-*', '--cd-height-upload-*', '--cd-spacing-upload-*', '--cd-radius-upload-*', '--cd-font-upload-*', '--cd-upload-dragger-*', '--cd-upload-item-*', '--cd-upload-border-warning', '--cd-upload-border-error', '--cd-button-height-*', '--cd-button-radius', '--cd-button-padding-x', '--cd-focus-ring', '--cd-motion-*', '--cd-color-danger', '--cd-spacing-*', '--cd-font-size-*', '--cd-border-radius-small'],
} as const;
