/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Upload',
  category: 'input',
  description: '文件上传，支持点击与拖拽选择、文件列表（名称/大小/状态/移除）。本轮不做真实网络上传。',
  props: [
    { name: 'value', type: 'UploadFileItem[]', default: 'undefined', desc: '受控文件列表；提供则为受控' },
    { name: 'defaultValue', type: 'UploadFileItem[]', default: '[]', desc: '非受控初始文件列表' },
    { name: 'accept', type: 'string', default: 'undefined', desc: '接受的文件类型（input accept）' },
    { name: 'multiple', type: 'boolean', default: 'false' },
    { name: 'directory', type: 'boolean', default: 'false', desc: '上传整个目录（webkitdirectory），递归选择目录下所有文件，保留 relativePath' },
    { name: 'limit', type: 'number', default: 'undefined', desc: '最大文件数；超出触发 onExceed' },
    { name: 'maxSize', type: 'number', default: 'undefined', desc: '单文件最大体积（KB）；超限标记 error' },
    { name: 'minSize', type: 'number', default: 'undefined', desc: '单文件最小体积（KB）；过小标记 error' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'size', type: "'small'|'default'|'large'", default: "'default'", desc: '组件级尺寸（触发按钮/拖拽区/列表项），区别于文件项的 file.size 体积' },
    { name: 'status', type: "'default'|'warning'|'error'", default: "'default'", desc: '组件级校验态（表单联动，影响上传区/边框色），区别于文件项的 file.status 上传进度态' },
    { name: 'listType', type: "'text'|'image'|'picture-card'|'none'", default: 'text', desc: 'image/picture-card 显示缩略图网格' },
    { name: 'drag', type: 'boolean', default: 'false', desc: 'true 渲染拖拽区，false 渲染按钮' },
    { name: 'action', type: 'string', default: 'undefined', desc: '上传地址；有则选文件后自动 XHR 上传' },
    { name: 'uploadName', type: 'string', default: "'file'", desc: '表单字段名' },
    { name: 'headers', type: 'Record<string,string>', default: 'undefined', desc: '额外请求头' },
    { name: 'uploadData', type: 'Record<string,string>', default: 'undefined', desc: '额外表单字段' },
    { name: 'concurrency', type: 'number', default: '0', desc: '同时进行的上传数上限；0/不传=不限，超出排队、完成补位' },
    { name: 'beforeUpload', type: '(file: File, fileList: File[]) => boolean | File | Promise<boolean | File>', default: 'undefined', desc: '上传前异步校验/转换：false/reject 跳过该文件，返回 File 替换，true 正常上传' },
    { name: 'customRequest', type: '(item: UploadFileItem) => void | Promise<void>', default: 'undefined', desc: '提供则由外部接管上传（优先于 action）；返回 Promise 时受 concurrency 调度' },
    { name: 'onChange', type: '(list: UploadFileItem[]) => void', default: 'undefined' },
    { name: 'onExceed', type: '(files: File[]) => void', default: 'undefined' },
    { name: 'onSuccess', type: '(response: string, item: UploadFileItem) => void', default: 'undefined' },
    { name: 'onError', type: '(item: UploadFileItem) => void', default: 'undefined' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '自定义触发器内容' },
    { name: 'showRetry', type: 'boolean', default: 'true', desc: '上传失败是否显示重试按钮' },
    { name: 'showReplace', type: 'boolean', default: 'false', desc: '是否允许替换已有文件（单文件模式下显示"替换"而不是"添加"）' },
    { name: 'showClear', type: 'boolean', default: 'false', desc: '是否显示批量清除按钮' },
    { name: 'onClear', type: '() => void', default: 'undefined', desc: '清除按钮点击回调' },
    { name: 'fileListTitle', type: 'string | false', default: 'undefined', desc: '文件列表标题文字；false 则不渲染' },
    { name: 'showTooltip', type: 'boolean', default: 'true', desc: '文件名超长是否展示 Tooltip（title 属性）' },
    { name: 'prompt', type: 'string | Snippet', default: 'undefined', desc: '上传区提示内容（文字或 Snippet）' },
    { name: 'promptPosition', type: "'left'|'right'|'bottom'", default: "'bottom'", desc: '提示位置：left/right 水平排列，bottom 下方' },
    { name: 'onDrop', type: '(e: DragEvent, files: File[], rejectFiles: File[]) => void', default: 'undefined', desc: '拖拽放下回调' },
    { name: 'onOpenFileDialog', type: '() => void', default: 'undefined', desc: '打开文件选择弹窗时回调' },
    { name: 'onPreviewClick', type: '(fileItem: UploadFileItem) => void', default: 'undefined', desc: '预览图点击回调（image/picture-card listType）' },
    { name: 'onAcceptInvalid', type: '(files: File[]) => void', default: 'undefined', desc: 'accept 校验失败（文件类型不符）的回调' },
    { name: 'onRetry', type: '(file: UploadFileItem) => void', default: 'undefined', desc: '重试回调' },
    { name: 'onSizeError', type: "(file: UploadFileItem, validResult: 'max' | 'min') => void", default: 'undefined', desc: '大小校验失败回调' },
    { name: 'validateMessage', type: 'string', default: 'undefined', desc: '校验失败统一文案（覆盖 i18n 默认文案）' },
    { name: 'withCredentials', type: 'boolean', default: 'false', desc: 'XHR withCredentials（跨域凭证）' },
    { name: 'transformFile', type: '(file: File) => Promise<File>', default: 'undefined', desc: '上传前文件转换（async，返回转换后的 File）' },
    { name: 'dragIcon', type: 'Snippet', default: 'undefined', desc: '拖拽区自定义图标 Snippet' },
    { name: 'dragMainText', type: 'string | Snippet', default: 'undefined', desc: '拖拽区主文案' },
    { name: 'dragSubText', type: 'string | Snippet', default: 'undefined', desc: '拖拽区副文案' },
    { name: 'addOnPasting', type: 'boolean', default: 'false', desc: '粘贴添加文件（监听 document paste）' },
    { name: 'hotSpotLocation', type: "'start'|'end'|'none'", default: "'start'", desc: "触发热点位置：'start'=前置，'end'=后置，'none'=隐藏触发器" },
  ],
  a11y: {
    role: 'button',
    keyboard: ['Enter', 'Space'],
    notes: ['隐藏的 file input（visually-hidden）', '触发器为 button', '移除按钮 aria-label「移除」', 'dragger role=button + tabindex + 键盘 Enter/Space'],
  },
  tokens: ['--cd-color-upload-*', '--cd-width-upload-*', '--cd-height-upload-*', '--cd-spacing-upload-*', '--cd-radius-upload-*', '--cd-font-upload-*', '--cd-upload-dragger-*', '--cd-upload-item-*', '--cd-upload-border-warning', '--cd-upload-border-error', '--cd-button-height-*', '--cd-button-radius', '--cd-button-padding-x', '--cd-focus-ring', '--cd-motion-*', '--cd-color-danger', '--cd-spacing-*', '--cd-font-size-*', '--cd-border-radius-small'],
} as const;
