/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Nav',
  category: 'navigation',
  description:
    '站点导航菜单（对齐 Semi Navigation）。支持垂直/水平模式、子导航（内联/浮层）、logo 头部、折叠按钮、多选。独立渲染，字段/回调对齐 Semi（itemKey/text/icon/items）。',
  props: [
    {
      name: 'items',
      type: 'NavItemDef[]',
      default: '[]',
      desc: '导航项列表，字段对齐 Semi：itemKey/text/icon/items（含 items 即子导航）',
    },
    { name: 'mode', type: "'vertical'|'horizontal'", default: "'vertical'", desc: '导航方向：侧边/顶部' },
    { name: 'selectedKeys', type: 'NavKey[]', default: 'undefined', desc: '受控选中项 key 数组' },
    { name: 'defaultSelectedKeys', type: 'NavKey[]', default: 'undefined', desc: '默认选中项 key 数组' },
    { name: 'openKeys', type: 'NavKey[]', default: 'undefined', desc: '受控展开子导航 key（vertical 且未折叠有效）' },
    { name: 'defaultOpenKeys', type: 'NavKey[]', default: 'undefined', desc: '默认展开子导航 key' },
    { name: 'multiple', type: 'boolean', default: 'false', desc: '多选模式（叠加选中，配合 onDeselect）' },
    { name: 'isCollapsed', type: 'boolean', default: 'undefined', desc: '受控折叠态（仅 vertical 有效）' },
    { name: 'defaultIsCollapsed', type: 'boolean', default: 'false', desc: '默认折叠态（仅 vertical 有效）' },
    { name: 'header', type: '{ logo?: Snippet; text?: string }', default: 'undefined', desc: '头部配置（logo + 文案）' },
    { name: 'footer', type: '{ collapseButton?: boolean }', default: 'undefined', desc: '底部配置（收起按钮，仅 vertical）' },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '整体禁用' },
    { name: 'limitIndent', type: 'boolean', default: 'true', desc: '仅一级缩进；false 时逐级缩进（依赖 level+indent）' },
    { name: 'toggleIconPosition', type: "'left'|'right'", default: "'right'", desc: '子导航展开箭头位置' },
    { name: 'expandIcon', type: 'Snippet', default: 'undefined', desc: '自定义展开箭头图标' },
    { name: 'subNavMotion', type: 'boolean', default: 'true', desc: '子导航展开动画开关' },
    { name: 'subNavOpenDelay', type: 'number', default: '0', desc: '浮层子导航展开延迟 ms（透传 Dropdown mouseEnterDelay）' },
    { name: 'subNavCloseDelay', type: 'number', default: '100', desc: '浮层子导航关闭延迟 ms（透传 Dropdown mouseLeaveDelay）' },
    { name: 'subDropdownProps', type: 'NavDropdownProps', default: 'undefined', desc: 'Nav 级：透传给所有子导航浮层 Dropdown 的默认属性' },
    { name: 'tooltipShowDelay', type: 'number', default: 'undefined', desc: '折叠态 tooltip 显示延迟 ms' },
    { name: 'tooltipHideDelay', type: 'number', default: 'undefined', desc: '折叠态 tooltip 隐藏延迟 ms' },
    { name: 'getPopupContainer', type: '() => HTMLElement', default: 'undefined', desc: '浮层挂载容器' },
    { name: 'renderWrapper', type: 'Snippet', default: 'undefined', desc: '自定义导航项外层包裹' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根元素自定义类名' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根元素自定义内联样式' },
    { name: 'bodyStyle', type: 'string', default: 'undefined', desc: '导航项列表容器样式（对齐 Semi bodyStyle）' },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '可访问性标签' },
  ],
  events: [
    { name: 'onSelect', payload: 'NavSelectData', desc: '选中导航项时触发（{itemKey,selectedKeys,selectedItems,domEvent,isOpen}）' },
    { name: 'onDeselect', payload: 'NavSelectData', desc: '多选下取消选中时触发' },
    { name: 'onClick', payload: 'NavClickData', desc: '点击任意导航项时触发（{itemKey,domEvent,isOpen}）' },
    { name: 'onOpenChange', payload: 'NavOpenChangeData', desc: '展开/收起子导航时触发（{itemKey,openKeys,domEvent,isOpen}）' },
    { name: 'onCollapseChange', payload: 'boolean', desc: '折叠态变化时触发' },
  ],
  slots: [
    { name: 'headerSlot', desc: '自定义头部（覆盖 header 配置对象）' },
    { name: 'footerSlot', desc: '自定义底部（覆盖 footer 配置对象）' },
    { name: 'children', desc: '声明式子项（<Nav.Item>/<Nav.Sub>），与 items 二选一' },
  ],
  subComponents: [
    {
      name: 'Nav.Header',
      element: 'div',
      props: [
        { name: 'logo', type: 'Snippet', default: 'undefined', desc: 'Logo 节点' },
        { name: 'text', type: 'string | Snippet', default: 'undefined', desc: 'Logo 文案' },
        { name: 'link', type: 'string', default: 'undefined', desc: '链接地址（整体包裹 <a>）' },
        { name: 'linkOptions', type: 'Record<string,string>', default: 'undefined', desc: '透传给 <a> 的属性' },
        { name: 'class', type: 'string', default: 'undefined', desc: '自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '自定义内联样式' },
      ],
    },
    {
      name: 'Nav.Footer',
      element: 'div',
      props: [
        { name: 'collapseButton', type: 'boolean | Snippet', default: 'false', desc: '收起按钮（或自定义节点，仅 vertical 生效）' },
        { name: 'collapseText', type: '(collapsed: boolean) => string', default: 'undefined', desc: '收起按钮文案（默认用 locale）' },
        { name: 'onClick', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击事件回调' },
        { name: 'class', type: 'string', default: 'undefined', desc: '自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '自定义内联样式' },
      ],
    },
    {
      name: 'Nav.Item',
      element: 'li[role=menuitem]',
      props: [
        { name: 'itemKey', type: 'NavKey', default: '—', desc: '导航项唯一标识（必填）' },
        { name: 'text', type: 'string | Snippet', default: '—', desc: '导航项文案' },
        { name: 'icon', type: 'Snippet', default: 'undefined', desc: '项前置图标' },
        { name: 'disabled', type: 'boolean', default: 'false', desc: '是否禁用' },
        { name: 'indent', type: 'boolean', default: 'undefined', desc: '保留左侧图标占位（对齐 Semi indent）' },
        { name: 'link', type: 'string', default: 'undefined', desc: '链接地址（渲染原生 <a>）' },
        { name: 'linkOptions', type: 'Record<string,string>', default: 'undefined', desc: '透传给 <a> 的属性（target/rel/download）' },
        { name: 'onClick', type: '(data: NavClickData) => void', default: 'undefined', desc: '项级点击回调（富载荷 {itemKey,domEvent,isOpen}）' },
        { name: 'onMouseEnter', type: '(e: MouseEvent) => void', default: 'undefined', desc: '鼠标移入' },
        { name: 'onMouseLeave', type: '(e: MouseEvent) => void', default: 'undefined', desc: '鼠标移出' },
      ],
    },
    {
      name: 'Nav.Sub',
      element: 'li[role=menuitem]（浮层态用 Dropdown）',
      props: [
        { name: 'itemKey', type: 'NavKey', default: '—', desc: '子导航唯一标识（必填）' },
        { name: 'text', type: 'string | Snippet', default: '—', desc: '子导航标题文案' },
        { name: 'icon', type: 'Snippet', default: 'undefined', desc: '标题前置图标' },
        { name: 'disabled', type: 'boolean', default: 'false', desc: '是否禁用' },
        { name: 'indent', type: 'boolean', default: 'undefined', desc: '保留左侧图标占位（对齐 Semi indent）' },
        { name: 'maxHeight', type: 'number', default: '999', desc: '子导航最大高度（内联展开动画）' },
        { name: 'isOpen', type: 'boolean', default: 'undefined', desc: '子导航是否展开（对齐 Semi isOpen）' },
        { name: 'dropdownProps', type: 'NavDropdownProps', default: 'undefined', desc: '透传给该子导航浮层 Dropdown 的属性' },
        { name: 'dropdownStyle', type: 'string', default: 'undefined', desc: '透传给该子导航浮层 Dropdown 的内联样式' },
        { name: 'onMouseEnter', type: '(e: MouseEvent) => void', default: 'undefined', desc: '标题鼠标移入' },
        { name: 'onMouseLeave', type: '(e: MouseEvent) => void', default: 'undefined', desc: '标题鼠标移出' },
        { name: 'children', type: 'Snippet', default: 'undefined', desc: '内嵌 Nav.Item / Nav.Sub' },
      ],
    },
  ],
  a11y: {
    role: 'menu',
    keyboard: ['Tab', 'Shift+Tab', 'Enter', 'Space', 'ArrowLeft', 'ArrowRight'],
    notes: [
      '对齐 Semi：根为纯 <div>（无 nav landmark），列表 ul[role=menu][aria-orientation=mode]',
      '叶子/子导航标题均为 role=menuitem；选中靠 -selected class（无 aria-current）',
      '含 link 的叶子内含原生 <a>；子导航标题 aria-expanded 反映展开态',
      '折叠态浮层子导航复用 Dropdown（role=menu + menuitem）；折叠收起按钮为 icon-only Button + aria-label（Tooltip 提示）',
    ],
  },
  // Nav 直接消费 navigation.ts 主 token（命名镜像 Semi navigation/variables.scss）；
  // 已移除 Semi 没有的 --cd-nav-* 中间层。
  tokens: [
    '--cd-height-navigation-horizontal-header',
    '--cd-height-navigation-item-base',
    '--cd-width-navigation-item-borderradius',
    '--cd-font-size-navigation-header-text',
    '--cd-spacing-navigation-horizontal-paddingleft',
    '--cd-spacing-navigation-header-logo-marginright',
    '--cd-spacing-navigation-footer-paddingx',
    '--cd-spacing-navigation-footer-paddingy',
    '--cd-spacing-navigation-vertical-footer-collapse-text-marginleft',
    '--cd-color-navigation-header-text-default',
    '--cd-color-navigation-footer-icon-default',
    '--cd-color-navigation-border-default',
    '--cd-color-navigation-iteml1-bg-active',
    '--cd-color-navigation-iteml1-selected-disabled-bg-default',
    '--cd-color-navigation-iteml1-selected-disabled-text-default',
    '--cd-color-navigation-iteml1-selected-disabled-icon-default',
    '--cd-font-navigation-header-item-fontweight',
    '--cd-font-navigation-popover-nav-item-selected-fontweight',
    '--cd-width-navigation-icon-left',
    '--cd-spacing-navigation-vertical-footer-paddingx',
  ],
  aiHints: [
    '侧边导航用 mode=vertical + footer={{collapseButton:true}}；顶部导航用 mode=horizontal。',
    'items 字段对齐 Semi：itemKey/text/icon/items。',
    '配合 Layout：<Layout.Sider><Nav mode=vertical/></Layout.Sider> 或 <Layout.Header><Nav mode=horizontal/></Layout.Header>。',
  ],
  examples: [
    {
      title: '侧边导航',
      code: '<Nav mode="vertical" items={items} header={{logo, text:"后台"}} footer={{collapseButton:true}} />',
    },
  ],
} as const;
