/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Radio',
  category: 'input',
  description: '单选框，通常置于 RadioGroup 中，遵循 WAI-ARIA radiogroup 模式（roving tabindex + 方向键）。',
  props: [
    { name: 'value', type: 'string | number | boolean', default: '—', desc: '选项值（必填）' },
    { name: 'checked', type: 'boolean', default: 'undefined', desc: '独立使用时受控选中' },
    { name: 'defaultChecked', type: 'boolean', default: 'false' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'type', type: "'default'|'button'|'card'|'pureCard'", default: '继承 Group 或 default', desc: 'button/card/pureCard 用 role=radio 容器 + aria-checked' },
    { name: 'name', type: 'string', default: 'undefined' },
    { name: 'extra', type: 'string', default: 'undefined', desc: '辅助说明，aria-describedby 关联' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '标签内容' },
    { name: 'onChange', type: '(e: RadioChangeEvent) => void', default: 'undefined', desc: '对齐 Semi：回调收到合成事件，e.target.{checked,value}' },
    { name: 'addonId', type: 'string', default: 'undefined', desc: '内容容器 id，用作 input 的 aria-labelledby' },
    { name: 'addonClassName', type: 'string', default: 'undefined', desc: '内容容器附加 class' },
    { name: 'addonStyle', type: 'string', default: 'undefined', desc: '内容容器内联样式' },
    { name: 'autoFocus', type: 'boolean', default: 'false', desc: '挂载时自动聚焦' },
    { name: 'extraId', type: 'string', default: 'undefined', desc: '自定义 extra 元素 id（默认由 fieldId 派生）' },
    { name: 'mode', type: "'advanced'|''", default: "''", desc: "advanced：再次点击选中项可取消（onChange(e.target.checked=false)）" },
    { name: 'class', type: 'string', default: 'undefined', desc: '根元素附加 class（对齐 Semi className）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根元素内联样式' },
    { name: 'onMouseEnter', type: '(e: MouseEvent) => void', default: 'undefined' },
    { name: 'onMouseLeave', type: '(e: MouseEvent) => void', default: 'undefined' },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '无障碍标签' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: 'autoFocus 时阻止滚动' },
  ],
  methods: [
    { name: 'focus', signature: '() => void', desc: '命令式聚焦内部 input（对齐 Semi）' },
    { name: 'blur', signature: '() => void', desc: '命令式失焦内部 input（对齐 Semi）' },
  ],
  group: {
    name: 'RadioGroup',
    props: [
      { name: 'value', type: 'string | number | boolean', default: 'undefined', desc: '受控选中值' },
      { name: 'defaultValue', type: 'string | number | boolean', default: 'undefined' },
      { name: 'name', type: 'string', default: 'useId()' },
      {
        name: 'options',
        type: 'Array<string | number | {label,value,disabled?,extra?,className?,style?,addonId?,addonStyle?,addonClassName?,extraId?}>',
        default: 'undefined',
        desc: '对齐 Semi：支持 primitive 或对象形式',
      },
      { name: 'disabled', type: 'boolean', default: 'false' },
      {
        name: 'buttonSize',
        type: "'small'|'middle'|'large'",
        default: 'middle',
        desc: "对齐 Semi：仅 type='button' 时生效",
      },
      { name: 'type', type: "'default'|'button'|'card'|'pureCard'", default: 'default', desc: '整组形态，透传子项；非 default 用 role=radio + aria-checked' },
      { name: 'direction', type: "'horizontal'|'vertical'", default: 'horizontal' },
      { name: 'onChange', type: '(e: RadioChangeEvent) => void', default: 'undefined', desc: '对齐 Semi：回调收到合成事件，e.target.{checked,value}' },
      { name: 'children', type: 'Snippet', default: 'undefined' },
      { name: 'id', type: 'string', default: 'undefined', desc: '根元素 id（对齐 Semi）' },
      { name: 'class', type: 'string', default: 'undefined', desc: '根元素附加 class（对齐 Semi className）' },
      { name: 'style', type: 'string', default: 'undefined', desc: '根元素内联样式（对齐 Semi）' },
      { name: 'ariaLabel', type: 'string', default: 'undefined' },
      { name: 'ariaLabelledby', type: 'string', default: 'undefined', desc: '关联组可见标题 id（优先于 ariaLabel）' },
      { name: 'ariaDescribedby', type: 'string', default: 'undefined', desc: '对齐 Semi aria-describedby' },
      { name: 'ariaErrormessage', type: 'string', default: 'undefined', desc: '对齐 Semi aria-errormessage' },
      { name: 'ariaInvalid', type: 'boolean', default: 'undefined', desc: '对齐 Semi aria-invalid' },
      { name: 'ariaRequired', type: 'boolean', default: 'undefined', desc: '对齐 Semi aria-required' },
    ],
  },
  a11y: {
    role: 'radiogroup / radio',
    keyboard: ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Home', 'End', 'Space'],
    notes: [
      'div role=radiogroup 包裹',
      'roving tabindex：仅选中项（或首个可用项）tabindex=0',
      '方向键在可用项间循环移动并选中、聚焦，跳过 disabled',
      'Home/End 跳首/末可用项',
      'RTL（dir=rtl）下 ArrowLeft/ArrowRight 语义镜像翻转',
      'button/card/pureCard 型用容器 role=radio + aria-checked（非原生 input），Space/Enter 选中',
      'extra 经 aria-describedby 关联',
      'Group 支持 aria-describedby/errormessage/invalid/required 透传（对齐 Semi）',
    ],
  },
  tokens: [
    '--cd-color-radio-default-border-default',
    '--cd-color-radio-default-border-hover',
    '--cd-color-radio-default-bg-default',
    '--cd-color-radio-default-bg-hover',
    '--cd-color-radio-default-text-default',
    '--cd-color-radio-extra-text-default',
    '--cd-color-radio-primary-border-default',
    '--cd-color-radio-primary-bg-default',
    '--cd-color-radio-primary-bg-hover',
    '--cd-color-radio-primary-bg-active',
    '--cd-color-radio-primary-text-default',
    '--cd-color-radio-disabled-text-default',
    '--cd-color-radio-disabled-bg-default',
    '--cd-color-radio-default-border-disabled',
    '--cd-color-radio-checked-bg-disabled',
    '--cd-color-radio-checked-border-disabled',
    '--cd-color-radio-buttonradio-text-default',
    '--cd-color-radio-buttonradio-bg-default',
    '--cd-color-radio-cardradiogroup-border-active',
    '--cd-radius-radio-cardradiogroup',
    '--cd-radius-radio-buttonradio',
    '--cd-spacing-radio-addon-buttonradio-middle-paddingx',
    '--cd-spacing-radio-content-rowgap',
    '--cd-spacing-radio-group-horizontal-marginright',
    '--cd-spacing-radio-cardradiogroup-paddingx',
    '--cd-spacing-radio-cardradiogroup-paddingy',
    '--cd-radio-size-default',
    '--cd-radio-label-gap',
    '--cd-radio-button-height',
    '--cd-radio-button-height-small',
    '--cd-radio-button-height-large',
    // 通用基元
    '--cd-focus-ring',
    '--cd-motion-*',
    '--cd-border-radius-full',
    '--cd-font-size-small',
  ],
} as const;
