/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Transfer',
  category: 'input',
  description:
    '穿梭框，双栏列表间移动条目，严格对齐 Semi Design。支持多选、本地/自定义/远程搜索、分组（groupList）、树状源面板（treeList，内嵌复用 Tree 组件）、左侧分页、右侧拖拽重排（draggable）与右侧虚拟化（virtualize）。',
  props: [
    { name: 'style', type: 'string', default: 'undefined', desc: '根容器内联样式（对齐 Semi style）' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根容器自定义类名（对齐 Semi className）' },
    { name: 'value', type: '(string|number)[]', default: 'undefined', desc: '受控已选 key 数组；提供则为受控' },
    { name: 'defaultValue', type: '(string|number)[]', default: '[]', desc: '非受控初始已选 key' },
    {
      name: 'dataSource',
      type: 'TransferItem[] | TransferGroup[] | TransferTreeNode[]',
      default: '[]',
      desc: '平铺条目（key/label/disabled/group）、分组结构 {title, items}[]，或树结构 {key,label,children}[]（treeList）；树模式下源面板内嵌复用 Tree 组件，仅叶子可迁移到平铺目标面板，已迁移叶子在源树置灰',
    },
    { name: 'type', type: "'list'|'groupList'|'treeList'", default: "'list'", desc: '数据形态：平铺/分组/树（对齐 Semi type）' },
    { name: 'filter', type: 'boolean | ((input, item) => boolean)', default: 'true', desc: '是否显示本地搜索框，或传自定义匹配函数（对齐 Semi filter）' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'draggable', type: 'boolean', default: 'false', desc: '右侧已选列可鼠标拖拽重排（HTML5 DnD）；新顺序经 reorder 纯函数算出仅通过 onChange 通知，受控 value 不回写' },
    { name: 'virtualize', type: '{ height?: number; width?: number|string; itemSize: number }', default: 'undefined', desc: '右侧已选列虚拟化（对齐 Semi VirtualizeProps，仅右侧生效；draggable 时禁用）' },
    { name: 'onSearch', type: '(input: string) => void', default: 'undefined', desc: '远程搜索：提供后切远程模式，本地不再过滤，由父按 input 更新 dataSource（对齐 Semi 单参签名）' },
    { name: 'loading', type: 'boolean', default: 'false', desc: '远程加载中：源面板显示加载态' },
    { name: 'onChange', type: '(values: (string|number)[], items: TransferItem[]) => void', default: 'undefined', desc: '选中变更（对齐 Semi）：回传 (values, items) 两参' },
    { name: 'emptyContent', type: '{ left?: Snippet|string; right?: Snippet|string; search?: Snippet|string }', default: 'undefined', desc: '自定义空态（对齐 Semi）' },
    { name: 'inputProps', type: 'object', default: 'undefined', desc: '透传给搜索框 Input 的额外参数' },
    { name: 'treeProps', type: 'Omit<TreeProps, "value"|"onChange">', default: 'undefined', desc: 'type=treeList 时透传给内部 Tree 组件的全部属性（对齐 Semi）' },
    { name: 'showPath', type: 'boolean', default: 'false', desc: 'type=treeList 时右侧已选项显示完整路径（renderSelectedItem 参数含 fullPath）' },
    { name: 'pagination', type: '{ pageSize?: number; currentPage?: number; defaultCurrentPage?: number; onPageChange?: (page) => void }', default: 'undefined', desc: '左侧面板分页（仅 list/groupList；pageSize 默认 10）' },
    { name: 'onSelect', type: '(item: TransferItem) => void', default: 'undefined', desc: '勾选单项时回调' },
    { name: 'onDeselect', type: '(item: TransferItem) => void', default: 'undefined', desc: '取消勾选单项时回调' },
    { name: 'renderSourceItem', type: 'Snippet<[{item, onChange, checked}]>', default: 'undefined', desc: '自定义左侧条目渲染' },
    { name: 'renderSelectedItem', type: 'Snippet<[{item, onRemove, sortableHandle, fullPath}]>', default: 'undefined', desc: '自定义右侧条目渲染（含 sortableHandle / fullPath）' },
    { name: 'renderSourceHeader', type: 'Snippet<[{num, showButton, allChecked, onAllClick, leafOnlyNum}]>', default: 'undefined', desc: '自定义左侧面板头部' },
    { name: 'renderSelectedHeader', type: 'Snippet<[{num, showButton, onClear}]>', default: 'undefined', desc: '自定义右侧面板头部' },
    { name: 'renderSourcePanel', type: 'Snippet<[SourcePanelProps]>', default: 'undefined', desc: '完全自定义左侧面板' },
    { name: 'renderSelectedPanel', type: 'Snippet<[SelectedPanelProps]>', default: 'undefined', desc: '完全自定义右侧面板' },
  ],
  methods: [{ name: 'search(value)', desc: '命令式搜索：置值到左侧搜索框并过滤，不触发 onSearch（对齐 Semi）' }],
  a11y: {
    role: 'group',
    pattern: 'transfer',
    notes: [
      '容器 role=group；每侧列表容器 role=list（对齐 Semi，非 listbox）',
      '左侧为原生 Checkbox 行（Space 勾选）；右侧已选项 role=listitem + 删除按钮 aria-label',
      '搜索框 role=search + aria-label；中间移动按钮与全选/清空按钮为原生 Button 带 aria-label',
      'treeList 模式内嵌复用 Tree 组件，继承其键盘/ARIA 语义',
    ],
  },
  tokens: [
    // 严格对齐 Semi transfer/variables.scss（47 变量），无自造中间层。
    '--cd-color-transfer-bg',
    '--cd-color-transfer-border',
    '--cd-color-transfer-header-text',
    '--cd-color-transfer-empty-text',
    '--cd-color-transfer-group-title-text',
    '--cd-color-transfer-disabled-text',
    '--cd-color-transfer-close-icon-icon',
    '--cd-color-transfer-item-text',
    '--cd-color-transfer-selected-item-text',
    '--cd-color-transfer-item-bg-hover',
    '--cd-color-transfer-item-bg-active',
    '--cd-width-transfer-border',
    '--cd-width-transfer-min-width',
    '--cd-height-transfer',
    '--cd-height-transfer-header',
    '--cd-height-transfer-item-min-height',
    '--cd-width-transfer-item-close-icon',
    '--cd-width-transfer-left',
    '--cd-width-transfer-right',
    '--cd-height-transfer-left-empty',
    '--cd-width-transfer-left-border',
    '--cd-height-transfer-right-header',
    '--cd-height-transfer-right-empty',
    '--cd-width-transfer-empty',
    '--cd-height-transfer-group-title',
    '--cd-spacing-transfer-header-margin-top',
    '--cd-spacing-transfer-header-margin-right',
    '--cd-spacing-transfer-header-margin-bottom',
    '--cd-spacing-transfer-header-margin-left',
    '--cd-spacing-transfer-header-all-margin-left',
    '--cd-spacing-transfer-item-padding-top',
    '--cd-spacing-transfer-item-padding-right',
    '--cd-spacing-transfer-item-padding-bottom',
    '--cd-spacing-transfer-item-padding-left',
    '--cd-spacing-transfer-right-header-margin-top',
    '--cd-spacing-transfer-right-header-margin-bottom',
    '--cd-spacing-transfer-right-item-drag-handler-margin-right',
    '--cd-spacing-transfer-filter-margin-top',
    '--cd-spacing-transfer-filter-margin-right',
    '--cd-spacing-transfer-filter-margin-bottom',
    '--cd-spacing-transfer-filter-margin-left',
    '--cd-spacing-transfer-group-title-padding-left',
    '--cd-radius-transfer',
    '--cd-font-transfer-header-all-font-weight',
  ],
} as const;
