/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'TimePicker',
  category: 'input',
  description:
    '时间选择器，严格对齐 Semi。触发器复用 Input（可键入时间串），面板复用 ScrollList/ScrollItem 滚动列。单选 type=time（HH:mm:ss 三列，+12h AM/PM 列），type=timeRange 左右双列并排选起止。format 字符串决定显示列与 12h（含 ss 即显示秒列）。',
  props: [
    {
      name: 'value',
      type: 'Date | string | [Date|string|null, Date|string|null] | null',
      default: 'undefined',
    },
    {
      name: 'defaultValue',
      type: 'Date | string | [Date|string|null, Date|string|null] | null',
      default: 'null',
    },
    { name: 'type', type: "'time'|'timeRange'", default: "'time'" },
    { name: 'format', type: 'string', default: "'HH:mm:ss'", desc: '格式串，决定显示列与 12h（含 ss 显示秒列）' },
    { name: 'open', type: 'boolean', default: 'undefined' },
    { name: 'defaultOpen', type: 'boolean', default: 'false' },
    { name: 'placeholder', type: 'string', default: "'请选择时间'" },
    { name: 'size', type: "'small'|'default'|'large'", default: "'default'" },
    { name: 'validateStatus', type: "'default'|'warning'|'error'", default: "'default'" },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'hourStep', type: 'number', default: '1' },
    { name: 'minuteStep', type: 'number', default: '1' },
    { name: 'secondStep', type: 'number', default: '1' },
    { name: 'use12Hours', type: 'boolean', default: 'false' },
    { name: 'timeZone', type: 'string | number', default: 'undefined', desc: '时区（数字偏移 / GMT±HH:mm / IANA）' },
    { name: 'disabledHours', type: '() => number[]', default: 'undefined' },
    { name: 'disabledMinutes', type: '(hour: number) => number[]', default: 'undefined' },
    { name: 'disabledSeconds', type: '(hour: number, minute: number) => number[]', default: 'undefined' },
    { name: 'hideDisabledOptions', type: 'boolean', default: 'false' },
    { name: 'locale', type: 'string', default: "'zh-CN'" },
    {
      name: 'onChange',
      type: '(v: (Date|null) | [Date|null, Date|null]) => void',
      default: 'undefined',
    },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '浮层溢出自动调整' },
    { name: 'autoFocus', type: 'boolean', default: 'false', desc: '挂载时自动聚焦触发器' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除按钮图标' },
    { name: 'showClear', type: 'boolean', default: 'true', desc: '是否显示清除按钮' },
    { name: 'clearText', type: 'string', default: "'clear'", desc: '清除按钮 aria/title 文案' },
    { name: 'popupClassName', type: 'string', default: 'undefined', desc: '浮层 className' },
    { name: 'dropdownMargin', type: 'number | { x?: number; y?: number }', default: 'undefined', desc: '浮层溢出冗余' },
    { name: 'popupStyle', type: 'string | Record<string, string>', default: 'undefined', desc: '浮层内联样式' },
    { name: 'focusOnOpen', type: 'boolean', default: 'false', desc: '打开面板时自动聚焦触发器' },
    { name: 'getPopupContainer', type: '() => HTMLElement', default: 'undefined', desc: '浮层挂载容器' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '面板展开动画' },
    { name: 'panelHeader', type: 'string | Snippet', default: 'undefined', desc: '面板顶部自定义内容' },
    { name: 'panelFooter', type: 'string | Snippet', default: 'undefined', desc: '面板底部自定义内容' },
    { name: 'position', type: 'string', default: "'bottomLeft'", desc: '浮层弹出位置' },
    { name: 'rangeSeparator', type: 'string', default: "' ~ '", desc: '范围模式分隔符' },
    { name: 'scrollItemProps', type: 'Record<string, unknown>', default: 'undefined', desc: '滚动列 item 属性透传' },
    { name: 'stopPropagation', type: 'boolean', default: 'true', desc: '阻止浮层点击事件冒泡' },
    { name: 'zIndex', type: 'number', default: '1030', desc: '浮层 z-index（对齐 Semi popoverNumbers.DEFAULT_Z_INDEX）' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined', desc: '触发器失焦' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined', desc: '触发器聚焦' },
    { name: 'onChangeWithDateFirst', type: 'boolean', default: 'true', desc: 'onChange 参数 dateFirst 模式' },
    { name: 'disabledTime', type: "(date: Date | null, panelType?: 'left'|'right') => { disabledHours?; disabledMinutes?; disabledSeconds? } | undefined", default: 'undefined', desc: '按已选时间返回禁用规则，覆盖顶层 disabledHours/Minutes/Seconds' },
    { name: 'inputStyle', type: 'string | Record<string, string>', default: 'undefined', desc: '输入框样式（透传到 Input）' },
    { name: 'inputReadOnly', type: 'boolean', default: 'false', desc: '输入框 readonly（仅允许通过面板选择）' },
    { name: 'insetLabel', type: 'Snippet | string', default: 'undefined', desc: '内嵌标签（透传给 Input）' },
    { name: 'insetLabelId', type: 'string', default: 'undefined', desc: '内嵌标签容器 id（透传给 Input）' },
    { name: 'triggerRender', type: 'Snippet<[{ value: Date | null; placeholder: string; open: boolean; disabled: boolean }]>', default: 'undefined', desc: '完全自定义触发器渲染' },
    { name: 'borderless', type: 'boolean', default: 'false', desc: '无边框模式' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: 'focus 时阻止滚动' },
    { name: 'class', type: 'string', default: 'undefined', desc: '根节点类名' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根节点内联样式' },
    { name: 'id', type: 'string', default: 'undefined', desc: '根节点 id' },
    { name: 'ariaLabelledby', type: 'string', default: 'undefined', desc: 'aria-labelledby 透传' },
    { name: 'ariaDescribedby', type: 'string', default: 'undefined', desc: 'aria-describedby 透传' },
    { name: 'ariaErrormessage', type: 'string', default: 'undefined', desc: 'aria-errormessage 透传' },
    { name: 'ariaInvalid', type: 'boolean', default: 'undefined', desc: 'aria-invalid 透传' },
    { name: 'ariaRequired', type: 'boolean', default: 'undefined', desc: 'aria-required 透传' },
  ],
  methods: [
    { name: 'focus()', desc: '命令式聚焦触发器（对齐 Semi）' },
    { name: 'blur()', desc: '命令式移除焦点（对齐 Semi）' },
  ],
  a11y: {
    role: 'dialog',
    notes: [
      '触发器复用 Input，aria-haspopup=dialog、aria-expanded、aria-controls 指向面板',
      '面板 role=dialog；时间列复用 ScrollList/ScrollItem（-scrolllist-item > ul > li[role=option]）',
      '禁用项 aria-disabled=true 且不可点击；hideDisabledOptions 时从列移除',
      '触发器可键入时间串（Enter/Blur 解析提交）；Enter/↓ 打开；Esc 关闭',
      '12h 制额外 AM/PM 列；文案经 locale TimePicker.am/pm',
      '选择即生效（点击 ScrollItem 项 onSelect 立即 onChange），无「此刻」「确定」按钮',
      'timeRange 模式：左右两个 ScrollList 并排（对齐 Semi RANGE_PANEL_LISTS），一次编辑起止两端',
      'format 字符串经 core parseFormatSpec 决定显示列与 12h（含 ss 显示秒列）',
    ],
  },
  i18nKeys: ['TimePicker.placeholder', 'TimePicker.triggerLabel', 'TimePicker.hour', 'TimePicker.minute', 'TimePicker.second', 'TimePicker.am', 'TimePicker.pm', 'TimePicker.rangeStart', 'TimePicker.rangeEnd'],
  // 面板列宽/面板高/range 双列分割线/圆角/阴影对齐 Semi timePicker/variables.scss；触发输入框复用
  // Input（--cd-input-* + 专属 --cd-radius-time-picker-input），时间列复用 ScrollList/ScrollItem
  // （其自身 --cd-*-scroll-list-* token）。
  tokens: [
    '--cd-color-time-picker-range-picker-panel-split-border',
    '--cd-color-time-picker-range-panel-border',
    '--cd-width-time-picker-range-panel-border',
    '--cd-height-time-picker-panel-body',
    '--cd-width-time-picker-panel-list-ampm',
    '--cd-width-time-picker-panel-list-hour',
    '--cd-width-time-picker-panel-list-minute',
    '--cd-width-time-picker-panel-list-second',
    '--cd-width-time-picker-range-panel-scrolllist-body-border',
    '--cd-spacing-time-picker-range-panel-scrolllist-header-body-padding',
    '--cd-radius-time-picker-range-panel',
    '--cd-radius-time-picker-input',
    '--cd-shadow-time-picker-range-panel',
    '--cd-input-*',
    '--cd-color-scroll-list-*',
  ],
} as const;
