/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'TimePicker',
  category: 'input',
  description:
    '时间选择器，单选 type=time，HH:mm:ss 三列滚动选择，受控/非受控；展示经 Intl.DateTimeFormat 本地化。支持 type=timeRange 范围选择、format 字符串控制列、value 字符串入参。',
  props: [
    {
      name: 'value',
      type: 'Date | string | [Date|string|null, Date|string|null] | null',
      default: 'undefined',
    },
    {
      name: 'defaultValue',
      type: 'Date | string | [Date|string|null, Date|string|null] | null',
      default: 'null',
    },
    { name: 'type', type: "'time'|'timeRange'", default: "'time'" },
    { name: 'range', type: 'boolean', default: 'false' },
    { name: 'format', type: 'string', default: 'undefined' },
    { name: 'open', type: 'boolean', default: 'undefined' },
    { name: 'defaultOpen', type: 'boolean', default: 'false' },
    { name: 'placeholder', type: 'string', default: "'请选择时间'" },
    { name: 'size', type: "'small'|'default'|'large'", default: "'default'" },
    { name: 'status', type: "'default'|'warning'|'error'", default: "'default'" },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'clearable', type: 'boolean', default: 'true' },
    { name: 'hourStep', type: 'number', default: '1' },
    { name: 'minuteStep', type: 'number', default: '1' },
    { name: 'secondStep', type: 'number', default: '1' },
    { name: 'showSecond', type: 'boolean', default: 'true' },
    { name: 'use12Hours', type: 'boolean', default: 'false' },
    { name: 'disabledHours', type: '() => number[]', default: 'undefined' },
    { name: 'disabledMinutes', type: '(hour: number) => number[]', default: 'undefined' },
    { name: 'disabledSeconds', type: '(hour: number, minute: number) => number[]', default: 'undefined' },
    { name: 'hideDisabledOptions', type: 'boolean', default: 'false' },
    { name: 'locale', type: 'string', default: "'zh-CN'" },
    {
      name: 'onChange',
      type: '(v: (Date|null) | [Date|null, Date|null]) => void',
      default: 'undefined',
    },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '浮层溢出自动调整' },
    { name: 'autoFocus', type: 'boolean', default: 'false', desc: '挂载时自动聚焦触发器' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除按钮图标' },
    { name: 'showClear', type: 'boolean', default: 'undefined', desc: '是否显示清除按钮（clearable 别名）' },
    { name: 'dropdownClassName', type: 'string', default: 'undefined', desc: '浮层 className' },
    { name: 'dropdownMargin', type: 'number | { x?: number; y?: number }', default: 'undefined', desc: '浮层溢出冗余' },
    { name: 'dropdownStyle', type: 'string | Record<string, string>', default: 'undefined', desc: '浮层内联样式' },
    { name: 'focusOnOpen', type: 'boolean', default: 'true', desc: '打开面板时自动聚焦第一列' },
    { name: 'getPopupContainer', type: '() => HTMLElement', default: 'undefined', desc: '浮层挂载容器' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '面板展开动画' },
    { name: 'panelHeader', type: 'string | Snippet', default: 'undefined', desc: '面板顶部自定义内容' },
    { name: 'position', type: 'string', default: "'bottomLeft'", desc: '浮层弹出位置' },
    { name: 'prefix', type: 'string | Snippet', default: 'undefined', desc: '触发器前缀内容' },
    { name: 'rangeSeparator', type: 'string', default: "'~'", desc: '范围模式分隔符' },
    { name: 'scrollItemProps', type: 'Record<string, unknown>', default: 'undefined', desc: '滚动列 item 属性透传' },
    { name: 'stopPropagation', type: 'boolean', default: 'true', desc: '阻止浮层点击事件冒泡' },
    { name: 'zIndex', type: 'number', default: '1030', desc: '浮层 z-index' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined', desc: '触发器失焦' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined', desc: '触发器聚焦' },
    { name: 'onChangeWithDateFirst', type: 'boolean', default: 'false', desc: 'onChange 参数 dateFirst 模式' },
    { name: 'onClickOutSide', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击外部触发' },
    { name: 'disabledTime', type: '(date: Date) => { disabledHours?: () => number[]; disabledMinutes?: (h: number) => number[]; disabledSeconds?: (h: number, m: number) => number[] }', default: 'undefined', desc: '范围模式禁用函数' },
    { name: 'panelFooter', type: 'string | Snippet', default: 'undefined', desc: '面板底部自定义内容（在"此刻"/"确定"按钮上方插入）' },
    { name: 'inputStyle', type: 'string | Record<string, string>', default: 'undefined', desc: '输入框样式（透传到触发器 button）' },
    { name: 'inputReadOnly', type: 'boolean', default: 'false', desc: '输入框 readonly 属性（仅允许通过面板选择）' },
    { name: 'triggerRender', type: 'Snippet<[{ value: Date | null; placeholder: string; open: boolean; disabled: boolean }]>', default: 'undefined', desc: '完全自定义触发器渲染' },
    { name: 'borderless', type: 'boolean', default: 'false', desc: '无边框模式' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: 'focus 时阻止滚动' },
  ],
  a11y: {
    role: 'dialog',
    notes: [
      '触发器 button aria-haspopup=dialog、aria-expanded、aria-controls 指向面板',
      '面板 role=dialog；每列 role=listbox，项 role=option + aria-selected',
      '禁用项 aria-disabled=true 且不可点击/键选；hideDisabledOptions 时从列移除',
      '触发器 Enter/Space/↓ 打开；Esc 关闭；选项 Enter/Space 选择',
      '12h 制额外 AM/PM 列；文案经 locale TimePicker.am/pm',
      '打开时各列命令式 scrollIntoView 到选中项',
      'timeRange 模式：面板顶部 role=tablist 起止切换；确定从起跳到止',
      'format 字符串经 core parseFormatSpec 决定显示列与 12h（覆盖 showSecond/use12Hours）',
    ],
  },
  i18nKeys: ['TimePicker.placeholder', 'TimePicker.now', 'TimePicker.confirm', 'TimePicker.clear', 'TimePicker.triggerLabel', 'TimePicker.hour', 'TimePicker.minute', 'TimePicker.second', 'TimePicker.am', 'TimePicker.pm', 'TimePicker.rangeStart', 'TimePicker.rangeEnd'],
  // 全量对齐 Semi timePicker/variables.scss 的组件 token（面板分割线/描边/列宽/项高/圆角/阴影）。
  // 触发输入框复用 Input（--cd-input-* / --cd-height-input-*）、面板容器与单元格复用 DatePicker
  // （--cd-date-picker-panel-* / --cd-date-picker-cell-*），滚动列项高复用 ScrollList（--cd-scrolllist-item-height）。
  tokens: [
    '--cd-color-time-picker-range-picker-panel-split-border',
    '--cd-color-time-picker-range-panel-border',
    '--cd-width-time-picker-range-panel-border',
    '--cd-height-time-picker-panel-body',
    '--cd-height-time-picker-scrolllist-item',
    '--cd-width-time-picker-panel-list-ampm',
    '--cd-width-time-picker-panel-list-hour',
    '--cd-width-time-picker-panel-list-minute',
    '--cd-width-time-picker-panel-list-second',
    '--cd-width-time-picker-range-panel-scrolllist-body-border',
    '--cd-spacing-time-picker-range-panel-scrolllist-header-body-padding',
    '--cd-radius-time-picker-range-panel',
    '--cd-radius-time-picker-input',
    '--cd-shadow-time-picker-range-panel',
    '--cd-time-picker-time-col-width',
    '--cd-time-picker-time-item-height',
    '--cd-date-picker-panel-*',
    '--cd-date-picker-cell-*',
    '--cd-input-*',
    '--cd-focus-ring',
    '--cd-motion-*',
  ],
} as const;
