/**
 * Machine-readable component metadata for AI/docs consumption.
 * Banner — see specs/components/feedback/Banner.spec.md
 */
export const meta = {
  name: 'Banner',
  category: 'feedback',
  description:
    '横幅通知：info/success/warning/danger 四语义，full(铺满)/card(卡片) 两形态，标题 + 描述 + 语义图标；closable 受控关闭，role/aria-live 按 type 与 dynamic 推断，关闭过渡，reduced-motion 降级。内嵌文档流、非模态、不夺焦、不锁滚。受控 open 不回写，仅 onOpenChange/onClose 通知。',
  exports: ['Banner'],
  props: [
    {
      name: 'type',
      type: "'info'|'success'|'warning'|'danger'",
      default: "'info'",
      desc: '语义类型，决定背景/图标/竖条色与 role 推断',
    },
    { name: 'fullMode', type: 'boolean', default: 'true', desc: 'true 铺满(左侧竖条)；false 卡片' },
    { name: 'bordered', type: 'boolean', default: 'false', desc: 'card 模式显示 1px 边框' },
    { name: 'title', type: 'string', default: "''", desc: '标题文本，被 titleSnippet 覆盖' },
    { name: 'description', type: 'string', default: "''", desc: '描述文本，被 children 覆盖' },
    { name: 'open', type: 'boolean', default: 'undefined', desc: '受控显隐；受控时不回写' },
    { name: 'defaultOpen', type: 'boolean', default: 'true', desc: '非受控初值' },
    { name: 'closable', type: 'boolean', default: 'true', desc: '右侧关闭按钮' },
    {
      name: 'closeOnEsc',
      type: 'boolean',
      default: 'false',
      desc: '开启且可关闭时，按 Esc 关闭横幅（监听 window keydown，触发 onClose trigger:esc）',
    },
    { name: 'animation', type: 'boolean', default: 'true', desc: '关闭过渡(slide)，reduced-motion 降级' },
    {
      name: 'dynamic',
      type: 'boolean',
      default: 'false',
      desc: '是否动态插入，传给 resolveBannerRole 决定 role/aria-live',
    },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: 'region 模式的 aria-label' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '描述区主体，优先于 description' },
    { name: 'titleSnippet', type: 'Snippet', default: 'undefined', desc: '自定义标题区，覆盖 title' },
    {
      name: 'icon',
      type: 'Snippet<[{ type: BannerType }]> | boolean',
      default: 'true',
      desc: 'false 隐藏；snippet 自定义；其余真值用默认语义图标',
    },
    {
      name: 'action',
      type: 'Snippet<[{ close: () => void }]>',
      default: 'undefined',
      desc: '尾部操作区，渲染在关闭按钮前',
    },
    { name: 'closeIcon', type: 'Snippet', default: 'undefined', desc: '自定义关闭图标' },
    {
      name: 'onOpenChange',
      type: '(info: { open: boolean }) => void',
      default: 'undefined',
      desc: '显隐变更通知',
    },
    {
      name: 'onClose',
      type: "(info: { trigger: 'closeButton' | 'esc' }) => void",
      default: 'undefined',
      desc: '关闭触发通知',
    },
    { name: 'onAfterClose', type: '() => void', default: 'undefined', desc: '关闭过渡结束后回调' },
    { name: 'class', type: 'string', default: "''", desc: '附加类名' },
  ],
  events: [
    { name: 'onOpenChange', desc: '显隐状态变化（仅关闭时为 false）' },
    { name: 'onClose', desc: '关闭按钮/Esc 触发关闭' },
    { name: 'onAfterClose', desc: '关闭过渡播放结束' },
  ],
  slots: [
    { name: 'children', desc: '描述区主体，优先于 description prop' },
    { name: 'titleSnippet', desc: '自定义标题区，覆盖 title prop' },
    { name: 'icon', desc: '自定义图标，入参 { type }' },
    { name: 'action', desc: '尾部操作区，入参 { close }' },
    { name: 'closeIcon', desc: '自定义关闭图标' },
  ],
  a11y: {
    hasRole: true,
    focusable: false,
    note: 'role=alert/status/region 按 type 与 dynamic 推断（resolveBannerRole）；title→aria-labelledby、description→aria-describedby；region 模式加 aria-label；关闭按钮 aria-label「关闭」可 Tab + Enter/Space；默认图标 aria-hidden；非模态不夺焦不锁滚；reduced-motion 降级过渡。',
  },
  tokens: [
    '--cd-banner-radius',
    '--cd-banner-padding-y',
    '--cd-banner-padding-x',
    '--cd-banner-gap',
    '--cd-banner-icon-size',
    '--cd-banner-title-color',
    '--cd-banner-desc-color',
    '--cd-banner-title-size',
    '--cd-banner-desc-size',
    '--cd-banner-accent-width',
    '--cd-banner-info-bg',
    '--cd-banner-info-accent',
    '--cd-banner-success-bg',
    '--cd-banner-success-accent',
    '--cd-banner-warning-bg',
    '--cd-banner-warning-accent',
    '--cd-banner-danger-bg',
    '--cd-banner-danger-accent',
    '--cd-banner-close-color',
    '--cd-banner-close-hover-bg',
    '--cd-banner-motion-duration',
  ],
  responsive: false,
  examples: [
    { title: '页面顶部 full info', code: '<Banner title="系统提示" description="新版本已发布。" />' },
    {
      title: 'card danger 带操作',
      code: '<Banner type="danger" fullMode={false} bordered title="操作失败" description="请稍后重试。">{#snippet action({ close })}<button onclick={close}>重试</button>{/snippet}</Banner>',
    },
    {
      title: '可关闭受控',
      code: '<Banner type="success" open={visible} onOpenChange={({ open }) => (visible = open)} title="保存成功" />',
    },
  ],
} as const;
