/**
 * Machine-readable component metadata for AI/docs consumption.
 * FloatButton — 严格对齐 Semi Design。
 */
export const meta = {
  name: 'FloatButton',
  category: 'basic',
  stage: 'M1',
  semiEquivalent: 'FloatButton',
  description:
    '悬浮固定在视口的可操作按钮，用于承载全局快捷入口（AI 编辑、搜索、帮助等）。严格对齐 Semi：纯 div + onClick（非 button/a），href 靠 JS 跳转（target=_blank 用 window.open，否则 location.href），disabled 时不触发。可选包裹 Badge。形状 round(默认)/square、尺寸 small/default/large、colorful AI 渐变。默认 position:fixed 于右下角（bottom/right 24px），经 style 覆盖定位。FloatButtonGroup 将多项平铺成胶囊工具条，点击委托直接读 e.target.dataset.value 回传 value。',
  exports: ['FloatButton', 'FloatButtonGroup'],
  props: [
    { name: 'icon', type: 'Snippet', default: 'undefined', desc: '图标内容（Snippet）' },
    { name: 'badge', type: 'BadgeProps', default: 'undefined', desc: '徽章参数（复用本库 Badge：dot/count/overflowCount/type/theme），有值时外层包裹 Badge' },
    { name: 'shape', type: "'round'|'square'", default: "'round'", desc: '形状：round=正圆（默认）、square=方形（对齐 Semi）' },
    { name: 'size', type: "'small'|'default'|'large'", default: "'default'", desc: '尺寸三档（24/32/40px）' },
    { name: 'colorful', type: 'boolean', default: 'false', desc: 'AI 风格多彩渐变外观' },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用（不触发跳转/onClick）' },
    { name: 'href', type: 'string', default: 'undefined', desc: '有值时点击经 JS 跳转（对齐 Semi：_blank 用 window.open，否则 location.href）' },
    { name: 'target', type: 'string', default: 'undefined', desc: "链接打开目标；'_blank' 时用 window.open 新开" },
    { name: 'onClick', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击回调；disabled 时不触发' },
    { name: 'class', type: 'string', default: "''", desc: '根节点自定义类名' },
    { name: 'style', type: 'string', default: 'undefined', desc: '定位方式：设 bottom/right 等覆盖默认 fixed 位置' },
  ],
  events: [
    { name: 'onClick', payload: 'MouseEvent', desc: '点击；disabled 时不触发' },
  ],
  slots: [
    { name: 'icon', desc: '图标内容（也可用 icon prop）' },
  ],
  subComponents: [
    {
      name: 'FloatButtonGroup',
      usage: '<FloatButtonGroup items={...} onClick={(value, e) => {}} />',
      desc: '胶囊工具条（严格对齐 Semi）：一个背景圆角条内 inline-flex 横排多个「图标+文字」项（纯 div），点击委托直接读 e.target.dataset.value 回传 value。',
      props: [
        { name: 'items', type: 'FloatButtonGroupItem[]', default: '[]', desc: '子项数组；每项 = FloatButtonProps + { value: string; content?: Snippet|string }' },
        { name: 'disabled', type: 'boolean', default: 'false', desc: '组级禁用（不触发点击）' },
        { name: 'onClick', type: '(value: string, e: MouseEvent) => void', default: 'undefined', desc: '组级点击委托，回传被点项 value（直接读 e.target.dataset.value）' },
        { name: 'class', type: 'string', default: "''", desc: '根节点自定义类名' },
        { name: 'style', type: 'string', default: 'undefined', desc: '定位方式，同 FloatButton' },
      ],
    },
  ],
  a11y: {
    role: 'none',
    keyboard: [],
    hasRole: false,
    focusable: false,
    note: '严格对齐 Semi：FloatButton 与 FloatButtonGroup 均为纯 div + onClick（非 button/a），无内置 ARIA 语义、无键盘可达、无 focus 环。href 经 JS 跳转而非原生链接。如需可访问性由消费方在业务层补充。',
  },
  i18n: [],
  tokens: [
    '--cd-floatbutton-size-small',
    '--cd-floatbutton-size-default',
    '--cd-floatbutton-size-large',
    '--cd-floatbutton-radius-round',
    '--cd-floatbutton-radius-square',
    '--cd-floatbutton-bg',
    '--cd-floatbutton-bg-hover',
    '--cd-floatbutton-bg-active',
    '--cd-floatbutton-color',
    '--cd-floatbutton-shadow',
    '--cd-floatbutton-disabled-bg',
    '--cd-floatbutton-disabled-text',
    '--cd-floatbutton-colorful-bg',
    '--cd-floatbutton-colorful-bg-hover',
    '--cd-floatbutton-colorful-bg-active',
    '--cd-floatbutton-colorful-text',
    '--cd-floatbutton-bottom',
    '--cd-floatbutton-right',
    '--cd-floatbutton-z',
    '--cd-floatbutton-group-bg',
    '--cd-floatbutton-group-shadow',
    '--cd-floatbutton-group-radius',
    '--cd-floatbutton-group-padding',
    '--cd-floatbutton-group-gap',
    '--cd-floatbutton-group-bottom',
    '--cd-floatbutton-group-right',
    '--cd-floatbutton-group-item-padding-y',
    '--cd-floatbutton-group-item-padding-x',
    '--cd-floatbutton-group-item-gap',
    '--cd-floatbutton-group-item-radius',
    '--cd-floatbutton-group-item-color',
    '--cd-floatbutton-group-item-bg-hover',
    '--cd-floatbutton-group-item-bg-active',
    '--cd-floatbutton-group-item-font-size',
    '--cd-floatbutton-group-item-line-height',
    '--cd-floatbutton-group-item-font-weight',
  ],
  responsive: false,
  doNot: [
    '不要期望键盘可达 / 原生焦点：对齐 Semi 是纯 div，无内置 a11y 语义',
    '不要用 href 期望渲染 <a>：本组件经 JS 跳转（对齐 Semi）',
    '不要在 Group item 上依赖冒泡查找 data-value：对齐 Semi 直接读 e.target.dataset.value',
  ],
  examples: [
    { title: '单悬浮按钮', code: '<FloatButton style="bottom:24px;right:24px">{#snippet icon()}?{/snippet}</FloatButton>' },
    { title: '带徽章', code: '<FloatButton badge={{ count: 3 }} />' },
    { title: 'colorful', code: '<FloatButton colorful />' },
    { title: 'href 跳转', code: '<FloatButton href="/docs" target="_blank" />' },
    { title: 'Group 平铺', code: '<FloatButtonGroup items={[{ value: "help", content: "帮助" }]} onClick={(v) => {}} />' },
  ],
} as const;
