/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'DatePicker',
  category: 'input',
  description:
    '日期选择器（对齐 Semi 单组件 + 7 值 type 枚举）：type ∈ date/dateRange/year/month/monthRange/dateTime/dateTimeRange。range 类型渲染双面板 + 起止双输入框触发器（rangeInputFocus 焦点驱动、自动排序、跨面板 hover 预览区间），受控/非受控；显示与星期/月份/年份均经 Intl.DateTimeFormat 本地化。支持 multiple 多选（仅 date，value 为 Date[]、max 上限）、presets 快捷选项（可置四向）、format token 串使触发器变可输入文本框、disabledDate/disabledTime 禁用、maxRange 跨度、startDateOffset/endDateOffset 周选择、syncSwitchMonth 双面板同步翻月、timePickerOpts 透传、密度/无边框/自定义单元格与触发器渲染、面板四向 slot。',
  props: [
    { name: 'type', type: "'date'|'dateRange'|'year'|'month'|'monthRange'|'dateTime'|'dateTimeRange'", default: "'date'", desc: '对齐 Semi TYPE_SET：单组件靠 type 承载 7 种形态（含 3 range）' },
    { name: 'value', type: 'Date | Date[] | [Date|null, Date|null] | null', default: 'undefined', desc: '单选 Date；multiple 为 Date[]；range 为 [start,end] 元组' },
    { name: 'defaultValue', type: 'Date | Date[] | [Date|null, Date|null] | null', default: 'null' },
    { name: 'open', type: 'boolean', default: 'undefined' },
    { name: 'defaultOpen', type: 'boolean', default: 'false' },
    { name: 'placeholder', type: 'string', default: "'请选择日期'" },
    { name: 'startPlaceholder', type: 'string', default: "'开始日期'", desc: 'range 起始输入框占位' },
    { name: 'endPlaceholder', type: 'string', default: "'结束日期'", desc: 'range 结束输入框占位' },
    { name: 'size', type: "'small'|'default'|'large'", default: "'default'" },
    { name: 'validateStatus', type: "'default'|'warning'|'error'", default: "'default'", desc: '校验态（对齐 Semi validateStatus）' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'disabledDate', type: '(date: Date) => boolean', default: 'undefined' },
    {
      name: 'disabledTime',
      type: '(date: Date) => { disabledHours?: () => number[]; disabledMinutes?: (hour: number) => number[]; disabledSeconds?: (hour: number, minute: number) => number[] }',
      default: 'undefined',
    },
    {
      name: 'presets',
      type: '{ label: string; value: Date | (() => Date) | [Date, Date] | (() => [Date, Date]) }[]',
      default: 'undefined',
      desc: '快捷选项：单选给 Date，range 给 [start,end] 元组（点击即时求值）',
    },
    { name: 'locale', type: 'string', default: "'zh-CN'" },
    { name: 'maxRange', type: 'number', default: 'undefined', desc: 'range 起止跨度上限（天）；选定起始后超出的日期禁用' },
    { name: 'startDateOffset', type: '(date: Date) => Date', default: 'undefined', desc: '单击范围选择（周选择）：与 endDateOffset 同提供，单击某日即选定 [startDateOffset(clicked), endDateOffset(clicked)]；仅 dateRange/dateTimeRange' },
    { name: 'endDateOffset', type: '(date: Date) => Date', default: 'undefined', desc: '单击范围选择的结束偏移' },
    { name: 'syncSwitchMonth', type: 'boolean', default: 'false', desc: 'range 双面板同步翻月（对齐 Semi）' },
    { name: 'rangeSeparatorNode', type: 'Snippet | string', default: 'undefined', desc: 'range 起止输入框之间的自定义分隔节点' },
    { name: 'timePickerOpts', type: '{ showSecond?: boolean; use12Hours?: boolean }', default: 'undefined', desc: '透传给内部时间列的配置（对齐 Semi timePickerOpts）' },
    { name: 'defaultPickerValue', type: 'Date | Date[]', default: 'undefined', desc: '面板初始定位日期（非受控，不改选中值）；仅无选中值时 seed 面板游标显示的月/年' },
    { name: 'timeZone', type: 'string', default: 'undefined', desc: '按 IANA 时区显示（仅格式化层注入 Intl { timeZone }；不做完整跨时区值转换，底层 Date 绝对时刻不变）' },
    { name: 'format', type: 'string', default: 'undefined' },
    { name: 'onChange', type: '(value: Date | Date[] | [Date|null, Date|null] | null, dateString: string) => void', default: 'undefined', desc: '值变化回调；第二参 dateString 为格式化字符串（range 用 rangeSeparator 连接），参数顺序由 onChangeWithDateFirst 控制' },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'onPanelChange', type: '(e: { panelDate: Date }) => void', default: 'undefined' },
    {
      name: 'onPresetClick',
      type: '(item: Preset, e?: MouseEvent) => void',
      default: 'undefined',
      desc: '点击快捷选项（对齐 Semi (item, e)）',
    },
    { name: 'onClear', type: '(e: {}) => void', default: 'undefined' },
    { name: 'onConfirm', type: '(e: { value: Date | Date[] | [Date|null, Date|null] | null }) => void', default: 'undefined' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'insetLabel', type: 'string | Snippet', default: 'undefined', desc: '内嵌标签：浮入触发器左侧的常驻标签（纯展示，不影响值/解析）' },
    { name: 'insetLabelId', type: 'string', default: 'undefined', desc: 'insetLabel 的 id，经 aria-labelledby 关联触发器 combobox（仅 insetLabel 存在时生效）' },
    { name: 'rangeSeparator', type: 'string', default: "' ~ '", desc: '范围日期分隔符（对齐 Semi DEFAULT_SEPARATOR_RANGE）' },
    { name: 'autoSwitchDate', type: 'boolean', default: 'true', desc: '年月滚轮（PANEL_YAM）里选完年/月后自动切回日期网格视图（仅 type=date/dateTime）' },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '浮层自动调整位置防溢出' },
    { name: 'insetInput', type: 'boolean', default: 'false', desc: "在面板顶部内嵌可编辑输入框（仅 type=date/dateTime）：date 一个日期框，dateTime 日期框+时间框；与面板选择双向同步，键入解析复用 formatDate/parseDateString" },
    { name: 'position', type: 'string', default: "'bottomLeft'", desc: '浮层弹出位置' },
    { name: 'spacing', type: 'number', default: 'undefined', desc: '触发器与浮层间距' },
    { name: 'getPopupContainer', type: '() => HTMLElement', default: 'undefined', desc: '浮层挂载容器' },
    { name: 'weekStartsOn', type: '0|1|2|3|4|5|6', default: '0', desc: '一周起始日（0=周日 … 6=周六）' },
    { name: 'onCancel', type: '() => void', default: 'undefined', desc: '点击取消按钮（对齐 Semi 无参）' },
    { name: 'onChangeWithDateFirst', type: 'boolean', default: 'true', desc: 'true→onChange(value, dateString)（默认，value-first）；false→onChange(dateString, value)' },
    { name: 'onClickOutSide', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击外部关闭时触发' },
    { name: 'borderless', type: 'boolean', default: 'false', desc: '无边框模式' },
    { name: 'density', type: "'default' | 'compact'", default: "'default'", desc: 'compact 时面板更紧凑' },
    { name: 'prefix', type: 'Snippet | string', default: 'undefined', desc: '触发器前缀内容，渲染在 input 左侧' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除按钮图标' },
    { name: 'showClear', type: 'boolean', default: 'true', desc: '是否显示清除按钮（对齐 Semi 单一 showClear）' },
    { name: 'inputReadOnly', type: 'boolean', default: 'false', desc: '输入框 readonly 属性' },
    { name: 'inputStyle', type: 'CSSProperties | string', default: 'undefined', desc: '输入框内联样式' },
    { name: 'autoFocus', type: 'boolean', default: 'false', desc: '挂载时自动聚焦' },
    { name: 'dropdownClassName', type: 'string', default: 'undefined', desc: '下拉浮层 className' },
    { name: 'dropdownStyle', type: 'CSSProperties | string', default: 'undefined', desc: '下拉浮层样式' },
    { name: 'dropdownMargin', type: 'number | { x?: number; y?: number }', default: 'undefined', desc: '浮层溢出冗余值' },
    { name: 'zIndex', type: 'number', default: '1030', desc: '浮层 z-index' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '面板展开动画，false 时添加 cd-date-picker--no-motion' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: '聚焦时阻止滚动' },
    { name: 'stopPropagation', type: 'boolean', default: 'true', desc: '阻止浮层点击事件冒泡' },
    { name: 'topSlot', type: 'Snippet', default: 'undefined', desc: '面板顶部额外区域' },
    { name: 'bottomSlot', type: 'Snippet', default: 'undefined', desc: '面板底部额外区域' },
    { name: 'leftSlot', type: 'Snippet', default: 'undefined', desc: '面板左侧额外区域' },
    { name: 'rightSlot', type: 'Snippet', default: 'undefined', desc: '面板右侧额外区域' },
    { name: 'multiple', type: 'boolean', default: 'false', desc: "多选（仅 type='date'），value 变为 Date[]" },
    { name: 'max', type: 'number', default: 'undefined', desc: 'multiple=true 时最多选择数量' },
    { name: 'startYear', type: 'number', default: 'undefined', desc: '年份滚轮最小年' },
    { name: 'endYear', type: 'number', default: 'undefined', desc: '年份滚轮最大年' },
    { name: 'renderDate', type: 'Snippet<[{ day: number; fullDate: string }]>', default: 'undefined', desc: '自定义日期单元格内容' },
    { name: 'renderFullDate', type: 'Snippet<[{ day: number; fullDate: string; dayStatus: DayStatus }]>', default: 'undefined', desc: '完全自定义日期格子' },
    { name: 'triggerRender', type: 'Snippet<[{ value: Date | Date[] | [Date|null, Date|null] | null; placeholder: string }]>', default: 'undefined', desc: '完全自定义触发器' },
    { name: 'hideDisabledOptions', type: 'boolean', default: 'false', desc: '隐藏禁止的时间选项' },
    { name: 'disabledTimePicker', type: 'boolean', default: 'false', desc: '禁止时间选择' },
    { name: 'needConfirm', type: 'boolean', default: 'undefined', desc: '需点击确认才写入（dateTimeRange 默认 true，其它默认 false，对齐 Semi）' },
    { name: 'presetPosition', type: "'left'|'right'|'top'|'bottom'", default: "'bottom'", desc: '快捷选项列表位置' },
    { name: 'yearAndMonthOpts', type: '{ yearCyclic?: boolean; monthCyclic?: boolean } | Record<string, unknown>', default: 'undefined', desc: '透传给年月 ScrollList 的参数' },
    { name: 'class', type: 'string', default: "''", desc: '根节点自定义类名（对齐 Semi className）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根节点内联样式' },
  ],
  methods: [
    { name: 'open()', desc: '命令式展开面板（对齐 Semi）' },
    { name: 'close()', desc: '命令式关闭面板（对齐 Semi）' },
    { name: 'focus()', desc: '命令式聚焦触发器（尊重 preventScroll，对齐 Semi）' },
    { name: 'blur()', desc: '命令式移除触发器焦点（对齐 Semi）' },
  ],
  a11y: {
    role: 'dialog',
    notes: [
      '触发器 button aria-haspopup=dialog、aria-expanded、aria-controls 指向面板',
      '面板 role=dialog；日期网格 role=grid，单元格 role=gridcell + aria-selected',
      '触发器 Enter/Space/↓ 打开；面板内方向键移动高亮日、Enter 选中、Esc 关闭',
      'roving tabindex：仅高亮日可聚焦',
      'type=dateTime：时/分/秒列 role=listbox + option，选日期不关面板，点确定关闭',
      'disabledTime：dateTime 时/分/秒列被禁用值 aria-disabled、点击/键盘无效（分/秒列联动已选时/分）',
      'presets：面板侧边快捷日期按钮 role=group，点击直接选中（dateTime 连带时间）并关闭',
      'type=month：12 个月格，头部显示年份 + 左右切年；点月份选中并关闭',
      'type=year：一页 12 年（一十年 + 前后各 1 占位），头部显示十年范围 + 左右切十年；点年份选中并关闭',
      'format：传 token 串（YYYY/MM/DD/HH/mm/ss）时触发器变 text 输入框，显示+手输解析均走 formatDate/parseDateString；不传沿用 Intl 显示',
      'insetInput：面板顶部渲染可编辑输入框（date 一个日期框；dateTime 日期框+时间框），键盘用户可直接键入起止日期；Enter/blur 提交解析，Esc 关闭；与日历/时间列选择双向同步',
      '年月滚轮快速跳转（PANEL_YAM，对齐 Semi）：点头部年/月标题（button aria-expanded）展开年 + 月两列 ScrollList（复用 ScrollList，role=listbox 逐列），选中即跳转面板游标（不写 value），「返回」按钮回日期网格；yearAndMonthOpts.yearCyclic/monthCyclic 控制列循环滚动；type=year 面板仍走十年格，不进滚轮',
    ],
  },
  tokens: [
    '--cd-date-picker-*',
    '--cd-color-date-picker-*',
    '--cd-width-date-picker-*',
    '--cd-height-date-picker-*',
    '--cd-spacing-date-picker-*',
    '--cd-radius-date-picker-*',
    '--cd-font-date-picker-*',
    '--cd-line-height-date-picker-*',
    '--cd-transition-date-picker-*',
    '--cd-input-*',
    '--cd-focus-ring',
    '--cd-motion-*',
  ],
} as const;
