/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'RangePicker',
  category: 'input',
  description:
    '日期范围选择器，双面板（两个月并排，右面板=左面板+1）序列选择（点起始→点结束，自动排序、起止可跨面板、hover 跨面板预览区间），受控/非受控；显示与星期/月份均经 Intl.DateTimeFormat 本地化。type=dateTimeRange 时在双日期面板右侧各挂一组时/分/秒时间列（复用 DatePicker dateTime 列逻辑），起止各自携带时分秒；needConfirm（dateTimeRange 默认 true）时选择进 pending 缓冲，点确定才提交。支持 showSecond/disabledTime/disabledTimePicker/hideDisabledOptions（语义与 DatePicker dateTime 一致）。type=monthRange（对齐 Semi）时改用双「月份」面板（各 12 个月格，头部年份 + 左右切年、左右面板相邻两年）选起止月，value=[起始月, 结束月]（Date 落在该月 1 号），区间高亮/hover 预览按月粒度；不含时间列，maxRange 不适用。',
  props: [
    { name: 'type', type: "'dateRange'|'dateTimeRange'|'monthRange'", default: "'dateRange'", desc: 'dateRange 纯日期范围 / dateTimeRange 带时间范围（每端时/分/秒列 + 确认）/ monthRange 月份范围（双月份面板选起止月）' },
    { name: 'value', type: '[Date|null, Date|null] | null', default: 'undefined' },
    { name: 'defaultValue', type: '[Date|null, Date|null] | null', default: 'null' },
    { name: 'open', type: 'boolean', default: 'undefined' },
    { name: 'defaultOpen', type: 'boolean', default: 'false' },
    { name: 'startPlaceholder', type: 'string', default: "'开始日期'" },
    { name: 'endPlaceholder', type: 'string', default: "'结束日期'" },
    { name: 'size', type: "'small'|'default'|'large'", default: "'default'" },
    { name: 'status', type: "'default'|'warning'|'error'", default: "'default'" },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'clearable', type: 'boolean', default: 'true' },
    { name: 'disabledDate', type: '(date: Date) => boolean', default: 'undefined' },
    {
      name: 'disabledTime',
      type: '(date: Date) => { disabledHours?: () => number[]; disabledMinutes?: (hour: number) => number[]; disabledSeconds?: (hour: number, minute: number) => number[] }',
      default: 'undefined',
      desc: 'dateTimeRange：按日期返回各时间列禁用值（分/秒列联动已选时/分）',
    },
    { name: 'showSecond', type: 'boolean', default: 'true', desc: 'dateTimeRange：是否显示秒列' },
    { name: 'hideDisabledOptions', type: 'boolean', default: 'false', desc: 'dateTimeRange：隐藏被禁用的时间选项（默认仅置灰）' },
    { name: 'disabledTimePicker', type: 'boolean', default: 'false', desc: 'dateTimeRange：禁止时间列（只保留日期面板 + 确认）' },
    { name: 'needConfirm', type: 'boolean', default: 'undefined', desc: '需点击确认才提交（dateTimeRange 默认 true，dateRange 默认 false）' },
    { name: 'maxRange', type: 'number', default: 'undefined' },
    { name: 'startDateOffset', type: '(date: Date) => Date', default: 'undefined', desc: '单击范围选择：与 endDateOffset 同时提供后，单击某日即选定 [startDateOffset(clicked), endDateOffset(clicked)]（如周选择），一步完成不进两步；仅 dateRange/dateTimeRange 生效' },
    { name: 'endDateOffset', type: '(date: Date) => Date', default: 'undefined', desc: '单击范围选择的结束偏移；与 startDateOffset 同时提供才生效' },
    { name: 'weekStart', type: '0 | 1', default: '0' },
    { name: 'locale', type: 'string', default: "'zh-CN'" },
    { name: 'presets', type: '{ label: string; value: [Date, Date] | (() => [Date, Date]) }[]', default: 'undefined', desc: '快捷区间列表：点击直接选定整段 [start, end]（惰性 value 即时求值、自动排序）；needConfirm 时进 pending 缓冲否则直接提交并关面板；monthRange 时 value 落每月 1 号' },
    { name: 'presetPosition', type: "'left' | 'right' | 'top' | 'bottom'", default: "'bottom'", desc: '快捷区间列表位置（left/right 竖排并列于面板侧，top/bottom 横排于面板上/下）' },
    { name: 'onChange', type: '(v: [Date|null,Date|null] | null) => void', default: 'undefined' },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'onPanelChange', type: '(e: { panelDate: Date }) => void', default: 'undefined' },
    { name: 'onClear', type: '(e: {}) => void', default: 'undefined' },
    { name: 'onPresetClick', type: '(e: { preset: { label: string; value: [Date, Date] | (() => [Date, Date]) } }) => void', default: 'undefined', desc: '点击快捷区间选项' },
    { name: 'onConfirm', type: '(e: { value: [Date|null,Date|null] | null }) => void', default: 'undefined', desc: '点击确认按钮（needConfirm）' },
    { name: 'onCancel', type: '(e: { value: [Date|null,Date|null] | null }) => void', default: 'undefined', desc: '点击取消按钮（needConfirm）' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'position', type: 'string', default: "'bottomLeft'", desc: '浮层弹出位置' },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '浮层自动调整位置防溢出' },
    { name: 'spacing', type: 'number', default: 'undefined', desc: '触发器与浮层间距（px）' },
    { name: 'getPopupContainer', type: '() => HTMLElement', default: 'undefined', desc: '浮层挂载容器' },
    { name: 'dropdownMargin', type: 'number | { x?: number; y?: number }', default: 'undefined', desc: '浮层相对触发器的额外偏移' },
    { name: 'class', type: 'string', default: "''", desc: '根节点自定义类名（对齐 Semi className）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根节点内联样式' },
  ],
  methods: [
    { name: 'open()', desc: '命令式展开面板（对齐 Semi）' },
    { name: 'close()', desc: '命令式关闭面板（对齐 Semi）' },
    { name: "focus(focusType?: 'rangeStart'|'rangeEnd')", desc: '命令式聚焦触发器（单触发器结构下 focusType 退化为聚焦整体，签名对齐 Semi）' },
    { name: 'blur()', desc: '命令式移除触发器焦点（对齐 Semi）' },
  ],
  a11y: {
    role: 'dialog',
    notes: [
      '触发器 button aria-haspopup=dialog、aria-expanded、aria-controls 指向面板',
      '面板 role=dialog；左右各一 role=grid（aria-label 为各自月份），单元格 role=gridcell + aria-selected（端点）',
      '双面板并排显示相邻两月：最左「上一月」、最右「下一月」整体翻页；第一次点击设起始、第二次设结束并自动排序，起止可跨面板；hover 跨面板实时预览区间',
      'maxRange：选定起始后，离起点超过 maxRange 天的日期 aria-disabled 置灰、点击/hover 无效（daysBetween 纯函数判定）',
      'startDateOffset/endDateOffset（单击范围选择，如周选择）：两者都提供时单击某日即选定整个区间 [startDateOffset(clicked), endDateOffset(clicked)]，不进「点起始→点结束」两步；悬停整段预览高亮；仅 dateRange/dateTimeRange 生效',
      '触发器 Enter/Space/↓ 打开、Esc 关闭',
      'type=dateTimeRange：面板右侧挂起/止两组时/分/秒列 role=listbox + option；时间列作用于当前激活端 activeEnd（选起始日/点左侧列=start，选结束日/点右侧列=end），激活端有 --active 底色标示',
      'dateTimeRange 默认 needConfirm=true：选择进 pending 缓冲，footer「确定」提交、「取消」回退并关闭',
      'disabledTime：dateTimeRange 时/分/秒列被禁用值 aria-disabled、点击/键盘无效（分/秒列联动激活端已选时/分）',
      'type=monthRange：左右各一 role=grid 的 12 月格（3 列大格），头部显示年份 + 左右按钮切年（左右面板相邻两年）；点起始月→点结束月自动排序、起止可跨面板、hover 跨面板预览区间；单元格 role=gridcell + aria-selected（端点）。选完即提交 onChange（无确认、无时间列）',
    ],
  },
  tokens: [
    '--cd-date-picker-*',
    '--cd-color-date-picker-*',
    '--cd-date-picker-inline-time-col-width',
    '--cd-date-picker-inline-time-item-height',
    '--cd-input-*',
    '--cd-focus-ring',
    '--cd-motion-*',
  ],
} as const;
