/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Popover',
  category: 'show',
  description:
    '气泡卡片，点击/悬停/聚焦触发元素时弹出富内容浮层。支持标题、常用 position、对齐、箭头与间距，浮层纯 CSS 定位。',
  props: [
    { name: 'content', type: 'string | Snippet', default: 'undefined', desc: '简单文本内容' },
    { name: 'title', type: 'string | Snippet', default: 'undefined', desc: '标题，提供则渲染标题区与下边框' },
    { name: 'open', type: 'boolean', default: 'undefined', desc: '受控显隐' },
    { name: 'defaultOpen', type: 'boolean', default: 'false', desc: '非受控初始显隐' },
    { name: 'trigger', type: "'hover'|'click'|'focus'|'custom'", default: 'hover', desc: "触发方式；custom 时显隐完全由受控 open + onOpenChange 控制，不自动响应交互、不启用外部点击/Esc 关闭" },
    { name: 'position', type: "'top'|'bottom'|'left'|'right'", default: 'bottom', desc: '浮层主方向' },
    { name: 'align', type: "'start'|'center'|'end'", default: 'center', desc: '交叉轴对齐' },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '视口溢出时翻转到对侧' },
    { name: 'showArrow', type: 'boolean', default: 'true', desc: '是否显示箭头' },
    {
      name: 'arrowPointAtCenter',
      type: 'boolean',
      default: 'false',
      desc: 'start/end 对齐时箭头指向触发器中心',
    },
    { name: 'spacing', type: 'number', default: '8', desc: '浮层与触发器间距(px)' },
    { name: 'mouseEnterDelay', type: 'number', default: '100', desc: 'hover 进入延迟(ms)' },
    { name: 'mouseLeaveDelay', type: 'number', default: '100', desc: 'hover 离开延迟(ms)' },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用触发' },
    {
      name: 'getPopupContainer',
      type: '() => HTMLElement',
      default: '() => body',
      desc: '浮层挂载容器，回退 ConfigProvider 全局再回退 body',
    },
    { name: 'zIndex', type: 'number', default: 'var(--cd-popover-z)', desc: '浮层层级' },
    {
      name: 'trapFocus',
      type: 'boolean',
      default: "trigger==='click'",
      desc: '是否陷入焦点（Tab 循环）',
    },
    {
      name: 'returnFocus',
      type: 'boolean',
      default: 'true',
      desc: '关闭后焦点是否归还触发器（仅 trapFocus 生效）',
    },
    { name: 'closeOnEsc', type: 'boolean', default: 'true', desc: 'Esc 关闭' },
    {
      name: 'closeOnOutsideClick',
      type: 'boolean',
      default: 'true',
      desc: '外部点击关闭',
    },
    { name: 'lockScroll', type: 'boolean', default: 'false', desc: '打开时锁定背景滚动' },
    {
      name: 'destroyOnClose',
      type: 'boolean',
      default: 'false',
      desc: '关闭时销毁浮层 DOM',
    },
    {
      name: 'rememberFocus',
      type: 'boolean',
      default: 'false',
      desc: '重新打开时恢复上次浮层内焦点位置（仅 trapFocus 生效）',
    },
    {
      name: 'stopPropagation',
      type: 'boolean',
      default: 'false',
      desc: '阻断浮层内事件冒泡',
    },
    {
      name: 'size',
      type: "'small'|'default'|'large'",
      default: 'default',
      desc: '内边距尺寸档位',
    },
    {
      name: 'motion',
      type: 'boolean | { duration?: number }',
      default: 'true',
      desc: '动画开关/配置，reduced-motion 退化',
    },
    { name: 'showCloseButton', type: 'boolean', default: 'false', desc: '浮层右上角显示关闭按钮' },
    { name: 'closeIcon', type: 'Snippet', default: 'undefined', desc: '自定义关闭按钮图标（showCloseButton=true 时有效）' },
    { name: 'okText', type: 'string', default: 'undefined', desc: '确定按钮文案（默认来自 locale）' },
    { name: 'cancelText', type: 'string', default: 'undefined', desc: '取消按钮文案（默认来自 locale）' },
    { name: 'okButtonProps', type: 'Record<string, unknown>', default: 'undefined', desc: '透传给确定 Button 的 props' },
    { name: 'cancelButtonProps', type: 'Record<string, unknown>', default: 'undefined', desc: '透传给取消 Button 的 props' },
    { name: 'onOk', type: '() => void', default: 'undefined', desc: '点击确定按钮回调' },
    { name: 'onCancel', type: '() => void', default: 'undefined', desc: '点击取消按钮回调' },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '触发元素（必填）' },
    { name: 'contentSlot', type: 'Snippet', default: 'undefined', desc: '富内容，优先于 content' },
  ],
  a11y: {
    role: 'dialog',
    keyboard: ['Escape', 'Tab', 'Shift+Tab'],
    notes: [
      '浮层 role=dialog aria-modal=false，使用 useId 生成唯一 id；有标题时 aria-labelledby，无标题兜底 aria-label（Popover.dialogLabel）',
      '触发元素 aria-haspopup=dialog + aria-expanded，open 时 aria-controls 指向浮层',
      'click 触发用 useDismiss 处理 Escape（closeOnEsc）与外部点击（closeOnOutsideClick）关闭',
      'trapFocus（默认随 click）用 useFocusTrap 陷入焦点并循环 Tab，关闭后 returnFocus 归还触发器；rememberFocus 可恢复上次焦点',
      'lockScroll 用 useScrollLock 锁背景滚动；motion 进场动画在 reduced-motion 下退化',
      'custom 触发完全受控，不启用 useDismiss，由调用方控制显隐',
    ],
  },
  tokens: [
    // chenzy-design Popover 运行时消费的组件 token（浮层/箭头/标题/动画/层级）
    '--cd-popover-*',
    // Semi 全量对齐 token（semi-foundation/popover/variables.scss，22 变量）
    '--cd-color-popover-bg-default',
    '--cd-color-popover-border-default',
    '--cd-color-popover-arrow-bg',
    '--cd-color-popover-arrow-border',
    '--cd-color-tooltip-arrow-icon-default',
    '--cd-width-popover-arrow',
    '--cd-height-popover-arrow',
    '--cd-width-popover-arrow-vertical',
    '--cd-height-popover-arrow-vertical',
    '--cd-width-tooltip-arrow',
    '--cd-height-tooltip-arrow',
    '--cd-width-tooltip-arrow-vertical',
    '--cd-height-tooltip-arrow-vertical',
    '--cd-width-popover-title-border',
    '--cd-spacing-popover-title-padding',
    '--cd-spacing-popover-witharrow-padding',
    '--cd-spacing-popover-arrow-adjusted-offset-y',
    '--cd-spacing-tooltip-arrow-adjusted-offset-y',
    '--cd-spacing-tooltip-arrow-adjusted-offset-x',
    '--cd-radius-popover',
    '--cd-filter-popover-bg',
    // 其它复用
    '--cd-spacing-*',
    '--cd-focus-ring',
    '--cd-motion-*',
  ],
} as const;
