/**
 * Machine-readable component metadata for AI/docs consumption.
 * Calendar — see specs/components/show/Calendar.spec.md
 */
export const meta = {
  name: 'Calendar',
  category: 'show',
  description:
    '月/周/日视图日历：日格网格 + 事件展示与 +N 折叠，today/selected/outside/weekend/disabled 态、导航（上一/今天/下一，月或周或天）；mode 切换月(6×7)/周(1×7)/日(单日时间轴)视图，day 模式纵向列出小时段(dayStartHour~dayEndHour)，带时间的事件按起始小时入对应时段、全天或跨天延续事件入顶部「全天」区，selectionMode 切换单选(selectedDate)/范围(rangeValue，起止+区间高亮+hover 预览)。受控 value(锚点)/selectedDate/rangeValue 不回写，仅通过 onChange/onSelect/onRangeChange/onDateClick/onMoreClick 通知。弹层、虚拟化延后。',
  exports: ['Calendar'],
  props: [
    { name: 'value', type: 'Date', default: 'undefined', desc: '受控锚点日期(决定展示月份/周)，受控时不回写' },
    { name: 'defaultValue', type: 'Date', default: 'new Date()', desc: '非受控初始锚点' },
    { name: 'mode', type: "'month' | 'week' | 'day'", default: "'month'", desc: '视图模式：月(6×7)/周(1×7)/日(单日时间轴)' },
    { name: 'selectionMode', type: "'single' | 'range'", default: "'single'", desc: '选择模式：单选或范围' },
    { name: 'events', type: 'CalendarEvent[]', default: '[]', desc: '事件列表' },
    { name: 'weekStartsOn', type: '0|1|2|3|4|5|6', default: '0', desc: '一周起始(0=周日)' },
    { name: 'maxEventsPerDay', type: 'number', default: '3', desc: '每格最多事件数，超出折叠 +N（month/week）' },
    { name: 'dayStartHour', type: 'number', default: '0', desc: 'day 视图时间轴起始小时(0-23)' },
    { name: 'dayEndHour', type: 'number', default: '23', desc: 'day 视图时间轴结束小时(0-23，含)' },
    { name: 'weekendDays', type: 'number[]', default: '[0, 6]', desc: '周末列序号' },
    { name: 'markWeekend', type: 'boolean', default: 'true', desc: '弱化高亮周末列' },
    { name: 'disabledDate', type: '(date: Date) => boolean', default: 'undefined', desc: '命中则该格禁用' },
    { name: 'selectedDate', type: 'Date', default: 'undefined', desc: '受控选中日(边框态，single 模式)，受控时不回写' },
    { name: 'defaultSelectedDate', type: 'Date', default: 'undefined', desc: '非受控选中日初值' },
    { name: 'rangeValue', type: '[Date, Date] | null', default: 'undefined', desc: '受控选中范围(range 模式)，受控时不回写' },
    { name: 'defaultRangeValue', type: '[Date, Date] | null', default: 'undefined', desc: '非受控范围初值' },
    { name: 'locale', type: 'string', default: "'zh-CN'", desc: 'Intl 月份/星期名格式化语言' },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '网格 aria-label，默认取月份标题' },
    { name: 'onChange', type: '(info: { value: Date }) => void', default: 'undefined' },
    { name: 'onSelect', type: '(info: { date: Date }) => void', default: 'undefined' },
    { name: 'onRangeChange', type: '(info: { range: [Date, Date] }) => void', default: 'undefined' },
    { name: 'onDateClick', type: '(info: { date: Date }) => void', default: 'undefined' },
    {
      name: 'onMoreClick',
      type: '(info: { date: Date; events: CalendarEvent[] }) => void',
      default: 'undefined',
    },
    { name: 'dateCell', type: 'Snippet', default: 'undefined', desc: '自定义整格内容' },
    { name: 'event', type: 'Snippet', default: 'undefined', desc: '自定义事件块' },
  ],
  events: [
    { name: 'onChange', desc: '锚点(翻月/翻周/今天)变化' },
    { name: 'onSelect', desc: '选中某日(single 模式)' },
    { name: 'onRangeChange', desc: '范围选择完成(range 模式，已排序)' },
    { name: 'onDateClick', desc: '点击日格' },
    { name: 'onMoreClick', desc: '点击 +N 折叠触发器' },
  ],
  slots: [
    { name: 'dateCell', desc: '自定义整格内容 { date, events, isToday, isOutside, disabled }' },
    { name: 'event', desc: '自定义事件块 { event }' },
  ],
  a11y: {
    hasRole: true,
    focusable: true,
    note: '网格 role=grid，星期表头行 role=row 含 role=columnheader，每周一行 role=row 含 role=gridcell；today 设 aria-current=date，选中设 aria-selected，禁用设 aria-disabled；可交互格 Enter/Space 触发点击与选中。',
  },
  tokens: [
    '--cd-calendar-bg',
    '--cd-calendar-border',
    '--cd-calendar-header-bg',
    '--cd-calendar-text',
    '--cd-calendar-text-secondary',
    '--cd-calendar-today-bg',
    '--cd-calendar-today-fg',
    '--cd-calendar-selected-border',
    '--cd-calendar-range-bg',
    '--cd-calendar-range-edge-bg',
    '--cd-calendar-week-cell-min-h',
    '--cd-calendar-hour-min-h',
    '--cd-calendar-hour-label-w',
    '--cd-calendar-weekend-bg',
    '--cd-calendar-cell-bg-hover',
    '--cd-calendar-event-default-bg',
    '--cd-calendar-event-fg',
    '--cd-calendar-disabled-bg',
    '--cd-calendar-more-color',
    '--cd-calendar-cell-min-h',
    '--cd-calendar-radius',
  ],
  responsive: false,
  examples: [
    { title: '基础月历', code: '<Calendar />' },
    {
      title: '带事件',
      code: '<Calendar events={[{ key: 1, start: new Date(), title: "会议" }]} />',
    },
    { title: '周视图', code: '<Calendar mode="week" />' },
    {
      title: '日视图（单日时间轴）',
      code: '<Calendar mode="day" dayStartHour={8} dayEndHour={20} events={[{ key: 1, start: new Date(), title: "会议" }]} />',
    },
    {
      title: '范围选择',
      code: '<Calendar selectionMode="range" onRangeChange={(i) => console.log(i.range)} />',
    },
  ],
} as const;
