/**
 * Machine-readable component metadata for AI/docs consumption.
 * Calendar — see specs/components/show/Calendar.spec.md
 */
export const meta = {
  name: 'Calendar',
  category: 'show',
  description:
    '月/周/日视图日历：日格网格 + 事件展示与 +N 折叠，today/selected/outside/weekend/disabled 态、导航（上一/今天/下一，月或周或天）；mode 切换月(6×7)/周(1×7)/日(单日时间轴)视图，day 模式纵向列出小时段(dayStartHour~dayEndHour)，带时间的事件按起始小时入对应时段、全天或跨天延续事件入顶部「全天」区，selectionMode 切换单选(selectedDate)/范围(rangeValue，起止+区间高亮+hover 预览)。受控 value(锚点)/selectedDate/rangeValue 不回写，仅通过 onChange/onSelect/onRangeChange/onDateClick/onMoreClick 通知。完整 WAI-ARIA grid roving 键盘焦点（方向键/PageUp-Down/Home-End/Enter-Space），popup 弹层模式（复用 _floating 门户 + 外部点击/Esc 关闭），day 视图时间轴虚拟化（复用 core fixedRange）。',
  exports: ['Calendar'],
  props: [
    { name: 'value', type: 'Date', default: 'undefined', desc: '受控锚点日期(决定展示月份/周)，受控时不回写' },
    { name: 'defaultValue', type: 'Date', default: 'new Date()', desc: '非受控初始锚点' },
    { name: 'mode', type: "'month' | 'week' | 'day'", default: "'month'", desc: '视图模式：月(6×7)/周(1×7)/日(单日时间轴)' },
    { name: 'selectionMode', type: "'single' | 'range'", default: "'single'", desc: '选择模式：单选或范围' },
    { name: 'events', type: 'CalendarEvent[]', default: '[]', desc: '事件列表' },
    { name: 'weekStartsOn', type: '0|1|2|3|4|5|6', default: '0', desc: '一周起始(0=周日)' },
    { name: 'maxEventsPerDay', type: 'number', default: '3', desc: '每格最多事件数，超出折叠 +N（month/week）' },
    { name: 'dayStartHour', type: 'number', default: '0', desc: 'day 视图时间轴起始小时(0-23)' },
    { name: 'dayEndHour', type: 'number', default: '23', desc: 'day 视图时间轴结束小时(0-23，含)' },
    { name: 'weekendDays', type: 'number[]', default: '[0, 6]', desc: '周末列序号' },
    { name: 'markWeekend', type: 'boolean', default: 'true', desc: '弱化高亮周末列' },
    { name: 'disabledDate', type: '(date: Date) => boolean', default: 'undefined', desc: '命中则该格禁用' },
    { name: 'selectedDate', type: 'Date', default: 'undefined', desc: '受控选中日(边框态，single 模式)，受控时不回写' },
    { name: 'defaultSelectedDate', type: 'Date', default: 'undefined', desc: '非受控选中日初值' },
    { name: 'rangeValue', type: '[Date, Date] | null', default: 'undefined', desc: '受控选中范围(range 模式)，受控时不回写' },
    { name: 'defaultRangeValue', type: '[Date, Date] | null', default: 'undefined', desc: '非受控范围初值' },
    { name: 'range', type: '[Date, Date] | null', default: 'undefined', desc: "范围选择区间（mode='range' 初始化用，同 rangeValue）" },
    { name: 'displayValue', type: 'Date', default: 'undefined', desc: '受控展示锚点（Semi API：displayValue，等同 value）' },
    { name: 'locale', type: 'string', default: "'zh-CN'", desc: 'Intl 月份/星期名格式化语言' },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '网格 aria-label，默认取月份标题' },
    { name: 'popup', type: 'boolean', default: 'false', desc: '弹层模式：渲染 trigger，日历作为浮层弹出（复用 _floating 门户定位）' },
    { name: 'open', type: 'boolean', default: 'undefined', desc: '受控展开态(popup)，受控时不回写仅 onOpenChange' },
    { name: 'defaultOpen', type: 'boolean', default: 'false', desc: '非受控初始展开态' },
    { name: 'onOpenChange', type: '(info: { open: boolean }) => void', default: 'undefined', desc: '展开态变化回调' },
    { name: 'placement', type: 'Placement', default: "'bottomStart'", desc: '浮层相对 trigger 的位置' },
    { name: 'getContainer', type: '() => HTMLElement | null', default: 'undefined', desc: '浮层门户挂载容器(默认 body)' },
    { name: 'trigger', type: 'Snippet', default: 'undefined', desc: 'popup 模式 trigger 自定义内容 { open, toggle }' },
    { name: 'virtualizeDay', type: "boolean | 'auto'", default: "'auto'", desc: 'day 时间轴虚拟化：auto 按阈值/true 强制/false 关闭' },
    { name: 'virtualizeThreshold', type: 'number', default: '18', desc: '触发虚拟化的最少小时行数(auto 生效)' },
    { name: 'timelineViewportHeight', type: 'number', default: '360', desc: 'day 时间轴虚拟化视口高度(px)' },
    { name: 'showCurrTime', type: 'boolean', default: 'true', desc: '是否显示当前时间红线（day/week 视图）' },
    { name: 'scrollTop', type: 'number', default: '400', desc: 'day/week 视图默认滚动高度（px）' },
    { name: 'minEventHeight', type: 'number', default: 'undefined', desc: '事件块最小高度（px）' },
    { name: 'width', type: 'number | string', default: 'undefined', desc: '日历整体宽度' },
    { name: 'height', type: 'number | string', default: 'undefined', desc: '日历整体高度' },
    {
      name: 'renderTimeDisplay',
      type: '(hour: number) => string',
      default: 'undefined',
      desc: '自定义时间文案 (hour: 0-23)',
    },
    {
      name: 'renderDateDisplay',
      type: '(date: Date) => string',
      default: 'undefined',
      desc: '自定义日期文案',
    },
    {
      name: 'dateGridRender',
      type: '(dateString: string, date: Date) => Snippet | null | undefined',
      default: 'undefined',
      desc: "自定义单元格额外内容 (dateString: 'YYYY-MM-DD', date)",
    },
    {
      name: 'allDayEventsRender',
      type: '(events: CalendarEvent[]) => Snippet | null | undefined',
      default: 'undefined',
      desc: '自定义全天事件区域渲染',
    },
    { name: 'header', type: 'Snippet', default: 'undefined', desc: '自定义头部内容，替换默认头部' },
    { name: 'onChange', type: '(info: { value: Date }) => void', default: 'undefined' },
    { name: 'onSelect', type: '(info: { date: Date }) => void', default: 'undefined' },
    { name: 'onRangeChange', type: '(info: { range: [Date, Date] }) => void', default: 'undefined' },
    { name: 'onDateClick', type: '(info: { date: Date }) => void', default: 'undefined' },
    {
      name: 'onMoreClick',
      type: '(info: { date: Date; events: CalendarEvent[] }) => void',
      default: 'undefined',
    },
    {
      name: 'onEventClick',
      type: '(info: { event: CalendarEvent; nativeEvent: Event }) => void',
      default: 'undefined',
      desc: '点击/键盘激活事件块（事件块 role=button + Enter/Space 触发）',
    },
    { name: 'onClose', type: '() => void', default: 'undefined', desc: '关闭回调（popup 模式）' },
    { name: 'dateCell', type: 'Snippet', default: 'undefined', desc: '自定义整格内容' },
    { name: 'event', type: 'Snippet', default: 'undefined', desc: '自定义事件块' },
  ],
  events: [
    { name: 'onChange', desc: '锚点(翻月/翻周/今天)变化' },
    { name: 'onSelect', desc: '选中某日(single 模式)' },
    { name: 'onRangeChange', desc: '范围选择完成(range 模式，已排序)' },
    { name: 'onDateClick', desc: '点击日格' },
    { name: 'onMoreClick', desc: '点击 +N 折叠触发器' },
  ],
  slots: [
    { name: 'dateCell', desc: '自定义整格内容 { date, events, isToday, isOutside, disabled }' },
    { name: 'event', desc: '自定义事件块 { event }' },
    { name: 'trigger', desc: 'popup 模式 trigger 自定义内容 { open, toggle }' },
  ],
  a11y: {
    hasRole: true,
    focusable: true,
    note: '网格 role=grid，星期表头行 role=row 含 role=columnheader，每周一行 role=row 含 role=gridcell；today 设 aria-current=date，选中设 aria-selected，禁用设 aria-disabled。完整 WAI-ARIA grid roving 焦点：网格内仅活动格 tabindex=0（余 -1），方向键移动焦点（←→ 天、↑↓ 周、PageUp/Down 月、Home/End 周首末），跨月/周自动翻页并落焦，Enter/Space 选中。popup 模式：trigger aria-haspopup=dialog/aria-expanded，浮层 role=dialog，外部点击/Esc 关闭并归还焦点。',
  },
  tokens: [
    // 全量对齐 Semi calendar/variables.scss（94 变量）
    '--cd-color-calendar-*',
    '--cd-width-calendar-*',
    '--cd-height-calendar-*',
    '--cd-spacing-calendar-*',
    '--cd-radius-calendar-*',
    '--cd-font-calendar-*',
    '--cd-z-calendar-*',
    // 组件消费补充段（Calendar.svelte 消费）
    '--cd-calendar-*',
    '--cd-font-size-*',
    '--cd-focus-ring',
    '--cd-motion-*',
    '--cd-shadow-elevated',
    '--cd-z-popover',
    '--cd-color-danger',
  ],
  responsive: false,
  examples: [
    { title: '基础月历', code: '<Calendar />' },
    {
      title: '带事件',
      code: '<Calendar events={[{ key: 1, start: new Date(), title: "会议" }]} />',
    },
    { title: '周视图', code: '<Calendar mode="week" />' },
    {
      title: '日视图（单日时间轴）',
      code: '<Calendar mode="day" dayStartHour={8} dayEndHour={20} events={[{ key: 1, start: new Date(), title: "会议" }]} />',
    },
    {
      title: '范围选择',
      code: '<Calendar selectionMode="range" onRangeChange={(i) => console.log(i.range)} />',
    },
    {
      title: '弹层模式',
      code: '<Calendar popup defaultOpen onSelect={(i) => console.log(i.date)} />',
    },
    {
      title: '弹层模式（自定义 trigger）',
      code: '<Calendar popup>{#snippet trigger({ toggle })}<button onclick={toggle}>选择日期</button>{/snippet}</Calendar>',
    },
  ],
} as const;
