/**
 * Machine-readable component metadata for AI/docs consumption.
 * Table — see specs/components/show/Table.spec.md
 */
export const meta = {
  name: 'Table',
  category: 'show',
  description:
    '表格：列定义驱动渲染，三态排序(升/降/无)、客户端分页、行选择(含半选 indeterminate)；sortState / rowSelection.selectedRowKeys / pagination.currentPage 受控不回写，仅经 onSortChange / onChange 通知。复用 @chenzy-design/core 纯函数算法与 Pagination 组件。支持行展开 expandable（受控/非受控）。固定列 fixed、列筛选 filters/onFilter、列宽拖拽 resizable（本地覆盖宽度不写回 columns）。树形数据 tree（行含 children 自动嵌套，第一列展开三角+缩进，排序/分页作用于顶层行，扁平化用 core flattenTreeRows 纯函数，受控展开 keys 不回写）。树形行选择父子联动 rowSelection.checkStrictly（默认 false 勾父连带后代+半选，true 父子独立；联动用 core conductRows/toggleRowCheck 纯函数）。行虚拟滚动 virtualized：仅渲染视口内行切片（复用 core fixedRange），首尾 padding spacer tr 撑总高，保持原生 table 语义；thead sticky 固定顶部；与 pagination 互斥（虚拟时忽略分页）。',
  exports: ['Table', 'Column'],
  props: [
    { name: 'columns', type: 'ColumnDef<T>[]', default: '[]', desc: '列定义：key/dataIndex/title/width/fixed/resize/align/className/ellipsis/sorter/filters/onFilter/filterConfirmMode/render；children 表头合并（子列，父列 title 横跨叶子列）；onCell 返回 colSpan/rowSpan 行列合并（值 0 跳过渲染）；useFullRender 完全自定义（render 额外收到 expandIcon/indentText 物料自行摆放）' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '组合式列容器（对齐 Semi Table.Column）：放 <Column> 子组件声明列，嵌套 <Column> 即表头合并。与 columns 并存，传了 columns 用配置式否则用组合式收集' },
    { name: 'dataSource', type: 'T[]', default: '[]', desc: '数据行' },
    { name: 'rowKey', type: "string | ((record: T) => RowKey)", default: "'key'", desc: '行唯一键解析' },
    { name: 'size', type: "'small'|'default'|'middle'", default: "'default'" },
    { name: 'tableLayout', type: "'' | 'auto' | 'fixed'", default: "''", desc: '控制 <table> 的 table-layout（对齐 Semi）。缺省沿用既有推导：存在 fixed 列时 fixed，否则 auto；显式传值覆盖推导' },
    { name: 'direction', type: "'ltr' | 'rtl'", default: "'ltr'", desc: 'RTL/LTR 方向（对齐 Semi direction）' },
    { name: 'bordered', type: 'boolean', default: 'false', desc: '单元格边框' },
    { name: 'stripe', type: 'boolean', default: 'false', desc: '斑马纹' },
    { name: 'loading', type: 'boolean', default: 'false', desc: '加载态；复用 Spin 组件（对齐 Semi <Spin spinning size="large">），包裹标题/分页/表体/footer 整个内容区' },
    { name: 'sortState', type: 'SortState', default: 'undefined', desc: '受控排序态；受控时不回写，仅 onSortChange' },
    { name: 'defaultSortState', type: 'SortState', default: '{ key: null, order: null }', desc: '非受控初始排序' },
    { name: 'onSortChange', type: '(state: SortState) => void', default: 'undefined' },
    {
      name: 'pagination',
      type: "false | { pageSize?: number; currentPage?: number; defaultCurrentPage?: number; total?: number; position?: 'bottom'|'top'|'both'; formatPageText?: boolean | ((info) => string); onPageChange?: (page: number) => void; onChange?: (page: number) => void }",
      default: 'undefined',
      desc: 'false 关闭；对象/缺省启用内置分页(pageSize 默认 10)。currentPage 受控不回写(对齐 Semi currentPage)；total 覆盖本地数据长度(对齐 Semi total)；position 分页器位置(对齐 Semi position，默认 bottom)；formatPageText 左侧文案自定义格式化(对齐 Semi)；onPageChange 页码变化(对齐 Semi)，onChange 为本库旧名与其等效',
    },
    {
      name: 'rowSelection',
      type: 'RowSelection<T>',
      default: 'undefined',
      desc: 'selectedRowKeys 受控不回写；defaultSelectedRowKeys / onChange / getCheckboxProps；checkStrictly(默认 false) 树形父子联动开关：false 勾父连带勾后代+后代部分选中父行半选，true 父子独立',
    },
    {
      name: 'expandable',
      type: 'Expandable<T>',
      default: 'undefined',
      desc: 'expandedRowRender / rowExpandable / expandedRowKeys 受控不回写 / defaultExpandedRowKeys / onExpand',
    },
    {
      name: 'tree',
      type: 'boolean | TreeTable',
      default: 'undefined',
      desc: '树形数据：true 或 { childrenColumnName(默认 children) / indentSize(默认 16) / expandedRowKeys 受控不回写 / defaultExpandedRowKeys / onExpand }。第一列内展开三角+逐级缩进；排序/分页/筛选作用于顶层行',
    },
    { name: 'rowClassName', type: '(record: T, index: number) => string', default: 'undefined' },
    { name: 'empty', type: 'string', default: "'暂无数据'", desc: '空数据占位文案' },
    { name: 'emptySnippet', type: 'Snippet', default: 'undefined', desc: '空数据占位自定义渲染（富内容，如 Empty 组件；优先于 empty 文案，对齐 Semi empty: ReactNode）' },
    { name: 'aria-label', type: 'string', default: 'undefined', desc: 'table aria-label' },
    { name: 'onRowClick', type: '(info: { record: T; index: number }) => void', default: 'undefined' },
    { name: 'virtualized', type: 'boolean', default: 'false', desc: '行虚拟滚动：仅渲染视口内行，适合大数据(1000+)。启用时忽略 pagination(全量滚动)、表头 sticky 固定顶部；假定行等高，不建议与 expandable 混用' },
    { name: 'height', type: 'number', default: '400', desc: '虚拟滚动视口高度(px)，virtualized 时生效' },
    { name: 'rowHeight', type: 'number', default: '48', desc: '虚拟滚动行高(px)，virtualized 时生效' },
    { name: 'onChange', type: '(info: TableChangeInfo) => void', default: 'undefined', desc: '聚合事件：排序/筛选/分页任一变化的主入口（受控数据回流）' },
    { name: 'onFilterChange', type: '(info: { dataIndex: string; values: (string|number)[] }) => void', default: 'undefined', desc: '筛选状态变化（含重置）' },
    { name: 'onPaginationChange', type: '(info: { current: number; pageSize: number }) => void', default: 'undefined', desc: '分页变化' },
    { name: 'onSelectChange', type: '(info: { selectedRowKeys: RowKey[]; selectedRows: T[] }) => void', default: 'undefined', desc: '选择集变化（与 rowSelection.onChange 同时触发）' },
    { name: 'onExpandChange', type: '(info: { expanded: boolean; record: T; expandedRowKeys: RowKey[] }) => void', default: 'undefined', desc: '行展开/收起（展开行与树形行均触发）' },
    { name: 'onScroll', type: '(info: TableScrollInfo) => void', default: 'undefined', desc: '滚动位置（含触底，用于无限加载）' },
    { name: 'onReachBottom', type: '() => void', default: 'undefined', desc: '纵向触底（懒加载触发），距底 reachBottomThreshold 像素内触发一次' },
    { name: 'reachBottomThreshold', type: 'number', default: '0', desc: 'onReachBottom 触发阈值（距底像素），默认 0（精确触底）' },
    { name: 'scroll', type: 'ScrollConfig', default: 'undefined', desc: '横/纵向滚动配置：x 设最小宽度横向溢出，y 设最大高度纵向溢出；scrollToFirstRowOnChange 分页/排序/筛选变化后滚回顶部' },
    { name: 'components', type: '{ table?; header?; body? }（tag 名 + body.colgroup 槽位）', default: 'undefined', desc: '覆盖组成元素 tag（对齐 Semi）：thead/tbody/行经 svelte:element 换标签，内部 class/role/事件仍注入；body.colgroup.{wrapper,col} 覆盖 colgroup/col 标签名。header.outer/body.outer/footer.* 未实现：Semi 自身实现里这些槽位也未被消费（仅存在于类型声明）' },
    { name: 'getVirtualizedListRef', type: '(ref: { scrollTo; scrollToItem }) => void', default: 'undefined', desc: '返回虚拟化滚动控制句柄，仅 virtualized 有效（对齐 Semi）' },
    { name: 'sticky', type: 'boolean | { offsetHeader?: number }', default: 'false', desc: '表头吸顶：true 时 sticky 定位；对象可指定 offsetHeader（px）' },
    { name: 'showHeader', type: 'boolean', default: 'true', desc: '是否显示表头' },
    { name: 'defaultExpandAllRows', type: 'boolean', default: 'false', desc: '默认展开全部行（含树形行）' },
    { name: 'expandAllRows', type: 'boolean', default: 'undefined', desc: '是否展开所有行（对齐 Semi expandAllRows；受控语义弱化为初始态同 defaultExpandAllRows）' },
    { name: 'resizable', type: 'boolean | ResizableConfig<T>', default: 'false', desc: 'Table 级列伸缩开关（对齐 Semi resizable）：true 时所有带 width 的列可拖拽伸缩（column.resize=false 单列关闭）；对象态提供 onResize/onResizeStart/onResizeStop 事件（返回的对象与该列合并，如 className）' },
    { name: 'getPopupContainer', type: '() => HTMLElement', default: 'undefined', desc: '筛选浮层挂载容器，默认跟随触发按钮' },
    { name: 'onRow', type: '(record: T, index: number, rowStatus?: { disabled?; selected? }) => { onClick?; onDoubleClick?; onMouseEnter?; onMouseLeave?; className?; style? }', default: 'undefined', desc: '行级事件与属性（返回值合并到 tr；第三参 rowStatus 含 disabled/selected）' },
    { name: 'onHeaderRow', type: '(columns: ColumnDef<T>[], index: number) => { onClick?; className?; style? }', default: 'undefined', desc: '表头行级事件与属性' },
    { name: 'expandRowByClick', type: 'boolean', default: 'false', desc: '点击行体触发展开/收起' },
    { name: 'expandCellFixed', type: "boolean | 'left' | 'right'", default: 'undefined', desc: '展开图标列固定方向' },
    { name: 'keepDOM', type: 'boolean', default: 'false', desc: 'true 时保留已展开行 DOM 但隐藏（display:none）' },
    { name: 'indentSize', type: 'number', default: '20', desc: '树形缩进像素（tree.indentSize 优先）' },
    { name: 'groupBy', type: 'string | ((record: T) => string)', default: 'undefined', desc: '按字段名或函数对数据行分组，插入分组标题行' },
    { name: 'renderGroupSection', type: 'Snippet<[{ groupKey: string; group: T[] }]>', default: 'undefined', desc: '自定义分组标题渲染' },
    { name: 'clickGroupedRowToExpand', type: 'boolean', default: 'false', desc: '点击分组标题行折叠/展开该组内数据行（groupBy 时生效，disclosure 模式 role=button+aria-expanded+Enter/Space 可达）' },
    { name: 'defaultExpandAllGroupRows', type: 'boolean', default: 'false', desc: '非受控：默认是否展开分组行。对齐 Semi，仅显式 true 才默认展开，缺省与 false 均默认折叠。动态加载数据不生效' },
    { name: 'expandAllGroupRows', type: 'boolean', default: 'undefined', desc: '受控：true 展开全部分组、false 折叠全部分组；受控时不回写，仅经 onGroupExpandChange 通知' },
    { name: 'onGroupExpandChange', type: '(info: { groupKey: string; expanded: boolean; expandedGroupKeys: string[] }) => void', default: 'undefined', desc: '分组展开/收起变化回调（点击分组标题行触发）。Semi 无此专属回调（Semi 仅有 expandAllGroupRows/clickGroupedRowToExpand 等分组展开控制 props，无逐组变化通知），本库参照 Semi 展开行 onExpand 的模式补充，属合理扩展' },
    { name: 'onGroupedRow', type: '(group: T[], index: number) => { onClick?; onDoubleClick?; className?; style? }', default: 'undefined', desc: '分组标题行自定义属性回调（类似 onRow，仅作用于分组头行），返回值合并进分组头 tr' },
    { name: 'titleSnippet', type: 'Snippet', default: 'undefined', desc: '表格顶部标题区域' },
    { name: 'footerSnippet', type: 'Snippet<[{ currentData: T[] }]>', default: 'undefined', desc: '表格底部内容区域（接收 currentData）' },
    { name: 'renderPagination', type: 'Snippet<[{ total: number; currentPage: number; pageSize: number; onChange: (page: number) => void }]>', default: 'undefined', desc: '自定义分页器渲染，替换内置 Pagination UI；调用 onChange(page) 触发内部翻页（受控 currentPage 不回写）' },
    { name: 'expandIcon', type: 'Snippet<[{ expanded: boolean; record: T }]>', default: 'undefined', desc: '自定义展开行的展开/收起图标（替换默认三角），仅 expandable 展开列生效' },
    { name: 'hideExpandedColumn', type: 'boolean', default: 'true', desc: '展开按钮是否并入首列。默认 true（并入首列，对齐 Semi）；false 时展开按钮单独成列' },
    { name: 'rowSpanHover', type: 'boolean', default: 'false', desc: '合并单元格（rowSpan）时 hover 高亮整个合并区（渐进能力，依赖单元格合并）' },
    { name: 'headerStyle', type: 'string | Record<string, string>', default: 'undefined', desc: '表头单元格（所有 th，含 fixed 表头）自定义内联样式' },
    { name: 'title', type: 'string', default: 'undefined', desc: '表格标题（字符串；富内容用 titleSnippet）' },
    { name: 'footer', type: 'string', default: 'undefined', desc: '表格尾部（字符串；富内容用 footerSnippet）' },
    { name: 'childrenRecordName', type: 'string', default: "'children'", desc: '树形 dataSource 中子级字段名（对齐 Semi childrenRecordName；tree.childrenColumnName 优先）' },
    { name: 'class', type: 'string', default: 'undefined', desc: '最外层 .cd-table-wrapper 自定义样式名（对齐 Semi className）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '最外层 .cd-table-wrapper 内联样式（对齐 Semi style）' },
  ],
  events: [
    { name: 'onChange', desc: '排序/筛选/分页任一变化的聚合主入口（受控数据回流）' },
    { name: 'onSortChange', desc: '表头排序切换(三态循环)' },
    { name: 'onFilterChange', desc: '列筛选状态变化（含重置）' },
    { name: 'onPaginationChange', desc: '分页变化' },
    { name: 'onSelectChange', desc: '选择集变化（与 rowSelection.onChange 同时触发）' },
    { name: 'onExpandChange', desc: '行展开/收起（展开行与树形行均触发）' },
    { name: 'onGroupExpandChange', desc: '分组展开/收起（点击分组标题行触发）。Semi 无此专属回调，本库合理扩展' },
    { name: 'onScroll', desc: '滚动位置（含触底）' },
    { name: 'onReachBottom', desc: '纵向触底（懒加载触发）' },
    { name: 'rowSelection.onChange', desc: '行选择变更，回传 keys 与对应 rows' },
    { name: 'pagination.onChange', desc: '页码变更' },
    { name: 'onRowClick', desc: '行点击(复选框/排序按钮已阻止冒泡)' },
  ],
  slots: [
    { name: 'column.render', desc: '单元格自定义渲染 Snippet<[{ value, record, index }]>' },
    { name: 'titleSnippet', desc: '表格顶部标题区域 Snippet' },
    { name: 'footerSnippet', desc: '表格底部内容区域 Snippet<[{ currentData: T[] }]>' },
    { name: 'renderGroupSection', desc: '分组标题渲染 Snippet<[{ groupKey, group }]>' },
    { name: 'renderPagination', desc: '自定义分页器渲染 Snippet<[{ total, currentPage, pageSize, onChange }]>' },
    { name: 'expandIcon', desc: '自定义展开图标 Snippet<[{ expanded, record }]>' },
    { name: 'empty', desc: '空态文案经 empty prop 配置(字符串)' },
  ],
  a11y: {
    hasRole: true,
    focusable: false,
    pattern: 'grid|treegrid',
    note: '对齐 Semi：role 静态标注为 grid 或 treegrid（分组 groupBy / 展开行 expandedRowRender / 树形 tree 任一存在时 treegrid，否则 grid），不因交互能力(排序/筛选/行选择等)与否切换。table 静态 aria-rowcount(顶层数据源行数)/aria-colcount(叶子列数)；表头行 role=row + aria-rowindex，表头格 role=columnheader + aria-colindex；数据行 role=row(aria-rowindex/aria-expanded/aria-level 视展开/树形层级而定)，数据格 role=gridcell + aria-colindex。无方向键漫游、无 roving tabindex(Semi 无此实现，本库不再自造超集，浏览器默认 Tab 序逐格移动)。可排序列 aria-sort(ascending/descending/none)；行选择原生 checkbox，全选 aria-label「全选」、行选「选择此行」，半选经 attachment 命令式设 input.indeterminate(只写属性、不读几何、无响应式循环)；焦点环 --cd-focus-ring；reduced-motion 关闭 spinner 与图标过渡。',
  },
  tokens: [
    // 全量对齐 Semi table/variables.scss —— 组件直接消费 Semi 全名 token（无自造中间短名）
    // 间距
    '--cd-spacing-table-paddingy',
    '--cd-spacing-table-paddingx',
    '--cd-spacing-table-middle-paddingy',
    '--cd-spacing-table-small-paddingy',
    '--cd-spacing-table-title-paddingy',
    '--cd-spacing-table-title-paddingx',
    '--cd-spacing-table-footer-padding',
    '--cd-spacing-table-expand-row-paddingleft',
    '--cd-spacing-table-expand-row-paddingright',
    '--cd-spacing-table-expand-row-paddingtop',
    '--cd-spacing-table-expand-row-paddingbottom',
    '--cd-spacing-table-resizable-offset-y',
    '--cd-spacing-table-resizable-bottom',
    '--cd-spacing-table-row-head-paddingy',
    '--cd-spacing-table-row-head-paddingx',
    '--cd-spacing-table-react-resizable-handle-right',
    '--cd-spacing-table-tbody-rowcell-padding',
    '--cd-spacing-table-tbody-rowselection-rowcell-notselection-paddingx',
    '--cd-spacing-table-tbody-rowselection-rowcell-notselection-paddingy',
    '--cd-spacing-table-column-sorter-marginleft',
    '--cd-spacing-table-column-filter-marginleft',
    '--cd-spacing-table-expand-icon-marginright',
    // 尺寸
    '--cd-width-table-base-border',
    '--cd-width-table-header-border',
    '--cd-width-table-resizer-border',
    '--cd-width-table-column-selection',
    '--cd-width-table-column-sorter-icon',
    '--cd-height-table-column-sorter-icon',
    '--cd-width-table-column-filter-icon',
    '--cd-height-table-column-filter-icon',
    '--cd-width-table-cell-fixed-left-last',
    '--cd-width-table-cell-fixed-right-first',
    '--cd-width-table-react-resizable-handle',
    '--cd-height-table-pagination-outer-min',
    '--cd-height-table-column-filter-dropdown',
    // 颜色
    '--cd-color-table-bg-default',
    '--cd-color-table-text-default',
    '--cd-color-table-border-default',
    '--cd-color-table-shadow-border-default',
    '--cd-color-table-th-bg-default',
    '--cd-color-table-th-border-default',
    '--cd-color-table-th-text-default',
    '--cd-color-table-th-clicksort-bg-hover',
    '--cd-color-table-pl-bg-default',
    '--cd-color-table-body-bg-default',
    '--cd-color-table-body-bg-hover',
    '--cd-color-table-footer-bg-default',
    '--cd-color-table-row-expanded-bg-default',
    '--cd-color-table-expanded-icon-default',
    '--cd-color-table-expanded-bg-default',
    '--cd-color-table-filter-on-text-default',
    '--cd-color-table-filter-text-default',
    '--cd-color-table-sorter-on-text-default',
    '--cd-color-table-sorter-text-default',
    '--cd-color-table-page-text-default',
    '--cd-color-table-resizer-bg-default',
    '--cd-color-table-selection-bg-default',
    '--cd-color-table-placeholder-text-default',
    '--cd-color-table-cell-bg-hover',
    // 其他
    '--cd-font-table-base-fontsize',
    '--cd-border-table-base-borderstyle',
    '--cd-shadow-table-left',
    '--cd-shadow-table-right',
    '--cd-z-table-fixed-column',
  ],
  responsive: false,
  examples: [
    {
      title: '基础',
      code: '<Table {columns} dataSource={data} rowKey="id" />',
    },
    {
      title: '可排序',
      code: '<Table columns={[{ dataIndex: "age", title: "年龄", sorter: true }]} dataSource={data} />',
    },
    {
      title: '行选择 + 分页',
      code: '<Table {columns} dataSource={data} rowSelection={{ onChange: (keys) => (selected = keys) }} pagination={{ pageSize: 10 }} />',
    },
    {
      title: '列宽拖拽',
      code: '<Table columns={[{ dataIndex: "name", title: "姓名", width: 160 }]} dataSource={data} resizable />',
    },
    {
      title: '树形数据',
      code: '<Table {columns} dataSource={treeRows} rowKey="key" tree={{ defaultExpandedRowKeys: [1] }} />',
    },
    {
      title: '树形行选择父子联动',
      code: '<Table {columns} dataSource={treeRows} rowKey="key" tree rowSelection={{ onChange: (keys) => (selected = keys) }} />',
    },
    {
      title: '行虚拟滚动（大数据）',
      code: '<Table {columns} dataSource={bigData} rowKey="id" virtualized height={400} rowHeight={48} />',
    },
  ],
} as const;
