/**
 * Machine-readable component metadata for AI/docs consumption.
 * MarkdownRender — 对标 Semi Design MarkdownRender，用 unified 管线（remark/rehype）替代 MDX。
 */
export const meta = {
  name: 'MarkdownRender',
  category: 'show',
  description:
    'Markdown 渲染组件：unified 管线（remark-parse + 条件 remark-gfm + remark-rehype + 透传 remark/rehype 插件）把 raw 编译成 hast，再由 Svelte 递归渲染成组件 / 原生标签。支持 components 覆盖元素与注册自定义标签对应的 Svelte 组件；默认剥离 raw HTML（对齐 Semi format=md，保留 HTML 需自传 rehype-raw 并自负 XSS）；代码块默认交给 CodeHighlight（存在则用，否则降级纯 <pre><code>）。不支持 md 正文里任意 JSX 表达式求值（Semi format=mdx 深度能力，Svelte 无 JSX runtime）。',
  exports: ['MarkdownRender', 'defaultComponents'],
  props: [
    { name: 'raw', type: 'string', default: "''", desc: 'Markdown 源码' },
    {
      name: 'components',
      type: 'Record<string, Component | string>',
      default: 'undefined',
      desc: '元素覆盖 / 自定义标签注册；浅合并覆盖 defaultComponents（值为 string 时别名到另一原生标签）',
    },
    {
      name: 'format',
      type: "'md'",
      default: "'md'",
      desc: '仅支持 md（unified 管线）；mdx 不支持（Svelte 无 JSX runtime）',
    },
    {
      name: 'remarkGfm',
      type: 'boolean',
      default: 'true',
      desc: '启用 GitHub Flavored Markdown（表格 / 任务列表 / 删除线 / 自动链接）',
    },
    {
      name: 'remarkPlugins',
      type: 'UnifiedPluginEntry[]',
      default: 'undefined',
      desc: '透传 remark 插件（mdast 阶段），支持 plugin 或 [plugin, options] 元组',
    },
    {
      name: 'rehypePlugins',
      type: 'UnifiedPluginEntry[]',
      default: 'undefined',
      desc: '透传 rehype 插件（hast 阶段）；传 rehype-raw 可保留 raw HTML（自负 XSS）',
    },
    { name: 'class', type: 'string', default: "''", desc: '根容器附加类名' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根容器内联样式' },
  ],
  events: [],
  slots: [],
  a11y: {
    hasRole: false,
    focusable: false,
    note: '渲染语义化 HTML（标题 / 列表 / 表格 / 链接等）保留原生可访问性；外链自动补 rel=noopener noreferrer + target=_blank；默认剥离 raw HTML 规避注入；图片 alt 由 Markdown 源码 `![alt](url)` 提供。',
  },
  // 可覆盖元素（对齐 Semi）：默认 a / pre 已由 defaultComponents 覆盖，其余可由使用方注册。
  overridableTags: [
    'a',
    'blockquote',
    'br',
    'code',
    'em',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'img',
    'li',
    'ol',
    'p',
    'pre',
    'strong',
    'ul',
    'table',
  ],
  tokens: [
    '--cd-markdown-render-text-color',
    '--cd-markdown-render-font-size',
    '--cd-markdown-render-line-height',
    '--cd-markdown-render-block-gap',
    '--cd-markdown-render-heading-color',
    '--cd-markdown-render-heading-weight',
    '--cd-markdown-render-heading-margin-top',
    '--cd-markdown-render-heading-margin-bottom',
    '--cd-markdown-render-h1-size',
    '--cd-markdown-render-h1-line-height',
    '--cd-markdown-render-h2-size',
    '--cd-markdown-render-h2-line-height',
    '--cd-markdown-render-h3-size',
    '--cd-markdown-render-h3-line-height',
    '--cd-markdown-render-h4-size',
    '--cd-markdown-render-h4-line-height',
    '--cd-markdown-render-h5-size',
    '--cd-markdown-render-h5-line-height',
    '--cd-markdown-render-h6-size',
    '--cd-markdown-render-h6-line-height',
    '--cd-markdown-render-link-color',
    '--cd-markdown-render-link-hover-color',
    '--cd-markdown-render-code-color',
    '--cd-markdown-render-code-bg',
    '--cd-markdown-render-code-radius',
    '--cd-markdown-render-code-padding-x',
    '--cd-markdown-render-code-font-size',
    '--cd-markdown-render-pre-bg',
    '--cd-markdown-render-pre-radius',
    '--cd-markdown-render-pre-padding',
    '--cd-markdown-render-quote-color',
    '--cd-markdown-render-quote-border-color',
    '--cd-markdown-render-quote-border-width',
    '--cd-markdown-render-quote-padding-x',
    '--cd-markdown-render-table-border-color',
    '--cd-markdown-render-table-cell-padding-x',
    '--cd-markdown-render-table-cell-padding-y',
    '--cd-markdown-render-table-head-bg',
    '--cd-markdown-render-list-padding-inline',
    '--cd-markdown-render-hr-color',
    '--cd-markdown-render-img-radius',
  ],
  responsive: false,
  examples: [
    {
      title: '基础渲染',
      code: '<MarkdownRender raw={`# 标题\\n\\n正文 **加粗** 与 [链接](https://example.com)。`} />',
    },
    {
      title: 'GFM 表格 / 任务列表',
      code: '<MarkdownRender raw={`| a | b |\\n| - | - |\\n| 1 | 2 |\\n\\n- [x] done\\n- [ ] todo`} />',
    },
    {
      title: '覆盖 h1 为自定义 Svelte 组件',
      code: '<MarkdownRender raw="# 你好" components={{ h1: MyHeading }} />',
    },
    {
      title: '注册自定义标签（配合 remark 插件产出的节点）',
      code: '<MarkdownRender raw={md} components={{ callout: Callout }} remarkPlugins={[myDirectivePlugin]} />',
    },
    {
      title: '保留 raw HTML（自负 XSS）',
      code: "import rehypeRaw from 'rehype-raw';\n<MarkdownRender raw={htmlMd} rehypePlugins={[rehypeRaw]} />",
    },
    {
      title: '关闭 GFM',
      code: '<MarkdownRender raw={md} remarkGfm={false} />',
    },
  ],
} as const;
