/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Form',
  category: 'input',
  description: '表单容器，桥接 headless createForm，提供字段注册、校验、布局与 a11y。',
  subComponents: ['Form.Field', 'Form.Input'],
  props: [
    { name: 'value', type: 'Record<string, unknown>', default: 'undefined', desc: '受控整表单值；变更经 onChange 上报' },
    { name: 'initValues', type: 'Record<string, unknown>', default: '{}', desc: '非受控初始值' },
    { name: 'layout', type: "'vertical'|'horizontal'", default: 'vertical' },
    { name: 'labelPosition', type: "'top'|'left'|'inset'", default: 'top' },
    { name: 'labelWidth', type: 'number | string', default: 'undefined' },
    { name: 'labelAlign', type: "'left'|'right'", default: 'left', desc: 'Label 文本对齐（spec §4）' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'requiredMark', type: 'boolean', default: 'true' },
    { name: 'colon', type: 'boolean', default: 'false' },
    { name: 'scrollToError', type: 'boolean', default: 'false', desc: '提交校验失败时滚动并聚焦首个错误字段' },
    { name: 'validateTrigger', type: "'change'|'blur'|'submit'|'mount'|string[]", default: "['blur','change']", desc: '全局默认校验时机，字段可经 trigger 覆盖（spec §4）' },
    { name: 'showValidateIcon', type: 'boolean', default: 'true', desc: '错误/警告文案是否带状态图标（spec §4）' },
    { name: 'stopValidateWithError', type: 'boolean', default: 'false', desc: '字段命中首条错误即停止该字段后续 rule（spec §4）' },
    { name: 'preventDefault', type: 'boolean', default: 'true', desc: '是否拦截原生 submit 默认行为（spec §4）' },
    { name: 'allowEmpty', type: 'boolean', default: 'false', desc: '收集值时是否保留空值字段键（spec §4）' },
    { name: 'getFormApi', type: '(formApi: FormApi) => void', default: 'undefined', desc: 'Form 挂载后一次性回传内部 FormApi 句柄，供父级外部命令式 setFieldsValue/validate/resetFields（Semi getFormApi）' },
    { name: 'onSubmit', type: '(r: { valid; values; errors }) => void', default: 'undefined' },
    { name: 'onChange', type: '(values: Record<string, unknown>) => void', default: 'undefined' },
    { name: 'onReset', type: '() => void', default: 'undefined', desc: '表单重置时回调（原生 reset 或 formApi.resetFields()）（Semi onReset）' },
    { name: 'onErrorChange', type: '(errors: FieldErrors) => void', default: 'undefined', desc: '任意字段错误集合变化时回调，入参为最新 errors（Semi onErrorChange）' },
    { name: 'children', type: 'Snippet', default: 'undefined' },
    { name: 'footer', type: 'Snippet<[{ submitting: boolean }]>', default: 'undefined' },
    // Form.Field
    { name: 'Field.field', type: 'string', default: '—', desc: '字段名（必填）' },
    { name: 'Field.label', type: 'string', default: 'undefined' },
    { name: 'Field.rules', type: 'Rule[]', default: '[]' },
    { name: 'Field.initValue', type: 'unknown', default: 'undefined', desc: '字段级初始值，覆盖容器 initValues（spec §4.2）' },
    { name: 'Field.required', type: 'boolean', default: 'false' },
    { name: 'Field.validateStatus', type: "'default'|'warning'|'error'", default: 'undefined', desc: '外部强制校验态（受控展示，不经内部校验、不回写）（spec §4.2）' },
    { name: 'Field.extraText', type: 'string', default: 'undefined' },
    { name: 'Field.noStyle', type: 'boolean', default: 'false', desc: '仅注册收集、不渲染布局 DOM（纯收集）（spec §4.2 §190）' },
    { name: 'Field.span', type: 'number', default: 'undefined', desc: 'Form.Section 栅格内占列（grid-column: span N）（spec §4.2）' },
    { name: 'Field.transform', type: '(v, values) => unknown', default: 'undefined', desc: '提交前值转换（纯函数，不回写 state）（spec §4.2）' },
    { name: 'Field.dependencies', type: 'string[]', default: 'undefined', desc: '依赖字段名；其值变化时本字段自动重校验' },
    { name: 'Field.trigger', type: "'change'|'blur'|'submit'|'mount'|string[]", default: '继承容器', desc: '字段级校验时机覆盖（spec §4）' },
    { name: 'Field.valuePropName', type: 'string', default: "'value'", desc: "控件值属性名；如 Checkbox/Switch 用 'checked'，snippet 参数即多出同名别名映射字段值" },
    { name: 'Field.children', type: 'Snippet<[{ value; [valuePropName]; onChange; onBlur; status; id; describedBy; disabled }]>', default: 'undefined', desc: 'snippet 参数含通用 value 及按 valuePropName 命名的别名（默认 value）；id 用于 label for/id 关联，describedBy 用于控件 aria-describedby' },
    // Form.Input
    { name: 'Input.field', type: 'string', default: '—', desc: '字段名（必填）' },
    { name: 'Input.label', type: 'string', default: 'undefined' },
    { name: 'Input.rules', type: 'Rule[]', default: '[]' },
    { name: 'Input.initValue', type: 'unknown', default: 'undefined', desc: '字段级初始值，覆盖容器 initValues（spec §4.2）' },
    { name: 'Input.required', type: 'boolean', default: 'false' },
    { name: 'Input.validateStatus', type: "'default'|'warning'|'error'", default: 'undefined', desc: '外部强制校验态（受控展示）（spec §4.2）' },
    { name: 'Input.extraText', type: 'string', default: 'undefined' },
    { name: 'Input.span', type: 'number', default: 'undefined', desc: 'Form.Section 栅格内占列（spec §4.2）' },
    { name: 'Input.transform', type: '(v, values) => unknown', default: 'undefined', desc: '提交前值转换（纯函数）（spec §4.2）' },
    { name: 'Input.placeholder', type: 'string', default: 'undefined' },
    { name: 'Input.type', type: "'text'|'password'", default: 'text' },
    { name: 'Input.clearable', type: 'boolean', default: 'false' },
    { name: 'Input.maxLength', type: 'number', default: 'undefined' },
    { name: 'Input.dependencies', type: 'string[]', default: 'undefined', desc: '依赖字段名；其值变化时本字段自动重校验' },
    { name: 'Input.trigger', type: "'change'|'blur'|'submit'|'mount'|string[]", default: '继承容器', desc: '字段级校验时机覆盖（spec §4）' },
  ],
  a11y: {
    role: 'form',
    notes: [
      '原生 <form>，submit 经 preventDefault 接管',
      '字段错误用 role=alert，经 aria-describedby 关联控件',
      'extraText 无错误时经 aria-describedby 关联',
      '必填星标 aria-hidden，必填语义由校验承载',
      'Form.Input 经 Field 自动生成的 id 用 label for/id 精确关联控件（点击 label 聚焦 input）；id 也可由 Input 外部传入',
    ],
  },
  tokens: [
    // —— chenzy-design 组件消费的补充 token（组件实际引用） ——
    '--cd-form-item-gap',
    '--cd-form-label-color',
    '--cd-form-label-gap',
    '--cd-form-required-color',
    '--cd-form-optional-color',
    '--cd-form-extra-color',
    '--cd-form-error-color',
    '--cd-form-warning-color',
    '--cd-form-error-font-size',
    '--cd-form-section-gap',
    '--cd-form-spinner-track-color',
    '--cd-form-spinner-active-color',
    // —— 全量对齐 Semi form/variables.scss（field / label / extra / errormessage / section） ——
    '--cd-spacing-form-field-horizontal-paddingright',
    '--cd-spacing-form-field-group-horizontal-paddingright',
    '--cd-spacing-form-field-vertical-paddingtop',
    '--cd-spacing-form-field-vertical-paddingbottom',
    '--cd-spacing-form-field-group-vertical-paddingtop',
    '--cd-spacing-form-field-group-vertical-paddingbottom',
    '--cd-spacing-form-label-paddingright',
    '--cd-spacing-form-label-paddingtop',
    '--cd-spacing-form-label-marginbottom',
    '--cd-spacing-form-label-margintop',
    '--cd-spacing-form-label-extra-marginleft',
    '--cd-spacing-form-label-required-marginleft',
    '--cd-spacing-form-label-posleft-marginright',
    '--cd-spacing-form-label-posleft-marginbottom',
    '--cd-spacing-form-label-postop-paddingtop',
    '--cd-spacing-form-label-postop-paddingbottom',
    '--cd-spacing-form-extra-posmid-margintop',
    '--cd-spacing-form-extra-posmid-marginbottom',
    '--cd-spacing-form-extra-posbottom-margintop',
    '--cd-spacing-form-switch-rating-marginy',
    '--cd-color-form-requiredmark-disabled-text-default',
    '--cd-color-form-label-disabled-text-default',
    '--cd-font-form-label-fontweight',
    '--cd-color-form-label-text-default',
    '--cd-color-form-label-optional-text-default',
    '--cd-color-form-label-extra-text-default',
    '--cd-color-form-requiredmark-text-default',
    '--cd-font-form-requiredmark-fontweight',
    '--cd-color-form-message-error-text-default',
    '--cd-color-form-alerticon-icon-default',
    '--cd-spacing-form-statusicon-marginright',
    '--cd-spacing-form-message-margintop',
    '--cd-color-form-section-text-default',
    '--cd-color-form-section-border-default',
    '--cd-width-form-section-border',
    '--cd-spacing-form-section-margintop',
    '--cd-spacing-form-section-text-paddingbottom',
    '--cd-spacing-form-section-text-marginbottom',
    '--cd-spacing-form-section-text-paddingtop',
    '--cd-spacing-form-section-text-margintop',
    '--cd-spacing-*',
    '--cd-color-*',
  ],
} as const;
