/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Tabs',
  category: 'navigation',
  description:
    '标签页，在同一区域内组织并切换多组对等内容。全量对齐 Semi Design：支持 line/card/button/slash 类型、top/left 位置、small/medium/large 尺寸、数据驱动 tabList 或纯声明式 <Tabs.Pane> 自动收集、renderTabBar 自定义标签栏、roving tabindex 键盘导航、可关闭标签、more 收纳与 collapsible 滚动折叠（含 auto 自动检测）。',
  props: [
    { name: 'value', type: 'string|number', default: 'undefined', desc: '受控选中标签 key' },
    { name: 'defaultValue', type: 'string|number', default: '首个标签', desc: '非受控初始 key' },
    { name: 'type', type: "'line'|'card'|'button'|'slash'", default: 'line', desc: '视觉风格（button=分段按钮组，slash=斜线式仅横向）' },
    { name: 'size', type: "'small'|'medium'|'large'", default: 'large', desc: '尺寸档（对齐 Semi）' },
    {
      name: 'tabPosition',
      type: "'top'|'left'",
      default: 'top',
      desc: '标签栏位置：top 水平 / left 垂直（对齐 Semi；slash 仅 top）',
    },
    { name: 'lazy', type: 'boolean', default: 'false', desc: '首次激活后才挂载面板' },
    { name: 'keepDOM', type: 'boolean', default: 'false', desc: '激活过的面板保留 DOM' },
    {
      name: 'tabList',
      type: 'TabItem[]',
      default: 'undefined',
      desc: '数据驱动标签定义；不传则从子 <Tabs.Pane> 的 tab/itemKey/icon/disabled/closable 纯声明式自动收集。TabItem 支持 icon?: Snippet（标签文字前渲染的图标）',
    },
    { name: 'closable', type: 'boolean', default: 'false', desc: '全局可关闭（单项可覆盖）' },
    {
      name: 'addable',
      type: 'boolean',
      default: 'false',
      desc: '标签栏末尾显示「+」按钮，点击触发 onAdd（受控，由父组件追加）',
    },
    {
      name: 'keyboardActivation',
      type: "'auto'|'manual'",
      default: 'auto',
      desc: '方向键聚焦即激活 / 需 Enter/Space 激活',
    },
    {
      name: 'overflow',
      type: "'scroll'|'dropdown'",
      default: 'scroll',
      desc: 'dropdown 等价于传 more：把溢出标签收进末尾「更多」下拉（仅横向生效）',
    },
    {
      name: 'collapsible',
      type: "boolean | 'auto'",
      default: 'false',
      desc: '滚动折叠（对齐 Semi）：true 溢出时显示前/后切换箭头；auto 自动检测溢出再决定是否折叠（仅横向生效）',
    },
    {
      name: 'more',
      type: "number | { count?: number; render?: Snippet; dropdownProps?: object }",
      default: 'undefined',
      desc: '把末尾若干标签收进「更多」下拉（对齐 Semi）：数字简写或对象形式（count/render/dropdownProps）',
    },
    {
      name: 'arrowPosition',
      type: "'start'|'end'|'both'",
      default: 'both',
      desc: 'collapsible 折叠模式中前/后切换箭头位置',
    },
    {
      name: 'renderArrow',
      type: "Snippet<[{ type: 'start'|'end'; onClick: () => void }]>",
      default: 'undefined',
      desc: 'collapsible 折叠模式下自定义前/后切换箭头',
    },
    {
      name: 'showRestInDropdown',
      type: 'boolean',
      default: 'true',
      desc: 'more 收纳模式是否在下拉中展示收起 tabs',
    },
    {
      name: 'dropdownProps',
      type: '{ start?: object; end?: object }',
      default: 'undefined',
      desc: '折叠模式下透传下拉参数（对齐 Semi）：start=前箭头下拉，end=末尾「更多」下拉',
    },
    {
      name: 'onVisibleTabsChange',
      type: '(visibleTabKeys: (string|number)[]) => void',
      default: 'undefined',
      desc: 'dropdown 模式下溢出项变化时回调，携带当前可见 tab keys',
    },
    {
      name: 'contentStyle',
      type: 'string | Record<string, string>',
      default: 'undefined',
      desc: '内容区外层样式（string 或 CSSProperties 对象）',
    },
    {
      name: 'preventScroll',
      type: 'boolean',
      default: 'false',
      desc: 'Tab 聚焦时是否阻止页面滚动',
    },
    {
      name: 'tabPaneMotion',
      type: 'boolean',
      default: 'true',
      desc: '面板切换是否启用动画',
    },
    {
      name: 'tabBarExtraContent',
      type: 'Snippet',
      default: 'undefined',
      desc: '标签栏右侧额外内容',
    },
    {
      name: 'tabBarClassName',
      type: 'string',
      default: 'undefined',
      desc: '标签栏容器（.cd-tabs__bar）自定义 class',
    },
    {
      name: 'tabBarStyle',
      type: 'string | Record<string, string>',
      default: 'undefined',
      desc: '标签栏容器（.cd-tabs__bar）自定义样式',
    },
    {
      name: 'visibleTabsStyle',
      type: 'string | Record<string, string>',
      default: 'undefined',
      desc: '可见标签区域自定义样式（scroll 模式作用于 .cd-tabs__nav，dropdown 模式作用于 .cd-tabs__list）',
    },
    { name: 'onChange', type: '(key: string|number) => void', default: 'undefined' },
    { name: 'onTabClose', type: '(key: string|number) => void', default: 'undefined' },
    {
      name: 'onTabClick',
      type: '(key: string|number, event: MouseEvent) => void',
      default: 'undefined',
      desc: '标签被点击触发（含已选中标签，未必触发 onChange；disabled 拦截前发出，可用于埋点）',
    },
    {
      name: 'onAdd',
      type: '() => void',
      default: 'undefined',
      desc: 'addable=true 时点击「+」按钮回调（受控数据，组件内不改 tabList）',
    },
    {
      name: 'renderTabBar',
      type: 'Snippet<[TabItem[], string|number|undefined, (key) => void]>',
      default: 'undefined',
      desc: '自定义整个标签栏渲染（接收 tab 列表、当前激活 key、切换回调 setActive）；传入时跳过内置标签栏与溢出处理，面板内容仍按 activeKey 显隐',
    },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '声明式 TabPane 内容（<Tabs.Pane>），<Tabs.Pane> 支持 icon?: Snippet（标签文字前渲染的图标）' },
  ],
  a11y: {
    role: 'tablist',
    keyboard: ['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Home', 'End', 'Enter', 'Space'],
    notes: [
      'tablist 内每个标签为 role=tab，aria-selected 标记激活，aria-controls 关联面板',
      'roving tabindex：仅激活标签 tabindex=0，其余 -1',
      'keyboardActivation=auto 聚焦即激活，manual 需 Enter/Space 确认',
      '面板 role=tabpanel；关闭叉为带 aria-label 的原生 button',
      '标签溢出时出现前/后滚动箭头（带 aria-label，tabindex=-1 不入 Tab 序），激活标签自动滚到可视区',
      'overflow=dropdown 时溢出标签收进末尾「更多」下拉（aria-haspopup=menu，带 aria-label），激活标签始终保持可见',
      'addable 的「+」为带 aria-label 的原生 button',
      'renderTabBar 自定义标签栏时由调用方负责无障碍语义（role=tab/aria-selected 等）',
      'preventScroll=true 时 Tab 聚焦不触发页面滚动',
    ],
  },
  // 组件实际消费的 token（名值一一对齐 Semi tabs/variables.scss；见 tokens/src/components/tabs.ts）。
  tokens: [
    // —— 颜色 ——
    '--cd-color-tabs-tab-line-border-default', '--cd-color-tabs-tab-line-border-hover', '--cd-color-tabs-tab-line-border-active',
    '--cd-color-tabs-tab-line-text-default', '--cd-color-tabs-tab-line-text-hover', '--cd-color-tabs-tab-line-text-active',
    '--cd-color-tabs-tab-line-selected-text-default', '--cd-color-tabs-tab-line-selected-indicator-default',
    '--cd-color-tabs-tab-line-vertical-selected-bg-default', '--cd-color-tabs-tab-line-vertical-bg-hover', '--cd-color-tabs-tab-line-vertical-bg-active',
    '--cd-color-tabs-tab-line-disabled-text-default',
    '--cd-color-tabs-tab-card-border-default', '--cd-color-tabs-tab-card-selected-indicator-default',
    '--cd-color-tabs-tab-card-bg-hover', '--cd-color-tabs-tab-card-bg-active', '--cd-color-tabs-tab-card-selected-bg-default',
    '--cd-color-tabs-tab-button-text-default', '--cd-color-tabs-tab-button-bg-hover', '--cd-color-tabs-tab-button-bg-active',
    '--cd-color-tabs-tab-button-selected-bg-default', '--cd-color-tabs-tab-button-selected-text-default',
    '--cd-color-tabs-tab-icon-default', '--cd-color-tabs-tab-icon-hover', '--cd-color-tabs-tab-icon-active', '--cd-color-tabs-tab-selected-icon-default',
    '--cd-color-tabs-tab-pane-text-default', '--cd-color-tabs-tab-slash-line',
    '--cd-color-tabs-tab-pane-arrow-text-default', '--cd-color-tabs-tab-pane-arrow-bg-hover', '--cd-color-tabs-tab-pane-arrow-bg-active', '--cd-color-tabs-tab-pane-arrow-disabled-text-default',
    // —— 字重 / 字号 ——
    '--cd-font-tabs-tab-fontweight', '--cd-font-tabs-tab-active-fontweight', '--cd-font-tabs-tab-fontsize',
    // —— 线宽 / 斜线尺寸 ——
    '--cd-width-tabs-bar-line-border', '--cd-width-tabs-bar-line-tab-border', '--cd-width-tabs-bar-card-border',
    '--cd-width-tabs-tab-slash-line', '--cd-height-tabs-tab-slash-line',
    // —— 间距（图标 / 箭头 / 附加 / 各类型内外边距 / 内容区）——
    '--cd-spacing-tabs-tab-icon-marginright', '--cd-spacing-tabs-tab-pane-arrow',
    '--cd-spacing-tabs-overflow-icon-marginleft', '--cd-spacing-tabs-overflow-icon-marginright',
    '--cd-spacing-tabs-bar-extra-paddingx', '--cd-spacing-tabs-bar-extra-paddingy',
    '--cd-spacing-tabs-bar-line-tab-paddingtop', '--cd-spacing-tabs-bar-line-tab-paddingx', '--cd-spacing-tabs-bar-line-tab-paddingbottom', '--cd-spacing-tabs-bar-line-tab-marginright',
    '--cd-spacing-tabs-bar-line-tab-small-paddingtop', '--cd-spacing-tabs-bar-line-tab-small-paddingbottom',
    '--cd-spacing-tabs-bar-line-tab-medium-paddingtop', '--cd-spacing-tabs-bar-line-tab-medium-paddingbottom',
    '--cd-spacing-tabs-bar-line-tab-left-padding', '--cd-spacing-tabs-bar-line-tab-left-small-padding', '--cd-spacing-tabs-bar-line-tab-left-medium-padding',
    '--cd-spacing-tabs-bar-slash-tab-paddingy', '--cd-spacing-tabs-bar-slash-tab-paddingx', '--cd-spacing-tabs-bar-slash-marginright', '--cd-spacing-tabs-bar-slash-line-marginleft', '--cd-spacing-tabs-bar-slash-line-marginy',
    '--cd-spacing-tabs-content-paddingy', '--cd-spacing-tabs-content-paddingx', '--cd-spacing-tabs-content-left-paddingx',
    '--cd-spacing-tabs-bar-card-tab-marginright', '--cd-spacing-tabs-bar-card-tab-paddingy', '--cd-spacing-tabs-bar-card-tab-paddingx', '--cd-spacing-tabs-bar-card-tab-active-paddingbottom', '--cd-spacing-tabs-bar-card-tab-left-marginbottom',
    '--cd-spacing-tabs-bar-button-tab-marginright', '--cd-spacing-tabs-bar-button-tab-marginbottom', '--cd-spacing-tabs-bar-button-tab-paddingy', '--cd-spacing-tabs-bar-button-tab-paddingx',
    // —— 圆角 ——
    '--cd-radius-tabs-tab-card', '--cd-radius-tabs-tab-card-left', '--cd-radius-tabs-tab-button',
    // —— 全局别名 ——
    '--cd-focus-ring', '--cd-border-radius-small',
  ],
} as const;
