/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'TreeSelect',
  category: 'input',
  description: '树形选择器，单面板可展开/收起的树，单选叶子或任意节点；支持 multiple 多选（checkbox + 父子联动 + 多 tag 回显 + 收敛策略）、可搜索过滤（本地/远程 + 命中高亮）、异步加载子节点、虚拟滚动大数据树、自定义字段映射与节点/tag/触发器渲染。',
  props: [
    { name: 'value', type: 'TreeKey|TreeKey[]|null', default: 'undefined' },
    { name: 'defaultValue', type: 'TreeKey|TreeKey[]|null', default: 'null' },
    { name: 'treeData', type: 'TreeNode[]', default: '[]', desc: '树数据源；字段名可经 fieldNames 自定义' },
    {
      name: 'fieldNames',
      type: '{ key?: string; label?: string; children?: string }',
      default: "{ key:'key', label:'label', children:'children' }",
      desc: '自定义节点字段名映射，适配任意后端数据（如 { key:\'id\', label:\'name\', children:\'sub\' }）。派生只读映射；onChange 回传的 key 即原始字段值',
    },
    { name: 'open', type: 'boolean', default: 'undefined' },
    { name: 'defaultOpen', type: 'boolean', default: 'false' },
    { name: 'multiple', type: 'boolean', default: 'false', desc: 'checkbox 多选 + 父子联动，多 tag 回显' },
    { name: 'checkStrictly', type: 'boolean', default: 'false', desc: '多选时父子勾选互不影响（向后兼容，等价 checkRelation=unRelated）' },
    { name: 'checkRelation', type: "'related'|'unRelated'", default: "'related'", desc: '多选父子是否级联联动；unRelated 互不影响。checkStrictly=true 强制 unRelated' },
    { name: 'showCheckedStrategy', type: "'all'|'parent'|'child'", default: "'all'", desc: '回填值/Tag 收敛策略：all 全部勾选节点；parent 折叠为父；child 仅叶子。仅 related 生效' },
    { name: 'maxTagCount', type: 'number', default: 'undefined', desc: '多选回填 Tag 最大展示数，超出折叠为 +N（仅影响显示）' },
    { name: 'placeholder', type: 'string', default: "'请选择'" },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'clearable', type: 'boolean', default: 'false' },
    { name: 'leafOnly', type: 'boolean', default: 'false' },
    { name: 'defaultExpandAll', type: 'boolean', default: 'false' },
    { name: 'treeDefaultExpandedKeys', type: 'TreeKey[]', default: '[]', desc: '默认展开的节点 key（非受控初始展开集，与 defaultExpandAll 取并集）' },
    { name: 'filterable', type: 'boolean', default: 'false', desc: '面板搜索框过滤节点 + 高亮命中' },
    { name: 'remote', type: 'boolean', default: 'false', desc: '远程搜索：输入防抖后仅触发 onSearch，不本地过滤（外部更新 treeData）' },
    { name: 'searchDebounce', type: 'number', default: '300', desc: 'onSearch 防抖毫秒（remote 时生效）' },
    { name: 'onSearch', type: '(query: string) => void', default: 'undefined', desc: '远程搜索输入回调（防抖后）' },
    { name: 'showIcon', type: 'boolean', default: 'true', desc: '是否预留节点图标位（icon 提供时渲染在 label 前），与 Tree 对齐' },
    {
      name: 'loadData',
      type: '(node: TreeNode) => Promise<TreeNode[]>',
      default: 'undefined',
      desc: '异步加载子节点：展开未加载的非叶子节点时调用，返回该节点子节点数组（加载中显示 spinner，竞态去重，不写回 treeData）。与 Tree 的 loadData 对齐',
    },
    { name: 'virtualized', type: 'boolean', default: 'false', desc: '虚拟滚动：仅渲染视口内可见行，适合大数据树。复用 Tree 范式（core fixedRange），保持 role=tree/treeitem 语义' },
    { name: 'height', type: 'number', default: '224', desc: '虚拟滚动视口高度（px），virtualized 时生效' },
    { name: 'itemHeight', type: 'number', default: '32', desc: '虚拟滚动行高（px），virtualized 时生效' },
    {
      name: 'icon',
      type: 'Snippet<[{ node: TreeNode; expanded: boolean; level: number }]>',
      default: 'undefined',
      desc: '自定义节点图标，showIcon 为真时渲染在 label 前；参数含节点与展开态，与 Tree 的 icon API 对齐',
    },
    {
      name: 'onChange',
      type: '(value: TreeKey|TreeKey[]|null) => void',
      default: 'undefined',
      desc: '多选返回 checked 全集数组，单选返回单 key',
    },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'virtualizeThreshold', type: 'number', default: '100', desc: '可见扁平行数 ≥ 此值时自动开启虚拟化；virtualized=true 强制开启' },
    { name: 'dropdownMatchSelectWidth', type: 'boolean', default: 'true', desc: '浮层宽度对齐触发器（min-inline-size = 触发器宽）' },
    { name: 'getPopupContainer', type: '() => HTMLElement | null | undefined', default: 'undefined', desc: '浮层挂载容器，缺省 ConfigProvider 全局值再回退 document.body' },
    { name: 'destroyOnClose', type: 'boolean', default: 'false', desc: '关闭即从 DOM 卸载浮层（重开重建）；默认首开后保留 DOM 仅隐藏' },
    { name: 'borderless', type: 'boolean', default: 'false', desc: '无边框模式：trigger 边框透明' },
    { name: 'prefix', type: 'Snippet | string', default: 'undefined', desc: 'trigger 前缀' },
    { name: 'suffix', type: 'Snippet | string', default: 'undefined', desc: 'trigger 后缀' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除按钮图标' },
    { name: 'expandIcon', type: 'Snippet<[{ node: TreeNode; expanded: boolean; level: number }]>', default: 'undefined', desc: '自定义展开图标；也可传无参 Snippet 统一渲染' },
    { name: 'arrowIcon', type: 'Snippet', default: 'undefined', desc: '自定义右侧下拉箭头（expandIcon 的别名）' },
    { name: 'showLine', type: 'boolean', default: 'false', desc: '显示节点连接线（垂直导引线）' },
    { name: 'labelEllipsis', type: 'boolean', default: 'true', desc: '节点 label 单行省略截断，可关闭以允许换行' },
    { name: 'style', type: 'string', default: 'undefined', desc: '选择框样式' },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '浮层遮挡时自动调整方向' },
    { name: 'validateStatus', type: "'default'|'error'|'warning'", default: 'undefined', desc: 'status 的别名（优先于 status）' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined', desc: '失焦回调' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined', desc: '聚焦回调' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: '聚焦时阻止滚动' },
    { name: 'outerTopSlot', type: 'Snippet', default: 'undefined', desc: '面板顶部外层 slot（在搜索框之上）' },
    { name: 'outerBottomSlot', type: 'Snippet', default: 'undefined', desc: '面板底部外层 slot（在树之下）' },
    { name: 'searchAutoFocus', type: 'boolean', default: 'false', desc: '面板打开时搜索框自动获焦' },
    { name: 'searchPosition', type: "'dropdown'|'trigger'", default: "'dropdown'", desc: "搜索框位置：'dropdown' 面板内；'trigger' trigger 内" },
    { name: 'searchPlaceholder', type: 'string', default: 'undefined', desc: '搜索框占位文字' },
    { name: 'treeNodeFilterProp', type: 'string', default: "'label'", desc: '搜索过滤属性' },
    { name: 'showSearchClear', type: 'boolean', default: 'true', desc: '搜索框右侧显示清除按钮（有内容时）' },
    { name: 'showFilteredOnly', type: 'boolean', default: 'false', desc: '搜索激活时仅显示命中节点，不显示祖先链' },
    { name: 'expandedKeys', type: 'TreeKey[]', default: 'undefined', desc: '受控展开的节点 keys' },
    { name: 'expandAll', type: 'boolean', default: 'false', desc: '动态全部展开（受控/动态，区别于 defaultExpandAll）' },
    { name: 'expandAction', type: "false | 'click' | 'doubleClick'", default: 'false', desc: "行点击展开方式：false 仅展开按钮；'click' 单击行；'doubleClick' 双击行" },
    { name: 'autoExpandParent', type: 'boolean', default: 'false', desc: '展开节点时自动展开其所有祖先链' },
    { name: 'motionExpand', type: 'boolean', default: 'true', desc: '展开/折叠动画' },
    { name: 'onExpand', type: '(expandedKeys: TreeKey[], info: { expanded: boolean; node: unknown }) => void', default: 'undefined', desc: '节点展开回调' },
    { name: 'autoMergeValue', type: 'boolean', default: 'true', desc: "自动合并值：父节点全选时 value 不含后代（等价 showCheckedStrategy='parent'）" },
    { name: 'onChangeWithObject', type: 'boolean', default: 'false', desc: 'onChange 回调携带完整节点对象而非仅 key' },
    { name: 'showRestTagsPopover', type: 'boolean', default: 'false', desc: '超出 maxTagCount 折叠的 tag 以 popover 展示剩余项' },
    { name: 'restTagsPopoverProps', type: 'Record<string, unknown>', default: 'undefined', desc: '传给剩余 tags popover 的额外 props' },
    { name: 'triggerTagWrap', type: 'boolean', default: 'false', desc: 'trigger 多选 tags 换行显示（默认单行截断折叠）' },
    { name: 'renderLabel', type: 'Snippet<[{ label: string; data: TreeNode; searchWord: string }]>', default: 'undefined', desc: '自定义节点 label 渲染（仅替换文字部分）' },
    { name: 'renderFullLabel', type: 'Snippet<[{ node: TreeNode; expanded: boolean; level: number; checked: boolean; halfChecked: boolean; selected: boolean }]>', default: 'undefined', desc: '完全自定义节点行渲染（替换整行内容）' },
    { name: 'renderSelectedItem', type: 'Snippet<[{ node: TreeNode; onRemove: () => void }]>', default: 'undefined', desc: '自定义 trigger 已选 tag 渲染（多选时每个 tag 独立渲染）' },
    { name: 'treeNodeLabelProp', type: 'string', default: "'label'", desc: '节点数据中用作显示 label 的字段名' },
    { name: 'keyMaps', type: '{ key?: string; label?: string; value?: string }', default: 'undefined', desc: '自定义 key/label/value 字段映射（优先级高于 fieldNames 的 key/label 部分）' },
    { name: 'optionListStyle', type: 'string | Record<string, string>', default: 'undefined', desc: '选项列表容器的内联 style' },
    { name: 'loadedKeys', type: 'Set<TreeKey>', default: 'undefined', desc: '受控已加载的节点 keys' },
    { name: 'clickToHide', type: 'boolean', default: 'true', desc: '单选选中后自动关闭面板' },
    { name: 'clickTriggerToHide', type: 'boolean', default: 'true', desc: '面板开启时点击 trigger 关闭面板' },
    { name: 'disableStrictly', type: 'boolean', default: 'false', desc: '严格禁用：disabled 节点不因父节点联动而影响，禁用态独立' },
    { name: 'dropdownMargin', type: 'number | { marginTop?: number; marginBottom?: number; marginLeft?: number; marginRight?: number }', default: 'undefined', desc: '浮层与 trigger 的额外间距（px）' },
    { name: 'onClear', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击清除按钮回调' },
    { name: 'onSelect', type: '(selectedKey: TreeKey, selected: boolean, node: unknown) => void', default: 'undefined', desc: '节点选中回调' },
    { name: 'onLoad', type: '(loadedKeys: TreeKey[], treeNode: TreeNode) => void', default: 'undefined', desc: '异步加载完成回调（含已加载 key 集合与当前节点）' },
    { name: 'onVisibleChange', type: '(isVisible: boolean) => void', default: 'undefined', desc: '面板可见性变化回调（与 onOpenChange 语义相同，Semi 风格别名）' },
  ],
  a11y: {
    role: 'combobox',
    notes: [
      'combobox 触发器 + role="tree" 面板 + role="treeitem"',
      '有 children 节点 aria-expanded 标记展开态',
      'aria-selected 标记选中节点',
      'leafOnly 时非叶子节点仅切换展开，不可选',
    ],
  },
  tokens: ['--cd-tree-select-*', '--cd-select-*', '--cd-tree-*', '--cd-focus-ring'],
} as const;
