/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'TreeSelect',
  category: 'input',
  description: '树形选择器，单面板可展开/收起的树，单选叶子或任意节点；支持 multiple 多选（checkbox + 父子联动 + 多 tag 回显）、可搜索过滤（本地/远程 + 命中高亮）、异步加载子节点、虚拟滚动大数据树、keyMaps 自定义字段映射与节点/tag/触发器渲染。严格对齐 Semi。',
  props: [
    { name: 'value', type: 'TreeKey|TreeKey[]|null', default: 'undefined' },
    { name: 'defaultValue', type: 'TreeKey|TreeKey[]|null', default: 'null' },
    { name: 'treeData', type: 'TreeNode[]', default: '[]', desc: '树数据源；字段名可经 keyMaps 自定义' },
    { name: 'defaultOpen', type: 'boolean', default: 'false' },
    { name: 'multiple', type: 'boolean', default: 'false', desc: 'checkbox 多选 + 父子联动，多 tag 回显' },
    { name: 'checkRelation', type: "'related'|'unRelated'", default: "'related'", desc: '多选父子是否级联联动；unRelated 互不影响（对齐 Semi）' },
    { name: 'maxTagCount', type: 'number', default: 'undefined', desc: '多选回填 Tag 最大展示数，超出折叠为 +N（仅影响显示）' },
    { name: 'placeholder', type: 'string', default: "'请选择'" },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'showClear', type: 'boolean', default: 'false', desc: '值不为空时 trigger 展示清除按钮（对齐 Semi）' },
    { name: 'leafOnly', type: 'boolean', default: 'false' },
    { name: 'defaultExpandAll', type: 'boolean', default: 'false' },
    { name: 'defaultExpandedKeys', type: 'TreeKey[]', default: '[]', desc: '默认展开的节点 key（非受控初始展开集，与 defaultExpandAll 取并集；对齐 Semi）' },
    { name: 'filterable', type: 'boolean', default: 'false', desc: '面板搜索框过滤节点 + 高亮命中' },
    { name: 'filterTreeNode', type: 'boolean | ((inputValue: string, treeNodeString: string, data?: TreeNode) => boolean)', default: 'undefined', desc: '按输入筛选节点（对齐 Semi）：true 开启搜索并默认按 treeNodeFilterProp 包含匹配；函数则自定义匹配谓词。与 filterable 其一为真即显示搜索框' },
    { name: 'remote', type: 'boolean', default: 'false', desc: '远程搜索：输入仅触发 onSearch，不本地过滤（外部更新 treeData）' },
    { name: 'onSearch', type: '(input: string, filteredExpandedKeys: TreeKey[], filteredNodes: TreeNode[]) => void', default: 'undefined', desc: '搜索输入回调（对齐 Semi 三入参）：入参为当前输入、过滤后应展开的节点 keys、命中节点数组' },
    {
      name: 'loadData',
      type: '(node: TreeNode) => Promise<TreeNode[]>',
      default: 'undefined',
      desc: '异步加载子节点：展开未加载的非叶子节点时调用，返回该节点子节点数组（加载中显示 spinner，竞态去重，不写回 treeData）。与 Tree 的 loadData 对齐',
    },
    { name: 'virtualize', type: '{ height?: number; width?: number | string; itemSize?: number }', default: 'undefined', desc: '列表虚拟化（对齐 Semi）：传入对象即开启，仅渲染视口内可见行；height 视口高（默认 224）、itemSize 行高（默认 32）。复用 Tree 范式（core fixedRange），保持 role=tree/treeitem 语义' },
    {
      name: 'triggerRender',
      type: 'Snippet<[{ value: TreeKey|TreeKey[]|null|undefined; placeholder: string; isOpen: boolean; disabled: boolean }]>',
      default: 'undefined',
      desc: '完全自定义触发器渲染（替换默认选择框）；参数含当前 value/placeholder/isOpen/disabled，与 Cascader.triggerRender 对齐',
    },
    { name: 'insetLabel', type: 'Snippet | string', default: 'undefined', desc: '触发器内嵌标签，渲染在回填值/占位符之前（对齐 Semi insetLabel），消费 --cd-color/font-tree-select-label token' },
    { name: 'insetLabelId', type: 'string', default: 'undefined', desc: '内嵌标签的 id（a11y 关联用），对齐 Semi insetLabelId' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '下拉浮层开合动画（淡入）；与 Cascader/Dropdown 的 motion 对齐。reduced-motion 退化' },
    {
      name: 'onChange',
      type: '(value: TreeKey|TreeKey[]|null) => void',
      default: 'undefined',
      desc: '多选返回 checked 全集数组，单选返回单 key',
    },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'ariaLabelledby', type: 'string', default: 'undefined', desc: 'aria-labelledby：关联外部 label 元素（Form.Field 透传 labelId，对齐 Semi）' },
    { name: 'ariaDescribedby', type: 'string', default: 'undefined', desc: 'aria-describedby：关联 helpText / extraText（Form.Field 透传）' },
    { name: 'ariaErrormessage', type: 'string', default: 'undefined', desc: 'aria-errormessage：error 态关联错误信息容器（Form.Field 透传）' },
    { name: 'ariaRequired', type: 'boolean', default: 'undefined', desc: 'aria-required：必填语义（Form.Field required 透传）' },
    { name: 'position', type: 'string', default: "'bottomLeft'", desc: '浮层弹出位置（对齐 Semi，参考 Tooltip position）；映射到 use:floating placement' },
    { name: 'dropdownMatchSelectWidth', type: 'boolean', default: 'true', desc: '浮层宽度对齐触发器（min-inline-size = 触发器宽）' },
    { name: 'getPopupContainer', type: '() => HTMLElement | null | undefined', default: 'undefined', desc: '浮层挂载容器，缺省 ConfigProvider 全局值再回退 document.body' },
    { name: 'stopPropagation', type: 'boolean', default: 'true', desc: '触发器点击是否阻止事件冒泡（对齐 Semi）' },
    { name: 'borderless', type: 'boolean', default: 'false', desc: '无边框模式：trigger 边框透明' },
    { name: 'prefix', type: 'Snippet | string', default: 'undefined', desc: 'trigger 前缀' },
    { name: 'suffix', type: 'Snippet | string', default: 'undefined', desc: 'trigger 后缀' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除按钮图标' },
    { name: 'expandIcon', type: 'Snippet<[{ node: TreeNode; expanded: boolean; level: number }]>', default: 'undefined', desc: '自定义展开图标；也可传无参 Snippet 统一渲染' },
    { name: 'arrowIcon', type: 'Snippet', default: 'undefined', desc: '自定义右侧下拉箭头（expandIcon 的别名）' },
    { name: 'showLine', type: 'boolean', default: 'false', desc: '显示节点连接线（垂直导引线）' },
    { name: 'labelEllipsis', type: 'boolean', default: 'true', desc: '节点 label 单行省略截断，可关闭以允许换行' },
    { name: 'style', type: 'string', default: 'undefined', desc: '选择框样式' },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '浮层遮挡时自动调整方向' },
    { name: 'validateStatus', type: "'default'|'error'|'warning'", default: 'undefined', desc: 'status 的别名（优先于 status）' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined', desc: '失焦回调' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined', desc: '聚焦回调' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: '聚焦时阻止滚动' },
    { name: 'outerTopSlot', type: 'Snippet', default: 'undefined', desc: '面板顶部外层 slot（在搜索框之上）' },
    { name: 'outerBottomSlot', type: 'Snippet', default: 'undefined', desc: '面板底部外层 slot（在树之下）' },
    { name: 'searchAutoFocus', type: 'boolean', default: 'false', desc: '面板打开时搜索框自动获焦' },
    { name: 'searchPosition', type: "'dropdown'|'trigger'", default: "'dropdown'", desc: "搜索框位置：'dropdown' 面板内；'trigger' trigger 内" },
    { name: 'searchPlaceholder', type: 'string', default: 'undefined', desc: '搜索框占位文字' },
    { name: 'treeNodeFilterProp', type: 'string', default: "'label'", desc: '搜索过滤属性' },
    { name: 'showSearchClear', type: 'boolean', default: 'true', desc: '搜索框右侧显示清除按钮（有内容时）' },
    { name: 'showFilteredOnly', type: 'boolean', default: 'false', desc: '搜索激活时仅显示命中节点，不显示祖先链' },
    { name: 'emptyContent', type: 'string | Snippet', default: 'undefined', desc: '无匹配/无数据占位内容（对齐 Semi emptyContent）；未传回退 i18n TreeSelect.emptyText' },
    { name: 'searchRender', type: 'boolean | Snippet<[{ value: string; onInput: (v: string) => void; onKeydown: (e: KeyboardEvent) => void; placeholder: string }]>', default: 'undefined', desc: '自定义搜索框渲染：false 隐藏内置搜索框；Snippet 完全接管渲染（回调回填输入）' },
    { name: 'expandedKeys', type: 'TreeKey[]', default: 'undefined', desc: '受控展开的节点 keys' },
    { name: 'expandAll', type: 'boolean', default: 'false', desc: '动态全部展开（受控/动态，区别于 defaultExpandAll）' },
    { name: 'expandAction', type: "false | 'click' | 'doubleClick'", default: 'false', desc: "行点击展开方式：false 仅展开按钮；'click' 单击行；'doubleClick' 双击行" },
    { name: 'autoExpandParent', type: 'boolean', default: 'false', desc: '展开节点时自动展开其所有祖先链' },
    { name: 'motionExpand', type: 'boolean', default: 'true', desc: '展开/折叠动画' },
    { name: 'onExpand', type: '(expandedKeys: TreeKey[], info: { expanded: boolean; node: unknown }) => void', default: 'undefined', desc: '节点展开回调' },
    { name: 'autoMergeValue', type: 'boolean', default: 'true', desc: '自动合并值：父节点全选时 value 折叠为父不含后代（对齐 Semi）；leafOnly 时改为仅叶子' },
    { name: 'onChangeWithObject', type: 'boolean', default: 'false', desc: 'onChange 回调携带完整节点对象而非仅 key' },
    { name: 'showRestTagsPopover', type: 'boolean', default: 'false', desc: '多选 maxTagCount 折叠出 +N 时，hover +N 用 Popover 浮层展示折叠掉的剩余全部 Tag' },
    { name: 'restTagsPopoverProps', type: 'Record<string, unknown>', default: 'undefined', desc: '透传给剩余 Tag Popover 浮层的额外 props（在默认 trigger=hover/position=top 之后展开，可覆盖）' },
    { name: 'triggerTagWrap', type: 'boolean', default: 'false', desc: 'trigger 多选 tags 换行显示（默认单行截断折叠）' },
    { name: 'renderLabel', type: 'Snippet<[{ label: string; data: TreeNode; searchWord: string }]>', default: 'undefined', desc: '自定义节点 label 渲染（仅替换文字部分）' },
    { name: 'renderFullLabel', type: 'Snippet<[{ node: TreeNode; expanded: boolean; level: number; checked: boolean; halfChecked: boolean; selected: boolean }]>', default: 'undefined', desc: '完全自定义节点行渲染（替换整行内容）' },
    { name: 'renderSelectedItem', type: 'Snippet<[{ node: TreeNode; onRemove: () => void }]>', default: 'undefined', desc: '自定义 trigger 已选 tag 渲染（多选时每个 tag 独立渲染）' },
    { name: 'treeNodeLabelProp', type: 'string', default: "'label'", desc: '节点数据中用作显示 label 的字段名' },
    { name: 'keyMaps', type: '{ key?: string; label?: string; value?: string; children?: string }', default: 'undefined', desc: '自定义节点字段名映射（对齐 Semi keyMaps）：适配任意后端数据结构，如 { key:\'id\', label:\'name\', children:\'sub\' }' },
    { name: 'optionListStyle', type: 'string | Record<string, string>', default: 'undefined', desc: '选项列表容器的内联 style' },
    { name: 'loadedKeys', type: 'Set<TreeKey>', default: 'undefined', desc: '受控已加载的节点 keys' },
    { name: 'clickToHide', type: 'boolean', default: 'true', desc: '单选选中后自动关闭面板' },
    { name: 'clickTriggerToHide', type: 'boolean', default: 'true', desc: '面板开启时点击 trigger 关闭面板' },
    { name: 'disableStrictly', type: 'boolean', default: 'false', desc: '严格禁用：disabled 节点不因父节点联动而影响，禁用态独立' },
    { name: 'dropdownMargin', type: 'number | { marginTop?: number; marginBottom?: number; marginLeft?: number; marginRight?: number }', default: 'undefined', desc: '浮层与 trigger 的额外间距（px）；数字映射到浮层 offset，对象取 marginTop' },
    { name: 'dropdownClassName', type: 'string', default: 'undefined', desc: '追加到浮层根节点的自定义类名（与内置类名并存）' },
    { name: 'dropdownStyle', type: 'string | Record<string, string>', default: 'undefined', desc: '合并进浮层根节点的内联样式（不覆盖内置定位样式）' },
    { name: 'zIndex', type: 'number', default: 'undefined', desc: '浮层层级（z-index），未传由 CSS 控制' },
    { name: 'onClear', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击清除按钮回调' },
    { name: 'onSelect', type: '(selectedKey: TreeKey, selected: boolean, node: unknown) => void', default: 'undefined', desc: '节点选中回调' },
    { name: 'onLoad', type: '(loadedKeys: TreeKey[], treeNode: TreeNode) => void', default: 'undefined', desc: '异步加载完成回调（含已加载 key 集合与当前节点）' },
    { name: 'onVisibleChange', type: '(isVisible: boolean) => void', default: 'undefined', desc: '面板可见性变化回调（对齐 Semi onVisibleChange）' },
  ],
  methods: [
    { name: 'search(sugInput)', desc: '命令式搜索：把值置给内部搜索态并触发过滤（对齐 Semi，用于外部自定义搜索框）' },
  ],
  a11y: {
    role: 'combobox',
    notes: [
      'combobox 触发器 + role="tree" 面板 + role="treeitem"',
      '有 children 节点 aria-expanded 标记展开态',
      'aria-selected 标记选中节点',
      'leafOnly 时非叶子节点仅切换展开，不可选',
    ],
  },
  tokens: ['--cd-tree-select-*', '--cd-color-tree-select-label', '--cd-font-tree-select-label', '--cd-dropdown-motion-*', '--cd-select-*', '--cd-tree-*', '--cd-focus-ring'],
} as const;
