/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'TreeSelect',
  category: 'input',
  description: '树形选择器，单面板可展开/收起的树，单选叶子或任意节点。',
  props: [
    { name: 'value', type: 'TreeKey|TreeKey[]|null', default: 'undefined' },
    { name: 'defaultValue', type: 'TreeKey|TreeKey[]|null', default: 'null' },
    { name: 'treeData', type: 'TreeNode[]', default: '[]', desc: '树数据源；字段名可经 fieldNames 自定义' },
    {
      name: 'fieldNames',
      type: '{ key?: string; label?: string; children?: string }',
      default: "{ key:'key', label:'label', children:'children' }",
      desc: '自定义节点字段名映射，适配任意后端数据（如 { key:\'id\', label:\'name\', children:\'sub\' }）。派生只读映射；onChange 回传的 key 即原始字段值',
    },
    { name: 'open', type: 'boolean', default: 'undefined' },
    { name: 'defaultOpen', type: 'boolean', default: 'false' },
    { name: 'multiple', type: 'boolean', default: 'false', desc: 'checkbox 多选 + 父子联动，多 tag 回显' },
    { name: 'checkStrictly', type: 'boolean', default: 'false', desc: '多选时父子勾选互不影响（向后兼容，等价 checkRelation=unRelated）' },
    { name: 'checkRelation', type: "'related'|'unRelated'", default: "'related'", desc: '多选父子是否级联联动；unRelated 互不影响。checkStrictly=true 强制 unRelated' },
    { name: 'showCheckedStrategy', type: "'all'|'parent'|'child'", default: "'all'", desc: '回填值/Tag 收敛策略：all 全部勾选节点；parent 折叠为父；child 仅叶子。仅 related 生效' },
    { name: 'maxTagCount', type: 'number', default: 'undefined', desc: '多选回填 Tag 最大展示数，超出折叠为 +N（仅影响显示）' },
    { name: 'placeholder', type: 'string', default: "'请选择'" },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'clearable', type: 'boolean', default: 'false' },
    { name: 'leafOnly', type: 'boolean', default: 'false' },
    { name: 'defaultExpandAll', type: 'boolean', default: 'false' },
    { name: 'treeDefaultExpandedKeys', type: 'TreeKey[]', default: '[]', desc: '默认展开的节点 key（非受控初始展开集，与 defaultExpandAll 取并集）' },
    { name: 'filterable', type: 'boolean', default: 'false', desc: '面板搜索框过滤节点 + 高亮命中' },
    { name: 'remote', type: 'boolean', default: 'false', desc: '远程搜索：输入防抖后仅触发 onSearch，不本地过滤（外部更新 treeData）' },
    { name: 'searchDebounce', type: 'number', default: '300', desc: 'onSearch 防抖毫秒（remote 时生效）' },
    { name: 'onSearch', type: '(query: string) => void', default: 'undefined', desc: '远程搜索输入回调（防抖后）' },
    { name: 'showIcon', type: 'boolean', default: 'true', desc: '是否预留节点图标位（icon 提供时渲染在 label 前），与 Tree 对齐' },
    {
      name: 'loadData',
      type: '(node: TreeNode) => Promise<TreeNode[]>',
      default: 'undefined',
      desc: '异步加载子节点：展开未加载的非叶子节点时调用，返回该节点子节点数组（加载中显示 spinner，竞态去重，不写回 treeData）。与 Tree 的 loadData 对齐',
    },
    { name: 'virtualized', type: 'boolean', default: 'false', desc: '虚拟滚动：仅渲染视口内可见行，适合大数据树。复用 Tree 范式（core fixedRange），保持 role=tree/treeitem 语义' },
    { name: 'height', type: 'number', default: '224', desc: '虚拟滚动视口高度（px），virtualized 时生效' },
    { name: 'itemHeight', type: 'number', default: '32', desc: '虚拟滚动行高（px），virtualized 时生效' },
    {
      name: 'icon',
      type: 'Snippet<[{ node: TreeNode; expanded: boolean; level: number }]>',
      default: 'undefined',
      desc: '自定义节点图标，showIcon 为真时渲染在 label 前；参数含节点与展开态，与 Tree 的 icon API 对齐',
    },
    {
      name: 'onChange',
      type: '(value: TreeKey|TreeKey[]|null) => void',
      default: 'undefined',
      desc: '多选返回 checked 全集数组，单选返回单 key',
    },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
  ],
  a11y: {
    role: 'combobox',
    notes: [
      'combobox 触发器 + role="tree" 面板 + role="treeitem"',
      '有 children 节点 aria-expanded 标记展开态',
      'aria-selected 标记选中节点',
      'leafOnly 时非叶子节点仅切换展开，不可选',
    ],
  },
  tokens: ['--cd-tree-select-*', '--cd-select-*', '--cd-tree-*', '--cd-focus-ring'],
} as const;
