/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 * 严格对齐 Semi Design semi-ui/popconfirm。Popconfirm 封装 Popover（对齐 Semi
 * `Popconfirm extends PopoverProps` + `<Popover content={renderConfirmPopCard}>`），
 * 复用 Popover→Tooltip 的全部定位/触发/焦点/dismiss/12 方位/箭头基建。
 */
export const meta = {
  name: 'Popconfirm',
  category: 'feedback',
  description:
    '气泡确认框：目标元素操作需二次确认时使用。封装 Popover，内置确认/取消双按钮，比 Modal 更轻量。支持 title/content、危险分级 type（default/warning/danger）、okType/cancelType、onConfirm 返回 Promise 时确认按钮 loading（resolve 关闭 / reject 保持）、12 方位 position（默认 bottomLeft）。role=dialog non-modal。',
  exports: ['Popconfirm'],
  props: [
    { name: 'visible', type: 'boolean', default: 'undefined', desc: '受控显隐（配合 trigger=custom）；不回写，仅 onVisibleChange' },
    { name: 'defaultVisible', type: 'boolean', default: 'false', desc: '非受控初始显隐' },
    { name: 'title', type: 'string', default: 'undefined', desc: '确认标题' },
    { name: 'titleSnippet', type: 'Snippet', default: 'undefined', desc: '覆盖 title（富文本标题）' },
    { name: 'content', type: 'string', default: 'undefined', desc: '补充说明' },
    { name: 'contentSnippet', type: 'Snippet', default: 'undefined', desc: '覆盖 content（富文本正文）' },
    {
      name: 'type',
      type: "'default'|'danger'|'warning'",
      default: "'default'",
      desc: '影响默认图标与确认按钮默认类型',
    },
    {
      name: 'icon',
      type: 'Snippet | false',
      default: 'undefined',
      desc: '自定义图标；false 隐藏；缺省按 type 默认图标',
    },
    { name: 'okText', type: 'string', default: "'确认'（locale）", desc: '确认按钮文字' },
    { name: 'cancelText', type: 'string', default: "'取消'（locale）", desc: '取消按钮文字' },
    {
      name: 'okType',
      type: "'primary'|'secondary'|'tertiary'|'warning'|'danger'",
      default: "'primary'",
      desc: '确认按钮类型；缺省 type=danger→danger 否则 primary',
    },
    { name: 'cancelType', type: 'ButtonType', default: "'tertiary'", desc: '取消按钮类型（对齐 Semi）' },
    { name: 'okButtonProps', type: 'ExtraButtonProps', default: 'undefined', desc: '透传确认按钮额外属性（onclick/loading 组件托管）' },
    { name: 'cancelButtonProps', type: 'ExtraButtonProps', default: 'undefined', desc: '透传取消按钮额外属性（onclick/disabled 组件托管）' },
    { name: 'showCancel', type: 'boolean', default: 'true', desc: '是否显示取消按钮' },
    {
      name: 'position',
      type: "'top'|'topLeft'|...|'bottomRight' 等 12 方位",
      default: "'bottomLeft'",
      desc: '弹出方位（对齐 Semi 默认 bottomLeft）',
    },
    { name: 'trigger', type: "'click'|'hover'|'focus'|'custom'", default: "'click'", desc: '触发方式（对齐 Semi）' },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '禁用触发' },
    { name: 'closeOnEsc', type: 'boolean', default: 'true', desc: 'Esc 关闭' },
    { name: 'arrowPointAtCenter', type: 'boolean', default: 'true', desc: '箭头指向触发元素中心（需 showArrow）' },
    { name: 'showArrow', type: 'boolean', default: 'false', desc: '是否显示箭头三角（对齐 Semi 默认 false）' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '入场动效（reduced-motion 退化）' },
    { name: 'mouseEnterDelay', type: 'number', default: '50', desc: 'hover 进入延迟(ms)' },
    { name: 'mouseLeaveDelay', type: 'number', default: '50', desc: 'hover 离开延迟(ms)' },
    { name: 'getPopupContainer', type: '() => HTMLElement', default: 'undefined', desc: '自定义浮层容器' },
    { name: 'zIndex', type: 'number', default: 'undefined', desc: '浮层层级' },
    { name: 'guardFocus', type: 'boolean', default: 'trigger∈{click,custom}', desc: 'Tab 焦点在浮层内循环' },
    { name: 'returnFocusOnClose', type: 'boolean', default: 'true', desc: '关闭后焦点归还触发器' },
    { name: 'stopPropagation', type: 'boolean', default: 'true', desc: '阻止浮层内事件冒泡（对齐 Semi）' },
    { name: 'rePosKey', type: 'string | number', default: 'undefined', desc: '手动触发重新定位' },
    { name: 'class', type: 'string', default: "''", desc: '卡片自定义类名' },
    { name: 'style', type: 'string', default: "''", desc: '卡片自定义内联样式' },
    { name: 'children', type: 'Snippet', default: 'undefined', desc: '触发元素（必填）' },
    { name: 'onVisibleChange', type: '(visible: boolean) => void', default: 'undefined', desc: '显隐切换回调' },
    { name: 'onClickOutSide', type: '(e: MouseEvent) => void', default: 'undefined', desc: '点击浮层外部回调' },
    { name: 'onConfirm', type: '() => void | Promise<unknown>', default: 'undefined', desc: '确认回调；返回 Promise 时按钮 loading，resolve 关闭 / reject 保持' },
    { name: 'onCancel', type: '() => void', default: 'undefined', desc: '取消回调' },
  ],
  a11y: {
    role: 'dialog',
    keyboard: ['Escape', 'Tab', 'Shift+Tab', 'Enter', 'Space'],
    notes: [
      '浮层 role=dialog（aria-modal=false，复用 Popover），aria-labelledby 指向 Popconfirm 标题',
      '触发元素承载 role=button + aria-haspopup=dialog + aria-expanded/controls（复用 Popover dialog 语义）',
      'guardFocus（默认随 click/custom）用 useFocusTrap 陷入焦点，关闭后 returnFocusOnClose 归还触发器',
      '异步确认 loading 时经 useLiveAnnouncer 播报「处理中」给屏幕阅读器',
      'closeOnEsc 与外部点击关闭复用 Popover→Tooltip 的 useDismiss',
    ],
  },
  tokens: [
    // chenzy-design Popconfirm 卡片消费 token（值全量对齐 Semi popconfirm/variables.scss）
    '--cd-color-popconfirm-header-text',
    '--cd-color-popconfirm-body-text',
    '--cd-color-popconfirm-header-alert-icon',
    '--cd-width-popconfirm-icon',
    '--cd-width-popconfirm-maxwidth',
    '--cd-spacing-popconfirm-top',
    '--cd-spacing-popconfirm-bottom',
    '--cd-spacing-popconfirm-header-title-marginbottom',
    '--cd-spacing-popconfirm-header-icon-marginright',
    '--cd-spacing-popconfirm-footer-margintop',
    '--cd-spacing-popconfirm-footer-btn-marginright',
    '--cd-font-popconfirm-header-title-fontweight',
    '--cd-radius-popconfirm-popover',
    '--cd-popconfirm-icon-color-danger',
    '--cd-popconfirm-icon-color-warning',
    // 卡面/定位复用 Popover→Tooltip
    '--cd-popover-*',
    '--cd-tooltip-*',
  ],
} as const;
