/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Cascader',
  category: 'input',
  description: '级联选择器，点击（或 hover）逐级展开列，单选叶子/任一层级；支持 multiple 多选（每列 checkbox + 父子联动 + 多 tag 回显）、可搜索过滤（本地/远程 + 结果虚拟滚动）、动态加载子节点、自定义字段映射与触发器/结果渲染。',
  props: [
    { name: 'value', type: '(string|number)[] | (string|number)[][]', default: 'undefined', desc: '单选单条路径；多选多条路径' },
    { name: 'defaultValue', type: '(string|number)[] | (string|number)[][]', default: 'undefined' },
    { name: 'treeData', type: 'CascaderNode[]', default: '[]' },
    { name: 'open', type: 'boolean', default: 'undefined' },
    { name: 'defaultOpen', type: 'boolean', default: 'false' },
    { name: 'multiple', type: 'boolean', default: 'false', desc: '每列 checkbox 多选 + 父子联动，多 tag 回显' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default' },
    { name: 'placeholder', type: 'string', default: "'请选择'" },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'clearable', type: 'boolean', default: 'false' },
    { name: 'changeOnSelect', type: 'boolean', default: 'false', desc: '单选：点击任一层级（含中间非叶子）即提交该路径并触发 onChange，非叶子同时展开子列且不关闭面板，叶子提交并关闭；关闭时仅叶子提交并关闭' },
    { name: 'expandTrigger', type: "'click'|'hover'", default: "'click'", desc: "'hover' 悬停非叶子节点即展开子级列" },
    { name: 'leafOnly', type: 'boolean', default: 'false', desc: '多选时完全勾选的父级折叠为父路径（只回传/计数到该父级）；默认 false 仅回传叶子' },
    { name: 'filterable', type: 'boolean', default: 'false', desc: '可搜索（向后兼容别名，等价 filterTreeNode=true）' },
    { name: 'filterTreeNode', type: 'boolean | ((query, path) => boolean)', default: 'undefined', desc: '是否可搜索及自定义匹配：false 关闭；true 默认 label 链子串匹配；函数自定义谓词。未传时回退 filterable' },
    { name: 'filterLeafOnly', type: 'boolean', default: 'true', desc: '搜索结果是否仅展示到叶子路径' },
    { name: 'displayProp', type: "'label'|'value'", default: "'label'", desc: '触发器回显使用的字段' },
    { name: 'separator', type: 'string', default: "' / '", desc: '路径分隔符（回显 + 搜索 label 链拼接）' },
    { name: 'maxTagCount', type: 'number', default: 'undefined', desc: '多选 Tag 溢出折叠阈值：超出显示前 N 个 + +M' },
    { name: 'emptyContent', type: 'string | Snippet', default: 'undefined', desc: '列为空时内容；缺省走 i18n' },
    { name: 'destroyOnClose', type: 'boolean', default: 'false', desc: '关闭即卸载浮层内容（{#if}），重开重建；默认 false 首开后保留 DOM 仅隐藏' },
    { name: 'zIndex', type: 'number', default: '1030', desc: '浮层层级' },
    { name: 'getPopupContainer', type: '() => HTMLElement | null | undefined', default: 'undefined', desc: '浮层挂载容器，缺省 document.body；非 body 容器时 absolute 定位相对该容器' },
    { name: 'columnWidth', type: 'number | number[]', default: '180', desc: '列宽：统一（number）或逐列（number[]，超出取末项）' },
    { name: 'loadData', type: '(node: CascaderNode) => Promise<CascaderNode[]>', default: 'undefined', desc: '动态加载子节点' },
    { name: 'displayRender', type: '(labels: string[], selectedNodes: CascaderNode[]) => string', default: 'undefined', desc: '自定义触发器选中路径回显（单选 + 多选每个 tag 共用）' },
    { name: 'onChange', type: '(value: (string|number)[] | (string|number)[][]) => void', default: 'undefined', desc: '单选回调单条路径；多选回调多条叶子路径' },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
    { name: 'borderless', type: 'boolean', default: 'false', desc: '无边框模式' },
    { name: 'prefix', type: 'Snippet | string', default: 'undefined', desc: '前置内容' },
    { name: 'insetLabel', type: 'Snippet | string', default: 'undefined', desc: '内嵌标签：触发器在值前渲染的标签（如「地区：」），Semi 中为 prefix 的别名' },
    { name: 'insetLabelId', type: 'string', default: 'undefined', desc: '内嵌标签的 DOM id（供外部 aria-labelledby 引用）' },
    { name: 'suffix', type: 'Snippet | string', default: 'undefined', desc: '后置内容' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除图标' },
    { name: 'expandIcon', type: 'Snippet', default: 'undefined', desc: '自定义展开图标（expandIcon / arrowIcon 均可，expandIcon 优先）' },
    { name: 'arrowIcon', type: 'Snippet', default: 'undefined', desc: '自定义右侧下拉箭头（expandIcon 的别名）' },
    { name: 'motion', type: 'boolean', default: 'true', desc: '下拉框展开动画' },
    { name: 'mouseEnterDelay', type: 'number', default: '50', desc: '鼠标移入延迟（ms）' },
    { name: 'mouseLeaveDelay', type: 'number', default: '50', desc: '鼠标移出延迟（ms）' },
    { name: 'autoAdjustOverflow', type: 'boolean', default: 'true', desc: '下拉框自动调整方向' },
    { name: 'position', type: 'string', default: "'bottomStart'", desc: '下拉框方向' },
    { name: 'style', type: 'string', default: 'undefined', desc: '选择框样式' },
    { name: 'dropdownStyle', type: 'string | Record<string, string>', default: 'undefined', desc: '下拉菜单样式' },
    { name: 'onBlur', type: '(e: MouseEvent) => void', default: 'undefined', desc: '失焦回调' },
    { name: 'onFocus', type: '(e: MouseEvent) => void', default: 'undefined', desc: '聚焦回调' },
    { name: 'preventScroll', type: 'boolean', default: 'false', desc: '聚焦时阻止滚动' },
    { name: 'stopPropagation', type: 'boolean', default: 'true', desc: '阻止下拉框点击冒泡' },
    { name: 'topSlot', type: 'Snippet', default: 'undefined', desc: '面板顶部插槽' },
    { name: 'bottomSlot', type: 'Snippet', default: 'undefined', desc: '面板底部插槽' },
    { name: 'searchPosition', type: "'trigger'|'custom'", default: "'trigger'", desc: "搜索框位置：'trigger' 内置；'custom' 不渲染内置搜索框" },
    { name: 'searchPlaceholder', type: 'string', default: 'undefined', desc: '搜索框占位文字' },
    { name: 'treeNodeFilterProp', type: 'string', default: "'label'", desc: '搜索时过滤的属性' },
    { name: 'filterRender', type: 'Snippet<[{ path: FlatPath }]>', default: 'undefined', desc: '自定义搜索结果项渲染' },
    { name: 'filterSorter', type: '(a: FlatPath, b: FlatPath, input: string) => number', default: 'undefined', desc: '搜索结果自定义排序' },
    { name: 'onSearch', type: '(value: string) => void', default: 'undefined', desc: '搜索输入回调' },
    { name: 'remote', type: 'boolean', default: 'false', desc: '远程搜索模式：跳过本地过滤，只触发 onSearch' },
    { name: 'virtualizeInSearch', type: '{ height: number; width: number; itemSize: number }', default: 'undefined', desc: '搜索结果虚拟滚动配置' },
    { name: 'autoMergeValue', type: 'boolean', default: 'true', desc: '选中父节点时 value 不包含后代' },
    { name: 'checkRelation', type: "'related'|'unRelated'", default: "'related'", desc: "勾选关系：'related' 父子联动；'unRelated' 独立" },
    { name: 'onChangeWithObject', type: 'boolean', default: 'false', desc: 'onChange 回调是否返回完整 option 对象' },
    { name: 'max', type: 'number', default: 'undefined', desc: '多选可勾选数量上限；超出时不选入并触发 onExceed（减少始终允许）' },
    { name: 'onExceed', type: '(items: CascaderNode[]) => void', default: 'undefined', desc: '超出 max 时回调，传当前（含超出项）勾选的节点集合' },
    { name: 'showRestTagsPopover', type: 'boolean', default: 'false', desc: '超出 maxTagCount 时是否显示 popover' },
    { name: 'restTagsPopoverProps', type: 'Record<string, unknown>', default: 'undefined', desc: '超出 tag popover 的 props' },
    { name: 'showClear', type: 'boolean', default: 'undefined', desc: '是否显示清除按钮（clearable 的别名）' },
    { name: 'keyMaps', type: '{ value?: string; label?: string; children?: string; disabled?: string; isLeaf?: string }', default: 'undefined', desc: '自定义字段名映射' },
    { name: 'clickToSelect', type: 'boolean', default: 'false', desc: '点击任意节点即选中（含非叶子）' },
    { name: 'enableLeafClick', type: 'boolean', default: 'false', desc: '多选模式下点击叶子节点触发勾选' },
    { name: 'disableStrictly', type: 'boolean', default: 'false', desc: '禁用不从父节点继承（严格禁用）' },
    { name: 'showNext', type: "'click'|'hover'", default: "'click'", desc: '展开触发方式（canonical prop，优先于 expandTrigger）' },
    { name: 'onClear', type: '() => void', default: 'undefined', desc: '清空回调' },
    { name: 'onLoad', type: '(loadedKeys: Key[], data: CascaderNode) => void', default: 'undefined', desc: '异步加载完成回调' },
    { name: 'onSelect', type: '(value: Key) => void', default: 'undefined', desc: '节点选中回调（单选叶子选中时）' },
    { name: 'onDropdownVisibleChange', type: '(visible: boolean) => void', default: 'undefined', desc: '下拉面板显隐回调' },
    { name: 'onListScroll', type: '(e: Event, info: { panelIndex: number; activeNode: CascaderNode | null }) => void', default: 'undefined', desc: '列滚动回调' },
    { name: 'triggerRender', type: 'Snippet<[{ value: Key[] | Key[][] | undefined; placeholder: string; isOpen: boolean; disabled: boolean }]>', default: 'undefined', desc: '完全自定义触发器渲染' },
  ],
  a11y: {
    role: 'combobox',
    notes: [
      'combobox + 每列 listbox + option ARIA 模式',
      '触发器 aria-haspopup="listbox"、aria-expanded',
      '每列 option aria-selected 标记当前路径',
      'disabled 节点 aria-disabled 且不可点击',
    ],
  },
  tokens: [
    // 触发器复用 Input/Select 填充式 token（背景/描边/圆角/内边距/状态描边）
    '--cd-select-*',
    '--cd-input-*',
    // 菜单节点尺寸复用 Tree（节点高度/内边距）
    '--cd-tree-node-height',
    '--cd-tree-node-padding-x',
    // Cascader 专属 token（全量对齐 Semi cascader/variables.scss）
    '--cd-color-cascader-option-bg-hover',
    '--cd-color-cascader-option-bg-active',
    '--cd-color-cascader-option-main-text-default',
    '--cd-color-cascader-option-icon-default',
    '--cd-color-cascader-icon-default',
    '--cd-color-cascader-prefix-suffix-text-default',
    // insetLabel 内嵌标签消费的 label token
    '--cd-color-cascader-label-text-default',
    '--cd-font-cascader-label-fontweight',
    '--cd-color-cascader-select-highlight',
    '--cd-cascader-column-width',
    '--cd-cascader-column-border',
    '--cd-focus-ring',
  ],
} as const;
