/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'Cascader',
  category: 'input',
  description: '级联选择器，点击逐级展开列，单选叶子节点。',
  props: [
    { name: 'value', type: '(string|number)[] | (string|number)[][]', default: 'undefined', desc: '单选单条路径；多选多条路径' },
    { name: 'defaultValue', type: '(string|number)[] | (string|number)[][]', default: 'undefined' },
    { name: 'treeData', type: 'CascaderNode[]', default: '[]' },
    { name: 'open', type: 'boolean', default: 'undefined' },
    { name: 'defaultOpen', type: 'boolean', default: 'false' },
    { name: 'multiple', type: 'boolean', default: 'false', desc: '每列 checkbox 多选 + 父子联动，多 tag 回显' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default' },
    { name: 'placeholder', type: 'string', default: "'请选择'" },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'clearable', type: 'boolean', default: 'false' },
    { name: 'changeOnSelect', type: 'boolean', default: 'false', desc: '单选：点击任一层级（含中间非叶子）即提交该路径并触发 onChange，非叶子同时展开子列且不关闭面板，叶子提交并关闭；关闭时仅叶子提交并关闭' },
    { name: 'expandTrigger', type: "'click'|'hover'", default: "'click'", desc: "'hover' 悬停非叶子节点即展开子级列" },
    { name: 'leafOnly', type: 'boolean', default: 'false', desc: '多选时完全勾选的父级折叠为父路径（只回传/计数到该父级）；默认 false 仅回传叶子' },
    { name: 'filterable', type: 'boolean', default: 'false', desc: '可搜索（向后兼容别名，等价 filterTreeNode=true）' },
    { name: 'filterTreeNode', type: 'boolean | ((query, path) => boolean)', default: 'undefined', desc: '是否可搜索及自定义匹配：false 关闭；true 默认 label 链子串匹配；函数自定义谓词。未传时回退 filterable' },
    { name: 'filterLeafOnly', type: 'boolean', default: 'true', desc: '搜索结果是否仅展示到叶子路径' },
    { name: 'displayProp', type: "'label'|'value'", default: "'label'", desc: '触发器回显使用的字段' },
    { name: 'separator', type: 'string', default: "' / '", desc: '路径分隔符（回显 + 搜索 label 链拼接）' },
    { name: 'maxTagCount', type: 'number', default: 'undefined', desc: '多选 Tag 溢出折叠阈值：超出显示前 N 个 + +M' },
    { name: 'emptyContent', type: 'string | Snippet', default: 'undefined', desc: '列为空时内容；缺省走 i18n' },
    { name: 'destroyOnClose', type: 'boolean', default: 'false', desc: '关闭即卸载浮层内容（{#if}），重开重建；默认 false 首开后保留 DOM 仅隐藏' },
    { name: 'zIndex', type: 'number', default: '1030', desc: '浮层层级' },
    { name: 'getPopupContainer', type: '() => HTMLElement | null | undefined', default: 'undefined', desc: '浮层挂载容器，缺省 document.body；非 body 容器时 absolute 定位相对该容器' },
    { name: 'columnWidth', type: 'number | number[]', default: '180', desc: '列宽：统一（number）或逐列（number[]，超出取末项）' },
    { name: 'loadData', type: '(node: CascaderNode) => Promise<CascaderNode[]>', default: 'undefined', desc: '动态加载子节点' },
    { name: 'displayRender', type: '(labels: string[], selectedNodes: CascaderNode[]) => string', default: 'undefined', desc: '自定义触发器选中路径回显（单选 + 多选每个 tag 共用）' },
    { name: 'onChange', type: '(value: (string|number)[] | (string|number)[][]) => void', default: 'undefined', desc: '单选回调单条路径；多选回调多条叶子路径' },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'ariaLabel', type: 'string', default: 'undefined' },
  ],
  a11y: {
    role: 'combobox',
    notes: [
      'combobox + 每列 listbox + option ARIA 模式',
      '触发器 aria-haspopup="listbox"、aria-expanded',
      '每列 option aria-selected 标记当前路径',
      'disabled 节点 aria-disabled 且不可点击',
    ],
  },
  tokens: [
    '--cd-select-*',
    '--cd-tree-*',
    '--cd-cascader-column-width',
    '--cd-cascader-column-border',
    '--cd-focus-ring',
  ],
} as const;
