/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 */
export const meta = {
  name: 'AutoComplete',
  category: 'input',
  description: '输入联想框，支持本地过滤候选、远程异步搜索、选项分组、内嵌标签与键盘选择。',
  props: [
    { name: 'value', type: 'string', default: 'undefined' },
    { name: 'defaultValue', type: 'string', default: "''" },
    { name: 'data', type: 'ItemOrGroup[]', default: '[]' },
    { name: 'open', type: 'boolean', default: 'undefined' },
    { name: 'defaultOpen', type: 'boolean', default: 'false' },
    { name: 'placeholder', type: 'string', default: "''" },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: 'combobox 输入框可访问名；缺省回退 placeholder 或 locale 默认' },
    { name: 'ariaLabelledby', type: 'string', default: 'undefined', desc: '关联外部 label 的 id（优先于 ariaLabel）' },
    { name: 'insetLabel', type: 'string|Snippet', default: 'undefined' },
    { name: 'openOnFocus', type: 'boolean', default: 'false' },
    { name: 'size', type: "'small'|'default'|'large'", default: 'default' },
    { name: 'status', type: "'default'|'warning'|'error'", default: 'default' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'filter', type: 'boolean', default: 'true' },
    { name: 'defaultActiveFirstOption', type: 'boolean', default: 'true' },
    { name: 'clearable', type: 'boolean', default: 'false' },
    { name: 'onSearch', type: '(query: string) => void', default: 'undefined' },
    { name: 'loading', type: 'boolean', default: 'false' },
    { name: 'searchDebounce', type: 'number', default: '300' },
    { name: 'maxCount', type: 'number', default: '0' },
    { name: 'onChange', type: '(v: string) => void', default: 'undefined' },
    { name: 'onSelect', type: '(value: string|number|NormalizedItem) => void', default: 'undefined', desc: 'onSelectWithObject=true 时回传完整候选对象' },
    { name: 'onSelectWithObject', type: 'boolean', default: 'false', desc: 'true 时 onSelect 入参从 value 变为 { value, label, disabled } 对象（对齐 Semi）' },
    { name: 'onKeyDown', type: '(e: KeyboardEvent) => void', default: 'undefined', desc: '透传输入框原始 keydown 事件（对齐 Semi）' },
    { name: 'onOpenChange', type: '(open: boolean) => void', default: 'undefined' },
    { name: 'dropdownMatchSelectWidth', type: 'boolean', default: 'true', desc: '浮层宽度与触发器同宽' },
    { name: 'getPopupContainer', type: '() => HTMLElement', default: 'undefined', desc: '浮层挂载容器' },
    { name: 'dropdownClassName', type: 'string', default: 'undefined', desc: '浮层 className' },
    { name: 'dropdownStyle', type: 'string | Record<string, string>', default: 'undefined', desc: '浮层样式' },
    { name: 'triggerRender', type: 'Snippet<[{ value: string; placeholder: string; disabled: boolean }]>', default: 'undefined', desc: '完全自定义触发器' },
    { name: 'renderItem', type: 'Snippet<[{ item: NormalizedItem; isSelected: boolean }]>', default: 'undefined', desc: '自定义候选项渲染' },
    { name: 'renderSelectedItem', type: 'Snippet<[{ item: NormalizedItem }]>', default: 'undefined', desc: '自定义已选项显示' },
    { name: 'emptyContent', type: 'Snippet | string', default: 'undefined', desc: '无候选时展示内容' },
    { name: 'prefix', type: 'Snippet | string', default: 'undefined', desc: '输入框前缀' },
    { name: 'suffix', type: 'Snippet | string', default: 'undefined', desc: '输入框后缀' },
    { name: 'showClear', type: 'boolean', default: 'undefined', desc: '显示清除按钮（clearable 的别名，showClear 优先）' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除图标' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined' },
    { name: 'onClear', type: '() => void', default: 'undefined' },
    { name: 'remote', type: 'boolean', default: 'false', desc: '显式远程模式（关闭本地过滤），不依赖 onSearch 是否存在' },
    { name: 'autoFocus', type: 'boolean', default: 'false', desc: '挂载自动聚焦' },
    { name: 'position', type: 'string', default: "'bottomLeft'", desc: '浮层位置' },
    { name: 'maxHeight', type: 'number|string', default: 'undefined', desc: '下拉浮层最大高度，number→px（对齐 Semi）' },
    { name: 'zIndex', type: 'number', default: 'undefined', desc: '下拉浮层 z-index（对齐 Semi）' },
    { name: 'class', type: 'string', default: "''", desc: '根节点 className' },
    { name: 'style', type: 'string', default: "''", desc: '根节点内联样式' },
  ],
  a11y: {
    role: 'combobox',
    notes: [
      'combobox + aria-autocomplete="list" + listbox',
      'aria-activedescendant 指向高亮候选',
      '键盘：↑↓ 移动、Enter 选中、Esc 关闭',
    ],
  },
  tokens: ['--cd-autocomplete-*', '--cd-focus-ring', '--cd-motion-*'],
} as const;
