/**
 * Machine-readable component metadata for AI/docs consumption.
 * See specs/00-foundation/ai-friendly.spec.md.
 * 严格对齐 Semi Design autoComplete props（已删超集 remote/searchDebounce/maxCount/filter/
 * openOnFocus/status/clearable/open/onOpenChange；status→validateStatus；onOpenChange→onDropdownVisibleChange）。
 */
export const meta = {
  name: 'AutoComplete',
  category: 'input',
  description: '输入联想框，data 由用户按 query 准备（远程或本地），支持键盘选择、内嵌标签与关键词高亮。',
  props: [
    { name: 'value', type: 'string|number', default: 'undefined', desc: '受控输入值' },
    { name: 'defaultValue', type: 'string|number', default: "''", desc: '非受控初始值' },
    { name: 'data', type: 'Item[]', default: '[]', desc: '候选数据（由用户按 query 准备，组件不做本地过滤）' },
    { name: 'defaultOpen', type: 'boolean', default: 'false', desc: '非受控初始展开' },
    { name: 'placeholder', type: 'string', default: "''" },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: 'combobox 可访问名；缺省回退 placeholder 或 locale 默认' },
    { name: 'ariaLabelledby', type: 'string', default: 'undefined', desc: '关联外部 label 的 id（优先于 ariaLabel）' },
    { name: 'insetLabel', type: 'string|Snippet', default: 'undefined', desc: '输入框内嵌前缀标签' },
    { name: 'insetLabelId', type: 'string', default: 'undefined', desc: '内嵌标签 id（关联 combobox 可访问名，对齐 Semi）' },
    { name: 'size', type: "'small'|'large'|'default'", default: 'default' },
    { name: 'validateStatus', type: "'default'|'warning'|'error'", default: 'default', desc: '校验状态（对齐 Semi validateStatus）' },
    { name: 'disabled', type: 'boolean', default: 'false' },
    { name: 'defaultActiveFirstOption', type: 'boolean', default: 'false', desc: '打开时默认高亮首项（对齐 Semi 默认 false）' },
    { name: 'onSearch', type: '(query: string) => void', default: 'undefined', desc: '远程搜索回调（提供即远程模式，由外部更新 data）' },
    { name: 'loading', type: 'boolean', default: 'false', desc: '远程加载中（显示 Spin）' },
    { name: 'onChange', type: '(value: string|number) => void', default: 'undefined' },
    { name: 'onSelect', type: '(value: string|number|NormalizedItem) => void', default: 'undefined', desc: 'onSelectWithObject=true 时回传完整候选对象' },
    { name: 'onSelectWithObject', type: 'boolean', default: 'false', desc: 'true 时 onSelect 入参从 value 变为 { value, label, disabled } 对象（对齐 Semi）' },
    { name: 'onDropdownVisibleChange', type: '(visible: boolean) => void', default: 'undefined', desc: '浮层显隐切换回调（对齐 Semi）' },
    { name: 'onKeyDown', type: '(e: KeyboardEvent) => void', default: 'undefined', desc: '透传输入框原始 keydown 事件（对齐 Semi）' },
    { name: 'dropdownMatchSelectWidth', type: 'boolean', default: 'true', desc: '浮层宽度与触发器同宽' },
    { name: 'getPopupContainer', type: '() => HTMLElement', default: 'undefined', desc: '浮层挂载容器' },
    { name: 'dropdownClassName', type: 'string', default: 'undefined', desc: '浮层 className' },
    { name: 'dropdownStyle', type: 'string | Record<string, string>', default: 'undefined', desc: '浮层样式' },
    { name: 'triggerRender', type: 'Snippet<[{ value: string; placeholder: string; disabled: boolean }]>', default: 'undefined', desc: '完全自定义触发器' },
    { name: 'renderItem', type: 'Snippet<[{ item: NormalizedItem; isSelected: boolean }]>', default: 'undefined', desc: '自定义候选项渲染' },
    { name: 'renderSelectedItem', type: 'Snippet<[{ item: NormalizedItem }]>', default: 'undefined', desc: '自定义已选项显示（仅 string）' },
    { name: 'emptyContent', type: 'Snippet | string', default: 'undefined', desc: '无候选时展示内容' },
    { name: 'prefix', type: 'Snippet | string', default: 'undefined', desc: '输入框前缀' },
    { name: 'suffix', type: 'Snippet | string', default: 'undefined', desc: '输入框后缀' },
    { name: 'showClear', type: 'boolean', default: 'false', desc: '显示清除按钮（对齐 Semi showClear）' },
    { name: 'clearIcon', type: 'Snippet', default: 'undefined', desc: '自定义清除图标' },
    { name: 'onBlur', type: '(e: FocusEvent) => void', default: 'undefined' },
    { name: 'onFocus', type: '(e: FocusEvent) => void', default: 'undefined' },
    { name: 'onClear', type: '() => void', default: 'undefined' },
    { name: 'autoFocus', type: 'boolean', default: 'false', desc: '挂载自动聚焦' },
    { name: 'position', type: "'bottomLeft'|'bottomRight'|'topLeft'|'topRight'", default: "'bottomLeft'", desc: '浮层位置' },
    { name: 'maxHeight', type: 'number|string', default: '300', desc: '下拉浮层最大高度，number→px（对齐 Semi 默认 300）' },
    { name: 'zIndex', type: 'number', default: 'undefined', desc: '下拉浮层 z-index（对齐 Semi）' },
    { name: 'class', type: 'string', default: "''", desc: '根节点 className' },
    { name: 'style', type: 'string', default: "''", desc: '根节点内联样式' },
  ],
  a11y: {
    role: 'combobox',
    notes: [
      'combobox + aria-autocomplete="list" + listbox',
      'aria-activedescendant 指向高亮候选',
      '键盘：↑↓ 移动、Enter 选中、Esc 关闭',
    ],
  },
  tokens: ['--cd-autocomplete-*', '--cd-focus-ring', '--cd-motion-*'],
} as const;
