/**
 * Machine-readable component metadata for AI/docs consumption.
 * Carousel — 对齐 Semi Design（@douyinfe/semi-ui/carousel）API 契约。
 */
export const meta = {
  name: 'Carousel',
  category: 'show',
  description:
    '走马灯：多张幻灯片轮流播放。支持 slide/fade 切换动画、autoPlay 自动播放（含 interval/hoverToPause）、dot/line/columnar 指示器（位置 left/center/right，尺寸 small/medium）、prev/next 箭头（always/hover）、自定义箭头 arrowProps、primary/light/dark 主题、受控 activeIndex 与 onChange。slide 通过 Snippet[] 传入。DOM 结构、tokens、动画逐项对齐 Semi。',
  exports: ['Carousel'],
  props: [
    { name: 'slides', type: 'Snippet[]', default: '[]', desc: '每项一张幻灯片的 Snippet 数组（对齐 Semi children）' },
    { name: 'activeIndex', type: 'number', default: 'undefined', desc: '受控当前激活索引（不回写）' },
    { name: 'defaultActiveIndex', type: 'number', default: '0', desc: '非受控初始索引' },
    {
      name: 'autoPlay',
      type: 'boolean | { interval?: number; hoverToPause?: boolean }',
      default: 'true',
      desc: '自动播放；布尔或对象形式（interval 默认 2000ms，hoverToPause 默认 true）',
    },
    { name: 'animation', type: "'slide'|'fade'", default: "'slide'", desc: '切换动画' },
    { name: 'speed', type: 'number', default: '300', desc: '切换动画时长（ms）' },
    { name: 'showIndicator', type: 'boolean', default: 'true', desc: '是否展示指示器（每张一个）' },
    { name: 'indicatorType', type: "'dot'|'line'|'columnar'", default: "'dot'", desc: '指示器类型' },
    { name: 'indicatorPosition', type: "'left'|'center'|'right'", default: "'center'", desc: '指示器位置' },
    { name: 'indicatorSize', type: "'small'|'medium'", default: "'small'", desc: '指示器尺寸' },
    { name: 'showArrow', type: 'boolean', default: 'true', desc: '是否展示左右箭头' },
    { name: 'arrowType', type: "'always'|'hover'", default: "'always'", desc: '箭头展示时机：always 始终 / hover 悬停显示' },
    {
      name: 'arrowProps',
      type: '{ leftArrow?: ArrowButton; rightArrow?: ArrowButton }',
      default: 'undefined',
      desc: '自定义箭头（props 透传 onClick/style，children 覆盖默认 Icon）',
    },
    { name: 'theme', type: "'primary'|'light'|'dark'", default: "'light'", desc: '指示器与箭头主题' },
    { name: 'slideDirection', type: "'left'|'right'", default: "'left'", desc: 'slide 动画滑动方向' },
    { name: 'trigger', type: "'click'|'hover'", default: "'click'", desc: '指示器触发切换的交互方式' },
    { name: 'onChange', type: '(index: number, preIndex: number) => void', default: 'undefined', desc: '索引变更回调（对齐 Semi）' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根元素内联样式（常用于设定宽高）' },
    { name: 'class', type: 'string', default: "''", desc: '根类名透传' },
  ],
  methods: [
    { name: 'play', signature: '() => void', desc: '开始自动播放' },
    { name: 'stop', signature: '() => void', desc: '停止自动播放' },
    { name: 'goTo', signature: '(targetIndex: number) => void', desc: '切换到指定索引' },
    { name: 'prev', signature: '() => void', desc: '切换到上一张' },
    { name: 'next', signature: '() => void', desc: '切换到下一张' },
  ],
  events: [{ name: 'onChange', desc: '当前索引变更（index, preIndex）' }],
  slots: [{ name: 'slides', desc: '幻灯片 Snippet 数组，每项一张' }],
  a11y: {
    role: 'region',
    focusable: true,
    notes: [
      '根 role=region aria-roledescription="carousel" aria-label（i18n）',
      'slide 区 aria-live=polite；autoPlay 实际播放中降级为 off',
      '根 tabindex=0 承接键盘导航：←/→ 切换、Home/End 跳首末；RTL 下 ←/→ 镜像',
      '每张 role=group aria-roledescription="slide" aria-label「第 N 张」，非可见张 aria-hidden + inert',
      '指示器 role=tablist/tab，aria-selected，可 Enter/Space 触发',
      '箭头 role=button aria-label 上一张/下一张，可键盘操作',
      'autoPlay 提供可见播放/暂停按钮（WCAG 2.2.2，aria-pressed），hover/键盘 focus 进入自动暂停',
      'reduced-motion 下切换动画归零且 autoPlay 不自启',
    ],
  },
  tokens: [
    // 指示器主题色（primary/light/dark × default/hover/active）
    '--cd-carousel-color-indicator-theme-dark-bg-default',
    '--cd-carousel-color-indicator-theme-dark-bg-hover',
    '--cd-carousel-color-indicator-theme-dark-bg-active',
    '--cd-carousel-color-indicator-theme-primary-bg-default',
    '--cd-carousel-color-indicator-theme-primary-bg-hover',
    '--cd-carousel-color-indicator-theme-primary-bg-active',
    '--cd-carousel-color-indicator-theme-light-bg-default',
    '--cd-carousel-color-indicator-theme-light-bg-hover',
    '--cd-carousel-color-indicator-theme-light-bg-active',
    // 箭头主题色
    '--cd-carousel-color-arrow-theme-dark-bg-default',
    '--cd-carousel-color-arrow-theme-dark-bg-hover',
    '--cd-carousel-color-arrow-theme-primary-bg-default',
    '--cd-carousel-color-arrow-theme-primary-bg-hover',
    '--cd-carousel-color-arrow-theme-light-bg-default',
    '--cd-carousel-color-arrow-theme-light-bg-hover',
    // 尺寸
    '--cd-carousel-width-indicator-line',
    '--cd-carousel-width-indicator-columnar-small',
    '--cd-carousel-width-indicator-columnar-medium',
    '--cd-carousel-width-indicator-dot-small',
    '--cd-carousel-width-indicator-dot-medium',
    '--cd-carousel-width-arrow',
    '--cd-carousel-height-indicator-columnar-small-default',
    '--cd-carousel-height-indicator-columnar-small-active',
    '--cd-carousel-height-indicator-columnar-medium-default',
    '--cd-carousel-height-indicator-columnar-medium-active',
    '--cd-carousel-height-indicator-line-small',
    '--cd-carousel-height-indicator-line-medium',
    '--cd-carousel-radius-indicator-dot',
    // 间距
    '--cd-carousel-spacing-indicator-padding',
    '--cd-carousel-spacing-indicator-columnar-marginx',
    '--cd-carousel-spacing-indicator-line-marginx',
    '--cd-carousel-spacing-indicator-dot-marginx',
    '--cd-carousel-spacing-arrow-left',
    '--cd-carousel-spacing-arrow-right',
    // 动效
    '--cd-carousel-animation-transition-function',
    '--cd-carousel-animation-transition-duration',
    '--cd-carousel-animation-transition-delay',
  ],
  examples: [
    {
      title: '基础',
      code:
        '{#snippet s1()}<img src="/1.jpg" alt="" />{/snippet}\n{#snippet s2()}<img src="/2.jpg" alt="" />{/snippet}\n<Carousel slides={[s1, s2]} style="width:100%;height:400px" />',
    },
  ],
} as const;
