/**
 * Machine-readable component metadata for AI/docs consumption.
 * Progress — 严格对齐 Semi Design（semi-ui/progress）。
 */
export const meta = {
  name: 'Progress',
  category: 'feedback',
  description:
    '进度条：line（horizontal / vertical）与 circle 两形态；percent 钳制到 0..100，showInfo/format 控制信息区，stroke 支持字符串或分段颜色数组（配合 strokeGradient 渐变），orbitStroke 自定义轨道色，数字滚动线性动画；role=progressbar，受控 percent 不回写。',
  exports: ['Progress'],
  props: [
    { name: 'percent', type: 'number', default: '0', desc: '受控进度，钳制到 0..100' },
    { name: 'type', type: "'line'|'circle'", default: "'line'", desc: '形态' },
    {
      name: 'direction',
      type: "'horizontal'|'vertical'",
      default: "'horizontal'",
      desc: '条状进度条方向',
    },
    {
      name: 'size',
      type: "'default'|'small'|'large'",
      default: "'default'",
      desc: 'small 仅 type=circle 生效，large 仅 type=line 生效',
    },
    {
      name: 'width',
      type: 'number',
      default: "size='default' 时 72，'small' 时 24",
      desc: '环形进度条直径 px',
    },
    { name: 'strokeWidth', type: 'number', default: '4', desc: 'type=circle 时进度条宽度' },
    {
      name: 'strokeLinecap',
      type: "'round'|'square'",
      default: "'round'",
      desc: 'circle 端点形状（仅 type=circle 生效）',
    },
    { name: 'showInfo', type: 'boolean', default: 'false', desc: '是否显示信息区/中心文本' },
    {
      name: 'stroke',
      type: 'string | Array<{percent:number; color:string}>',
      default: "'var(--cd-color-success)'",
      desc: '填充色；数组时按 percent 区间取色（color 支持 Hex/Hsl(a)/Rgb(a)/Design Token）',
    },
    {
      name: 'strokeGradient',
      type: 'boolean',
      default: 'false',
      desc: '自动补齐颜色区间生成渐变（需 stroke 为区间数组）',
    },
    {
      name: 'orbitStroke',
      type: 'string',
      default: "'var(--cd-color-fill-0)'",
      desc: '进度条轨道填充色',
    },
    {
      name: 'format',
      type: '(percent: number) => string | null',
      default: "(percent) => percent + '%'",
      desc: '格式化信息区文本，入参为当前百分比',
    },
    {
      name: 'motion',
      type: 'boolean',
      default: 'true',
      desc: '数字滚动/过渡动画，被 reduced-motion 覆盖',
    },
    { name: 'class', type: 'string', default: 'undefined', desc: '根节点样式类名' },
    { name: 'style', type: 'string', default: 'undefined', desc: '根节点内联样式（如自定义 height/width）' },
    { name: 'id', type: 'string', default: 'undefined', desc: 'id 标识' },
    { name: 'aria-label', type: 'string', default: 'undefined', desc: '无障碍标签' },
    { name: 'aria-labelledby', type: 'string', default: 'undefined', desc: '关联标签元素 id' },
    { name: 'aria-valuetext', type: 'string', default: 'undefined', desc: '无障碍值文本（优先于 valuenow）' },
    {
      name: 'formatSnippet',
      type: 'Snippet<[{ percent: number }]>',
      default: 'undefined',
      desc: '信息区自定义内容 snippet，优先于 format prop',
    },
  ],
  events: [],
  slots: [{ name: 'formatSnippet', desc: '自定义信息区内容（优先于 format prop）' }],
  a11y: {
    hasRole: true,
    focusable: false,
    note: 'role=progressbar + aria-valuemin/max=0/100 与 aria-valuenow；支持 aria-valuetext（优先于 valuenow）、aria-label、aria-labelledby；不可聚焦不设 tabindex；reduced-motion 禁用数字滚动与过渡。',
  },
  tokens: [
    // —— Semi 全量对齐（semi-foundation/progress/variables.scss 19 个） ——
    '--cd-color-progress-default-bg',
    '--cd-color-progress-track-inner-bg',
    '--cd-color-progress-line-text-text',
    '--cd-color-progress-circle-text',
    '--cd-motion-progress-transition-duration',
    '--cd-motion-progress-transition-timing-function',
    '--cd-height-progress-horizontal',
    '--cd-height-progress-horizontal-large',
    '--cd-spacing-progress-line-text-marginleft',
    '--cd-spacing-progress-line-text-marginright',
    '--cd-spacing-progress-vertical-marginx',
    '--cd-spacing-progress-horizontal-marginy',
    '--cd-spacing-progress-vertical-line-text-margintop',
    '--cd-font-progress-line-text-fontweight',
    '--cd-width-progress-line-text',
    '--cd-width-progress-vertical',
    '--cd-width-progress-vertical-large',
    '--cd-radius-progress-track',
    '--cd-radius-progress-track-inner',
  ],
  responsive: false,
  examples: [
    { title: 'line 受控', code: '<Progress percent={percent} aria-label="进度" />' },
    { title: 'line 带百分比', code: '<Progress percent={50} showInfo aria-label="进度" />' },
    { title: 'vertical', code: '<Progress percent={50} direction="vertical" aria-label="进度" />' },
    { title: 'circle', code: '<Progress type="circle" percent={75} showInfo aria-label="进度" />' },
    {
      title: '分段颜色',
      code: '<Progress percent={p} stroke={[{percent:50,color:"red"},{percent:100,color:"green"}]} aria-label="进度" />',
    },
  ],
} as const;
