/**
 * Machine-readable component metadata for AI/docs consumption.
 * Tree — see specs/components/show/Tree.spec.md
 */
export const meta = {
  name: 'Tree',
  category: 'show',
  description:
    '树形控件：层级展示节点，支持展开/收起、单选/多选、可勾选父子联动（含半选 mixed）、内置搜索高亮。受控 value/checkedKeys/expandedKeys 均不回写，仅通过 onChange/onCheck/onExpandedChange 通知。键盘导航遵循 WAI-ARIA APG Tree View（单一 tab stop + aria-activedescendant）。',
  exports: ['Tree'],
  props: [
    { name: 'treeData', type: 'TreeNodeData[]', default: '[]', desc: '树数据源；字段名可经 fieldNames 自定义' },
    {
      name: 'fieldNames',
      type: '{ key?: string; label?: string; children?: string }',
      default: "{ key:'key', label:'label', children:'children' }",
      desc: '自定义节点字段名映射，适配任意后端数据（如 { key:\'id\', label:\'name\', children:\'sub\' }）。派生只读映射，回调回传原始节点',
    },
    {
      name: 'value',
      type: 'TreeKey | TreeKey[] | null',
      default: 'undefined',
      desc: '受控选中；multiple 时为数组。受控时不回写',
    },
    {
      name: 'defaultValue',
      type: 'TreeKey | TreeKey[] | null',
      default: 'null',
      desc: '非受控初始选中',
    },
    { name: 'multiple', type: 'boolean', default: 'false', desc: '多选模式' },
    { name: 'checkable', type: 'boolean', default: 'false', desc: '显示勾选框' },
    {
      name: 'checkedKeys',
      type: 'TreeKey[]',
      default: 'undefined',
      desc: '受控勾选；内部用 conduct 归一。受控时不回写',
    },
    { name: 'defaultCheckedKeys', type: 'TreeKey[]', default: '[]', desc: '非受控初始勾选' },
    {
      name: 'checkStrictly',
      type: 'boolean',
      default: 'false',
      desc: 'true 时父子解耦，仅切换单节点',
    },
    {
      name: 'checkRelation',
      type: "'related' | 'unRelated'",
      default: "'related'",
      desc: "父子勾选是否联动。'related'（默认）联动含半选；'unRelated' 父子独立无半选（效果同 checkStrictly=true）",
    },
    {
      name: 'expandedKeys',
      type: 'TreeKey[]',
      default: 'undefined',
      desc: '受控展开。受控时不回写',
    },
    { name: 'defaultExpandedKeys', type: 'TreeKey[]', default: '[]', desc: '非受控初始展开' },
    { name: 'defaultExpandAll', type: 'boolean', default: 'false', desc: '初始展开全部' },
    {
      name: 'expandedDepth',
      type: 'number',
      default: 'undefined',
      desc: '默认展开到第 N 层（仅初始化非受控展开集时生效，优先级低于 defaultExpandAll，与 defaultExpandedKeys 取并集）',
    },
    {
      name: 'autoExpandParent',
      type: 'boolean',
      default: 'true',
      desc: '受控展开时自动展开父节点（派生祖先链，不写回受控 expandedKeys）',
    },
    {
      name: 'accordion',
      type: 'boolean',
      default: 'false',
      desc: '手风琴模式：同层级最多展开一个，展开节点时自动收起同父级其它节点（不同层级互不影响）。受控 expandedKeys 同样生效，仅经 onExpandedChange 回传新集不回写',
    },
    { name: 'selectable', type: 'boolean', default: 'true', desc: '节点是否可选中' },
    { name: 'showIcon', type: 'boolean', default: 'true', desc: '是否预留节点图标位' },
    { name: 'showLine', type: 'boolean', default: 'false', desc: '显示层级连接线（├/└/竖线）' },
    {
      name: 'virtualized',
      type: 'boolean',
      default: 'false',
      desc: '虚拟滚动：仅渲染视口内可见节点行，适合大数据树（1000+ 节点）',
    },
    { name: 'height', type: 'number', default: '320', desc: '虚拟滚动视口高度（px），virtualized 时生效' },
    { name: 'itemHeight', type: 'number', default: '32', desc: '虚拟滚动行高（px），virtualized 时生效' },
    { name: 'filterable', type: 'boolean', default: 'false', desc: '渲染内置搜索框' },
    {
      name: 'filterTreeNode',
      type: 'boolean | ((input: string, node: TreeNodeData) => boolean)',
      default: 'undefined',
      desc: '自定义搜索过滤谓词；传函数即开启搜索，boolean 形态等价 filterable，不传回退内置 label 包含匹配',
    },
    {
      name: 'searchValue',
      type: 'string',
      default: 'undefined',
      desc: '受控搜索关键词；传入走受控模式，输入变化仅触发 onSearch 不更新内部 state',
    },
    { name: 'blockNode', type: 'boolean', default: 'false', desc: '整行点击选中' },
    { name: 'disabled', type: 'boolean', default: 'false', desc: '整树禁用' },
    { name: 'size', type: "'small'|'default'|'large'", default: "'default'" },
    { name: 'status', type: "'default'|'warning'|'error'", default: "'default'" },
    { name: 'emptyContent', type: 'string', default: 'undefined', desc: '空态文案' },
    { name: 'ariaLabel', type: 'string', default: 'undefined', desc: '无障碍标签' },
    {
      name: 'loadData',
      type: '(node) => Promise<TreeNodeData[]>',
      default: 'undefined',
      desc: '异步加载子节点：展开未加载的非叶子节点时调用',
    },
    {
      name: 'onLoad',
      type: "(loadedKeys: string[], info: { event: 'load'; node: TreeNodeData }) => void",
      default: 'undefined',
      desc: '异步加载完成回调',
    },
    {
      name: 'draggable',
      type: 'boolean',
      default: 'false',
      desc: '启用 HTML5 拖拽排序：节点可拖动改变层级/顺序（before/inside/after）',
    },
    {
      name: 'onDrop',
      type: '(info: { dragNode, dropNode, dropPosition }) => void',
      default: 'undefined',
      desc: '放下时回调；受控数据由父组件按 info 重排 treeData，组件不内部改',
    },
    {
      name: 'onDragStart',
      type: '(node: TreeNodeData) => void',
      default: 'undefined',
      desc: '开始拖拽节点',
    },
    {
      name: 'onDragEnter',
      type: '(info: { dragNode: TreeNodeData; dropNode: TreeNodeData }) => void',
      default: 'undefined',
      desc: '拖拽进入候选目标节点',
    },
    {
      name: 'onRightClick',
      type: '(e: MouseEvent, node: TreeNodeData) => void',
      default: 'undefined',
      desc: '节点右键菜单回调',
    },
    {
      name: 'onSearch',
      type: '(value: string, filteredKeys: string[]) => void',
      default: 'undefined',
      desc: '搜索关键词变化回调，附命中节点 key 列表',
    },
    { name: 'onChange', type: '(info) => void', default: 'undefined', desc: '选中变更' },
    { name: 'onCheck', type: '(info) => void', default: 'undefined', desc: '勾选变更' },
    {
      name: 'onExpandedChange',
      type: '(info) => void',
      default: 'undefined',
      desc: '展开变更',
    },
    { name: 'label', type: 'Snippet', default: 'undefined', desc: '自定义节点内容' },
    { name: 'icon', type: 'Snippet<[{ node, expanded, level }]>', default: 'undefined', desc: '自定义节点图标（showIcon 时渲染在 label 前）' },
    {
      name: 'switcher',
      type: 'Snippet<[{ node: TreeNodeData; expanded: boolean; loading: boolean }]>',
      default: 'undefined',
      desc: '自定义展开/收起箭头；参数含节点、展开态与加载态',
    },
    {
      name: 'suffix',
      type: 'Snippet<[{ node: TreeNodeData }]>',
      default: 'undefined',
      desc: '节点尾部操作区（渲染在 label 右侧）',
    },
    {
      name: 'dragGhost',
      type: 'Snippet<[{ node: TreeNodeData }]>',
      default: 'undefined',
      desc: '自定义拖拽幽灵节点',
    },
  ],
  events: [
    { name: 'onChange', desc: '选中节点变更：{ value, node, selected }' },
    { name: 'onCheck', desc: '勾选变更：{ checked, node, halfChecked }' },
    { name: 'onExpandedChange', desc: '展开/收起：{ expanded, node, expand }' },
    { name: 'onDrop', desc: '拖拽放下：{ dragNode, dropNode, dropPosition: before|inside|after }' },
  ],
  slots: [{ name: 'label', desc: '自定义节点渲染：{ node, level, searchValue, selected, checked }' }],
  a11y: {
    hasRole: true,
    focusable: true,
    note: 'role=tree（aria-multiselectable）容器为单一 tab stop，焦点通过 aria-activedescendant 指向当前高亮 treeitem；每行 role=treeitem 含 aria-level/setsize/posinset/expanded/selected/disabled，可勾选时 aria-checked 支持 true/false/"mixed"（半选）。方向键导航：↑↓ 移动、→ 展开/进入子、← 折叠/回父、Home/End 首末、Enter 选中、Space 勾选或选中。',
  },
  // 组件消费的 Tree token（原名保留，值全量对齐 Semi tree/variables.scss；
  // 另有 29 个 Semi 语义 token color-tree-option-* / spacing-tree-* / width-tree-* 等被这些间接引用）。
  tokens: [
    '--cd-tree-node-height',
    '--cd-tree-node-height-small',
    '--cd-tree-node-height-large',
    '--cd-tree-row-height',
    '--cd-tree-indent',
    '--cd-tree-node-font-size',
    '--cd-tree-node-color',
    '--cd-tree-node-color-disabled',
    '--cd-tree-node-color-selected',
    '--cd-tree-node-bg-hover',
    '--cd-tree-node-bg-active',
    '--cd-tree-node-bg-selected',
    '--cd-tree-expand-icon-color',
    '--cd-tree-search-highlight-bg',
    '--cd-tree-search-highlight-color',
    '--cd-tree-search-highlight-weight',
    '--cd-tree-focus-ring',
    '--cd-tree-border-color',
    '--cd-tree-border-color-warning',
    '--cd-tree-border-color-error',
    '--cd-tree-line-color',
    '--cd-tree-radius',
    // Semi 语义 token（tree/variables.scss，被上方组件 token 及组件样式引用）
    '--cd-color-tree-option-loading-icon-default',
    '--cd-color-tree-option-draggable-insert-border-default',
    '--cd-radius-tree-checkbox-addon',
    '--cd-width-tree-option-draggable-border',
  ],
  responsive: false,
  examples: [
    {
      title: '基础',
      code: '<Tree treeData={data} defaultExpandAll onChange={(i) => (v = i.value)} />',
    },
    {
      title: '可勾选联动',
      code: '<Tree treeData={data} checkable onCheck={(i) => (keys = i.checked)} />',
    },
    {
      title: '可搜索',
      code: '<Tree treeData={data} filterable />',
    },
  ],
} as const;
