/**
 * Machine-readable component metadata for AI/docs consumption.
 * Toast — 严格对齐 Semi Design（semi-ui/toast）。
 */
export const meta = {
  name: 'Toast',
  category: 'feedback',
  description:
    '轻提示：命令式全局反馈 API（Toast.info/success/warning/error/open/close/destroyAll/config/useToast + ToastFactory.create），严格对齐 Semi Design。单例容器惰性挂载到 body（wrapper 固定顶部居中，config 的 top/left/bottom/right 整体偏移）；type=info/success/warning/error/default（default 无内置图标）；theme=normal（白）/light（多色填充+描边）；stack 多条堆叠、Hover 展开（3D 透视折叠）；duration 自动关闭（0 常驻）、mouseenter 暂停/mouseleave 从头计时；showClose 关闭按钮（复用 IconButton）；textMaxWidth 内容最大宽度；content/icon 支持 string 或 Snippet；对已存在 id 再调 info/success 即原地更新。useToast() 返回 [api, holderStore] 经 <ToastHolder> 渲染在组件树内继承上下文；ToastFactory.create(config) 创建带独立 config 的新实例（如 getPopupContainer）。a11y：卡片 role=alert + aria-label="{type} type"（对齐 Semi），关闭按钮 IconButton 带可访问名。',
  exports: ['Toast', 'ToastFactory', 'useToast', 'ToastHolder'],
  imperative: true,
  props: [
    { name: 'content', type: 'string | Snippet', default: "''", desc: '提示内容（必填），支持文本或自定义 Snippet' },
    { name: 'id', type: 'string', default: 'undefined', desc: '自定义 ToastId；已存在则原地合并更新并重启定时器' },
    {
      name: 'type',
      type: "'info'|'success'|'warning'|'error'|'default'",
      default: "'default'",
      desc: '语义类型，决定图标与色；default 无内置图标',
    },
    {
      name: 'duration',
      type: 'number',
      default: '3',
      desc: '自动关闭秒数；0 = 不自动关闭（须手动关闭）',
    },
    { name: 'showClose', type: 'boolean', default: 'true', desc: '是否展示关闭按钮' },
    { name: 'textMaxWidth', type: 'number | string', default: '450', desc: '内容的最大宽度' },
    {
      name: 'theme',
      type: "'normal'|'light'",
      default: "'normal'",
      desc: "填充样式；'light' 浅色填充 + 类型描边",
    },
    { name: 'stack', type: 'boolean', default: 'false', desc: '是否堆叠 Toast（多条叠一摞、Hover 展开）' },
    { name: 'icon', type: 'Snippet', default: 'undefined', desc: '自定义图标（覆盖类型内置图标）' },
    { name: 'direction', type: "'ltr'|'rtl'", default: "'ltr'", desc: '书写方向' },
    { name: 'onClose', type: '() => void', default: 'undefined', desc: 'toast 关闭时的回调（无参数，对齐 Semi）' },
  ],
  config: [
    { name: 'top', type: 'number | string', default: '-', desc: '弹出位置 top（wrapper 整体偏移）' },
    { name: 'bottom', type: 'number | string', default: '-', desc: '弹出位置 bottom' },
    { name: 'left', type: 'number | string', default: '-', desc: '弹出位置 left' },
    { name: 'right', type: 'number | string', default: '-', desc: '弹出位置 right' },
    { name: 'zIndex', type: 'number', default: '1010', desc: 'wrapper z-index' },
    { name: 'theme', type: "'normal'|'light'", default: "'normal'", desc: '默认填充样式' },
    { name: 'duration', type: 'number', default: '3', desc: '默认自动关闭延时（秒），0 不自动关闭' },
    { name: 'getPopupContainer', type: '() => HTMLElement | null', default: '() => document.body', desc: '指定容器挂载父级 DOM' },
  ],
  events: [{ name: 'onClose', desc: 'toast 关闭时触发（无参数，对齐 Semi）' }],
  slots: [],
  a11y: {
    hasRole: true,
    focusable: false,
    note: '每张 toast 卡片自身 role=alert + aria-label="{type} type"（对齐 Semi），屏幕阅读器直接播报卡片内容。关闭按钮 IconButton 带 aria-label（locale Toast.close）。不抢焦点、不锁滚动。',
  },
  tokens: [
    '--cd-color-toast-bg-default',
    '--cd-color-toast-text-default',
    '--cd-color-toast-warning-icon',
    '--cd-color-toast-success-icon',
    '--cd-color-toast-info-icon',
    '--cd-color-toast-danger-icon',
    '--cd-color-toast-warning-light-bg',
    '--cd-color-toast-warning-light-icon',
    '--cd-color-toast-warning-light-border',
    '--cd-color-toast-success-light-bg',
    '--cd-color-toast-success-light-icon',
    '--cd-color-toast-success-light-border',
    '--cd-color-toast-info-light-bg',
    '--cd-color-toast-info-light-icon',
    '--cd-color-toast-info-light-border',
    '--cd-color-toast-danger-light-bg',
    '--cd-color-toast-danger-light-icon',
    '--cd-color-toast-danger-light-border',
    '--cd-spacing-toast-wrapper-top',
    '--cd-spacing-toast-content-paddingy',
    '--cd-spacing-toast-content-paddingx',
    '--cd-spacing-toast-content-paddingtop',
    '--cd-spacing-toast-content-paddingbottom',
    '--cd-spacing-toast-content-paddingleft',
    '--cd-spacing-toast-content-paddingright',
    '--cd-spacing-toast-content-margin',
    '--cd-spacing-toast-content-close-btn-margintop',
    '--cd-spacing-toast-content-text-marginleft',
    '--cd-spacing-toast-content-text-marginright',
    '--cd-spacing-toast-perspective-originy',
    '--cd-spacing-toast-perspective',
    '--cd-width-toast-wrapper',
    '--cd-width-toast-light-border',
    '--cd-radius-toast-content',
    '--cd-font-toast-content-fontweight',
  ],
  responsive: false,
  examples: [
    { title: '成功', code: "Toast.success('已保存')" },
    { title: '错误', code: "Toast.error('保存失败')" },
    { title: '堆叠', code: "Toast.info({ content: '已同步', stack: true })" },
    { title: '多色', code: "Toast.warning({ content: '存储空间不足', theme: 'light' })" },
    { title: '常驻', code: "Toast.info({ content: '手动关闭', duration: 0 })" },
    { title: '更新', code: "const id = 'x'; Toast.info({ content: '处理中', id }); Toast.success({ content: '完成', id })" },
  ],
} as const;
