/**
 * Machine-readable component metadata for AI/docs consumption.
 * Toast — see specs/components/feedback/Toast.spec.md
 */
export const meta = {
  name: 'Toast',
  category: 'feedback',
  description:
    '轻提示：命令式全局反馈 API（Toast.info/success/warning/error/loading/open/promise/close/update/destroyAll）。单例容器惰性挂载到 body；类型预设图标 + 自动消失 + 悬停暂停 + 按方位 maxCount FIFO 淘汰 + 同 id 去重更新；6 方位独立堆叠（topLeft/top/topRight/bottomLeft/bottom/bottomRight，对齐 Notification）多条同方位纵向堆叠不重叠；theme(light/dark) 卡片主题；Toast.promise(promise, { loading, success, error }) 传入 Promise 自动 pending→resolve/reject 切文案（success/error 可为函数接收值，默认文案经 @chenzy-design/locale）；a11y 播报走单例 ARIA live region（error->assertive、其余->polite），卡片本身纯视觉无 role/aria-live。',
  exports: ['Toast', 'ToastPromiseMessages'],
  imperative: true,
  props: [
    { name: 'content', type: 'string', default: '—', desc: '提示文本（必填）' },
    { name: 'id', type: 'string', default: 'undefined', desc: '指定 id；已存在则原地更新并重启定时器' },
    {
      name: 'type',
      type: "'info'|'success'|'warning'|'error'|'loading'",
      default: "'info'",
      desc: '语义类型，决定图标与色',
    },
    {
      name: 'duration',
      type: 'number',
      default: '3',
      desc: '自动消失秒数；0 持久。loading 默认 0',
    },
    {
      name: 'position',
      type: "'topLeft'|'top'|'topRight'|'bottomLeft'|'bottom'|'bottomRight'",
      default: "'top'",
      desc: '出现方位，每方位独立纵向堆叠',
    },
    { name: 'closable', type: 'boolean', default: 'true', desc: '是否显示关闭按钮' },
    { name: 'pauseOnHover', type: 'boolean', default: 'true', desc: '悬停/聚焦时暂停定时器' },
    {
      name: 'theme',
      type: "'light'|'dark'",
      default: "'light'",
      desc: '卡片主题；dark 为深色卡片',
    },
    {
      name: 'onClose',
      type: "(id: string, reason: 'timeout'|'manual'|'replace'|'destroyAll') => void",
      default: 'undefined',
      desc: '关闭回调，附关闭原因',
    },
    { name: 'icon', type: 'Snippet | false', default: 'undefined', desc: '自定义图标 snippet；false 隐藏图标' },
    { name: 'showClose', type: 'boolean', default: 'true', desc: '是否显示关闭按钮（closable 别名）' },
    { name: 'textMaxWidth', type: 'number | string', default: '450', desc: '内容区最大宽度（px 数字或 CSS 字符串）' },
    { name: 'stack', type: 'boolean', default: 'false', desc: '堆叠显示：容器附加 cd-toast-wrapper--stacked class' },
  ],
  events: [{ name: 'onClose', desc: '单条关闭（超时/手动/被替换/清空）时触发，带 id 与 reason' }],
  slots: [],
  a11y: {
    hasRole: true,
    focusable: false,
    note: '所有文案播报走 body 上单例 ARIA live region（全局唯一一对：role=status/aria-live=polite + role=alert/aria-live=assertive）；error 走 assertive 立即打断，其余走 polite。store 在新增/更新 toast 时命令式写入 region 文案，卡片本身纯视觉、不带 role/aria-live，避免多 region 重复/竞争播报。关闭按钮 button + aria-label「关闭」。不抢焦点、不锁滚动。',
  },
  tokens: [
    '--cd-toast-bg',
    '--cd-toast-color-text',
    '--cd-toast-color-icon-info',
    '--cd-toast-color-icon-success',
    '--cd-toast-color-icon-warning',
    '--cd-toast-color-icon-error',
    '--cd-toast-color-close',
    '--cd-toast-color-close-hover',
    '--cd-toast-radius',
    '--cd-toast-shadow',
    '--cd-toast-padding',
    '--cd-toast-gap',
    '--cd-toast-font-size',
    '--cd-toast-font-weight',
    '--cd-toast-max-width',
    '--cd-toast-min-width',
    '--cd-toast-stack-gap',
    '--cd-toast-z',
    '--cd-toast-motion-duration',
    '--cd-toast-bg-dark',
    '--cd-toast-color-text-dark',
    '--cd-toast-color-close-dark',
    '--cd-toast-color-close-hover-dark',
  ],
  responsive: false,
  examples: [
    { title: '成功', code: "Toast.success('已保存')" },
    { title: '错误', code: "Toast.error('保存失败')" },
    { title: '加载（持久）', code: "Toast.loading('上传中', { duration: 0 })" },
    { title: '右下角', code: "Toast.info('已同步', { position: 'bottomRight' })" },
    { title: '深色主题', code: "Toast.success('已保存', { theme: 'dark' })" },
    {
      title: 'promise',
      code: "Toast.promise(save(), { loading: '保存中…', success: '已保存', error: (e) => `失败：${e.message}` })",
    },
  ],
} as const;
